### ISSUE TITLE
read_bmp uses wrong dimension for flip

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1006]
Using READ_BMP on a non-square true-colour image uses the wrong dimension for the reversal, as a result the dimension is changed. e.g. reading a 640x480 true-colour image, a 4x480x480 image is returned.

Suggested fix:
````
diff -c read_bmp.pro /usr/share/gnudatalanguage/lib/read_bmp.pro 
*** read_bmp.pro        2021-07-09 16:06:52.388845546 +0100
--- /usr/share/gnudatalanguage/lib/read_bmp.pro 2021-04-29 10:07:55.000000000 +0100
***************
*** 89,95 ****
     ;;
     ;; flip image
     sz  = SIZE( data, /DIM)
!    rev = sz[1] - 1L - LINDGEN( sz[1])
     data = data[ *, rev, *]
     ;;
  endelse
--- 89,95 ----
     ;;
     ;; flip image
     sz  = SIZE( data, /DIM)
!    rev = sz[2] - 1L - LINDGEN( sz[2])
     data = data[ *, rev, *]
     ;;
  endelse
````

**Comment by GillesDuvert** [comment]
@jtappin thanks, but is it true with GDL's last sate, including #999 ?
Because bmp files appear OK within IDL's DIALOG_READ_IMAGE()

**Comment by jtappin** [comment]
> @jtappin thanks, but is it true with GDL's last sate, including #999 ?
> Because bmp files appear OK within IDL's DIALOG_READ_IMAGE()

The current git version does work correctly but needs an `if keyword_set(rgb)` condition on the definition of `myrgb`, otherwise it crashes if RGB is not specified.

**Comment by GillesDuvert** [comment]
There is a case where IDL returns empty r,g,b . When the bmp is truecolor.
```
IDL> $file /usr/share/printconf/tests/netpbm.test-image.bmp
/usr/share/printconf/tests/netpbm.test-image.bmp: PC bitmap, Windows 3.x format, 256 x 256 x 24
IIDL>  a=read_bmp('/usr/share/printconf/tests/netpbm.test-image.bmp',r,g,b)
IDL> help,r
R               UNDEFINED = <Undefined>
```
Would you be in that case?

**Comment by jtappin** [comment]
> There is a case where IDL returns empty r,g,b . When the bmp is truecolor.
> Would you be in that case?

I don't think so. The problem is that when converting the RGB keyword to a short, the conversion is attempted even if it's not specified.
````
img = read_bmp('111.bmp')
% FIX: Variable is undefined: RGB
% Error occurred at: READ_BMP            82 /scratch/RAL/home/tappin/Documents/TSE/SCOPE_TESTS_RAL/Data_phase_4/baffle measurement/read_bmp_local.pro
````
Exactly the same error if the R, G, B args are given.

`img = read_bmp('111.bmp', rgb=0)` does work.

FWIW:
````
$ file 111.bmp
111.bmp: PC bitmap, Windows 3.x format, 640 x 480 x 32, resolution 3780 x 3780 px/m, cbSize 1228854, bits offset 54
````

**Comment by GillesDuvert** [comment]
ok, we have a bug :smile:

**Comment by GillesDuvert** [comment]
@jtappin please check if issue is solved by #1028, and open a new issue if not.

**Comment by jtappin** [comment]
It may be that my interpreter is still the RC3 version, but after downloading the updated `read_bmp.pro` and `read_anygraphicsfilewithmagick.pro` and compiling them, when reading a true-colour bitmap, I get an error from within the Magick libraries:
````
GDL> img1 = read_bmp('115.bmp')
MAGICK_COLORMAPSIZE: Magick: Image does not contain a colormap reported by Magick++/lib/Exception.cpp:435 (throwExceptionExplicit)
````
Since the call to magick_colorsize is in read_bmp, I don't think that I've missed anything that I need.
````
$ pacman -Q graphicsmagick
graphicsmagick 1.3.36-3
````

**Comment by GillesDuvert** [comment]
Ahem, my tests are with the current (devel) version, that is improved to RC3 by #999, so with ~18 files changed. RC3 is soo old...

**Comment by jtappin** [comment]
> Ahem, my tests are with the current (devel) version, that is improved to RC3 by #999, so with ~18 files changed. RC3 is soo old...

I can confirm that the current git works, however I've found another showstopper (for me at least). ( https://github.com/gnudatalanguage/gdl/issues/1032#issue-955707965 )
