### ISSUE TITLE
crash when KEYWORD_SET and test ?: used in N_ELEMENTS()

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1011]
```
GDL> f=1 & a=1 & b=1
GDL> print, n_elements(f ? a : b)
           0
GDL> print, n_elements(keyword_set(f) ? a : b)
 (core dumped) 
```

**Comment by alaingdl** [comment]
in fact the situation is even worse and unclear and unpredicatable: 
```
GDL> f=1 & a=1 & b=1
GDL> print, n_elements(f ? a : b)
           0
GDL> print, n_elements(f) ? a : b 
       1
GDL> print, n_elements(f ? a : b)     <<-- the same two lines above ...
 9636 Erreur de segmentation  (core dumped) $GDL_ROOT/last-gdl/src/gdl $@
```

**Comment by GillesDuvert** [comment]
this bug is here from at least 0.9.8

**Comment by alaingdl** [comment]
gdl-0.9.6cvs161102 & gdl-0.9.7cvs170530CMake too :smiley:

**Comment by alaingdl** [comment]
Should be solved by #1029 
But we need to write some test in testsuite

**Comment by alaingdl** [comment]
in fact it was not crashing on FC28 before, may-be some internal options in c++ for the pointers are different ? @opoplawski  any advice ?

**Comment by GillesDuvert** [comment]
some compiler options initialize all variables...
Closing as solved, as tidying the issues list is important these days...
