### ISSUE TITLE
widgets on OSX 10.14.6 (Mojave) not working

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1012]
On a OSX 10.14.6, compiled with "build_gdl.sh build", ATV and _test_widgets.pro_ don't open at all.
(not on remote, I am just in from of the screen ;)
Yes, HELP, /device gives X

**Comment by GillesDuvert** [comment]
see https://wiki.wxwidgets.org/WxMac-specific_topics#My_app_can.27t_be_brought_to_the_front.21
it's quite possible this is the reason.

**Comment by GillesDuvert** [comment]
check with my new patches.
