### ISSUE TITLE
contour,/fill,/xlog,/ylog

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#102]
As reported on SF.net by @alaingdl:

In CONTOUR, when /fill and /xlog or /ylog activated,
the visual result is not as expected.

one example :

contour,dist(100), /fill, nlev=10,ys=1,tit='Axe Y: echelle log',/ylog

(the same with /xlog)

ystyle keyword seems to be not usefull in this case

visual self consistant example:
```
;
; bug report by Baptiste C., 7 Nov. 2016
; https://sourceforge.net/p/gnudatalanguage/bugs/713/
;
pro TEST_CONTOUR_FILL_LOG, postscript=postscript, test=test
;
z = findgen(100)+100.
zz = rebin(reform(z,1,100),1000,100)
x = findgen(1000)/10.
y = findgen(100.)/100.+0.5
;
loadct,39
if KEYWORD_SET(postscript) then begin
    set_plot,'ps'
    device,file='test_contour_fill_log.ps',/color
endif
;  
!p.multi=[0,1,3]
!p.charsize=2
CONTOUR, zz,x,y,/fill,nlev=100,ys=1,tit='Axe Y: echelle lin'
CONTOUR, zz,x,y,/fill,nlev=100,ys=1,/ylog,tit='Axe Y: echelle log'
CONTOUR, zz,x,alog10(y),/fill,nlev=100,ys=1,tit='Axe Y: alog10(echelle lin)'
;
if KEYWORD_SET(postscript) then begin
    device,/close
    set_plot,'x'
endif
;
if KEYWORD_SET(test) then STOP
;
end
```

![image](https://user-images.githubusercontent.com/89685/38468626-b31ed8f2-3b51-11e8-945f-f6d0e7d9711b.png)

**Comment by slayoo** [comment]
Further comment from @GillesDuvert:

This is a plplot bug, or rather, feature. To be removed along with plplot use one day.

**Comment by slayoo** [comment]
Should we report it to plplot maintainers then?

**Comment by GillesDuvert** [comment]
![test_contour_fill_log](https://user-images.githubusercontent.com/33936193/38557579-c6c2b306-3ccd-11e8-9fcd-6c4d263f1c47.png)

as seen above, using a more contrasted image (Saturn.jpg) permits to see that there is no difference and no bug.
But! the device,/decomposed above image shows that idl's red ramp is slightly more luminous than the one used by gdl's plplot library.
