### ISSUE TITLE
plot, psym=3 doesn't generate any symbols

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1032]
Attempting to plot something using `psym=3` (dot) e.g.
````
plot, randomu(seed, 1000), randomu(seed, 1000), psym=3
````
produces a correctly scaled set of axes, but no visible points (at least to the X display). This did work correctly in RC3.

(I know that a point symbol is tricky in plplot).

**Comment by Barney-9000** [comment]
Seems to work fine for both WxWidgets and postscript devices in Version 1.0.0-rc.3 git (compiled on macOS 10.14.6 from source downloaded 27/07/21).

**Comment by alaingdl** [comment]
I can replicate it, it does appear (on Debian) between 2021-02-16 & 2021-03-27

**Comment by jtappin** [comment]
Other (possibly) useful notes:
I'm running Manjaro (Stable)
plplot is 5.15.0

I've only tested with the regular X window output.

**Comment by GillesDuvert** [comment]
OK, two things in one:
- called without options, gdl now uses the wxwidgets driver, and for some reason plplot's wxwidgets driver does not plot points (too optimised wxwidgets point-filling algorithm?) --- we have to solve that.
- called with  option '--no-use-wx' gdl uses the x11 plplot driver and points are drawn.
- So in the meantime, provided your GDL is also compiled with X11 ( -DX11=ON ), the --no-use-wx option is what you need.

**Comment by GillesDuvert** [comment]
solved by #1036
