### ISSUE TITLE
Fix tiff deprecations warnings

### ISSUE THREAD

**Issue by jkohnert** [gnudatalanguage/gdl#1034]
uint16/uint32 etc are deprecated. The patch changes those types to uint16_t/uint32_t etc.

[fix_tiff_deprecation_warnings.txt](https://github.com/gnudatalanguage/gdl/files/6912767/fix_tiff_deprecation_warnings.txt)

**Comment by alaingdl** [comment]
Thanks you. Such cleanings of the code are very welcome. 
Since you will trying to do PR, we can wait till that !
But the sooner the better since we are close to deliver 1.0.0 !

**Comment by jkohnert** [comment]
See https://github.com/gnudatalanguage/gdl/pull/1038

**Comment by GillesDuvert** [comment]
thanks!
