### ISSUE TITLE
WIDGET_INFO(/n_children) does not work for a menu button.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1052]
Sorry folks, here's another widget issue.

When a button widget is created with the /menu option and a number of menu buttons are connected to it, `widget_info(mb, /n_children)` returns 0, even though `widget_info(mb, /all_children)` correctly returns the IDs of all the menu buttons.

Example: [wi_test.pro](https://github.com/gnudatalanguage/gdl/files/6983313/wi_test.txt)

When clicking on any of the regular buttons (with a base as a parent) the number of children of that base is correctly shown, but when a menu item is selected the number of children shows as zero.

**Comment by jtappin** [comment]
P.S. It looks like widget_info(/child) also has the same problem.

**Comment by GillesDuvert** [comment]
there are several INFO unfinished business indeed...

**Comment by GillesDuvert** [comment]
solved in #1054
