### ISSUE TITLE
check if generated ANTLR files match .g files within CI

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#1056]
@pjb7687 Once we were testing using Travis if the generated ANTLR files match the .g files:
https://github.com/gnudatalanguage/gdl/pull/529/commits/1af865695a772363297c8a6fb97a49193f986636

I haven't found relevant code in the current GithubActions scripts, but I'm not familiar with the new script yet, please could you confirm if this is still part of our CI runs or not? (and if not, it would be great to bring it back)

**Comment by pjb7687** [comment]
I have made a small modification to the scripts to test ANTLR, the workflow will be run once a week regularly, or also can be triggered manually here:
https://github.com/gnudatalanguage/gdl/actions/workflows/antlr.yml

**Comment by GillesDuvert** [comment]
very useful! :+1:

**Comment by slayoo** [comment]
Thank you !!!
