### ISSUE TITLE
REBIN is veeery slow

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#1061]
Especially annoying as CONGRID() , forcibly more complicated, is as fast as IDL's.

**Comment by Jeanne-jw** [comment]
We did some tests these days.  Right, it's veeery slow !!
And we found something very interesting : 
```
GDL> a=dist(1024*8L)
% Compiled module: DIST.
GDL> tic & b=rebin(a, 128,128) & toc  
% Time elapsed :       0.80554295 seconds.
GDL> tic & b=rebin(a, 128,256) & toc
% Time elapsed :      0.076997042 seconds.
```
It seems possible to choose a better strategy of the order of calculate in the REBIN() code and make it quicker.  Trying...

**Comment by GillesDuvert** [comment]
Indeed, quite strange.
notice that 
```
GDL> tic & b=rebin(a,128,128,/sam) & toc
% Time elapsed :      0.021533012 seconds.
GDL> tic & b=rebin(a,128,256,/sam) & toc
% Time elapsed :     0.0085539818 seconds.
```
Shows the same behaviour, but the `/SAMPLE` makes the calculation fast as there is no addition of adjacents pixels.
perhaps the algorithm takes a wrong decision on whether it should explore the 'big' array 'linearly' and add to the 'small' or the inverse.
The code is a bit nightmarish as it whoudl work for 8 dimensions...

**Comment by GillesDuvert** [comment]
solved in https://github.com/gnudatalanguage/gdl/pull/1217/commits/6f772b9a1d3fc3c5481a4fdd2aa261b2d6f3696c
