### ISSUE TITLE
WIDGET_TEXT, a number of issues.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1064]
There are a number of issues I've found with editable text widgets under GDL (all with 1.0.0 on Manjaro Linux).

1. When the text from a multi-line widget is retrieved with `widget_control, id, get_value=text`, it is returned as a single string with line-feed characters rather than as a string array.
2. When an `enter` is entered in a widget with `editable` set and `all_events` not set (upper box in the demo), a `WIDGET_TEXT_CH` event is returned with the `CH` field set to 10b, but the newline is not entered into the text.
3. When  `all_events` is set as well (lower box) then **any** character entry action produces two `WIDGET_TEXT_CH` events, the first is the expected one with `CH` set to the character entered and then the second has the `CH` field set to the character immediately after the entry point.
The first two can be worked around in the event handler though it's a bit clumsy (the commented-out code in the demo is a workaround for Number 2), not sure about the last one.

A quick demo code that allows these effects to be seen [test_text.pro](https://github.com/gnudatalanguage/gdl/files/7015416/test_text.txt).

**Comment by GillesDuvert** [comment]
Thx @jtappin there is hope on this one.

**Comment by GillesDuvert** [comment]
Hi James, thanks to testing so accurately the widget suite.
concerning 2 above, I note that 'return' is not inserted when the widget ysize is 1.

**Comment by GillesDuvert** [comment]
solved by  #1081

**Comment by jtappin** [comment]
Thanks @GillesDuvert, 
I am currently trying to get my venerable GRAFFER plotting program running under GDL[*], so it's giving the widgets a fairly thorough workout. This is the original all-IDL version rather than the GTK-Fortran port that is on GitHub, and since about 1.0.0.rc3 the widgets have been mature enough to make that a viable proposition--well-done the core team for that.

[*] the first version came out in 1995, before livetools or itools were invented.

**Comment by GillesDuvert** [comment]
Oh  yes, graffer of course. I have it around, but never got it to work, until now. Well, almost, as it crashes GDL, even with my most recent changes. Excellent GDL bugs hunting place!

**Comment by GillesDuvert** [comment]
(blush) I have to patch GDL fast. Error was introduced in the "/child" option added recently.

**Comment by GillesDuvert** [comment]
Patch done.
