### ISSUE TITLE
GDL reserves LUN for spawn command and does not free it

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1066]
GDL reserves for each spawn command a LUN and does not free it later. IDL does not have this problem.

bash$ pwd
/tmp

bash$ gdl
  GDL - GNU Data Language, Version 1.0.0-rc.3 git
GDL> for i=0,30 do spawn,'pwd &'
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
/tmp
% SPAWN: SPAWN: Failed to get new LUN: GetLUN says: All available logical units are currently in use.
% Execution halted at: $MAIN$          
GDL> 
GDL> help,/files
 maxUserLun : 99 fileUnits.size() : 128
         lun 100: /dev/zero
         lun 101: /dev/zero
         lun 102: /dev/zero
         lun 103: /dev/zero
         lun 104: /dev/zero
         lun 105: /dev/zero
         lun 106: /dev/zero
         lun 107: /dev/zero
         lun 108: /dev/zero
         lun 109: /dev/zero
         lun 110: /dev/zero
         lun 111: /dev/zero
         lun 112: /dev/zero
         lun 113: /dev/zero
         lun 114: /dev/zero
         lun 115: /dev/zero
         lun 116: /dev/zero
         lun 117: /dev/zero
         lun 118: /dev/zero
         lun 119: /dev/zero
         lun 120: /dev/zero
         lun 121: /dev/zero
         lun 122: /dev/zero
         lun 123: /dev/zero
         lun 124: /dev/zero
         lun 125: /dev/zero
         lun 126: /dev/zero
         lun 127: /dev/zero
         lun 128: /dev/zero
GDL>

**Comment by GillesDuvert** [comment]
solved by #1081
