### ISSUE TITLE
Curent versions (git & 1.0.0) no more compilable on Debian 9, U1804, U1604, U1404 ... due to old cmake versions ?

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1073]
two weeks ago, I was able to compile GDL on my Debian 9 around, on U18.04, U16.04, U14.04, but today I can't, at the end on "cmake" I have
`-- Configuring incomplete, errors occurred!`

One serious problem is that I see no information how to fix that, and no clear message
in CMakeOutput.log & CMakeError.log . CMake run to the end, just issue this message.

I suspected CMake version, and yes, with 3.20 (loaded through module load ...) on Debian 9 it is OK, but it is not the default one on Debian 9

I try also other intermediate versions (cmake-3.10.3, cmake-3.12.4), without success

I do have success with 3.13.4 compiled by my-self

I clearly prefer we reduce the dependencies coverage and being able to compile with old Cmake versions !!

**Comment by pjb7687** [comment]
Could you try removing these two lines (lines 13-14 of `CMakeLists.txt`):

```
cmake_policy(SET CMP0075 NEW)
cmake_policy(SET CMP0077 NEW)
```

I had the same problem today, and I think this should be fixed in the next version...

**Comment by slayoo** [comment]
the policy lines were introduced here:
https://github.com/gnudatalanguage/gdl/pull/1047/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a

@jkohnert could you please elaborate on why we prefer "NEW"?

**Comment by jkohnert** [comment]
@slayoo there is no specific reason for "NEW" other than the old policies are deprecated, give warings on current versions of cmake, and will be removed in later versions.

CMP0075 was introduced in cmake 3.12, CMP0077 was introduced in cmake 3.13 , both released in 2018. Ubuntu 1404 and 1604 both have reached end-of-life in 2019, and 2021 respectively. However, Ubuntu 1804, and Debian 9 still have LTS, so should indeed be supported. I have some VMs available, so a can have a look on a better solution than just enabling them.

**Comment by alaingdl** [comment]
Thanks ! It is working fine now.

**Comment by slayoo** [comment]
Thanks @jkohnert!
