### ISSUE TITLE
Error: invalid attribute for formula 'gnudatalanguage': version ("")

### ISSUE THREAD

**Issue by QingjieYang7** [gnudatalanguage/gdl#1080]
Hi, I am trying to install GDL on my macOS Big Sur 11.5.2 by Homebrew.

Firstly, I did this:
$ brew create --cask –set-name gnudatalanguage /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/gnudatalanguage.rb

It works, then I copy the content from https://github.com/brewsci/homebrew-science/blob/master/Formula/gnudatalanguage.rb
 
Then, I tried to install GDL, then the below happened 
 
% brew install gnudatalanguage
Error: invalid attribute for formula 'gnudatalanguage': version ("")
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/formula.rb:286:in `validate_attributes!'
/usr/local/Homebrew/Library/Homebrew/formula.rb:215:in `initialize'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:181:in `new'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:181:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:412:in `factory'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:632:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:628:in `map'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:628:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cli/parser.rb:307:in `parse'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:131:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:129:in `<main>'
 
If you have any suggestions, please tell me what I should do next step.

**Comment by GillesDuvert** [comment]
Hi, all this looks like a homebrew problem, worth reporting to them. Especially since we have a new 1.0.0 version out.

But I suggest to follow the instructions in our wiki (link atop this page). Especially since the last changes in GDL provide a better user experience on mac (as they say).

Finally, have a look at #606 as our colleague @pjb7687 added the creation of a DMG as byproduct of the GH continuous integration, this is a WIP to be tested and commented on #1074

**Comment by QingjieYang7** [comment]
@GillesDuvert Thank you for your reply. I have installed GDL by Macport which is easier than using Homebrew. Like you said this looks like a homebrew problem.

**Comment by slayoo** [comment]
Please note that Macports, as of now, ships the Jun-2020 1.0.0-rc.3 version of GDL (https://ports.macports.org/port/gnudatalanguage/)
