### ISSUE TITLE
Windows installer artifact obtained with #1081 fails on infamous 'semaphore' assertion 

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#1087]
Was lazy enough to not try recompile from scratch with build_gdl.sh, tried the installer artefact on a W10 VM, got:

Assertion failed: semaphore_info != (SemaphoreInfo *) NULL, file ../GraphicsMagick-1.3.36/magick/semaphore.c, line 601

???

**Comment by pjb7687** [comment]
Fixed. It was due to #1063

**Comment by GillesDuvert** [comment]
We have a crash with any magick operation today. reopening this in case fix is just a revert.
