### ISSUE TITLE
histogram function returns very strange message and crashes: % GSL Error #1: x not found in range of h

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1089]
I have an array of 6231 integers that are almost a lindgen(6231). 
The histogram of it with the keyword REVERSE_INDICES crashes:

GDL> help,set_b
SET_B           LONG      = Array[6231]
GDL> bb=Histogram(set_b,REVERSE_INDICES=rb)
% GSL Error #1: x not found in range of h
% Execution halted at: $MAIN$          
GDL> 

In IDL the calculation is correct.

Here the plot of the variable set_b:

![image](https://user-images.githubusercontent.com/59102584/131176735-971f3799-3748-473b-bcd8-28d7262f3eba.png)

Here the histogram of it:

![image](https://user-images.githubusercontent.com/59102584/131176816-63b2a23b-e873-4adf-b76d-d4dfd38889ef.png)

Here how to reproduce:

>unzip set_b.zip
GDL> openr,1,'set_b'
GDL> set_b=lonarr(6231)
GDL> readu,1,set_b
GDL> close,1
GDL> bb=Histogram(set_b,REVERSE_INDICES=rb)
% GSL Error #1: x not found in range of h
% Execution halted at: $MAIN$          
GDL> 

[set_b.zip](https://github.com/gnudatalanguage/gdl/files/7068992/set_b.zip)

**Comment by alaingdl** [comment]
ok, thanks. I succeed to reproduce. If I do : 
`bb=Histogram(set_b-mean(set_b),REVERSE_INDICES=rb)`
the calculation are OK

I will look inside. May be we need to remove the offset ?

**Comment by alaingdl** [comment]
I *like* such funny bug if you change slightly a parameter you have a good result ...
* set_b+2000 is KO, set_b+20 000 is OK ...
* if nbins is set to anything bigger than unity, it is OK ...

**Comment by alaingdl** [comment]
Thanks for your very clear bug report.
Fortunately I clearly made a comment in the code years ago : this bug is related to a bug in old GSL version, which is now corrected.

If you need to go ahead you can comment the single line 
` gdl_make_uniform (hh, hh->n, a, b); ` in code `gsl_fun.cpp`
(you can see the comments above)

The problems are : 
* to make a protection against old buggy GSL versions
* to add more tests in testsuite related to Histogram

**Comment by alaingdl** [comment]
just to note that just making this correction is not OK for the basic tests in `test_histo.pro` then we do have some work to do before saying it is fixed !

**Comment by alaingdl** [comment]
Spend few time today on `test_histo.pro` : it has to be extended and improved ! And most of the code is not really tested ...

**Comment by alaingdl** [comment]
@Jeanne-jw  is working hard on that, and writing tests and reading documentation she discovered some __subtleties__ we never implemented in GDL. I hope we will have soon a PR !

**Comment by alaingdl** [comment]
Thanks to an important work by @Jeanne-jw the whole code of HISTOGRAM() has been revised, errors, inaccuracies corrected and new cases (eg for BYTE) added. The test was renamed in `test_histogram.pro` with a lot of new cases inside.
