### ISSUE TITLE
Text widgets & Arrays (another one)

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1092]
When setting a multi  line text widget with an array, the widget shows (correctly) one value per line when the text is an initial value in the `widget_text` call, but when it is set using `widget_control` the values are concatenated into a single string.

Quick demo code attached:
[test_text2.pro](https://github.com/gnudatalanguage/gdl/files/7077660/test_text2.txt)

Manjaro Linux, current GIT version of GDL (since the recent `widget_text` fixes, but the issue was there before but not isolated or analysed, so **not** a regression).

**Comment by GillesDuvert** [comment]
#1095 will solve this and probably other compatibility issues.

**Comment by GillesDuvert** [comment]
#1095 solves it. However the resizing of bases in some special cases is not good, and not what IDL does. To be worked on again..

Tested a bit graffer, obviously there is some bad event handling by GDL as I'm quickly stuck.

**Comment by jtappin** [comment]
> #1095 solves it. However the resizing of bases in some special cases is not good, and not what IDL does. To be worked on again..
> 
> Tested a bit graffer, obviously there is some bad event handling by GDL as I'm quickly stuck.

I doubt if the currently released graffer will work properly, I've done a fair bit of cleaning up since the last public release. 

What I want to do with it once it's usable in GDL, which it nearly is, is to combine the IDL/GDL version with the Fortran version and update the whole setup on GitHub at https://github.com/jtappin/graffer which currently has the Fortran version (very out of date) and a subset of GDL.

**Comment by GillesDuvert** [comment]
with #1103 I do not see any problem with "the currently released graffer", it permitted me to find and cure 2 more bugs.
Still, the pixmaps on buttons in graffer are missing, when they are not in the `testsuite/interactive_tests/test_widgets.pro` test.
This is probably related to #1101

**Comment by jtappin** [comment]
> with #1103 I do not see any problem with "the currently released graffer", it permitted me to find and cure 2 more bugs.
> Still, the pixmaps on buttons in graffer are missing, when they are not in the `testsuite/interactive_tests/test_widgets.pro` test.
> This is probably related to #1101

Almost certainly the case. I've dropped most pixmap buttons in recent versions as they were more trouble than they were worth, especially in pulldown menus.

**Comment by GillesDuvert** [comment]
Well, now that pixmap buttons work, they are not so ugly in the 'old' graffer ...
