### ISSUE TITLE
WIDGET_BASE sizing problem when child of WIDGET_TAB

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1093]
Sorry folks, me again. 
This one is a bit of a corner case, but made a nice mess of the axis settings menus in GRAFFER.

If a base widget that is a child of a tab widget does not have a row or column attribute, then even if it contains a column (and probably row as well) base as its first child, then the resulting widget layout is truncated. So far as I can see this happens if any of the children of the tab is a "simple" base.

At least in this case, there is a simple workaround by making the children of tabs be column bases.

Reasonably simple example: [test_bsize.pro](https://github.com/gnudatalanguage/gdl/files/7092310/test_bsize.txt)

Manjaro Linux, GDL from current GIT.

**Comment by GillesDuvert** [comment]
Hi James, well done! `widget_base` without /col or /row do not have an associated wxWidgets 'sizer' and the size and placement must be computed by GDL... for each internal widget types... Probably forgot the necessary in cas of a 'tab' container.
The easiest solution is to have all non-row or column bases declared with /col.
But indeed this is a bug, GDL widgets should ideally work with an unedited IDL code.

**Comment by jtappin** [comment]
Thanks, that's more-or-less what I thought was happening.

P.S. I think most of GRAFFER now works in GDL, there are a few uglies and glitches that I've not had time to chase into corners yet but plots can be displayed, edited and sent to PS files.

**Comment by GillesDuvert** [comment]
#1095 will close this.
