### ISSUE TITLE
map_proj_forward() doesn't like structure as a keyword

### ISSUE THREAD

**Issue by sjfrasier** [gnudatalanguage/gdl#1104]
GDL> map_set, 35,-70, 0, limit=[20,-80,50,-60], /mercator
% Compiled module: MAP_SET.
% Compiled module: MAP_ADJLON.
% Compiled module: FILEPATH.
% Compiled module: STRMATCH.
% Compiled module: MAP_CLIP_SET.
% MAP_PROJ_FORWARD: Unable to convert variable from type struct.
% Error occurred at: GDL_SET_MAP_LIMITS    47 /usr/share/gnudatalanguage/lib/map/gdl_set_map_limits.pro
%                    MAP_PROJ_INIT      616 /usr/share/gnudatalanguage/lib/map/map_proj_init.pro
%                    MAP_SET            158 /usr/share/gnudatalanguage/lib/map/map_set.pro
%                    $MAIN$          
% Execution halted at: $MAIN$

**Comment by alaingdl** [comment]
This seems to be related to a side effect of a very recent change in `envt.cpp`

```

   diff gdl-1.0.0-git210821CMake/src/envt.cpp gdl-1.0.0-git210827CMake/src/envt.cpp
1542,1543c1542,1552
<   if( !keyword->Scalar()) return true;
<   if( keyword->Type() == GDL_STRUCT) return true;
---
>   if( !keyword->Scalar()) Throw("Expression must be a scalar or 1 element array in this context.");
>   if( keyword->Type() == GDL_STRUCT) Throw("Unable to convert variable from type struct.");
>   return keyword->LogTrue();
> }
> //this version is for testing boolean KWs when the default is 'set' = true when they are not defined/present etc (see code)
> bool EnvBaseT::BooleanKeywordAbsentOrSet( SizeT ix)
> {
>   BaseGDL* keyword=env[ix];
>   if( keyword == NULL) return true;
>   if( !keyword->Scalar()) Throw("Expression must be a scalar or 1 element array in this context.");
>   if( keyword->Type() == GDL_STRUCT) Throw("Unable to convert variable from type struct.");
1546d1554

```

HTH

**Comment by GillesDuvert** [comment]
Indeed, the above patch will break GDL in unchecked places. Reverting it is mandatory. done.
caveat: the GDL and IDL behaviour is now different in some cases see #1051 but let's treat them when they come.
