### ISSUE TITLE
GDL built on Windows can't start (because of GraphicsMagick update ??)

### ISSUE THREAD

**Issue by eloirozier** [gnudatalanguage/gdl#1107]
I tried to compile from the current master branch on MSWin and everything went well.
But the executable throws an error and crashes:

`Assertion failed: semaphore_info != (SemaphoreInfo *) NULL, file ../GraphicsMagick-1.3.36/magick/semaphore.c, line 601`

**Comment by GillesDuvert** [comment]
idem in #1087
