### ISSUE TITLE
AXIS indexing does not match IDL

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1108]
The axis index numbers used by GDL start from 1 for the X-axis, whereas in IDL they start from 0.
This can cause problems if the [XYZ]TICKFORMAT keywords are used to pass a  formatting function that then makes decisions including the axis index.
Also the tick index is not reset to zero at the start of a new axis, thus preventing (e.g.) special actions for the first tick.

Quick demo: [axproc.pro](https://github.com/gnudatalanguage/gdl/files/7105143/axproc.txt)

**Comment by GillesDuvert** [comment]
awesome! solved in #1109
