### ISSUE TITLE
CONTOUR: incorrect results when one coordinate is 2-D and the other 1-D

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1114]
The CONTOUR procedure produces invalid plots when one of the coordinates is a 1-D array and the other is 2-D, a case that IDL supports, but PLPLOT does not.

For example this code:
````
a = findgen(20)
b = findgen(20)
x = a#b
aa = a[*,intarr(20)]
contour, x, a, b               ; Good
contour, x, aa, b              ; Bad
bb= transpose(aa)
contour, x, aa, bb             ; Good
contour, x, a, bb              ; Bad
````
As far as I can see, the only way around this is to promote the 1-D array to 2D in this case.

P.S. I don't think that PLPLOT's surface routines (plot3d* and plsurf3d*) can handle 2-D coordinate arrays at all so I don't think there's much we can do there.

**Comment by GillesDuvert** [comment]
OK, in restrospect this is logical (for IDL) but not foreseen when writing the GDL routine.
Implicit promotion should IMHO be implemented at lower level that function per function (PLOT (done), CONTOUR and SURFACE, SHADE..) in this case, but it's very simple.
