### ISSUE TITLE
WIDGET_CONTROL transposes colour bitmap buttons

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1118]
When using colour bitmap button labels, while passing the value in the `widget_button` call produces the expected result, if `widget_control` is used then the image is transposed. The attached demo code should illustrate the problem.

[cbm_check.pro](https://github.com/gnudatalanguage/gdl/files/7145452/cbm_check.txt)

**Comment by GillesDuvert** [comment]
#1119 should cure that, plus a severe bug found while testing. Thanks!
