### ISSUE TITLE
Bitmap areas are incorrectly sized in menu buttons.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1123]
More of an irritance than a showstopper, but when a button with a bitmap label (mono or colour) is a child of a button, the area allocated is (generally) too large and seems to be determined solely by the X- dimension of the bitmap.

It appears that the size allocated is 2*max(nx)+30 by nx+10. Not sure what's ideal but something like max(nx)+20 by ny+10 would seem sensible.

Quick demo: [pd_layout.pro](https://github.com/gnudatalanguage/gdl/files/7153449/pd_layout.txt)

**Comment by GillesDuvert** [comment]
@jtappin the demo procedure you take time to make and join are invaluable!
Unfortunately in this case, the extra size is due to wxWidgets, that reserve room for bitmap, text and accelerators in menu entries, and apparently there is no way to make the 'unused' parts to zero size.

**Comment by jtappin** [comment]
That's a bit of a pain. Thanks for checking anyway.

**Comment by GillesDuvert** [comment]
Actually there is one (or two) wxwidgets bugs. 1) the height of the menu entry is dictated by the largest dimension of the bitmap, not the height of the bitmap (silly). 2) wxwidgets asserts that the label string is non-null.
Obviously this follows (indirectly) so-called human interface guildelines followed by MacOSX, GTK... IDL, based on Motif, was there way before such things as human interface guidelines were present.
So, one simple counsel: use squared (16x16 or 32x32 preferably ) pixmaps!

**Comment by jtappin** [comment]
Seems a bit crazy. 
I'm not sure it is using the largest dimension as the portrait bitmaps are being truncated.
IDL (8.6.0) must do something different as the demo gives sensible spacings on IDL.
