### ISSUE TITLE
WRITE_TIFF replacement

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1126]
Since the current `write_tiff` doesn't support true colour images or honour colour tables correctly, here is an alternative. Still very limited functionality.

[write_tiff.pro](https://github.com/gnudatalanguage/gdl/files/7171104/write_tiff.txt)

**Comment by GillesDuvert** [comment]
commited directly in main today

**Comment by brandy125** [comment]
Why the distributed write_tiff is different from the mentioned one here above?
Can we replace it with that one here that supports true color images?

**Comment by slayoo** [comment]
Seems that the intended replacement was bogus: https://github.com/gnudatalanguage/gdl/commit/4235743960005111f24c50cac188bb76f15c5254

Here's a new PR introducing the new file: https://github.com/gnudatalanguage/gdl/pull/1458

Thanks @brandy125 for reporting it!

**Comment by slayoo** [comment]
@brandy125 @jtappin please suggest if there is any quick way to test the new functionalities so that we could add a unit test to the new PR ensuring that the CI workflow checks if these work, thanks.

**Comment by brandy125** [comment]
Mayby something based on the following:

pro test_write_tiff_func

   CATCH, Error_status
 
   IF Error_status NE 0 THEN BEGIN
      PRINT, 'Image array with (k,n,m) is not supported while it should be'
      exit,status=1
      CATCH, /CANCEL
   ENDIF
   on_error,3
   a=bytarr(3,4,4)
   write_tiff,'/dev/zero',a
end

**Comment by slayoo** [comment]
@brandy125 Thank you!
We need something more portable than `/dev/zero` as the CI tests are also run on Windows
If possible, could you please create a PR with such test.
Thank you!
