### ISSUE TITLE
Tree widgets not supported

### ISSUE THREAD

**Issue by SkippySky** [gnudatalanguage/gdl#1127]
Are Tree widgets on eh to-do list?

**Comment by GillesDuvert** [comment]
they are present.

**Comment by SkippySky** [comment]
Hi Giloo,

>they are present.

Really?

Not in a particularly useful way, it seems…

 

Regards,

 

Andrew

**Comment by GillesDuvert** [comment]
Probably not useful, but there.
The only way to improve the situation is to provide us with working (i.e., test procedures) examples of what would be an 'useful' tree widgets.
Such issues are often quicly set, see #1064 , #1092 etc

**Comment by SkippySky** [comment]
>The only way to improve the situation is to provide us with working (i.e., test procedures) examples of what would be an 'useful' tree widgets.

 

Ok, there’s a distributable package of IDL code that can be downloaded and run to show what real IDL does with the Tree widgets (and Check_menu parameter…)

and I have the source IDL code as well.



When, where and how do you want it all…?

 

The program is AVISTACK2 from http://www.avistack.de/

 

Andrew

 

PS : I’m not sure it’s possible to create a small working subset of the widgets. The program makes very extensive use of  Objects, and I think would be enormously difficult to trim down.

At least for me.

**Comment by GillesDuvert** [comment]
@SkippySky  According to its documentation avistack will be something GDL may have difficulties to swallow, not simply because of minimal support of widget_tree, but I suspect ROIs and reference points will be a problem. 
Meaning avistack is also an excellent testground for GDL's bugs and improvements! 
A quick test with IDL's examples for widget_tree shows that yes indeed : #1120 
I'm reluctant to deal with avistack's entire code at once. Let's first close #1120 .

**Comment by SkippySky** [comment]
Avistack2 dates from 2010, so there’s nothing outrageously new in the IDL, it’s just fully Object Orientated from the get-go through a  ~hundred different source code files.

 

The author, Dr Michael Theusner, lost interest in the programs some years ago, and made the source code public. A number of non-IDL folks tried to convert it to a C variant, but were stumped 

by the OO-ness of it all. 

 

AViStack2 has faded from being the pre-eminent processor of astronomy video due to the lack of ongoing development.

 

Andrew

**Comment by GillesDuvert** [comment]
Indeed and that's a major purpose of GDL, to enable use of such abandoned code. I gather you have the IDL procedures at hand? Because the distributed code is only for idl vm (and already that is important as it gives an idea of the widgets behaviour).
I will come back to you ASA  #1127 is solved.

**Comment by SkippySky** [comment]
Hi,

 

Here’s a working VM distributable of AVISTACK2 (IDL v8.71) and the source IDL code in the Source folder.  

 

http://www.cool.id.au/astronomy/AviStack_2.zip

 

This should keep you off the streets at night for some time… 😉

 

Andrew

**Comment by GillesDuvert** [comment]
Tree widget part is complete (including Draw widget drag and drop). Closing. 
Next issue for having AviStack2 working is now #1165.
@SkippySky , we count on you to periodically retrigger some interest in having Avistack2 up and running.
