### ISSUE TITLE
Checked_menu parameter not suported in WIdget_Button

### ISSUE THREAD

**Issue by SkippySky** [gnudatalanguage/gdl#1128]
Are checked_Menu ticks on the to-do list?

**Comment by GillesDuvert** [comment]
They are presently ignored.
```
GDL> ID = Widget_Button(3, Value='Complicated Menu',/checked)
% Warning: Keyword parameter CHECKED not supported in call to: WIDGET_BUTTON. Ignored.
```
They eventually will be implemented if demand is strong :smile:

**Comment by SkippySky** [comment]
>They eventually will be implemented if demand is strong 😄

So far, 100% of people asking about Checked_menu are in favour of implementing it… 😉

 

Andrew

**Comment by GillesDuvert** [comment]
Indeed, that's very strong :smile: 
See #1127 , an example?

**Comment by jtappin** [comment]
I would agree that it is one of the things I miss, but since I had a workaround in the form of a solution that I'd used before it existed in IDL, I resurrected that in `CW_PDMENU_PLUS` in [Graffer](https://github.com/jtappin/graffer-gdl). 

Basically it adds ` [ ]` to an unselected button and ` [*]` to a selected one.
Doesn't work on bitmap buttons though.

**Comment by GillesDuvert** [comment]
Should not be so hard, wxWidgets makes checked menus easily.

**Comment by GillesDuvert** [comment]
Should be OK as soon as #1136 is merged.

**Comment by jtappin** [comment]
There are a couple of issues that are likely to be toolkit related:

1. Although bitmap labels are accepted and the statefulness is recognized, no state indicator appears on the button.
2. The select field of a checkable menu button does not have a useful  SELECT field (as in IDL), however **unlike** IDL the toggle indicator does change state. I suspect that this is a fundamental difference between WxWidgets' implementation of check menus and Motif's.

**Comment by GillesDuvert** [comment]
Dear James, are your comments related to widget_tree , or another type? SELECT is not mentioned in widget_button's help page 
Concerning widget_tree indeed everything will soon be OK.

**Comment by jtappin** [comment]
Hi Gilles
Sorry, it got a bit garbled, but I was referring to the `SELECT` field in the widget_button event structure which for "normal" check buttons reflects the  state after the click, and the SET state as seen and controlled by `widget_info(/button_set, id)` and `widget_control, id,set_button={1|0}`.

In both IDL & GDL the `SELECT` field in the event is always 1 for checked menu items, but in GDL the indicator changes, in IDL it does not.
Also for any menu button (I've not tried with ordinary buttons), GDL does maintain a meaningful  and settable button set state for non check buttons, while IDL does not.

P.S. I've never used widget_tree (for one thing all of the "fresh start" IDL widget code that I've done started before it existed).
