### ISSUE TITLE
prototype 'WShow' does not match any in class 'DeviceWIN'

### ISSUE THREAD

**Issue by pjb7687** [gnudatalanguage/gdl#113]
When GDL is compiled with WxWidgets:
```
C:\projects\gdl\src\devicewin.cpp:407:6: error: prototype for 'bool DeviceWIN::WShow(int, bool, int)' does not match any in class 'DeviceWIN'
 bool DeviceWIN::WShow(int ix, bool show, int iconic)
      ^~~~~~~~~
In file included from C:\projects\gdl\src\devicewin.cpp:25:0:
C:\projects\gdl\src\devicewin.hpp:72:7: error: candidate is: bool DeviceWIN::WShow(int, bool, bool)
  bool WShow(int, bool, bool);
       ^~~~~
src\CMakeFiles\gdl.dir\build.make:678: recipe for target 'src/CMakeFiles/gdl.dir/devicewin.cpp.obj' failed
mingw32-make[2]: *** [src/CMakeFiles/gdl.dir/devicewin.cpp.obj] Error 1
mingw32-make[2]: *** Waiting for unfinished jobs....
CMakeFiles\Makefile2:123: recipe for target 'src/CMakeFiles/gdl.dir/all' failed
```
Build log: https://ci.appveyor.com/project/pjb7687/gdl/build/1.0.3

**Comment by slayoo** [comment]
@maynardGK is it related with the changes in WShow from you PRs #32 and #110 ?

**Comment by GillesDuvert** [comment]
@pjb7687  please, Wshow() definition should be removed from devicewin.cpp and devicewin.hpp. It is defined in graphicsdevice.cpp and has been patched in rev 7238160 to add functionalities. Should work ok.
Ultimate target for Windows port is of course to use only the wxWidgets interface which is common to all systems.

**Comment by maynardGK** [comment]
On Tue, Apr 10, 2018 at 5:23 AM, GillesDuvert <notifications@github.com>
wrote:

> @pjb7687 <https://github.com/pjb7687> please, Wshow() definition should
> be removed from devicewin.cpp and devicewin.hpp. It is defined in
> graphicsdevice.cpp and has been patched in rev 7238160
> <https://github.com/gnudatalanguage/gdl/commit/723816053fe7bf6b40d62d0b6830ecf2dcda9b08>
>  to add functionalities. Should work ok.
> Ultimate target for Windows port is of course to use only the wxWidgets
> interface which is common to all systems.
>

 In theory I agree, but when I did that trick and tested operation, the 2D plot window went away altogether. 

Overall, 2D plotting via wingcc/wingdi is less robust now that I have copied then new set of routines; I haven't had time to isolate what the problem is.
I will turn my attention to graphics once I can get the remainder of basic_pro and gdlhelp submitted.

**Comment by GillesDuvert** [comment]
@maynardGK Excellent! If switching to devicewx and removing devicewin is too complicated, it would be still nice to align as much as possible devicewin and gdlwinstream to the current shape of, respectively, devicewx and gdlwxstream. (devicex and gdlxstream have tons of tricks to bypass plplot's driver limitations)

**Comment by maynardGK** [comment]
I don't know why, but removing deviceWIN::WShow makes things much worse, but it is already bad:
![nowshow1](https://user-images.githubusercontent.com/7710053/39158246-c27c9fc8-4713-11e8-98ff-785fcc3b530d.png)

The dialog in the blue window shows the last run and prior to that, the run made with deviceWIN::show removed.  The grey boxes in the plots are what happens in windows when your plot has corrupted the program; this occured when I tried to close a window with the "close window" button.

**Comment by maynardGK** [comment]
@GillesDuvert OK I've just noticed what you are talking about, in the code.

class DeviceWIN : public GraphicsDevice{
...
class DeviceX : public GraphicsMultiDevice {
...
class GraphicsMultiDevice : public GraphicsDevice {

Probably, deviceWIN won't need WShow once it has become a GraphicsMultiDevice

**Comment by slayoo** [comment]
@pjb7687 @GillesDuvert @maynardGK can we close this one?

**Comment by maynardGK** [comment]
I think we are good with this now.
