### ISSUE TITLE
CVTTOBM: has a bit offset problem when the BM is not a multiple of 8.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1130]
I'm not quite sure I see where it's happening, but `cvttobm` produces a sheared image when the button is not a multiple of 8 along the X-direction (e.g. [3floppy_unmount.xbm](https://github.com/gnudatalanguage/gdl/files/7185200/3floppy_unmount.txt)).

I had implemented a somewhat different concept, shortly before `cvttobm` was added to GDL, so this proposed replacement is a fusion of the current version with that one:
[cvttobm.pro](https://github.com/gnudatalanguage/gdl/files/7185202/cvttobm.txt)

.

**Comment by GillesDuvert** [comment]
thanks a lot, will be implemented ASAP!
