### ISSUE TITLE
many links in the README cannot be opened

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1135]
There are 40 links in the README and 8 of them cannot be opened:

http://plplot.sourceforge.net/source/index.html
ftp://ftp.unidata.ucar.edu/pub/netcdf
ftp://ftp.ncsa.uiuc.edu/HDF/HDF/HDF_Current
ftp://ftp.ncsa.uiuc.edu/HDF/HDF5/current
http://numpy.scipy.org/
http://hdf.ncsa.uiuc.edu/
http://hdf.ncsa.uiuc.edu/HDF5
ftp://ftp.unidata.ucar.edu/pub/netcdf

Can anybody take care and "repair" them?

**Comment by alaingdl** [comment]
working on that. hdf4/hdf5 moved to a big consortium, the hdf group
the 2 unidata FTP are OK for me

**Comment by alaingdl** [comment]
done in #1137

Please check whether it is ok for you
