### ISSUE TITLE
"Variable is undefined: !NULL" when calling David Fanning's cgzplot procedure

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1143]
Don't know how important this issue is but if someone has time would be nice to repair it.

When downloading D. Fanning's coyote programs (http://www.idlcoyote.com/programs/zip_files/coyoteprograms.zip) and calling cgzplot then I get the following messages:

```
GDL> a=findgen(1000)
GDL> cgzplot,a,a
% Compiled module: CGZPLOT.
% Compiled module: CGZPLOT__DEFINE.
% Compiled module: CGGRAPHICSKEYWORDS__DEFINE.
% Compiled module: CGDEFCHARSIZE.
% Compiled module: LINKEDLIST__DEFINE.
% Compiled module: CGERASE.
% Compiled module: CGSETCOLORSTATE.
% Compiled module: CGGETCOLORSTATE.
% Compiled module: CGCOLOR.
% Compiled module: CGCOLOR24.
% Compiled module: CGPLOT.
% Compiled module: SETDEFAULTVALUE.
% Compiled module: CGCHECKFORSYMBOLS.
% Compiled module: CGDEFAULTCOLOR.
% Compiled module: COLORSAREIDENTICAL.
% Compiled module: CGERRORMSG.

Traceback Report from CGPLOT:

     Variable is undefined: !NULL
GDL> % Compiled module: CGBITGET.
% Compiled module: CONVERT_TO_TYPE.

Traceback Report from CGPLOT:

     Variable is undefined: !NULL

Traceback Report from CGPLOT:

     Variable is undefined: !NULL

Traceback Report from CGPLOT:

     Variable is undefined: !NULL

GDL> 
```

It opens an empty window and a second window with following message:

![Screenshot_2021-09-22 10 03 04_ljwjaQ](https://user-images.githubusercontent.com/59102584/134351217-9c8f4429-0c7a-49c0-878a-12ea7a330e29.png)

Doing the same in IDL I get a nice zoomable plot.

**Comment by GillesDuvert** [comment]
interestingly cgplot,a,a works.
and cgzplot works (sort of) with GDL 0.9.8
This bug is annoying, thanks for the report!

**Comment by GillesDuvert** [comment]
In fact, this is related to !NULL being passed in keywords, such as:
```
GDL> toto=Ptr_New(/Allocate_Heap)
GDL> a=*toto
GDL> plot,dist(10),xrange=a      
% PLOT: Keyword array parameter XRANGE must have 2 elements.
```
when IDL cleverly ignores such an 'undefined' argument, and behave just as if 'xrange=a' was never present.
closing and opening a new issue about this.
