### ISSUE TITLE
PLOT: {xy}style=2 is ignored.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1145]
The plot procedure ignores the "extended range" flag `xstyle=2` etc. (All the other flags seem to work correctly).
For example:
````
!p.multi=[0,2,2]
plot, findgen(20)                           
plot, findgen(20), xsty=1, ysty=1
plot, findgen(20), xsty=2, ysty=2
plot, findgen(20), xsty=3, ysty=3
````
I'm not sure if it ever worked or not, but in the current git (21 Sep.) , the first & third and the second and fourth plots are identical.

**Comment by GillesDuvert** [comment]
closed by #1190
