### ISSUE TITLE
HDF5: variables/attr treated as double regardless of type

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#115]
Double precision is assumed within the HDF5 interface.

Here's a minimal code drafted for a unit test as reported on SF.net back in 2011 (https://sourceforge.net/p/gnudatalanguage/bugs/358/):
```
GDL> $cat bug.pro
pro bug
spawn, 'rm -f bug.h5; echo -e "' $
+ 'PATH g1/d1 \n' $
+ 'INPUT-CLASS TEXTIN \n' $
+ 'INPUT-SIZE 16 \n' $
+ 'RANK 1 \n' $
+ 'DIMENSION-SIZES 3 \n' $
+ 'OUTPUT-CLASS IN \n' $
+ 'OUTPUT-SIZE 8 \n' $
+ '" | h5import bug.txt -c /dev/stdin -o bug.h5'
f = h5f_open('bug.h5')
d = h5d_open(f, 'g1/d1')
v = h5d_read(d)
help, v
print, v
end
GDL> $cat bug.txt
2011 01 23
GDL> bug
% Compiled module: BUG.
V DOUBLE = Array[3]
127.00000 1.0000000 23.000000
```

**Comment by slayoo** [comment]
@ogressel could you please comment on this one given the recent updates? Thanks!

**Comment by ogressel** [comment]
I encountered this as well. The routine that maps HDF5 types to GDL types vie H5Tequal() does not check for invalid type handles (causing it to return GDL_DOUBLE irrespectively). I have already refactored it using C++ lists instead of the boilerplate code. The patch breaks the H5T_STRING test thought, which I plan to generalize as soon as I find the time.

**Comment by ogressel** [comment]
I just checked that the current version gives the correct result (as does my refactoring of the type mapping from today).

GDL> bug
V               BYTE      = Array[3]
 127   1  23

My unit tests for reading data/attributes now also use '/no_typeconvert' in 'array_equal()', which catches such issues.

I'd say it is safe to close the issue.

**Comment by ogressel** [comment]
> The patch breaks the H5T_STRING test thought, which I plan to generalize as soon as I find the time.

I found a simple way to avoid this by testing the type *class* against H5T_STRING, rather than the data type itself.

**Comment by slayoo** [comment]
Thank you!
