### ISSUE TITLE
plot window requires a click to refresh

### ISSUE THREAD

**Issue by sjfrasier** [gnudatalanguage/gdl#1152]
I find that I must click in the plot window to get a new plot to show up, i.e. refresh.  Is there a setting somewhere that removes the need for this action?  I have been using GDL as a real-time display for a radar application, and this issue kills it.  Running GDL on CentOS 8 (actually Rocky Linux).  It worked great under the prior PLplot driven graphics.

**Comment by alaingdl** [comment]
:disappointed: 

1/ could you try to start GDL without Wx : `gdl --no-use-wx`
2/ could you please send a snippet around we can try to reproduce the behavior ? Is it just a PLOT, or a TV ??

**Comment by sjfrasier** [comment]
1/  flag seems to have no effect.  Still says using WxWidgets.
$ gdl --no-use-wx
  GDL - GNU Data Language, Version 1.0.0 Git
- For basic information type HELP,/INFO
- Using WxWidgets as graphics library (windows and widgets).
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

Behavior is the same with or without flag.

2/ 
GDL> plot, indgen(10)     ; window is created and the plot appears
GDL> plot, indgen(20)     ; has no effect until I click in the plot window

The issue is the same for both plot and tv.

**Comment by alaingdl** [comment]
The good new on my side : unable to reproduce that. On local and on remote.

Did you compile GDL ? Did you use a RPM ?

I see now no explanation

**Comment by brandy125** [comment]
On my machine the —no-use-wx flag has no effect as well (git version)

**Comment by sjfrasier** [comment]
I think this might be an issue with Wayland as opposed to X11 -- 'click-to-focus'.  Still, the 0.9.9 version (from rpm) appears to work fine on Wayland.

**Comment by GillesDuvert** [comment]
Hm folks the circumstances need to be precised a bit...Of course a 'plot' command must update the plot without the (silly) need to click on the window, and that up to now never happened, and does not happen in most cases as Alain confirms.
However, there is a potential problem with the new plot windows that use the plplot+wxWidgets driver, in that the update of the plot is done when the driver "thinks it is needed", so I can figure there may be a veto from the windowing system (Wayland) if the window does not have focus. This is embarrassing, these things are too clever, and there is no indication anywhere on how bypass these system barriers.
A simple solution would be to switch back to good ole plplot+X11 driver, that is the role of the `--no-use-wx` switch. But it needs that GDL is also compiled with X11, i.e., that` -DX11=ON` is passed to the Cmake building command. --- apparently not the case on @brandy125 machine too.
But @sjfrasier could you check that your window manager does not apply some sort of so-called "focus stealing prevention" (KDE example here)
![image](https://user-images.githubusercontent.com/33936193/135051678-cc16a68e-6887-4d62-b5f9-0cc8adede604.png)
If not, we'll try other solutions, but will need to get the same environment (CentOS RockyLinux) as yours to test.

**Comment by sjfrasier** [comment]
So, using gnome-tweaks, I changed the window focus to 'sloppy' from 'click-to-focus.'  In that instance, the plot window updates only when I move the cursor over the plot window.  So the window system is indeed intercepting the plot command.  I don't seem to have a 'focus stealing prevention' option in gnome-tweaks.

**Comment by sjfrasier** [comment]
I will try re-compiling with -DX11 and use the --no-use-wx flag for now

**Comment by sjfrasier** [comment]
Actually,  can login using x11 instead of Wayland, and the problem goes away.  So, definitely a Wayland issue.

**Comment by sjfrasier** [comment]
I spoke too soon...  The problem is resolved for the simple two interactive lines I used to illustrate the problem.  But the more general problem is illustrated by the following:

GDL> for i=0, 300 do plot, sin(2*!pi*findgen(100)/(200 - i))

With the old plplot driver, I see an animation as expected. With the new wx driver, even under X11, I get a long pause and eventually see the last plot.

**Comment by GillesDuvert** [comment]
Thanks for the report.
Well, I found [this](https://github.com/wxWidgets/Phoenix/issues/743).
Meaning that an additional `Refresh()` command is probably needed somewhere, but it can arrive from the eventloop itself.
could you uncomment lines 111 to 115 of gdl/src/gdlwxstream.cpp  and rebuild, without  -DX11 or with -DX11=OFF ?

(Funny, IDL complains about "`for i=0, 300 do plot, sin(2*!pi*findgen(100)/(200 - i))`" )

**Comment by sjfrasier** [comment]
That does indeed fix it.  It is quite a bit slower than with the plplot driver, however.

**Comment by sjfrasier** [comment]
With the uncommenting, while noticeably slower than plplot driver, it updates in a regular fashion under X11.  Under wayland it shows erratic jumpy behavior that seems to depend on if I move the mouse -- weird.

**Comment by GillesDuvert** [comment]
Hm we'll need to find the good tuning: too few calls to the wxWidgets eventloop update will hang the plots, too many will indeed slow the plot process. Will probably need that we install a CentOS8 machine for further tests.

**Comment by GillesDuvert** [comment]
@sjfrasier could you revert to the current GDL sources (commenting again lines 111 to 115 in gdl/src/gdlwxstream.cpp) and replace 
  `wxClientDC dc(this);` by   `wxPaintDC dc(this);` at line 5635 of gdlwidget.cpp
then rebuild etc ?

**Comment by sjfrasier** [comment]
Sure thing.  This happened:
 
  GDL - GNU Data Language, Version 1.0.0 Git
- For basic information type HELP,/INFO
- Using WxWidgets as graphics library (windows and widgets).
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

GDL> for i=0, 300 do plot, sin(2*!pi*findgen(100)/(200 - i))

../src/gtk/dc.cpp(276): assert "cr" failed in wxPaintDCImpl(): using wxPaintDC without being in a native paint event
Gtk-Message: 10:00:45.019: GtkDialog mapped without a transient parent. This is discouraged.

(gdl:65409): Gtk-WARNING **: 10:00:45.020: gtk_window_set_titlebar() called on a realized window
Gtk-Message: 10:00:45.021: GtkDialog mapped without a transient parent. This is discouraged.
Trace/BPT trap (core dumped)

**Comment by GillesDuvert** [comment]
Ah but I do not have this behaviour at all! (I love the 'this is discouraged') 
May I ask the version of gtk and wxWidgets on your system?

**Comment by sjfrasier** [comment]
Here's what's installed.  Not quite sure what is being used...

gtk2.x86_64                                    2.24.32-5.el8
gtk3.x86_64                                    3.22.30-6.el8

wxGTK.x86_64                                   2.8.12-20.el7
wxGTK3.x86_64                                  3.0.4-11.el8

**Comment by GillesDuvert** [comment]
I'll try to set up a Rocky Linux 8.3 virtual machine if that is what you have. For the time being, your solution is not to use Wayland I believe? (I see Wayland to be superior over X11 only for the security, well if it is to have tons of good ole X11 programs not working, thanks a lot.)

**Comment by sjfrasier** [comment]
Currently running Rocky Linux 8.4, identical to CentOS 8.4 until 12/31, and will follow RHEL8 after that.  I don't have any particular attachment to Wayland vs X11.  But I guess Wayland is the way things are going?

**Comment by sjfrasier** [comment]
So, yeah, will use X11.

**Comment by GillesDuvert** [comment]
Obliged to add a synchro point where the wxwidgets eventloop will catch the graphic update and refresh, otherwise plots in for...end loops will not show correctly. 'Normal' as the wx eventloop is not in a separate server thread (as would be X11) but in the same thread as GDL ... hopefully changed in the future.
IMHO solves this issue.

**Comment by slayoo** [comment]
@GillesDuvert @alaingdl Would this and other recent activity and fixes warrant a new release?
@pjb7687 what is the release workflow right now, how can we properly make a release?

**Comment by GillesDuvert** [comment]
I would say "yes"...

**Comment by alaingdl** [comment]
We (I) made the mistake to have RC around ... I am OK for a 1.0.1

We have room for : 
* 1.0.2 if I succeed to solve all the issues I detected in HELP
* 1.0.3 for HISTOGRAM (bugs + speed + tests ...)
* 1.0.4 for speed improvement in some String primitives 
* 1.1.0 for Qhull by Eloi ...

**Comment by pjb7687** [comment]
> @GillesDuvert @alaingdl Would this and other recent activity and fixes warrant a new release? @pjb7687 what is the release workflow right now, how can we properly make a release?

Hi @slayoo, sorry I have been a bit busy these days.. If i recall correctly you can just push a new tag to release a new version. But it seems the latest GA failed to compile and it needs to be fixed first.

**Comment by GillesDuvert** [comment]
Alain is right, we should try (if it is not too heavy for you publishers) release more often.

**Comment by slayoo** [comment]
@pjb7687 what is the workflow to bump version id? (https://github.com/gnudatalanguage/gdl/commit/e337f57f0a95d297e5420111c025ef10094cf3fa)

**Comment by pjb7687** [comment]
Oh I did it manually

**Comment by slayoo** [comment]
so (all in master branch):
- bump to 1.0.1
- tag release
- bump to 1.0.1 git
right?

**Comment by pjb7687** [comment]
Yes

**Comment by slayoo** [comment]
thanks, after the release (please do it), I volunteer to write up the changelog

**Comment by pjb7687** [comment]
okay, I will fix the GA build first and then release it

**Comment by pjb7687** [comment]
#1161

**Comment by slayoo** [comment]
release notes added
