### ISSUE TITLE
write_jpeg writes jpg upside down

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1153]
Can anybody confirm that write_jpeg writes the image upside down?

GDL> plot,findgen(100) & a=tvrd() & write_jpeg,'gdl.jpg',a

![image](https://user-images.githubusercontent.com/59102584/134959327-631bdb77-66e1-4af1-9533-cae1d7d318df.png)

Opening gdl.jpg with any image viewer:

![image](https://user-images.githubusercontent.com/59102584/134959209-382c97ee-95f2-4126-83d2-7b0cb042592f.png)

**Comment by alaingdl** [comment]
Horrible ! I factually saw the regression was introduced between 2021 June 30 (OK) and July 4 (KO) but I am not able to locate a diff related to that effect :( 
(just a X11 vs MAC ... but nothing related to jpeg or displaying)

**Comment by GillesDuvert** [comment]
ugly indeed!
corrected.
