### ISSUE TITLE
READ_ & WRITE_ PPM absent, QUERY_PPM non-functional (fixes attached)

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1154]
Currently the `read_ppm` & `write_ppm` routines are not available, and `query_ppm` always returns 0 (checks for 'PNM' when it should check for 'PPM' and for 'PGM'.
The attached routines should solve the problem.
[query_ppm.pro](https://github.com/gnudatalanguage/gdl/files/7245133/query_ppm.txt)
[write_ppm.pro](https://github.com/gnudatalanguage/gdl/files/7245134/write_ppm.txt)
[read_ppm.pro](https://github.com/gnudatalanguage/gdl/files/7245135/read_ppm.txt)

**Comment by GillesDuvert** [comment]
Thanks James, your changes are part of #1157
