### ISSUE TITLE
Procedure not found: GDL_IMPLIED_PRINT

### ISSUE THREAD

**Issue by kkin1995** [gnudatalanguage/gdl#1155]
Hi, I compiled and install GDL on Linux from the instructions given under "Way 1" on this page: https://github.com/gnudatalanguage/gdl/wiki/GDL-on-Linux.

The installation was successful, however, if I try to print on the REPL without using the "print" command, it gives the following error:

```
Procedure not found: GDL_IMPLIED_PRINT
```

Printing works as expected with the "print" command.

Thanks for any help!

**Comment by alaingdl** [comment]
Did you make the final `./scripts/build_gdl.sh install` ?
I think it is just a small problem of GDL_PATH. Could you check your GDL_PATH ?
When I did it, I do have :

```
./install/bin/gdl
  GDL - GNU Data Language, Version 1.0.0 Git
[...]
GDL> help,/path
!PATH (Disabled, 7 directories)
/home/alaingdl/GDL/gdl-1.0.0-git210929CMake/install/share/gnudatalanguage/lib (138 files)
/home/alaingdl/GDL/gdl-1.0.0-git210929CMake/install/share/gnudatalanguage/lib/CMprocedures (5 files)
[...]
GDL> a=1
GDL> a
       1
GDL> .r install/share/gnudatalanguage/lib/utilities/gdl_implied_print.pro 
```

Then `GDL_IMPLIED_PRINT` is in the path.

**Comment by kkin1995** [comment]
Apologies for late response. Yes, I ran the final script and the GDL_IMPLIED_PRINT worked after that. Thanks !
