### ISSUE TITLE
GAUSS2DFIT: missing MPFIT2DFUN

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1158]
When trying to use `gauss2dfit` the error:
````
% MPFIT2DPEAK: ERROR: the required functions MPFIT and MPFIT2DFUN must be in your IDL path
````
is generated. 
On checking, it turns out that `mpfit2dfun` is not in the GDL directories. Downloading it and adding it to my path allows the fitting to work.
This routine should be obtained from Craig M.'s site and included.

**Comment by GillesDuvert** [comment]
solved in #1164 , thanks James!
