### ISSUE TITLE
Status of GDL on Apple Silicon ?

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1167]
Do we have any report of success of GDL compilation on Apple with the new M1 processors ?

I did received one negative feedback, without details

**Comment by brandy125** [comment]
Tested it right now and compiled/run normally:

***@***.***:~/gdln/gdl-master/build/src$ uname -a
Linux ubuntu 5.8.0-56-generic #63~20.04.1-Ubuntu SMP Tue Jun 8 01:47:26 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

***@***.***:~/gdln/gdl-master/build/src$ ./gdl
  GDL - GNU Data Language, Version 1.0.1 Git
- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): /usr/local/share/gnudatalanguage/lib
- Using WxWidgets as graphics library (windows and widgets).
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

GDL> print,!GDL
{ 1.0.1 Git Oct 21 2021  1634785200   1   1   1}
GDL>

**Comment by Jeanne-jw** [comment]
I met the problem like this:
for way 0: brew install gnudatalanguage: No available formula or cask with the name "gnudatalanguage".
for way 1: In my Mac ( MacOS Big Sur 11.6, Apple M1) the path of CMAKE_C_COMPILER and CMAKE_CXX_COMPILER are separately "/opt/homebrew/opt/llvm/bin/clang" and "/opt/homebrew/opt/llvm/bin/clang++", they are different with what they are assumed to be in build_gdl.sh, which are "/usr/local/opt/llvm/bin/clang" and "/usr/local/opt/llvm/bin/clang++".
So I just changed the PATH in the file build_gdl.sh and then it worked.  
Will this cause problems in later procession ?

**Comment by alaingdl** [comment]
Way 0 : ha, sorry, gnudatalanguage formula is no more available in Brew, we have to correct that in the wiki.

Way 1 : did you already go a message from the script _build_gdl.sh_ ? I received positive feedback recently for OSX 11.x (not sure of the sub-version) and in the past, at some point, one is a link on the other one ...

**Comment by slayoo** [comment]
https://github.com/brewsci/homebrew-science/blob/master/Formula/gnudatalanguage.rb

**Comment by slayoo** [comment]
It seems to be still there:
https://github.com/brewsci/homebrew-science/blob/master/Formula/gnudatalanguage.rb

but first you need to ad the science tap:
```
$ brew tap brewsci/science 
```
or
```
$ brew tap homebrew/science
```

**Comment by Jeanne-jw** [comment]
Thank you very much!
Yes, after taping
$ brew tap brewsci/science
the formula gnudatalanguage can be found!

**Comment by GillesDuvert** [comment]
yes but it is 0.9.7, in eh, 2017? and we are 1.0.1

**Comment by alaingdl** [comment]
Concerning the compilation of current version, no problem on OSX with 1.0.1 git version with qhull (`brew install qhull`) on OSX 11.6 and the script build_gdl.sh

**Comment by Jeanne-jw** [comment]
I realize that using Homebrew for M1, packages are installed into the /opt/homebrew/ folder. But x86_64 Homebrew is still usable on M1 Mac, and using this version of homebrew, the path would be /usr/local/homebrew, which would match the path in build_gdl.sh 
Referencing website: https://medium.com/mkdir-awesome/how-to-install-x86-64-homebrew-packages-on-apple-m1-macbook-54ba295230f#bf20
