### ISSUE TITLE
reimplement WMENU using wxWidgets (as of now it is the only cause for dependency on zenity)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#117]
As reported on SF.net (https://sourceforge.net/p/gnudatalanguage/bugs/434/) by @lluvia, there are several routines in the src/pro collection implemented with help of calls to zenity (dialog_message, dialog_pickfile, wmenu), however, this dependency is not checked at build-time. Would be great to add a check to CMake.

**Comment by GillesDuvert** [comment]
dialog message and pickfile are now in C++ code using wxWidgets. wmenu should use widgets too.

**Comment by slayoo** [comment]
Should we move the dialog_message.pro and dialog_pickfile.pro to the pbsolete folder then?
