### ISSUE TITLE
write_csv multiple data field entry

### ISSUE THREAD

**Issue by brbarker** [gnudatalanguage/gdl#1178]
I was trying to write multiple data fields using write_csv and it wouldn't let me because it said the data fields must be the same size. I knew they were the same size, so I looked at the write_csv.pro file and in line 177, there is an issue with "input3" being called when "input2" should be called. I have screenshots of before and after tests to show the issue and it being resolved. I don't know how to go about reporting an issue when I already know the fix, so let me know if I should do anything past posting here. Thanks!

**Comment by slayoo** [comment]
Thank you!
I've just created a PR with this change: https://github.com/gnudatalanguage/gdl/pull/1179
Could you please provide the script which detects this error, so that we include it in the automatic test suite and thus ensure that it will be checked for regressions from now on, thanks!

**Comment by brbarker** [comment]
I'm sorry, can you please explain what you're looking for? I'm still new to coding, so when you say "the script which detects this error", are you asking for the error message that GDL displays when it stops running the procedure? Please forgive my lack of knowledge and I appreciate your help in advance!

**Comment by slayoo** [comment]
In the ``testsuite`` directory, you can find numerous tests written to assert for conditions that were not met before fixing a given bug in  GDL, e.g.: https://github.com/gnudatalanguage/gdl/blob/master/testsuite/test_bug_3313522.pro

What I meant is a .pro file that triggers the error you described. Basically, it should fail with any version of GDL prior to the one in which the bug is fixed, and succeed in a version that contains the fix.

Thanks!

**Comment by brbarker** [comment]
Roger that. I wrote a small .pro that triggers it, but it won't let me put it in this thread. Can I just add the file to the test directory?

**Comment by slayoo** [comment]
Of course, a pull request is the very best way to do it.
After you add the file to the ``testsuite`` directory in your fork, please add an entry to the ``testsuite/LIST`` file, and then create a pull request to the main repo. 
Thanks!

**Comment by brbarker** [comment]
Ok, I'm pretty sure I did all that correctly! Thanks for walking me through it!

**Comment by slayoo** [comment]
addressed in #1179 and #1180
