### ISSUE TITLE
CI test failures are not reported as failed builds

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#1181]
@pjb7687 here's an example of today's CI build in which there are failed tests, however the build is reported as "green":
https://github.com/gnudatalanguage/gdl/runs/4110526525?check_suite_focus=true

```
99% tests passed, 1 tests failed out of 193

Total Test time (real) = 440.87 sec

The following tests FAILED:
	179 - test_timestamp.pro (Failed)
Errors while running CTest
Output from these tests are in: /Users/runner/work/gdl/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
make: *** [test] Error 8
```

**Comment by pjb7687** [comment]
That's intended to mimic the previous Travis build behavior. I can make it fail again on GA if it makes more sense

**Comment by pjb7687** [comment]
And regarding `test_timestamp`, I notice that it only fails on the GA, never fails on my local machine. Perhaps that's not a GDL bug, but because the GA is virtual machine and might have some overhead running child processes?

**Comment by slayoo** [comment]
Thanks for quick reply.

For sure, at some point, it was working correctly on Travis as otherwise we would have not introduced all the sed one-liners to remove often-failing tests from the Makefile.am... 

Anyhow, by all means, I vote for failing the builds if any of the tests fail (as we have moved the "bad" tests out of the LIST).

**Comment by slayoo** [comment]
(and let's move the `test_timestemp` to `wrong` then for now...

**Comment by pjb7687** [comment]
Okay, fixed: https://github.com/gnudatalanguage/gdl/commit/566694e800facc6f9d082a0dcd1958c564044e67

**Comment by slayoo** [comment]
Thank you!

**Comment by slayoo** [comment]
yet, it seems the behaviour has not changed (https://github.com/gnudatalanguage/gdl/runs/4141902124?check_suite_focus=true):
![image](https://user-images.githubusercontent.com/89685/140800050-66105422-e7f6-44b4-9548-c681d6c10187.png)

**Comment by slayoo** [comment]
I assume it needs to be somehow handled in the ``function test_gdl`` in build_gdl.sh

**Comment by pjb7687** [comment]
Pushed another commit hopefully fix this - if not please open this again!

**Comment by slayoo** [comment]
thank you!
