### ISSUE TITLE
Windows CI stopped working (Cancelled after 360m)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#1184]
example here: https://github.com/gnudatalanguage/gdl/pull/1179

**Comment by pjb7687** [comment]
I think that means GDL compiles, but crashes while startup. Need to investigate recent patches. There might be some memory violations, etc.

**Comment by pjb7687** [comment]
FYI on Windows, when it crashes a dialog is displayed and stuck at there until it is dismissed.

**Comment by pjb7687** [comment]
![image](https://user-images.githubusercontent.com/1440536/140541356-0e5e6ae7-64ce-428b-8bac-8bfd115fa0d0.png)
No GDL bugs, library version mismatch of wxWindows. I will try rebuilding the library cache.

**Comment by slayoo** [comment]
thanks!

**Comment by pjb7687** [comment]
Works well now: https://github.com/gnudatalanguage/gdl/runs/4119205180
