### ISSUE TITLE
FILE_COPY & FILE_MOVE cannot handle ./ in source.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1207]
Neither `file_copy` nor `file_move` work correctly when the source file is of the form `./name`. Target seems to be OK.

e.g. (obviously `d3.png` is just an arbitrary file that exists in the  current directory)
````
GDL> file_copy, './d3.png', './tmp.png'
 FILE_COPY: Invalid source file specified:./d3.png
GDL> file_copy, file_expand_path('./d3.png'), './tmp.png'
GDL> file_copy, 'd3.png', './tmp.png'
GDL> file_move, './d3.png', './tmp.png'
% FILE_MOVE: Unable to obtain file status. File: ./d3.png
% Execution halted at: $MAIN$          
GDL> file_move, file_expand_path('./d3.png'), './tmp.png'
````
When needed `tmp.png` is removed/renamed from outside GDL.
Current GIT (18/11/21) on Manjaro Linux.

**Comment by GillesDuvert** [comment]
works for me, passes all tests... keep fingers crossed....

**Comment by alaingdl** [comment]
It is NOT working for me (U14.04, Debian 10)

(furthermore, the message for FILE_COPY should be revisited : 
GDL : FILE_COPY0: we FAILED to copy d3.png to ./tmp.png
IDL : % FILE_COPY: Destination file already exists. File: tmp.png. )

**Comment by alaingdl** [comment]
I suspect the culprit is WordExp() but be very very very cautious if modifying it, we made a lot of regressions due to that in the past ...

**Comment by jtappin** [comment]
Seems to work OK for me as of commit  https://github.com/gnudatalanguage/gdl/commit/27c415bfe41c189fb8324b3c55ae045e5709e8ed

**Comment by GillesDuvert** [comment]
Aain, your problem is different. It is the error message that is wrong, and not at all what IDL produces. easy to patch, but please submit a new PR.
In general, most of the file_xxx thingies C-like code is, ahem, pretty terrible to maintain ( sorry folks!) .
