### ISSUE TITLE
Writing plots to png unusable - Exporting direct graphics

### ISSUE THREAD

**Issue by abhip0595** [gnudatalanguage/gdl#1215]
probably the same issue. I am trying to export plots from direct graphics to png using write_png but output is unusable. 
I am using WSL - Ubuntu 20.04.3 LTS
![Screenshot 2021-11-25 205748](https://user-images.githubusercontent.com/66953815/143468102-87cff97e-771b-4fac-acd0-a9ddd23cabef.png)
example program I used: [colorfill.pro](http://www.idlcoyote.com/tip_examples/colorfill.pro)
code:
```
PRO 

- [ ] 

- [ ] ColorFill

   ; The data to plot.
   x = Findgen(101)
   y = 4 * Sin(x * !DtoR) / Exp( (x-15) / 25.)

   ; Initial data plot.
   cgDisplay, 750, 500, Title='Filled Area Under a Curve'
   cgPlot, x, y, Background=background, Color='red', /NODATA

   ; Set up the polygon to fill with color.
   low = 20
   high = 45
   lowY  = 4 * Sin(low * !DtoR) / Exp( (low-15) / 25.)
   highY = 4 * Sin(high * !DtoR) / Exp( (high-15) / 25.)
   indices = Value_Locate(x, [low, high])
   lowIndex = indices[0]
   highIndex = indices[1]
   IF x(lowIndex) LT low THEN lowIndex = lowIndex + 1
   IF x(highIndex) GT high THEN highIndex = highIndex - 1

   ; Fill the polygon with color.
   xpoly = [         low,  low, x[lowIndex:highIndex],  high,         high]
   ypoly = [!Y.CRange[0], lowY, y[lowIndex:highIndex], highY, !Y.CRange[0]]
   cgColorFill, xpoly, ypoly, Color='dodger blue'

   ; Repair plot damage caused by the polygon fill and spruce up the plot.
   cgPlotS, xpoly, ypoly, Color='navy', Thick=2
   cgPlot, x, y, /NoData, /NoErase
   cgOPlot, x, y, Color='red', Thick=3

   ;Added write_png to export plot
   write_png,'test.png',tvrd(/true,/order)

END
```

**Comment by GillesDuvert** [comment]
@abhip0595 this works for me very well with today's GDL. Unless you built GDL from scratch, yours (focal fossa) is probably still gdl.0.9.9, this explains that.

**Comment by abhip0595** [comment]
I have installed the latest build 1.0.1
followed steps from https://github.com/gnudatalanguage/gdl/wiki/GDL-on-Linux using the script build_gdl.sh

![image](https://user-images.githubusercontent.com/66953815/143901521-fea33b95-971d-4672-ba91-f7fadcde2e60.png)

I rolled back to previous version (v1.0.0), where I get usable png (plots exported).

the plots are fine in the graphics window but when I try to export (write_png), the image is unusable in (gdl v1.0.1).

**Comment by GillesDuvert** [comment]
Thanks @abhip0595 
OK, so 1.0 works and 1.0.1 is KO.
As there have been lots of changes (for the best) in the recent weeks on the subject of image formats, I guess 1.0.1 is in need of a replacement.
If 1.0 suits you, then keep it and perhaps have a new look when 1.0.2 appears.

**Comment by slayoo** [comment]
@GillesDuvert @acoulais @pjb7687 @ogressel should we then release 1.0.2?

**Comment by pjb7687** [comment]
Makes sense to me. Just ping me when you are ready and I will release 1.0.2.

**Comment by ogressel** [comment]
Not sure what the general release strategy is (how often?, what requirements?, ...).

Currently, I am trying to incrementally improve/extend the functionality of the HDF5 module, which is still "read only", though it should cover most real-world use cases by now, notably *excluding*
1. reading "enum" data types (who uses these?), 
2. partial reads from "compound" types (this might be useful, and maybe not too hard to implement)
3. non-scalar data spaces with compounds (for this I'd need to better understand DStructGDL descriptors/instances, I reckon)

The low-level write routines should in principle be very similar to the read routines, once the "H5T_idl_create" routine is in place.

**Comment by GillesDuvert** [comment]
@ogressel you could create a discussion forum for GDL/HDF5 users (or potential users) to get a roadmap, but at the moment you seem the best person to improve and extent the HDF5 module.
We will try to make much more frequent releases than in the past, 1.0.2  this time, making a note in the release comments that there is improvement continuing on HDF5 is not only necessary but may attract attention from potential users.

**Comment by abhip0595** [comment]
firstly, thank you for looking at the issue. I look forward to new release.
I am using a work around for the time being: SET_PLOT, 'PS' - this way i can still get usable plots for my paper.

once again thank you.

**Comment by GillesDuvert** [comment]
@pjb7687 on my side, #1217 is clearly not ready, so  unless somebody test #1041 and deem it OK, one can make a new release from current (quite adequate) state.
