### ISSUE TITLE
Geotiff

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#122]
As requested at SF.net by AndreasFromI (https://sourceforge.net/p/gnudatalanguage/feature-requests/151/): 

Are there any plans to support geotiff output? Even better, is somebody thinking about a GDAL bridge for IO operations of raster data?

Further comment by @GillesDuvert:

No, but this is probably a good subject for somebody wanting to help. READ_TIFF is already there (.pro file), implementing the /GEOTIFF option needs to tweak a bit the pro file and the C code.

**Comment by slayoo** [comment]
This was also requested here: https://sourceforge.net/p/gnudatalanguage/feature-requests/68/

**Comment by GillesDuvert** [comment]
should be closed as soon as #288 courtesy @rexso is merged!

**Comment by rexso** [comment]
Yes, #288 supports the **GEOTIFF** keyword for **QUERY_TIFF** and **READ_TIFF**.
WRITE_TIFF yet to be implemented.

**Comment by slayoo** [comment]
TIFF/GeoTIFF support is now merged (thank @rexso!)
Closing this ticket, remaining ones are:
- add WRITE_TIFF support: #121 
- enhance TIFF test coverage: #411 
- 3 channels for greyscale: #259

**Comment by maynardGK** [comment]
In windows, when I try geotiff=ON, I cannot run with my custom graphicsmagick build.  It lives ok
with tiff=on proj4=on but geotiff provokes a library loading error.

**Comment by rexso** [comment]
@maynardGK what kind of library error? A conflict between libgeotiff and GM?

**Comment by maynardGK** [comment]
Not much info on the error, the MSYS shell just won't load the graphicsmagick library, 
I haven't diagnosed it yet, but one of the dependencies is probably more advanced than the same dependency in GM.   I loaded geotiff on Feb 2017 but tiff in sept 2015,
so tiff lives ok.
I'll rebuild geotiff here (home) and then see if the result works.  GM is also looking for tiff, jpeg, and zlib.
for geotiff, 
```
depends=("${MINGW_PACKAGE_PREFIX}-gcc-libs"
         "${MINGW_PACKAGE_PREFIX}-libtiff"
         "${MINGW_PACKAGE_PREFIX}-libjpeg"
         "${MINGW_PACKAGE_PREFIX}-proj"
         "${MINGW_PACKAGE_PREFIX}-zlib")
```
<update> I re-built geotiff and simply replacing the library allows gdl.exe to run.
```

greg@Homerw7  /d/bld/sources/pkg/geotiff
$ gdltst
D:/bld/gdl/mingw64-tst1/src/gdl.exe: error while loading shared libraries: libGraphicsMagick++-Q32-3
.dll: cannot open shared object file: No such file or directory

greg@Homerw7  /d/bld/sources/pkg/geotiff
$ pacman -U $dsrc/mingw-w64-x86_64-libgeotiff-1.4.2-2-any.pkg.tar.xz
loading packages...
resolving dependencies...
```

 (then "gdltst" works)`
