### ISSUE TITLE
linker problem on Debian for libSM.so.6

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1220]
I have following problem installing the newest version on 
#1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11):

>make
[ 15%] Built target antlr
[ 15%] Linking CXX executable gdl
/usr/bin/ld: //lib/x86_64-linux-gnu/libSM.so.6: refer�ncia n�o definida para "uuid_generate@UUID_1.0"
/usr/bin/ld: //lib/x86_64-linux-gnu/libSM.so.6: refer�ncia n�o definida para "uuid_unparse_lower@UUID_1.0"
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/gdl.dir/build.make:2419: src/gdl] Error 1
make[1]: *** [CMakeFiles/Makefile2:130: src/CMakeFiles/gdl.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

How to solve this?

**Comment by alaingdl** [comment]
How do you arrive here, using the script `build_gdl.sh` or using by your-self Cmake ?

We have several entries with that, in the issues :( 
First, do you have any Conda related env. around ? If yes, please retry without it

**Comment by brandy125** [comment]
I run cmake by myself.

Yes, I had Conda related environment. Deactivating conda solved the issue.

Thanks for the hint!
