### ISSUE TITLE
problem at execution on OSX 12.0.1

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1221]
Hi. I can compile GDL on OSX 12.0.1 but I cannot start it : 

Compilation succeed with : 
```
cmake .. -DREADLINEDIR=/usr/local/opt/readline -DHDF=off -DPYTHON=off \
        -DLIBPROJ=off -DOPENMP=off -DINTERACTIVE_GRAPHICS=OFF -DQHULL=off
```

Execution fails with : 
```
:~/GDL/gdl-1.0.0rc3-git211207CMake/build/]$ sh ../quick_start_GDL.sh 
Running current GDL with ./src/pro and ./testsuite in GDL_PATH
+/Users/alaingdl/GDL/gdl-1.0.0rc3-git211207CMake/src/pro/:+/Users/alaingdl/GDL/gdl-1.0.0rc3-git211207CMake/testsuite/
2021-12-07 11:28:14.959 gdl[76937:3161595] XType: com.apple.fonts is not accessible.
2021-12-07 11:28:14.959 gdl[76937:3161595] XType: XTFontStaticRegistry is enabled.
./src/common/dpycmn.cpp(137): assert ""IsOk()"" failed in GetClientArea(): invalid wxDisplay object
Collecting stack trace information, please wait...../quick_start_GDL.sh: line 91: 76937 Trace/BPT trap: 5       ${Absolute_PATH}/src/gdl

```

Any idea ?

**Comment by GillesDuvert** [comment]
used build_gdl.sh ? 
there is a possibility that lines 945 to 949 of 'gdlwidget.cpp' creates such issue, in which case they can be safely removed.

**Comment by alaingdl** [comment]
(a small how-to on OSX 12.0.1)

### GDL on OSX 12.0.1 :

Preliminary success on a OSX 12.0.1 *upgraded* from 10.14.6. This is not anecdotal because : 
* I saw X11 files in two places (the new one here : /opt/X11, the old one here : /usr/X11/ )
* Brew is a mess, upgrade and re-install mandatory
* driver xwin for plplot is (may be) not available in Brew version
* compiling with `build_gdl.sh` can be OK but not usable remotely.

### Way 1 : using the script `build_gdl.sh` 

Step 0 : updating Brew `brew upgrade`
Step 1 : update/reinstall python3 and numpy (to avoid to re-run that after errors in the script)
```
brew reinstall python3
(if messages )
rm '/usr/local/bin/2to3'
brew link --overwrite python@3.9
brew reinstall python3
brew reinstall numpy
```
Step 2
```
git clone https://github.com/gnudatalanguage/gdl
cd gdl
mkdir build
cd build
../script/build_gdl.sh prep
../script/build_gdl.sh configure
../script/build_gdl.sh build
```

The problem is, at the end, connected on this machine by `ssh -X` I cannot run _gdl_ : 
```
~/GDL/last-gdl/build/]$ ./src/gdl 
2021-12-07 16:53:31.841 gdl[13693:3372949] XType: com.apple.fonts is not accessible.
2021-12-07 16:53:31.841 gdl[13693:3372949] XType: XTFontStaticRegistry is enabled.
./src/common/dpycmn.cpp(137): assert ""IsOk()"" failed in GetClientArea(): invalid wxDisplay object
Collecting stack trace information, please wait...Trace/BPT trap: 5
```

### Way 2 : compiling by hands

I tried using plplot 5.15 provided by Brew but at the ned, after compilation, when starting GDL X
is not in the device list, and when trying to plot, I got plplot missing xwin driver ...

Step 1 : compiling Plplot 5.15.0
```
wget https://sourceforge.net/projects/plplot/files/plplot/5.15.0%20Source/plplot-5.15.0.tar.gz/download
mv download plplot-5.15.0.tar.gz
tar -zxf plplot-5.15.0.tar.gz 
cd plplot-5.15.0
mkdir Compilation
cd Compilation/
(de-enable tk avoids some problems later when compiling)
cmake .. -DENABLE_tk=off -DENABLE_d=off -DCMAKE_INSTALL_PREFIX=$PWD
make -j 12
cmake install
cd ../..
```

Step 2 : now GDL

```
git clone https://github.com/gnudatalanguage/gdl
cd gdl
mkdir build-cmake
cd build_cmake
cmake .. -DX11=on -DINTERACTIVE_GRAPHICS=OFF -DWXWIDGETS=off -DPYTHON=off -DREADLINEDIR=/usr/local/opt/readline -DHDF=OFF -DHDF5=OFF -DOPENMP=off -DPLPLOTDIR=/Users/the/real/path/to/plplot-5.15.0/Compilation/
make -j 20
```

And now, yes, I do have plots remotely :smile:

**Comment by GillesDuvert** [comment]
It seems to me that to have a plot 'remotely' using ssh -X or the like, you must have X11 on the remote machine (the mac), and GDL using X11 for plots. What you did just fine, but that may not be the end of the story.
You should be able to get 'normal' wxwidget plots and... widgets, (not only must you compile with wxwidgets, have a wxwidget plplot driver (that's what build_gdl.sh does))  by using a remote desktop application  such as teamviewer. Cocoa's not X11 and wxwidgets on mac are cocoa-based.

**Comment by alaingdl** [comment]
I fully agree with you. X11 side clear & working fine.

For the other side (cocoa ...), we do have this issue since years. And IDL too ...

**Comment by alaingdl** [comment]
I forgot to mention that in 10.14.6 remote Matlab was OK for a colleague, but no more in 12.0.1 ... I do not understand why Apple can broke that _basic_ usage of a computer.
