### ISSUE TITLE
glpk detection hardcodes only some lib extensions

### ISSUE THREAD

**Issue by dmacks** [gnudatalanguage/gdl#1229]
In FindGLPK.cmake,
```
find_library(
    GLPK_LIBRARY
    NAMES libglpk.so libglpk.a
    PATHS /usr/lib64 /usr/local/lib /usr/lib
)
```
only accepts shared libs if they have the linux extension, or static libs. On OS X, shared libs have a different extension (and I assume Windows has yet a different extension). Instead of hard-coding "libglpk.so" and "libglpk.a" as the only acceptable filenames, it would be more portable to do:
```
find_library(
    GLPK_LIBRARY
    NAMES glpk
    PATHS /usr/lib64 /usr/local/lib /usr/lib
)
```
and let cmake construct a ton of filename possibilities for various platforms. See for example how FindGSL.cmake does it. I have no idea the wisdom of hardcoding these `PATHS` here, but again it seems non-standard compared to other find_library recipes.

**Comment by slayoo** [comment]
Thanks!
Something along these lines: https://github.com/gnudatalanguage/gdl/pull/1232 ?

**Comment by dmacks** [comment]
Works for me. For self-consistency, I also checked that removing PATHS in the find_path() for the associated glpk.h header works. Caveat is that my glpk is not in /usr or /usr/local, but instead in a different path that cmake knows.

**Comment by GillesDuvert** [comment]
@dmacks  GLPK provides SIMPLEX in GDL. I think it has not been thorougly tested. Please open an issue if you find something suspicious.

**Comment by slayoo** [comment]
>  For self-consistency, I also checked that removing PATHS in the find_path() for the associated glpk.h header works. 

See here: https://github.com/gnudatalanguage/gdl/pull/1235
Thanks!
