### ISSUE TITLE
How to search in history?  "GDL> ^my_favourite"   doesn't work.

### ISSUE THREAD

**Issue by AstroArtie** [gnudatalanguage/gdl#1233]
As it says in the title.

Also - thank you all developers for providing this fantastic alternative to IDL (they went for the wrong business model!). Having written a quarter million lines of IDL code I don't feel particularly compelled to rewrite it all in Python...  Besides, many things seems rather clunky in Python.

Thanks a 1d6,
Regner

**Comment by AstroArtie** [comment]
Okay - solved this one myself. It is indeed GNU readline at work here, and it turns out that <ctrl>-r will start a search back in history, and repeated uses of <ctrl>-r will find previous entries. That is more powerful than IDL's history search, and something I have often missed.
Thank you 'readline' developers! - in case any of you see this.

**Comment by GillesDuvert** [comment]
Wow, many thanks!

**Comment by AstroArtie** [comment]
By the way, how to search the history should be put in the GDL Wiki.
And I noticed that my attempts at writing `<ctrl>-r`  got truncated a bit. The commands are `<ctrl>-r` and `<ctrl>-s` for searching back and forth in history.

**Comment by GillesDuvert** [comment]
done!

**Comment by AstroArtie** [comment]
Perfect!
That was impressively fast :-)
Thank you!
