### ISSUE TITLE
How to interrupt?  <ctrl>-c  or  <ctrl>-d   doesn't work.

### ISSUE THREAD

**Issue by AstroArtie** [gnudatalanguage/gdl#1234]
If this is taken care of by a standard (non-GDL) package, I can read its man-page to find out. I just don't know where to look.
Any help, will be much appreciated!

**Comment by AstroArtie** [comment]
GDL does print:
`^C% Interrupt encountered.`
after a  <ctrl>-c  but it has no effect.

**Comment by GillesDuvert** [comment]
Hi @AstroArtie ^C normally interrupts the flow of actions ASAP, and in my experience it can even be sooner in GDL than IDL.
So you need to be more specific, what action do you want to interrupt by ^C but fail to do so?

**Comment by AstroArtie** [comment]
Hi @GillesDuvert, thank you very much for your reply.
I have now isolated the issue, and it turned out to be a plot with an inadvertently infinite y-range.
<ctrl>-c does indeed work in other cases.
