### ISSUE TITLE
GDL on M1-Pro

### ISSUE THREAD

**Issue by btom54** [gnudatalanguage/gdl#1236]
After building gdl for m1-pro MacBook pro using way 1, I've run into several problems. First I had to change path for clang and clang++ in the build files to /opt/homebrew/opt/llvm/bin. This resulted in a completed build but I've had issues since that I'm slowly working through (mostly IO and object inheritance). I'll probably have questions on object inheritance later but I'm currently having an issue with spawn. The following spawn command issues the indicated error:
GDL> spawn, "ls", unit=lun
% SPAWN: UNIT kw. relies on GNU extensions to the std C++ library (that were not available during compilation?)
% Execution halted at: $MAIN$          
GDL> 
Does this indicate I need to rebuild gdl using gcc rather than clang?

Thanks.

**Comment by GillesDuvert** [comment]
to be merged with #1187 ?
The error message comes from the absence of EXT_STDIO_FILEBUF_H during cmake, but it is very possible that it is the cmake test that is invalid (looks only for include <ext/stdio_filebuf.h>!). We have a bunch of old `#ifdef ` that are obsolete and probably counterproductive those days.

**Comment by btom54** [comment]
Yes I remade gdl and see the following message indicating failure to find EXT_STDIO_FILEBUF_H.

Performing Test REALLY_HAVE_EXT_STDIO_FILEBUF_H - Failed

Thanks.
