### ISSUE TITLE
test_radon (adapt code found on SF.net)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#124]
Joel posted good 12 years ago a test case for the radon (https://sourceforge.net/p/gnudatalanguage/feature-requests/30/):

```
(deleted)
```

Why not to adapt it for the testsuite?

**Comment by GillesDuvert** [comment]
This is word-per-word the test appearing in IDL's documentation for RADON().
I suggest deleting this test text ad make reference to the documentation only available on the web.
BTW, RADON() works with GDL (do this test!).

**Comment by slayoo** [comment]
Thanks Gilles for pointing that out!
