### ISSUE TITLE
force true gnu readline in OSX (12.0.1) with the script

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1241]
one time again a conflict between the pseudo readline/editline provided by OSX *without* some symbols (history) and the true complete GNU one (provided by Brew in the script)

We do need to set

cmake [...] -DREADLINEDIR=/usr/local/opt/readline 

otherwise CMake will link to the bad one ...

**Comment by Barney-9000** [comment]
Ah, is the new brew location of `/opt/homebrew/opt`  just for M1 Monterey, whereas Intel Monterey is still the usual `/usr/local/opt/`?  I didn't appreciate that. I only have Monterey running on an M1 MBP.

**Comment by alaingdl** [comment]
With my new student @Jeanne-jw we spend some time to try to compile GDL on her M1 OSX 12.1. Current version of `build_gdl.sh` is not OK.

At the end we do succeed to have a plot using : 
```
cmake .. -DX11=on -DINTERACTIVE_GRAPHICS=OFF -DWXWIDGETS=off -DPYTHON=off -DREADLINE=off  -DHDF=OFF -DOPENMP=off -DPLPLOTDIR=/Users/jw/GDL/PLplot/plplot-5.15.0/Compilation/
```
where plplot was compiled with : 
```
mkdir PLplot
cd PLplot/
wget https://sourceforge.net/projects/plplot/files/plplot/5.15.0%20Source/plplot-5.15.0.tar.gz/download
mv download plplot-5.15.0.tar.gz
tar -zxf plplot-5.15.0.tar.gz 
cd plplot-5.15.0
mkdir Compilation
cd Compilation/
cmake .. -DENABLE_tk=off -DENABLE_d=off -DCMAKE_INSTALL_PREFIX=$PWD
make -j 12
make install
```
(plplot provided by Brew was not OK (may our fault ;)

We do not succeed to compile with Readline (the version provided by Brew or a version compiled by us) and receive weird messages (after correcting the path for include as usual, to be fix as requested here above) saying gsl/blas/plplot are not OK. But when readline is switched off we can compiled then have plots (X11)


On a classic Intel OSX 12.0.1, I had no problem to have readline + remote plots (through ssh) with : 
```
cmake .. -DX11=on -DINTERACTIVE_GRAPHICS=OFF -DWXWIDGETS=off -DPYTHON=off -DREADLINEDIR=/usr/local/opt/readline  -DHDF=OFF -DOPENMP=off -DPLPLOTDIR=/Users/alaingdl/GDL/PLplot/plplot-5.15.0/Compilation/ 
```

On M1, yes, Brew is now in /opt/homebrew/opt. Before, it was in /usr/local/opt/ ...
