### ISSUE TITLE
10x slower start time on "remote + wx" compare to "remote + X11 only"

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1242]
On a remote computer, Debian 10, access with a VPN

version 1 : default compilation with wxwidget ON
version 2 : cmake .. -DPYTHON=off -DX11=on -DINTERACTIVE_GRAPHICS=OFF -DGRIB=OFF -DWXWIDGETS=off -DQHULL=OFF

I tested that because on version 1, `make test` required ~one hour !
With version, tests take 6 minutes (10 time less)

And I also made comparisons just to launch GDL, using : `time ./src/gdl -e "exit"`
version 1 : ~ 10 sec., version 2 : ~ 1 sec.

**Comment by GillesDuvert** [comment]
Alain,

Please remove lines 945 to 949 of gdlwidget.cpp and try again.

**Comment by alaingdl** [comment]
Tested. Seems to gain just/only 2 s on 10 s ...

I suspect that the time looses to search
Gtk-Message: 14:52:13.752: Failed to load module "canberra-gtk-module"
may also add some extra time ...

**Comment by GillesDuvert** [comment]
2 s is already something.
Wonder if there is some network timeout in addition?
Concerning libcanberra, it s a gtk requirement, what if you install it?

**Comment by GillesDuvert** [comment]
unconclusive
