### ISSUE TITLE
Compile error: includefirst.hpp: No such file or directory

### ISSUE THREAD

**Issue by goduck777** [gnudatalanguage/gdl#1245]
I am trying to compile the 1.01 version using cmake, and I always get the error for finding include files
```
gdl-1.0.1/src/otherdevices/gdlxstream.cpp:18:10: fatal error: includefirst.hpp: No such file or directory
   18 | #include "includefirst.hpp"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```
This error can be fixed by adding "../" before "includefirst.hpp". I wonder if this is an error in the source code, or I should set something for cmake.

**Comment by goduck777** [comment]
I found the error in my own cmake settings.

**Comment by thesamesam** [comment]
> I found the error in my own cmake settings.

What was your error?
