### ISSUE TITLE
missing EDGE_CONSTANT keyword in CONVOL

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1258]
which appeared in IDL 8.6.1

**Comment by GillesDuvert** [comment]
Ouch, CONVOL is too complicated.

**Comment by GillesDuvert** [comment]
On second thought, EDGE_CONSTANT=val is just the EDGE_ZERO case with a nonzero value. But still, implementation is tricky.

**Comment by alaingdl** [comment]
Really tricky ? I hoped to delegated that to @Jeanne-jw !

And you know my way : starting from a case, going in the details ...
(we founded bugs & weakness in the small code of SYSTIME(), unclear keywords management in IDL doc. ; even worse the test cases in `test_systime.pro` were wrong :smile: )

**Comment by GillesDuvert** [comment]
see #1267 . Needs tests.

**Comment by GillesDuvert** [comment]
merged, but tests needed
