### ISSUE TITLE
Missing parameter PSEUDO_COLOR to device routine

### ISSUE THREAD

**Issue by AstroArtie** [gnudatalanguage/gdl#1269]
Between  version  gdl-1.0.0-0.2.20210123git4892c96.fc34.x86_64
and version           gdl-1.0.1-1.fc35.x86_64
the parameter PSEUDO_COLOR is no longer recognized by the device routine:
```
GDL> device, PSEUDO_COLOR=8, decomposed=0
% Warning: Keyword parameter PSEUDO_COLOR not supported in call to: DEVICE. Ignored.

```In the earlier version that command worked perfectly and with no complaints.
Any help will be very much appreciated!

**Comment by GillesDuvert** [comment]
Hi @AstroArtie , I'm pretty sure PSEUDO_COLOR has never been active within GDL, and was even throwing an error before 0.9.7 . 
There may be an issue with the new wxwidgets driver that replaces the old x11 one however in that it may not automatically adjust to the screen depth. I have no way to check.
You may compile gdl with -DX11=ON and start GDL with the X11 driver with the switch `--no-use-wx`  (see 'gdl -h')

**Comment by GillesDuvert** [comment]
adding the wontfix tag is just a way to help us select our support amongst many issues of different importance.

**Comment by AstroArtie** [comment]
Thanks Gilles - sorry for long silence.
PSEUDO_COLOR is indeed not supported in earlier versions either.
And things work well with just
    `GDL> device, decomposed=0`
Except that a change of color-table only affects plotting after that change - the only drawback.
I accept the  'wontfix'.
