### ISSUE TITLE
post-git-migration commits from SVN

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#127]
Based on: https://sourceforge.net/p/gnudatalanguage/svn/log/

- [x] [r4137] by gilles-duvert
   ```correctly throws an error for widget_info(nonexisting_widget,/valid) instead of returning zero.```
- [x] [r4136] by gilles-duvert
   ```should remove GH #251. Please confirm.```
- [x] [r4135] by gilles-duvert
   ```conformant error message.```
- [x] [r4134] by gilles-duvert
   ```align with GH version today```
- [x] [r4133] by gilles-duvert
   ```align with GH version today```
- [x] [r4132] by gilles-duvert
   ```align with GH version today```
- [x] [r4131] by gilles-duvert
   ```align with GH version today```
- [x] [r4130] by gilles-duvert
   ```not valid anymore```
- [x] [r4129] by gilles-duvert
   ```replaced by formats.IDL```
- [x] [r4128] by gilles-duvert
- [x] [r4127] by gilles-duvert 
- [x] [r4126] by gilles-duvert
   ```align with GH repository```
- [x] [r4125] by alaingdl (https://github.com/gnudatalanguage/gdl/pull/292):
   ```these lines are mandatory on Debian with gcc 6.3.0```
- [x] [r4124] by alaingdl:
   ```update of "minimal_script4gdl.sh" to manage Cmake versions above 3.2 ... (needed on OSX)```
- [x] [r4123] by alaingdl (https://github.com/gnudatalanguage/gdl/pull/291):
   ```missing include <omp.h> in a special case```
- [x] [r4122] by alaingdl (https://github.com/gnudatalanguage/gdl/pull/293):
   ```as for CONTOUR, SURFACE should accept "degenerated" 3D equivalent to 2D array```
- [x] [r4121] by alaingdl:
   ```WordExp() crashed when called with a null string ... as a result, openr was broken ...```
- [x] [r4120] by alaingdl:
   ```update "minimum_script4gdl.sh" to have 0.9.8 & 0.9.8 svn```
- [x] [r4119] by gilles-duvert:
   ```align with GH repository (minor changes)```
- [ ] [r4118] by gilles-duvert:
   ```closed two formatting bugs. see on github, pr #197```
- [x] [r4117] by gilles-duvert:
   ```Various small changes to avoid most compilation warnings, especially on travis+icc and osx/clang```
- [x] [r4116] by gilles-duvert:
   ```Implement HEAP_REFCOUNT to show reference count of pointers and objects.```
- [x] [r4115] by gilles-duvert:
   ```trying to fix launchtest linkage problem with Intel compiler. Closes #15 (Github)```
- [ ] [r4114] by gilles-duvert:
   ```removed some icc and clang warnings```
- [x] [r4113] by gilles-duvert:
   ```Avoid using 'display' when there is no... display```
- [ ] [r4112] by gilles-duvert:
   ```removed unnecessary include```
- [ ] [r4111] by gilles-duvert:
   ```Use std::isinf, avoid ambiguous providers```
- [ ] [r4110] by gilles-duvert:
   ```Use proper typing for dynPro/dynFun to avoid strict-aliasing warning```
- [ ] [r4109] by gilles-duvert:
   ```Catch by reference```
- [ ] [r4108] by gilles-duvert:
   ```removed unnecessary include```
- [ ] [r4107] by gilles-duvert:
   ```bsd support (has no sincos)```
- [ ] [r4106] by gilles-duvert:
   ```aspect_ratio is not an iteger division...```
- [ ] [r4105] by alaingdl:
   ```intermittent problem within TEST_BYTSCL_TOP on u1404 ... (see also during make check)```
- [ ] [r4104] by gilles-duvert:
   ```prevent compilation problems when openmp is not present (MacOS). Consequently there will be no parallelism... Is that what MacOs users want? I guess not. Help wanted.```
- [x] [r4103] by gilles-duvert:
   ```simplified convol_inc0 also correcting bug```
- [x] [r4102] by gilles-duvert:
   ```ABSOLUTE kw must be set to be taken into account```
- [x] [r4101] by gilles-duvert:
  ```new more extended convol test.```
- [ ] [r4100] by gilles-duvert:
   ```displaced huge  functions from datatypes to separate files in order to speed up  compilation on multicores and avoid large memory needs for single  compilation.```
- [x] [r4099] by gilles-duvert:
  ```enable compilation without OPENMP```
- [x] [r4098] by gilles-duvert (https://github.com/gnudatalanguage/gdl/commit/15a124f149df663d64bdb54da37fe3dff193ce82#diff-44017ef551a04cb6fa12ff494073bde1):
   ```Thomas Ott patch for windows.```
- [x] [r4097] by gilles-duvert (https://github.com/gnudatalanguage/gdl/commit/15a124f149df663d64bdb54da37fe3dff193ce82#diff-65f7f206953a6602cd00af2548a850b5):
  ```Thomas Ott patch for file_lines and some windows-only patches.```
- [x] [r4096] by alaingdl (https://github.com/gnudatalanguage/gdl/pull/129):
  ```in ESCAPE_SPECIAL_CHAR(), the repetition of Spaces was not well done; in FILE_MOVE, removing "ESCAPE_SPECIAL_CHAR()" (ESC) in intrinsic updated FILE_TEST() &  FILE_EXISTS() functions ... (ESC is only need at spawn level !)```
- [x] [r4095] by gilles-duvert:
   ```(Previous commit message was erroneous). Option /ABSOLUTE of MIN and MAX must be SET and not PRESENT to be activated.``` 
- [x] [r4094] by gilles-duvert:
   ```Previous commit message was erroneous. This commit makes MinMax() optimized and parallell, huge gains in speed.```
- [x] [r4093] by gilles-duvert:
   ```Previous commit message was erroneous. This commit makes MinMax() optimized and parallell, huge gains in speed. This is the new include file for all minmax() operations.```
- [x] [r4092] by gilles-duvert:
   ```Previous commit message was erroneous. This commit makes MinMax() optimized and parallell, huge gains in speed. This is the new test script, giving the results of all testcases in a file.```
- [x] [r4091] by gilles-duvert:
   ```corrected long-standing regression due to the absence of initialization of plplot's colormap 0.```

**Comment by alaingdl** [comment]
what is the real status on that ?!

**Comment by slayoo** [comment]
Alain, just checked and the list above is complete in terms of SVN status.
On the git side, those marked with checkboxes should be OK, all other need checking if they exist in git, and if not need relevant PRs.

**Comment by slayoo** [comment]
@GillesDuvert Am I right that this the following is in SVN but not in git:
https://sourceforge.net/p/gnudatalanguage/svn/4137/
https://github.com/gnudatalanguage/gdl/blob/master/src/widget.cpp#L1919

**Comment by GillesDuvert** [comment]
Indeed, this change was not reported?
Anyway it is a bit false too, since the behaviour is different between /valid, /managed (which should return no error) and all the other keywords that complain when the widget ID is not valid
so the code should be
`if ( widget == NULL) {if (valid || managed) return new DLongGDL( 0 ); else e->Throw("Invalid widget identifier:"+i2s(widgetID));} //note: /display is not currently in gdl`

**Comment by slayoo** [comment]
@GillesDuvert please double check: https://github.com/gnudatalanguage/gdl/pull/573

**Comment by slayoo** [comment]
re r4136:
- SVN change (not reflected in git) https://sourceforge.net/p/gnudatalanguage/svn/4136/
- subsequent analogous changes in git:
  - https://github.com/gnudatalanguage/gdl/commit/06f93838b07f3a30bfdd336633b5e5cc091f2eb5#diff-1d35f875a1e0b27f6255f2b76770d251
  - https://github.com/gnudatalanguage/gdl/commit/61777ded2dd171e329a80821d757a89327e5d61a#diff-1d35f875a1e0b27f6255f2b76770d251

Just consulted with Alain to most likely be OK to tick as resolved

**Comment by slayoo** [comment]
r4130 is reflected here: https://github.com/gnudatalanguage/gdl/commit/d94e4bd64e7136316ba2fe85ad0099d95b4b3335#diff-27d1ca9e10b731476b7641eae2710ac0

**Comment by slayoo** [comment]
r4128 & r4129 addressed here: https://github.com/gnudatalanguage/gdl/commit/ec599b7950e31405489f1a8b760209d0fac7d9f8#diff-55a289f4c9851877b0f360db98821468

**Comment by slayoo** [comment]
r4127 here: https://github.com/gnudatalanguage/gdl/commit/a13729eaf4359ace0e38593a1984fbb24e814365#diff-655466e7abbf30e05cf5fef334078202

**Comment by slayoo** [comment]
r4117 addressed with:
- https://github.com/gnudatalanguage/gdl/commit/4b838d609d5d3680467575be02681e524ce305da
- https://github.com/gnudatalanguage/gdl/commit/4fe0c456be9ea5c671d132bd2ff3f363c1d7db03

**Comment by slayoo** [comment]
r4116 with: https://github.com/gnudatalanguage/gdl/commit/ddb8e051b51710385da7845e94a2f5efad399590#diff-4727f5c733e1875fa5f6e077c1fe3ab1

**Comment by slayoo** [comment]
r4113 with: https://github.com/gnudatalanguage/gdl/commit/6e1e826065ab1370b71c2392ea645e58a9bbad0c

**Comment by slayoo** [comment]
r4091 with multiple commits here: https://github.com/gnudatalanguage/gdl/pull/156

**Comment by slayoo** [comment]
r4099 (IIUC) here: https://github.com/gnudatalanguage/gdl/commit/21f972e664e4c40c401c7aa09609e2b2e1c41ad6

**Comment by slayoo** [comment]
r4101 here: https://github.com/gnudatalanguage/gdl/commit/731d166c5d435669736b241de290fd283e6f2f09#diff-a17787999cb9b912e7f1b67b5c84d79c

**Comment by slayoo** [comment]
r4135 (error message string) is in the repo

**Comment by slayoo** [comment]
r4120 obsolete (minimum_script4gdl changes for older version)

**Comment by slayoo** [comment]
r4102 with:
- https://github.com/gnudatalanguage/gdl/commit/b4b21b6326be1ca1bb00ce4b5403bba0cd453702
- https://github.com/gnudatalanguage/gdl/commit/b517c5bd0bc150a08c257cd4fbade5f77e1fed0e

**Comment by slayoo** [comment]
r4103 here: https://github.com/gnudatalanguage/gdl/commit/bebe840484eca39a6f74fab485ab63f8c02cdfef#diff-4f7baf6dc574054e5f5b0a5dde02dbbf

**Comment by slayoo** [comment]
r4124 obsolete (minimum_script4gdl)

**Comment by slayoo** [comment]
r4115 here: https://github.com/gnudatalanguage/gdl/commit/6a2d729ee5b1714f708db572769cf742f001b680

**Comment by slayoo** [comment]
Closing as done.
