### ISSUE TITLE
slow readf in for loop

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1270]
Reading an ASCII file, GDL is 3 to 5 slower than IDL.

Reading "src/widget.cpp" with the code joined : 

```
idl 8.8 : 0.003
idl 8.6 : 0.005
gdl 0.9.9 : 0.013
current : 0.015
```
[test_speed_readf.pro.txt](https://github.com/gnudatalanguage/gdl/files/7932731/test_speed_readf.pro.txt)

**Comment by GillesDuvert** [comment]
ALL string-related functions in GDL are slow by construction (slow std::string or std::istream) wrt. a pure C implementation.
Good luck!

**Comment by GillesDuvert** [comment]
readf as used in the example calls the method '>>' on the GDL string 'temp'.
This operator is very complicated and the speed is extremely bad as it gets character by character.
Besides, a number of equivalent functions exist in the GDL code, at various places, doing more or less the same, depending on the object where they are defined. One would have expected there exist one and one only Read() and Write() function in all GDL. This render the task of improving GDL speed for read/write extremely difficult and error-prone.

**Comment by GillesDuvert** [comment]
closed, the code is no more "Badly Written/Designed" since:
```
IDL> test_speed_readf,file="errors"
% Time elapsed: 1.4449770 seconds.
GDL> test_speed_readf,file="errors"
% Time elapsed :       0.59982514 seconds.

```
