### ISSUE TITLE
script "build_gdl.sh" not working on OSX 11.5 on M1 (Brew issue ?)

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1283]
We do spend a lot of time to try to compile current GDL git version and also PR #1278 on @Jeanne-jw laptop, a up-to-date Mac running Big Sur 11.5 with the script "build_gdl.sh". We are lost somewhere in the middle on the Brew mechanism.

The CMake way using packages already installed by Brew is not OK : 
* problem with Readline (READLINEDIR should be explicitly provided) 
* stupid problem as usual with python 2 & 3 :cry:
* and more problematic : no graphics with plplot 5.15.0_3 provided by Brew) (with and without --no-use-wx)

Nevertheless at the end we succeed, after compiling with : 
`
cmake .. -DINTERACTIVE_GRAPHICS=OFF -DHDF=off -DOPENMP=off -DPYTHON=off -DX11=on -DPLPLOTDIR=/Users/alaingdl/GDL0103/PLplot/plplot-5.15.0/Compilation -DREADLINEDIR=/opt/homebrew/Cellar/readline/8.1.2/`

Any feedback and advices are welcome.

A. & J.

**Comment by GillesDuvert** [comment]
I suspect #1074 will have problems too. (#1074 is better hanging until a BigSur/M1 version is secured)

**Comment by pjb7687** [comment]
I plan to purchase an M1 machine soon (in April I guess), after that I will try to solve this.

**Comment by GillesDuvert** [comment]
see #1510
