### ISSUE TITLE
Eclipse plugin?

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#130]
Reported back in April 2008 on SF.net (https://sourceforge.net/p/gnudatalanguage/feature-requests/48/):

```
i hope gdl will distributed as a eclipse plugin, so that can be used on several os easily, as IDL 7
```

@gnudatalanguage/gdlteam any comments?

**Comment by xuhdev** [comment]
Why not? :)

**Comment by GillesDuvert** [comment]
Hi folks, 
What would be an eclipse plugin?
Not the [gdlde](https://github.com/gnudatalanguage/gdlde) and not and eclipse IDL plugin (existing)?

**Comment by slayoo** [comment]
@GillesDuvert good point - we do have it: https://github.com/gnudatalanguage/gdlde
