### ISSUE TITLE
Should HISTOGRAM support a faulty feature?

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#1303]
In the course of testing HISTOGRAM() I find a strange IDL feature:
```
IDL> a=lonarr(5) & b=[2,2,3]                     
IDL> print,histogram(b,min=0,max=4,input=a)          
           0           0           2           1           0
IDL> print,histogram(b,min=0,max=4,input=a)
           0           0           4           2           0
```
that does not exist with other types than 'LONG':
```
IDL> a=intarr(5) & b=[2,2,3]               
IDL> print,histogram(b,min=0,max=4,input=a)
           0           0           2           1           0
IDL> print,histogram(b,min=0,max=4,input=a)
           0           0           2           1           0
```
I believe GDL should not reproduce what I would call a bug.
Opinions?

**Comment by alaingdl** [comment]
I can reproduce that in IDL 7.0, 8.4 and 8.8
I don't know the best way today to report a suspected bug to IDL :disappointed: 

```
IDL> a=lonarr(5) & b=[2,2,3]
IDL> for ii=0, 5 do print,histogram(b,min=0,max=4,input=a)
           0           0           2           1           0
           0           0           4           2           0
           0           0           6           3           0
           0           0           8           4           0
           0           0          10           5           0
           0           0          12           6           0
```

Yes, all numeric types but LONG don't do that !

**Comment by jtappin** [comment]
It's not clear to me which behaviour is intended, the documentation is hardly clear. What **is** happening is clear.
When `a` is not a LONG array, it is converted to LONG and the argument is thus treated as an expression.

Clearly the current behaviour is wrong in that it is inconsistent between data types.
To my way of thinking either behaviour is consistent with the documentation.

When I hit a bug in IDL I was able to get a response from the European support address on the L3Harris geospatial web site.

**Comment by alaingdl** [comment]
Now referenced as https://jira.exelisvis.com/browse/IDL-70915  in L3Harris universe

I also got that link https://www.l3harrisgeospatial.com/Support/Self-Help-Tools/Help-Articles/Help-Articles-Detail/ArtMID/10220/ArticleID/18140/The-Life-of-a-Bug-Report-or-Feature-Request-at-Harris-Geospatial
