### ISSUE TITLE
Error with latest git on Manjaro.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1312]
GDL built using the latest GIT as of commit : https://github.com/gnudatalanguage/gdl/commit/bebcbae82556dfa7a502f4503417e5e6d4108d2b, will not run on Manjaro Linux:
````
$ gdl

(process:210217): GLib-GObject-WARNING **: 14:26:05.961: invalid (NULL) pointer instance

(process:210217): GLib-GObject-CRITICAL **: 14:26:05.961: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(process:210217): Gdk-CRITICAL **: 14:26:05.961: IA__gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed

(process:210217): Gdk-CRITICAL **: 14:26:05.961: IA__gdk_colormap_get_visual: assertion 'GDK_IS_COLORMAP (colormap)' failed

(process:210217): Gdk-CRITICAL **: 14:26:05.961: IA__gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed

(process:210217): Gdk-CRITICAL **: 14:26:05.961: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:210217): Gdk-CRITICAL **: 14:26:05.961: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(process:210217): Gdk-CRITICAL **: 14:26:05.961: IA__gdk_window_new: assertion 'GDK_IS_WINDOW (parent)' failed
Segmentation fault (core dumped)
````
The build from: commit c40804b5 (~Apr 4) does run properly.

Installed library versions:
glib2 2.72.0-1
gdk-pixbuf2 2.42.8-1
gtk3 1:3.24.33-2
wxgtk3 3.0.5.1-3

Same as https://github.com/gnudatalanguage/gdl/issues/1305 I think, so that's not debian-specific.

**Comment by GillesDuvert** [comment]
@jtappin strange. The documented cause of the `assertion 'GDK_IS_SCREEN (screen)' failed` is that DISPLAY is not set ?

**Comment by jtappin** [comment]
Few extra notes to add:
- I also see the problem at https://github.com/gnudatalanguage/gdl/commit/c6a7b9a10501e9c48e4f12c53e77b81652ac6733 (on a different Manjaro box).
- On that box, I checked the setting of `DISPLAY` and it is set to `:0` which should be the normal setting when not remote or virtual. (Unsetting it doesn't help).
- All my installs are built as Arch/Manjaro packages using a `PKGBUILD` script.

**Comment by GillesDuvert** [comment]
I see 3 manjaro, manjaro Ornara 21.0 /XFCE and Manjaro Pahvo Gnome or Kde.  Which one is it?

**Comment by jtappin** [comment]
I'm running Manjaro KDE (stable branch, up-to-date).

**Comment by fawltylanguage** [comment]
I get the same error on OpenSuSE Tumbleweed with KDE. ab959bb3 from Apr 4 is OK. DISPLAY is set properly. Probably it's an incompatibility with the KDE desktop.

**Comment by GillesDuvert** [comment]
Pretty strange as the error is seen in #1305 dating back 12 Days (before https://github.com/gnudatalanguage/gdl/commit/ab959bb38be7592ef5687f626060dd8a017292b9) .  Besides, I have a KDE desktop and no problem.

**Comment by jtappin** [comment]
I wonder if there is a situation in which both an updated gdk-pixbuf (or glib2) and a recent gdl is needed?

The gdk-pixbuf package in Manjaro is an Arch package that was built on 17 Mar but only reached the Manjaro stable branch on 15 April. Might be worth checking gdk-pxbuf versions on the systems with problems and those where things run right.

(I'll also post a note in #1305 to suggest the same).

**Comment by GillesDuvert** [comment]
just rebuilt on an opensuse uptodate 20220419 (debug mode) (virtual machine) and no problem.

**Comment by fawltylanguage** [comment]
Here is my fresh (crashing) build on TW 20220419: [gdl](https://www.flxpert.hu/gdl/) Can you try it in your VM?

gdl-lib.txt contains the list of runtime libraries used, gdl-pkg.txt lists the rpm packages.

It was built with `cmake -DQHULL=OFF -DCMAKE_INSTALL_PREFIX=/tmp/gdl ../gdl`. (CMake can not find the system qhull library.)

**Comment by GillesDuvert** [comment]
Hi @fawltylanguage  there are many differences and it does not run.
Already your libwx_baseu-suse.so.3.0.5 is now  libwx_baseu-suse.so.5.0.0  on my openSUSE Tumbleweed . I had more than 1200 updates made when starting the vm.
But, I confirm (I was not paying attention) that 2 error messages appear at star:
```
(process:3373): Gdk-CRITICAL **: 18:47:34.708: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
(process:3373): Gdk-CRITICAL **: 18:47:34.708: _gdk_pixmap_new: assertion '(drawable != NULL) || (depth != -1)' failed
```
But GDL is OK so this is unrelated. Annoying but unrelated.

**Comment by GillesDuvert** [comment]
on Suze one needs to install qhullcpp-devel-static for qhull. Go figure.

**Comment by fawltylanguage** [comment]
I have both libwx_baseu-suse.so.3.0.5 and libwx_baseu-suse.so.5.0.0, cmake selected the older one. The 3.0.5 version is required for filezilla. After removing filezilla and its dependencies, gdl compiles and works. Probably cmake should require libwx 3.1 and reject 3.0.

qhull: OK, qhullcpp-devel-static fixes the problem. You should add qhullcpp to the optional libraries in the README file.

My problems are solved, thanks.

**Comment by GillesDuvert** [comment]
For the record, GDL is OK on my Tumbleweed, as stated above but the linker says:
```
[ 15%] Linking CXX executable gdl
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: warning: libjpeg.so.8, needed by /usr/lib64/libwx_gtk2u_core-3.1.so, may conflict with libjpeg.so.62
/usr/lib64/gcc/x86_64-suse-linux/11/../../../../x86_64-suse-linux/bin/ld: warning: libjpeg.so.8, needed by /usr/lib64/libwx_gtk2u_core-3.1.so, may conflict with libjpeg.so.62
```
... but ldd says i'm linked with `libwx_gtk2u_core-suse.so.5.0.0`
!!!

**Comment by jtappin** [comment]
I've just cross-checked on my system (and had a quick look at the wxwidgets web site.
- On my system there is only 3.0.5 (which is the current stable version).
- 5.0.0 must be a SuSE local convention as the current development version is listed as 3.1.6
- By default Qhull is found and used, disabling it doesn't have any effect on this problem (on Manjaro/Arch qhullcpp is included in the main qhull package).

**Comment by fawltylanguage** [comment]
Lesson learned: after ab959bb, GDL does not work with wxwidgets 3.0.x, only with 3.1.x. This should be documented somewhere or checked in cmake.

**Comment by jtappin** [comment]
Current version works for me after installing `wxgtk3-dev` from AUR. 
(But breaks other tools that I use that are installed from the repositories).

**Comment by GillesDuvert** [comment]
After installing the proper libraries I can run @fawltylanguage 's compiled GDL. It possibly crashes upon the creation of an wxIcon that is done before wxWidgets or something related is created. Simple enough to patch.

**Comment by GillesDuvert** [comment]
OK, solved in #1316

**Comment by jtappin** [comment]
Works for me now, with wx v3.0.5

**Comment by jtappin** [comment]
I guess this can now be closed.
