### ISSUE TITLE
Minor niggle with log plots.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1318]
When making a log plot of data with zeros or negative values, GDL gives the warning:
````
% Warning: Infinite plot range.
````
even when an explicit axis range has been set or the `MIN=` keyword has been set. While this is not a major problem, it does generate a lot of output (e.g. in GRAFFER where plots get redrawn whenever a setting is changed).
Example:
````
a = findgen(16)
b = exp(a)
plot, a, b, /yl
b[5]=0.
plot, a, b, /yl                    ; Gives a warning -- as it should
plot, a, b, /yl, yr=[1.,1e7]       ; Still a warning -- redundant now.
plot, a, b, /yl, min=.1            ; Ditto
````

**Comment by GillesDuvert** [comment]
should be patched now
