### ISSUE TITLE
Crash on compiling huge file

### ISSUE THREAD

**Issue by fawltylanguage** [gnudatalanguage/gdl#1329]
Generate a huge source file and compile it:

```
tmp> for i in `seq -w 1 100000`; do echo a$i=0 >> test.pro; done
tmp> echo end >> test.pro
tmp> gdl
  GDL - GNU Data Language, Version 1.0.1 Git ...
GDL> .comp test
Segmentation fault (core dumped)
```

**Comment by GillesDuvert** [comment]
Hi, clever!
GDL reaches the stack limit (ulimit -s) because the ANTLR parser allocates many objects.
setting a more generous limit and all is OK.
I make a one-liner that will give the same stacksize as IDL (1000000)
