### ISSUE TITLE
try if "make -j" would speed up Travis builds

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#133]

**Comment by alaingdl** [comment]
it should ! I am daily using that on VMs. But "datatype.cpp" is a bottleneck, using about 1.5 Go RAM ...

**Comment by GillesDuvert** [comment]
I'll make a PR soon which removes most of the burden out of datatype.cpp .

**Comment by slayoo** [comment]
Here's a PR with "make -j" added to the travis script: https://github.com/gnudatalanguage/gdl/pull/169

Quick stats (not that representative, as these times vary considerably from build to build):
- before @GillesDuvert's #163 (e.g. https://travis-ci.org/gnudatalanguage/gdl/builds/365645456):
  icc: 25 min. / 38 min 
  gcc: 9 min. / 11 min.
  clang: 13 min / 17 min.
- after #163 (e.g. https://travis-ci.org/gnudatalanguage/gdl/builds/365696137):
  icc: 25 min / 25 min. 
  gcc: 9 min / 12 min.
  clang: 20 min. / 22 min.
- with make -j 2:
   15 min / 22 min
   7 min / 9 min
  10 min / 11 min

Rrelated texts on travis website: 
- https://docs.travis-ci.com/user/speeding-up-the-build/
- https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System

**Comment by GillesDuvert** [comment]
parallel compilation time is minimally bound by the time for compilation of what is remaining of datatype.cpp anyway. As this is a bunch of templates, we cannot split it in numerous files as we drop the simplicity and usefullness of templates (AFAIK).
still on my machine, all gdl takes 1.5 minutes of real time to compile in 'make j 8', (gcc debug) so there is room for improvement on travis.
finally, putting the debug,gcc as first test on travis may serve the contributor to know faster if something is really wrong with the PR.

**Comment by slayoo** [comment]
I've suggested -j2 as Travis docs (second link) mention avail. of two cores per vm. The order is random IIUC?
