### ISSUE TITLE
oplot, psym=4 over MAP_SET is not OK

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1330]
With current GDL, no shape appears, even if I increase the symsize. If negative, at the good position. I tried to reduce this bug without success.

```
map_set, /mollweide, 0, 0, /isotropic, /horizon, /continents
oplot, [0, 10, 10, 0, 0], [0, 0, 10, 10, 0]+5, psym=4
oplot, [0, 10, 10, 0, 0], [0, 0, 10, 10, 0]+5, psym=4, syms=4
oplot, [0, 10, 10, 0, 0], [0, 0, 10, 10, 0]+5, psym=-4 ;ok on the map
```

(yes, I was trying to overplot the [SAA](https://en.wikipedia.org/wiki/South_Atlantic_Anomaly) region ...)

**Comment by GillesDuvert** [comment]
solved in #1338
