### ISSUE TITLE
palette in WRITE_PNG & READ_PNG

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1333]
Following a bug report and my test (based on example in  
https://www.l3harrisgeospatial.com/docs/query_png.html) : 

*  WRITE_PNG does not respect palette (a 2D array + 3 color indexes
is stored as 3D array)
* READ_PNG does not read back well 2D+ palette input

A.

**Comment by GillesDuvert** [comment]
solved in #1340
