### ISSUE TITLE
Maximum number of clients reached  on Ubuntu 22.04

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1342]
(context : XFCE + Ubuntu 22.04; very few windows opened, 2 firefox with few tabs, claws-mail, Emacs, few terminals)

In the middle of a GDL session calling a lot of time a basic procedures with 2 windows
(statistic on weird pixels & ramps) I got :
```
Maximum number of clients reached
% BASIC_STATS_PIXEL: Cannot connect to X server
```
And I can run anymore ... (having to close some large 4D cubes :cry: after large crawling in data)

I never got that before. 

Following 
https://unix.stackexchange.com/questions/368017/cant-start-applications-due-to-maximum-number-of-clients-reached-error
I got :
```
 lsof -U +c 15 | cut -f1 -d' ' | sort | uniq -c | sort -rn | head -3
lsof: WARNING: can't stat() fuse.portal file system /root/.cache/doc
      Output information may be incomplete.
    259 Xorg
    213 gdl
    117 dbus-daemon
```

I suspect we don't close well few plplot related calls ...

(Yes I will try to reproduce that)

**Comment by alaingdl** [comment]
very simple way to reproduce : 

Before starting GDL :
`lsof -U +c 15 | cut -f1 -d' ' | sort | uniq -c | sort -rn | head -3` 
no GDL

Then
`GDL> for ii=0, 50 do window, /free`

in another terminal : 
```
lsof -U +c 15 | cut -f1 -d' ' | sort | uniq -c | sort -rn | head -3
[...]
     53 gdl
```

Then
`GDL> for ii=0, 50 do wdelete`

But we don't free all : `52 gdl`

**Comment by GillesDuvert** [comment]
OK, two different causes, solved.

**Comment by GillesDuvert** [comment]
This problem may reappear as the solution used (call plend1 as destructor) makes gdl crash in some cases with a X11 window and changing resolution of a concurrent Z device.
