### ISSUE TITLE
support for compressed save files

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#135]
As reported by @opoplawski on SF.net (https://sourceforge.net/p/gnudatalanguage/feature-requests/54/):

Compressed IDL save files appear to simply have the contents of each record compressed with Zlib's deflate(). If Zlib's inflate()/deflate() api were available in GDL, CMSVLIB could be modified to support compressed save files.

**Comment by GillesDuvert** [comment]
SAVE and RESTORE have been written from scratch in C++ for 0.9.8. It includes the support for compressed files and many other things that CMSVLIB was not handling well. This issue can be closed.
