### ISSUE TITLE
bug when writing PNG

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1354]
Yes, this problem may depend on various parameters but this code don't work on my laptop for PNG (just uniformly black) on current GDL git version on U22.04

```
pro BUG_PNG
defsysv, '!GDL', exist=exist
if exist then prefix='GDL_' else prefix='IDL_'
plot, findgen(10)
WRITE_PNG, prefix+'fig_1_true.png', TVRD(/TRUE)
WRITE_PNG, prefix+'fig_2_notrue.png', TVRD()
; not valid WRITE_JPEG, 'fig3_true.jpeg', TVRD(/TRUE)
WRITE_JPEG, prefix+'fig4_notrue.jpeg', TVRD()
end
```

**Comment by GillesDuvert** [comment]
All the above give OK plots for me.
(in PR #1338)

**Comment by jtappin** [comment]
I believe this is the same issue as [#1206](https://github.com/gnudatalanguage/gdl/issues/1206).

**Comment by GillesDuvert** [comment]
solved in #1358 ?

**Comment by brandy125** [comment]
I have the same problem. Is there any workaround to get 3 bands images written as png or bmp that are not completely black?

**Comment by alaingdl** [comment]
ASAP I will try to compile with IM instead of GM just in case.

**Comment by alaingdl** [comment]
I tried but did not succeed to compile with Image Magick on Ubuntu 22.04 up-to-date

I also tried to replace our FindImageMagick.cmake by the new one (+ related ones) but same problem
I don't know if it is related to the location of the IM sub-dir (/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.11) or the .pc files

I will try later on Debian11

**Comment by alaingdl** [comment]
Sorry for the delay, quite busy with all those data coming from MIRI on [JWST](https://www.jwst.fr/) :smile: 

In fact the files written in GDL can be read back in GDL & IDL and do give good plots. But they cannot be displayed in external tools.

Maybe it is just because the internal type is not the good one ?

```
GDL> gdl=read_png('GDL_fig_1_true.png')
GDL> idl=read_png('IDL_fig_1_true.png')    ;generated by idl 8.8, same computer
GDL> help, idl, gdl
IDL             BYTE      = Array[3, 960, 600]
GDL             UINT      = Array[3, 960, 600]
```

**Comment by alaingdl** [comment]
OK, I just compile GDL version 1.0.0 and 1.0.1 (on ubuntu 22.04)

* WRITE_PNG in version 1.0.1 is buggy
* WRITE_PNG in version 1.0.0 is OK

A.

PS: I forgot to mention I have the same problem on OSX 10.14.6

**Comment by GillesDuvert** [comment]
so this is a duplicate of #1206

**Comment by alaingdl** [comment]
Size of outputs are always changing ! 
But we can check the type inside ...
(I also look at `pngcheck` but I see no way to check more than the validity)

Files generated by : 
```
[...]
plot, findgen(10)
WRITE_PNG, prefix+'fig_1_true.png', TVRD(/TRUE)
[...]
```

```
ll -gG */G*fig_1*
-rw-rw-r-- 1  5711 sept. 19 15:14 gdl100/GDL_fig_1_true.png
-rw-rw-r-- 1  7344 sept. 19 15:21 gdl101/GDL_fig_1_true.png
-rw-rw-r-- 1 16400 oct.  19 00:09 gdl101git221018/GDL_fig_1_true.png
-rw-rw-r-- 1  5122 nov.   8 09:40 gdl101git221108/GDL_fig_1_true.png
-rw-rw-r-- 1  4601 nov.  10 18:09 gdl101git221110/GDL_fig_1_true.png
-rw-rw-r-- 1  4601 nov.  27 23:08 gdl101git221127/GDL_fig_1_true.png
-rw-rw-r-- 1 19864 nov.  14 11:13 gdl_deb/GDL_fig_1_true.png
```
