### ISSUE TITLE
Visualization window not interactive and unable to use dependencies/libraries(?)

### ISSUE THREAD

**Issue by tushara04** [gnudatalanguage/gdl#1359]
Note: I use GDL Command Line in Windows, Version 1.0.1
I am unable to interact with the GDL's visualization window:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/108838006/184180833-fa38f8f9-4796-416b-9b0f-e2569e4b685c.png">

By interact, I mean there's no option to zoon, rotate, save, etc. (just like there is for matplotlib in python).
So, what am I doing wrong? Do i have to install some additional packages?

Next issue -- 
I don't know how to install additional packages or dependencies. Like, do we have to? I feel like I am missing something because I am unabel to use some functions such as "style = 'filled'" in surface function. So, what do I do?

**Comment by GillesDuvert** [comment]
Please for each function read the documentation, for [surface](https://www.l3harrisgeospatial.com/docs/SURFACE_Procedure.html) there is no style="filled" thing
surface is just a 3D 'flat' plot. Nothing fancy.  To rotate it, you must enter options ax=required elevation (degrees) and az=required azimuth (degrees).
`for az=0,360,10 do surface, dist(32), az=az` will rotate by steps of 10 degrees.
Note that GDL graphic procedures are not functions. IDL has a procedure and a function for all graphics commands. The procedures are the 'traditional' way to make plots. The functions are recent IDL developments that are not yet present in GDL.

Besides, the 3D plots are still buggy in GDL and will become perfect only for the 1.1 release.
