### ISSUE TITLE
Keyword parameter SET_FONT for DEVICE 

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#136]
@GillesDuvert could you update us (including @fkbreitl who reported it on SF.net: https://sourceforge.net/p/gnudatalanguage/feature-requests/95/) on the status of support for SET_FONT keyword for DEVICE? Thanks

**Comment by GillesDuvert** [comment]
The basic mechanism for DEVICE, SET_FONT is installed. The behaviour depending on the actual device used and the platform, which indirectly points to the limitations of the plplot library, is not satisfactory. This could be solved easily if we used only the wxWidgets driver for graphics. However the x11 driver is so much faster that we'll probably be unable to provide an unified solution.

**Comment by edromzans** [comment]
How can I use just wxWidgets driver for graphics? I didn't understand how can I do that.
I am very interested to change the fonts of my postscript plots (set_plot, 'ps') and I can't make it with set_font or /font_name keyword in device. 
If there are some solution to change the font on plots, I would like to know.
Thanks!!

**Comment by GillesDuvert** [comment]
@emanselmo the set_font will probably not work with set_plot='ps' as do not recall it is implemented in the plplot driver. 
OTHO, it should work with wxWidgets instead of X11, you can try by forcing wxWidgets with
gdl --use-wx

**Comment by GillesDuvert** [comment]
I amend my April, 11 comment: in recent plplot versions, the wxwidget backend is fast enough, and we probably should use it by default.

**Comment by edromzans** [comment]
Hi @GillesDuvert,  thanks! the --use-wx set up the WxWidgets here, but I had "wxPLViewer: not found". I am using a debian buster, and I have libplplotwxwidgets1 and plplot-driver-wxwidgets packages installed. So WxWidgets is not working here. 
Is there something that is missing in my wxwidgets support? 
 
$ gdl --use-wx
% WARNING: your version of the GraphicsMagick library will truncate images to 16 bits per pixel
- Using WxWidgets as graphics library (windows and widgets).

  GDL - GNU Data Language, Version 0.9.9 git

- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): 
  +/usr/local/share/gnudatalanguage/lib
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

GDL> a=findgen(10)
GDL> plot,a
sh: 1: wxPLViewer: not found

**Comment by GillesDuvert** [comment]
OK if it asks for wxPLViewer, then it's not going to work. Meaning the debian version of GDL is linked to a plplot that insists to use its own "viewer" (so, create its own windows). A workaround was found in PR #622 so the current sources on GH should perform better, but need to be compiled...

**Comment by edromzans** [comment]
Hi @GillesDuvert, when you refer "the current sources on GitHub" is the current gdl-master source code on git? Or is the plplot source (https://github.com/PLplot/PLplot)?

I am using GDL compiled, downloaded today (2019-09-24) from GitHub. 

Thanks!

**Comment by slayoo** [comment]
> I amend my April, 11 comment: in recent plplot versions, the wxwidget backend is fast enough, and we probably should use it by default.

What about a release soon, and then switching to wx as default right after the release?

**Comment by GillesDuvert** [comment]
@emanselmo if you have compiled recently, then the message about wxPlwiever is probably just because wxPLViewer has not been installed, which is possible if you have not installed plplot itself, just the libraries. On my mageia, after installing plplot (not libplplotxx), one finds wxPLViewer in /usr/bin.
Of course it is not what one expects from a library, that's why the packagers have overlooked this problem.
@slayoo meaning we should have in our build process a case really testing the creation of plots under wxWidgets or other "absence of plplot" related bugs such as plplot not finding the colormap (.pal) files.

**Comment by GillesDuvert** [comment]
@slayoo about the release, it would make a difference to merge several waiting PRs, and at the same time some are tagged WIP. Let's discuss that outside this page.

**Comment by slayoo** [comment]
> @slayoo about the release, it would make a difference to merge several waiting PRs, and at the same time some are tagged WIP. Let's discuss that outside this page.

added new issue as a venue for this discussion: #644
