### ISSUE TITLE
WIDGET_CONTROL : APPEND option error

### ISSUE THREAD

**Issue by im-going-nowng** [gnudatalanguage/gdl#1360]
PRO appenderror
    xdisplayFile, '', TEXT=("hi"), WTEXT=w
    WIDGET_CONTROL, w, SET_VALUE=("hello"), /APPEND, /SHOW
    WIDGET_CONTROL, w, SET_VALUE=("hello"), /APPEND, /SHOW
END

![image](https://user-images.githubusercontent.com/101169016/185837601-bef13a36-19d9-4a34-8550-16d5e5fc6e28.png)

If the APPEND option of WIDGET_CONTROL is executed more than once, an error occurs.

**Comment by GillesDuvert** [comment]
Hi thanks, but "worksforme"...
Could you give more details about the GDL version, platform?

**Comment by im-going-nowng** [comment]
> Hi thanks, but "worksforme"... Could you give more details about the GDL version, platform?

Thank you for checking. I tested it on Windows 10 with the version 1.0.1 downloaded in July.

When I checked again, I couldn't perform xdisplayFile when I ran gdl on the m1 Mac, but the append option in WIDGET_CONTROL worked normally. I think I misunderstood the cause of the error. I'll check again.
