### ISSUE TITLE
rpc.h is missing when building GDL on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by Csega** [gnudatalanguage/gdl#1362]
Hi Guys,

I have a completely working setup for GDL, which worked fine so far. However, the server was upgraded from 18.04 to 22.04 Ubuntu lately and my compilation stops now with the following error:

$ make
Consolidate compiler generated dependencies of target antlr
[ 14%] Built target antlr
Consolidate compiler generated dependencies of target gdl
[ 15%] Building CXX object src/CMakeFiles/gdl.dir/FMTIn.cpp.o
In file included from /home/csega/git/gdl/src/str.hpp:25,
                 from /home/csega/git/gdl/src/envt.hpp:26,
                 from /home/csega/git/gdl/src/FMTIn.hpp:14,
                 from /home/csega/git/gdl/src/FMTIn.cpp:5:
/home/csega/git/gdl/src/basegdl.hpp:27:12: fatal error: rpc/rpc.h: No such file or directory
   27 | #  include <rpc/rpc.h>
      |            ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/gdl.dir/build.make:90: src/CMakeFiles/gdl.dir/FMTIn.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: src/CMakeFiles/gdl.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

Could you help me figure this out, please?

Cheers,
Csega

**Comment by pjb7687** [comment]
perhaps installing this might help?

https://packages.ubuntu.com/jammy/libntirpc-dev

**Comment by Csega** [comment]
@pjb7687 Nope, unfortunately not. 😢 I tried and I got the same error.

I tried to add the path to rpc/rpc.h to PATH (/usr/include/ntirpc/), but that does not help either. I even tried to run make with the following options:

```bash
make CFLAGS=-I/usr/include/ntirpc
```

but no luck with that either. 😢

**Comment by GillesDuvert** [comment]
"new" transport library ... perhaps the [old one will be better](https://packages.ubuntu.com/jammy/libdevel/libtirpc-dev)

**Comment by alaingdl** [comment]
It works like a charm on my U22.04 (just compiled from current git)

(it is unclear in the report) Do you have the package ?

```
LANG=us dpkg -l libtirpc-dev
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version          Architecture Description
+++-==================-================-============-=====================================================
ii  libtirpc-dev:amd64 1.3.2-2ubuntu0.1 amd64        transport-independent RPC library - development files

```

and yes, I have it inside :
```
$ ls -F /usr/include/tirpc/
netconfig.h  rpc/  rpcsvc/
```

**Comment by Csega** [comment]
Thank you very much for your help! It worked with the libtirpc-dev in the end. I don't know, why this package disappeared at a release-upgrade...
