### ISSUE TITLE
in ATV, bug in input number (more than one digit) in slicer

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1364]
With the current Git compiled with the build script + install + adding idlastro+coyote + idl lib (at the end) in the GDL_PATH
I can start & run ATV (version 3.0b8) without major  trouble

I do have a 3D cube I would like to slice, but I cannot input a number (e.g. 350, see screenshot) just single digit ...

Thanks !

A.

![atv_slicer](https://user-images.githubusercontent.com/38264661/187440881-62e72375-3341-45c2-8ba4-f8139b89ac6a.png)

PS: ATV is not working for me on IDL 8.8 ? Large number of messages and don't start :disappointed: 
```
common atv_state
                ^
% Common block ATV_STATE must contain variables.
  At: /home/alaingdl/IDLetGDL/atv.pro, Line 2560
```
+ many compilation errors
```
...
% 5 Compilation error(s) in module ATV_SHUTDOWN.
...
% 2 Compilation error(s) in module ATV.
```

**Comment by GillesDuvert** [comment]
closed by #1541
