### ISSUE TITLE
no more iconify button in Window (u2204 + xfce4)

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1368]
furthermore the list of opened windows is no more visible in the "desk" 

all was OK few weeks ago ...

A.

(old behavior, was OK for me)
![old_4buttons](https://user-images.githubusercontent.com/38264661/187953064-b431e1e3-fae7-488b-a4c2-246746cdb437.png)

(new current behavior : not OK for me)
![new_3buttons](https://user-images.githubusercontent.com/38264661/187953058-8f0dc289-827d-4ab6-beea-2a2c9f41622e.png)

**Comment by GillesDuvert** [comment]
wxWidgets either allow the 'old  behavior' , but you **lose focus in your terminal** if you enable that, or make the new behavior and the focus stays in the command line.
This may well depend on the window manager, and probably wxWidgets could do better.
I chose to have the focus stay at the command line.
If anybody knows how to programmatically put back the focus in the command terminal, now with all those new fancy display managers, just tell me.

**Comment by alaingdl** [comment]
In the current Git version, compiled with the script (then with WX on), this is back to OK.
Then I think we can put that to _close_

@GillesDuvert I don't know what is you mention (_focus in your terminal_)
