### ISSUE TITLE
pb on OSX with old arch

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1370]
On "old" OSX  ProductVersion:	10.14.6
Cmake version 3.23.2 stops here :

```
CMake Error at CMakeLists.txt:321 (if):
  if given arguments:

    "STREQUAL" "arm64"

  Unknown arguments specified
```

I suspect this is a consequence to take into account M1

**Comment by alaingdl** [comment]
seems to be solved with current version of Cmake !

cmake version 3.24.3

May be we can switch it to solve ?

**Comment by GillesDuvert** [comment]
closed as old
