### ISSUE TITLE
VELOVECT is missing.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1372]
None of the vector field plotting routines from IDL exist in GDL.

Suggested solution, incorporate the attached version of `velovect` and the quick & dirty test routine into GDL.

[test_velovect.pro](https://github.com/gnudatalanguage/gdl/files/9665547/test_velovect.pro.txt)
[velovect.pro](https://github.com/gnudatalanguage/gdl/files/9665548/velovect.pro.txt)

N.B. I have disabled POLAR, XLOG & YLOG, because although the IDL documentation claims they are supported, they don't work in any sensible way.

**Comment by GillesDuvert** [comment]
Thank you  so much James, a nice improvement to GDL indeed!
