### ISSUE TITLE
any chance to implement .so and .out?

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1383]
I would need a lot the .so (stepover) and .out (leave the actual procedure/function).
Can we implement it?

**Comment by GillesDuvert** [comment]
Well, yes, in principle.
Sure everybody will be happy, me first of all.
This is the most touchy part of GDL alas. Odds are not good.

**Comment by GillesDuvert** [comment]
.SO done

.OUT to be done (new issue #1424)
