### ISSUE TITLE
% PLOT: Data coordinate system not established.

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1387]
With the newest version I get sometimes the error

% PLOT: Data coordinate system not established.

GDL> !gdl
{
    "RELEASE": "1.0.1 Git",
    "BUILD_DATE": "Oct 28 2022",
    "EPOCH": 1666926000,
    "GDL_USE_DSFMT": 1,
    "GDL_USE_WX": 1,
    "GDL_POSIX": 1
}

**Comment by GillesDuvert** [comment]
It would be interesting to know what action causes this message. Now that GDL strictly obeys the content of !X !Y !Z and !D .

**Comment by brandy125** [comment]
The problem is that it appears only sometimes. I will try to figure out how to reproduce...

**Comment by brandy125** [comment]
Installed yesterday the new version and now it happens constantly:
```
GDL> plot,findgen(100)
% PLOT: Data coordinate system not established.
```
I have around 20 jobs running in parallel for around 20 min executing "almost the same thing two times". When executing the second time all jobs stop in a line where (a different) plot command is being executed.
If I issue the simple plot command above it is not possible.

I will try to reconstruct the error with a standalone program. Lets see..
But for sure I can say that there is a difference between the newest version and the last one (not considering the update of bug #1377 ).

**Comment by brandy125** [comment]
Finally could reproduce it with few lines of code:
```
GDL>set_plot,'z'
GDL>!p.multi=[0,4,7,4,0]
GDL>plot,findgen(100)
% PLOT: Data coordinate system not established.
% Execution halted at: $MAIN$          
GDL> 
```

Anybody can confirm?

GDL> !gdl
{
    "RELEASE": "1.0.1 Git",
    "BUILD_DATE": "Nov  8 2022",
    "EPOCH": 1667876400,
    "GDL_USE_DSFMT": 1,
    "GDL_USE_WX": 1,
    "GDL_POSIX": 1
}
GDL> 
Linux localhost.localdomain 6.0.3-1-default #1 SMP PREEMPT_DYNAMIC Sat Oct 22 07:43:26 UTC 2022 (f00a35f) aarch64 aarch64 aarch64 GNU/Linux

**Comment by GillesDuvert** [comment]
Sorry but I do no have such problem, with both examples. I would never release a code that would not work on my machine on such simple and basic cases.
The error message is a new one in GDL, generated in gdlgstream.cpp, routine vpor(). It indicates an internal problem in the coordinates setup of GDL and yes, it comes from the new version that provides 3D support and  uses correctly the values of !D,!X,!Y and !Z.
Obviously something on your compiler/machine somehow differ from mine, and OSX, and Windows, in the way some values are compiled, or evaluated or compared one another. The test in vpor() that triggers the error can easily be debugged, and hopefully the origin of the problem traced back and solved, I believe.

**Comment by GillesDuvert** [comment]
incidentally, with `set_plot,'z'`  the ticklengths of the box made by `plot` will be ridiculous, this is a feature I have noted.

**Comment by brandy125** [comment]
My machine is 

bash$ cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20221024"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20221024"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20221024"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
bash$ 

running inside Parallels inside a Mac Studio with M1 Ultra 

What should I do to debug?

**Comment by brandy125** [comment]
BTW, it happens only if the number in the second dimension is higher than 6:

```
GDL> for i=0,9 do begin print, i & !p.multi=[0,0,i,0,0]& plot,findgen(100) & endfor
       0
       1
       2
       3
       4
       5
       6
       7
% PLOT: Data coordinate system not established.
% Execution halted at: $MAIN$          
GDL> 
```

**Comment by GillesDuvert** [comment]
interesting as there could be a link with the recent changes.
does
` for i=0,9 do begin print, i & !p.multi=[0,0,i,0,0]& plot,findgen(100),position=[0.1,0.1,0.7,0.8,0.2,0.3]& endfor `
work OK?

**Comment by brandy125** [comment]
Yes, works perfect!:

GDL> set_plot,'z'
GDL> for i=0,9 do begin print, i & !p.multi=[0,0,i,0,0]& plot,findgen(100),position=[0.1,0.1,0.7,0.8,0.2,0.3]& endfor
       0
       1
       2
       3
       4
       5
       6
       7
       8
       9
GDL>

**Comment by GillesDuvert** [comment]
interesting, so the problem probably comes from the few lines of code where the values of the default position (!P.POSITION etc) are retrieved (earlier versions of GDL did not fully comply with this)

**Comment by GillesDuvert** [comment]
Could you try to trigger some debug lines, by setting
`#define GDL_DEBUG_PLSTREAM 1`
at line 25 of gdlgstream.hpp,
recompile
and print the output of 
`for i=6,8 do begin print, i & !p.multi=[0,0,i,0,0]& plot,findgen(100) & endfor`
?
(very verbose output)

**Comment by brandy125** [comment]
Begin:
```
GDL> set_plot,'z' & for i=0,9 do begin print, i & !p.multi=[0,0,i,0,0]& plot,findgen(100) & endfor
       0
 new GDLGstream( 1 , 1 , mem ):pls=0x3e725b40 
ssub() 1x1x1 pages
SyncPageInfo()
         device resolution [107312485787905744881332201718740579043424450868846955149340567930562908980961535669477427219195052017227406950493561088464564097976232434601411441448259177801315222958971513305607623985370407869874176.000000,59244041613714824443989823614002209058991375662181243350211327489336120949999532231308534555048139300642694110402073063439356184759305304894216745146350788760089791561728.000000]mm^-1, device size [0.000000,0.000000], [0.000000,0.000000] mm
         subpage is 0.000000x0.000000 at [0.000000,0.000000] device units
adv() now at page 1
SetPageDPMM()
plpot driver returns inconsistent x DPI values (2).
plpot driver returns inconsistent y DPI values (2).
GDLGStream::DefaultCharSize()
schr(width=8.000000, scale=1.000000, spacing=12.000000)
current (fake?) dpi is 96.000000 : asking for a mm height size: 2.540000)
Able to check character width=2.515306, should have been 2.116667
got plplot character height in mm=2.137447 (2nd pass))
CurrentCharsize()
updatePageInfo():
             640.000000x480.000000 device units.
GetPlPlotDefaultCharsize()
             2.137447x2.137447,3.175000 (mm)
             0.013359x0.017812,0.026458 (norm)
             8.549790x8.549790,12.700000 (dev)
             0.013359x0.017812,0.026459 (world)
            sized by 1.000000 is 2.137447x2.137447 mm or 8.549790x8.549790 device or 0.013359x0.017812 world

```
End:
```
       7
vpor(): requesting x[0.133590:0.959923],y[0.939167:0.947083] (normalized, subpage)
vpor(): got x[0.133590:0.959923],x[0.939167:0.947083] (normalized, device)
SyncPageInfo()
         device resolution [0.006250,0.008333]mm^-1, device size [640.000000,480.000000], [102400.000000,57600.000000] mm
         subpage is 640.000000x80.000000 at [0.000000,0.000000] device units
wind(): setting x[-0.000000:98.999999],y[-0.000020:99.000258] (world) 
updateBoxDeviceCoords()
NormedDeviceToWorld()
          input [0.000000,0.000000] (nd) output [-16.005007,-11744.526316] (w)
NormedDeviceToWorld()
          input [1.000000,1.000000] (nd) output [103.801502,760.736842] (w)
NormToWorld()
         input [0.000000,0.000000] output [-16.005007,-11744.526316]
NormToWorld()
         input [1.000000,1.000000] output [103.801502,760.736842]
NormToDevice()
        input [0.133590,0.939167] output [85.497894,75.133333]
NormToDevice()
        input [0.959923,0.947083] output [614.350624,75.766668]
DeviceToWorld()
DeviceToNormedDevice()
          input [0.000000,0.000000] output [0.000000,0.000000]
NormedDeviceToWorld()
          input [0.000000,0.000000] (nd) output [-16.005007,-11744.526316] (w)
DeviceToWorld()
DeviceToNormedDevice()
          input [8.549790,8.549790] output [0.013359,0.017812]
NormedDeviceToWorld()
          input [0.013359,0.017812] (nd) output [-14.404506,-11521.781797] (w)
DeviceToWorld()
DeviceToNormedDevice()
          input [0.000000,12.700000] output [0.000000,0.026458]
NormedDeviceToWorld()
          input [0.000000,0.026458] (nd) output [-16.005007,-11413.657895] (w)
UpdateCurrentCharWorldSize(1.600501,222.744519)
NextPlot(erase=1)
ssub() 1x7x1 pages
SyncPageInfo()
         device resolution [0.006250,0.008333]mm^-1, device size [640.000000,480.000000], [102400.000000,57600.000000] mm
         subpage is 640.000000x68.571429 at [0.000000,0.000000] device units
adv() now at page 1
SizeChar(1.000000)
CurrentCharsize()
            sized by 1.000000 is 2.137447x2.137447 mm or 8.549790x8.549790 device or 1.600501x222.744519 world
SizeChar(1.000000)
CurrentCharsize()
            sized by 1.000000 is 2.137447x2.137447 mm or 8.549790x8.549790 device or 1.600501x222.744519 world
% PLOT: Data coordinate system not established.
% Execution halted at: $MAIN$          
GDL> 
```

**Comment by brandy125** [comment]
Begin:

GDL> set_plot,'z' & for i=0,9 do begin print, i & !p.multi=[0,0,i,0,0]& plot,findgen(100) & endfor
       0
 new GDLGstream( 1 , 1 , mem ):pls=0x3e725b40 
ssub() 1x1x1 pages
SyncPageInfo()
         device resolution [107312485787905744881332201718740579043424450868846955149340567930562908980961535669477427219195052017227406950493561088464564097976232434601411441448259177801315222958971513305607623985370407869874176.000000,59244041613714824443989823614002209058991375662181243350211327489336120949999532231308534555048139300642694110402073063439356184759305304894216745146350788760089791561728.000000]mm^-1, device size [0.000000,0.000000], [0.000000,0.000000] mm
         subpage is 0.000000x0.000000 at [0.000000,0.000000] device units
adv() now at page 1
SetPageDPMM()
plpot driver returns inconsistent x DPI values (2).
plpot driver returns inconsistent y DPI values (2).
GDLGStream::DefaultCharSize()
schr(width=8.000000, scale=1.000000, spacing=12.000000)
current (fake?) dpi is 96.000000 : asking for a mm height size: 2.540000)
Able to check character width=2.515306, should have been 2.116667
got plplot character height in mm=2.137447 (2nd pass))
CurrentCharsize()
updatePageInfo():
             640.000000x480.000000 device units.
GetPlPlotDefaultCharsize()
             2.137447x2.137447,3.175000 (mm)
             0.013359x0.017812,0.026458 (norm)
             8.549790x8.549790,12.700000 (dev)
             0.013359x0.017812,0.026459 (world)
            sized by 1.000000 is 2.137447x2.137447 mm or 8.549790x8.549790 device or 0.013359x0.017812 world

End:

       7
vpor(): requesting x[0.133590:0.959923],y[0.939167:0.947083] (normalized, subpage)
vpor(): got x[0.133590:0.959923],x[0.939167:0.947083] (normalized, device)
SyncPageInfo()
         device resolution [0.006250,0.008333]mm^-1, device size [640.000000,480.000000], [102400.000000,57600.000000] mm
         subpage is 640.000000x80.000000 at [0.000000,0.000000] device units
wind(): setting x[-0.000000:98.999999],y[-0.000020:99.000258] (world) 
updateBoxDeviceCoords()
NormedDeviceToWorld()
          input [0.000000,0.000000] (nd) output [-16.005007,-11744.526316] (w)
NormedDeviceToWorld()
          input [1.000000,1.000000] (nd) output [103.801502,760.736842] (w)
NormToWorld()
         input [0.000000,0.000000] output [-16.005007,-11744.526316]
NormToWorld()
         input [1.000000,1.000000] output [103.801502,760.736842]
NormToDevice()
        input [0.133590,0.939167] output [85.497894,75.133333]
NormToDevice()
        input [0.959923,0.947083] output [614.350624,75.766668]
DeviceToWorld()
DeviceToNormedDevice()
          input [0.000000,0.000000] output [0.000000,0.000000]
NormedDeviceToWorld()
          input [0.000000,0.000000] (nd) output [-16.005007,-11744.526316] (w)
DeviceToWorld()
DeviceToNormedDevice()
          input [8.549790,8.549790] output [0.013359,0.017812]
NormedDeviceToWorld()
          input [0.013359,0.017812] (nd) output [-14.404506,-11521.781797] (w)
DeviceToWorld()
DeviceToNormedDevice()
          input [0.000000,12.700000] output [0.000000,0.026458]
NormedDeviceToWorld()
          input [0.000000,0.026458] (nd) output [-16.005007,-11413.657895] (w)
UpdateCurrentCharWorldSize(1.600501,222.744519)
NextPlot(erase=1)
ssub() 1x7x1 pages
SyncPageInfo()
         device resolution [0.006250,0.008333]mm^-1, device size [640.000000,480.000000], [102400.000000,57600.000000] mm
         subpage is 640.000000x68.571429 at [0.000000,0.000000] device units
adv() now at page 1
SizeChar(1.000000)
CurrentCharsize()
            sized by 1.000000 is 2.137447x2.137447 mm or 8.549790x8.549790 device or 1.600501x222.744519 world
SizeChar(1.000000)
CurrentCharsize()
            sized by 1.000000 is 2.137447x2.137447 mm or 8.549790x8.549790 device or 1.600501x222.744519 world
% PLOT: Data coordinate system not established.
% Execution halted at: $MAIN$          
GDL>

**Comment by brandy125** [comment]
Should I put the complete output here or is this enough?

**Comment by GillesDuvert** [comment]
should be ok. will check ASAP

**Comment by GillesDuvert** [comment]
Your output for iteration 7 differs completely from mine starting at line 46... May I have the complete output for iteration 6, just above this one? thanks.

**Comment by brandy125** [comment]
Sure, here it is…
[plot.txt](https://github.com/gnudatalanguage/gdl/files/10014617/plot.txt)

**Comment by GillesDuvert** [comment]
sorry, can't see any log (???)

**Comment by brandy125** [comment]
Sorry, didn't come with the email. Now its there..

**Comment by GillesDuvert** [comment]
OK, (I should have known) you use !P.CHARSIZE=2 (somewhere in your preferences I suspect). At iteration 7 the characters become bigger than the REGION and the fussy test I wrote at line 1154 of gdlgstream.cpp is fulfilled and the error is activated.
I use charsize=1 and for this size the error appears at iteration 13... I never tested up to such number of plots  (went to 4 or 5 max)!
I'll correct this on GH  but you can just delete line 1154 of gdlgstream.cpp and change 1155 and 1156 to
```
  if (xmin >= xmax) {xmin=0; xmax=1;}
  if (ymin >= ymax) {ymin=0; ymax=1;}
```

**Comment by brandy125** [comment]
Ahh nice!

Thanks!
