### ISSUE TITLE
Succeed to build gdl but run errors while creating window in the command line

### ISSUE THREAD

**Issue by youngastronomy** [gnudatalanguage/gdl#1388]
msys2  and build smoothly.

after I go the install/bin/ directory to run the gdl.exe  and create the window, the errors
appeared.

GDL> window,0

*** PLPLOT ERROR, ABORTING OPERATION ***
plInitDispatchTable: Could not open drivers directory, aborting operation
% PLplot installation lacks the requested driver: wxwidgetsgdl
% Execution halted at: $MAIN$

**Comment by youngastronomy** [comment]
Lack of driver infomation.    copy gdl/src/plplotdriver/wxwidgetsgdl.driver_info   to  /mingw64/lib/plplot5.15.0/drivers/   . Problem resolved

**Comment by pjb7687** [comment]
Nice. I think that's perhaps the reason why the current build fails.

**Comment by GillesDuvert** [comment]
Did you use build_gdl.sh ?
Copying the gdlwxwidget.griver_info back in the plplot native driver directory will not work as expected. You may get correct 2D plots but not 3D plots for instance.

**Comment by youngastronomy** [comment]
Yes I use build_gdl.sh follow the instruction of  https://gnudatalanguage.github.io/. Only Check the  2D @GillesDuvert .  The 3D plots still have problems.

**Comment by GillesDuvert** [comment]
There is more than 3D stuff that will not work if the proper plplot drivers are not used. 
Could you try installing GDL using the installer produced by each new merge or better the one produced each week?
It should be ok for 3d and more.

**Comment by youngastronomy** [comment]
Thanks for your suggestion. I will test the one produced recent weeks. Let's see how it is going?
