### ISSUE TITLE
feedback on 1.0.1 package on Ubuntu 22.04 : similar issues

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1398]
Since I have problems with the packaged GDL 1.0.1 on Debian, I tested also locally on my laptop in ubuntu 22.04 + xfce 
(1.0.1-3build1 amd64)

* (basic) PNG are not OK  but when I read back the PNG created by GDL, it is OK (in IDL & in GDL)
* (basic) JPEG are OK
* clearly the first PLOT is done in two steps, because we see the size (axis) is changed !
* if a new plot (same command (plot, findgen(10))) again the size is change
* first TVSCL does not display, but call it again does give the plot :)
```
GDL> a=read_png('GDL_fig_2_notrue.png')
GDL> tvscl, a,/tru
```

**Comment by GillesDuvert** [comment]
How to provides tests that will avoid such unpleasant surprises ?

**Comment by alaingdl** [comment]
I have no magic answer and I do no use packaged versions ...

Maybe before a release we have to organize a one week or two weeks dedicated to **Call of bug reports** focused on the version. I am currently not useful to contribute in code but I always have few times to make regression tests.

For me we are now back on a normal path : I can compile _again_ and have windows _again_ on all my VM then we are back on normal bugs reports (#1410 AXIS; the fact that the first window is _bad_ with wxwidgets ...)

Concerning plot & co, it is no so difficult to run all the codes in testsuite/interactive time to time to see obvious regressions (like #1410)

Concerning PNG & co it is more difficult but we have to check few points : 
-- types when reading back were bad (and we did not checked that somewhere in the tests)
-- can we have a usable md5 sum ? (not sure due to various flavor of libs used to link)
-- can we compare what we read back and what we will create through TVRD() I made some tests in the past, example in some tests for background, that was OK for that point, should be usable.

**Comment by GillesDuvert** [comment]
@alaingdl I fully agree with you about the necessary period of call of bug reports.
However we need to test also the distributed versions (debian etc) as soon as they are available as they may show weaknesses we are not aware of. The example of the 0.9.9 with the crash due to absence of semaphore is typical. 
Here you examine some 1.0.1 distro, that is more than 1 year old and I believe, mostly cured now.  And these problems were not necessary visible, for example on my machine (compiler, library version, window manager...)

**Comment by alaingdl** [comment]
I don't know if using Docker may help to quickly test packages. In any case I plan to start some activities on that with an intern starting in spring 2023. 

I had a look on the PNG/JPEG outputs made by different versions of GDL (and IDL). 
(see https://github.com/gnudatalanguage/gdl/issues/1354#issuecomment-1328917857 )

I have a collection of VMs dedicated to tests, but for sure 

We need to deliver, the sooner the better, a version 1.0.2 with some critical issues we had in 1.0.1 and to be fixed :
- ** not solved now ** first plot with wxwidgets is not displayed : absolutely critical. If no solution the default should be the X11 version
- PNG/JPG outputs black on black (should be solved now in Git version ) (see comments to be add into #1354 )
-  ** not solved now ** Axis
- ... TBC
