### ISSUE TITLE
gdl segfaults when window size is bigger than 32767

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1399]
Even if it doesn't make much sense to have windows with this size but gdl should not segfault.

```
GDL> window,1,xs=100,ysize=32767
GDL> window,1,xs=100,ysize=32768
The program 'gdl' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadAlloc (insufficient resources for operation)'.
  (Details: serial 446 error_code 11 request_code 53 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by alaingdl** [comment]
in fact : 
- when the size is above screen size, IDL limits to the avaible size

```
IDL> get_screen_size()
        1920        1080
IDL> window,1,xs=10022,ysize=32767
IDL> print, !d.x_size, !d.y_size
        1920        1029
```
(1029 because I have an small upper fixed panel in Xfce)

- here (u22.04) in current Git GDL the plotting window does have a scrolling (barre de defilement) and can be bigger than the size of the screen. Do we need than ?

**Comment by GillesDuvert** [comment]
requesting a window bigger than the available screen was a request from... @brandy125  in #708 . :smile: 
Indeed there should be a limit (I believe 32768 is here not a X11 limit but a plplot limit, but this is irrelevant).
Easy to fix, obviously, but we are on our own as this never was possible in IDL.
I suggest regress to previous IDL limitation only if some legacy 'serious' code had problem with this ... not the case apparently.

**Comment by brandy125** [comment]
Well, in my version of IDL (7.0.1) I get:


IDL> window,1,xsize=10022,ysize=32767
IDL> print,!d.x_size,!d.y_size
       10022       32744
IDL> a=tvrd()
IDL> help,a
A               BYTE      = Array[10022, 32744]
IDL> 

and this is what I am used to and what I like.

**Comment by GillesDuvert** [comment]
interesting/strange, as in the 8.4 I have access to, the results are the same as for @alaingdl : no bigger than the physical screen.
So my comments on IDL were too hasty.

**Comment by GillesDuvert** [comment]
patched
