### ISSUE TITLE
GDL can not continue after accessing inexistent variable

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1403]
Don't know if anybody saw this behaviour already but for me is very boring that GDL can not continue after accessing an inexistent variable.
Can this be repaired?

```
bash$ cat testme.pro 
pro testme
        print,5
        stop
        print,6
end
```

```
GDL> testme
% Compiled module: TESTME.
       5
% Stop encountered: TESTME               3 /home/ultra/disk1/tii/20211123/radar1/acquisitions/testme.pro
GDL> print,out
% PRINT: Variable is undefined: OUT
% Execution halted at: TESTME               3 /home/ultra/disk1/tii/20211123/radar1/acquisitions/testme.pro
%                      $MAIN$          
GDL> .c
% PRINT: Variable is undefined: OUT
% Execution halted at: TESTME               3 /home/ultra/disk1/tii/20211123/radar1/acquisitions/testme.pro
%                      $MAIN$          
```

**Comment by GillesDuvert** [comment]
Yes, very painful, along with all issues labelled 'dot-commands'  .
It is quite understandable that all 'debug-like' commands were not top priority for GDL creators since GDL was intended to run historical pipelines. Now that GDL is used in (modest) replacement of IDL, we must look into this, although it seems tricky.

**Comment by brandy125** [comment]
I agree.

In my case I completely changed from IDL to GDL since IDL is not available on an aarch64 architecture.
Debugging works but is painful. 

Maybe some of dot-commands are not so complicated to implement but I really don’t know.

What I need most is .so and .out

**Comment by alaingdl** [comment]
the good point is you can skip over (.s 1) then twice .co

**Comment by brandy125** [comment]
I didn't get it.

1) .s 1 means ".step 1”, right?
2) what do you mean with twice .co ?

Do you know any “workaround” for the dot-commands?

**Comment by alaingdl** [comment]
```
GDL> .skip 1
% Can't continue from this point.
GDL> .continue
GDL> .continue
6
```

What do you mean by  “workaround” for the dot-commands ? 
I have the feeling not using that, doing all in pro/func or in interactive way.
But I may put some potential stopping points

```
pro toto, test=test
[... some code ...]
if KEYWORD_SET(test) then STOP
[... some code ...]
end
```
and call `toto,/test` then stop in the procedure, change/test some point then continue

**Comment by GillesDuvert** [comment]
Indeed, GDL is not completly dumb about debugging, but @brandy125 's example is a real showstopper for anyone wanting to debug a .pro in the 'normal' way. 
Did not fully realize GDL's interest for new architectures... 
OK, I'll have a look.

**Comment by brandy125** [comment]
Thanks!!!

**Comment by GillesDuvert** [comment]
OK, first question: what is the difference between .CONTINUE and .TRACE ?

**Comment by brandy125** [comment]
.TRACE is the same as .CONTINUE but showing the line of code that is being executed.
I think this is not so important for now

**Comment by GillesDuvert** [comment]
Ys, that's what TRACE means, but I have access to IDL 8.4 and TRACE does not show the line of code, and 8.4 help does not mention it should.

**Comment by brandy125** [comment]
strange, I tested now in IDL 7.0.1 and it does not show as well….

**Comment by GillesDuvert** [comment]
Yes I would say it is an IDL bug.
Personally I would like .TRACE to work as imagined, if not as in IDL. Probably easy too.
At the time I note that .SKIP  in GDL count lines differently from IDL, which is not going to help:
given:
```
pro testme
        print,"line 2"
        stop, "stop at line 3"
        print,"line 4"
        print, "line 5"
        print, "line 6"
end
```
I have (IDL):
```
IDL> testme
% Compiled module: TESTME.
line 2
stop at line 3
IDL> .sk 2
% Skipped to: TESTME              5 /home/gildas/testme.pro
IDL> .c
line 5
line 6
IDL> 
```
while GDL is wrong by 1 line (besides,  STOP command should be quiet when a variable is passed to STOP):
```
GDL> testme
% Compiled module: TESTME.
line 2
stop at line 3
% Stop encountered: TESTME               3 /home/gildas/testme.pro
GDL> .sk 2
% Skipped to: TESTME               6 /home/gildas/testme.pro
GDL> .c
line 6
GDL>
```

**Comment by GillesDuvert** [comment]
Well, guys, this is not for the faint of heart, I can assure you.

**Comment by GillesDuvert** [comment]
OK, #1414 makes debugging GDL much more easy, with correct line numbers, .RET and .SO

@brandy125 please test. Probably convoluted cases may break GDL (but they break IDL too!)

Please note that issuing an error at MAIN when debugging (the initial intent of this issue) leads to a behaviour different from IDL, and that cannot easily be made similar given the way GDL is coded. 
typing an erroneous code like
```
GDL> print,out
% PRINT: Variable is undefined: OUT
```
during a debug session 
will give the same error message (as reported above) all the time unless one skips the 'line':
```
GDL> testme
% Compiled module: TESTME.
line 8
stop at line 9
GDL> print,out
% PRINT: Variable is undefined: OUT
% Execution halted at: TESTME              10 /home/gildas/testme.pro
%                      $MAIN$          
GDL> .sk
% Can't continue from this point.
GDL> .s
GDL> .s
line 10
% Stepped to: TESTME              11 /home/gildas/testme.pro
```
You have to think that from the GDL perspective, the erroneous line is a false statement that has been inserted in the procedure (at level TESTME) not at level MAIN. Skipping the erroneous statement is the solution, as it would be for any line in error in a procedure. The .SK skips this error, the following .S (or .C) sort of 'return' to the line in the debugged procedure, and voila! (So, please ignore the `% Can't continue from this point` in this case).

**Comment by brandy125** [comment]
Thanks Giloo!


Ok, no problem to type .skip after insterting an erroneous line for now.
Just a question: Could this be avoided in future?

I tested with my program and I can see that after a .skip, followed by a .c, the program does not continue. I need to type a second time .c so that the program continues.

Could this be avoided in future?

I am not complaining, just giving hints from my point of view.

**Comment by GillesDuvert** [comment]
> I tested with my program and I can see that after a .skip, followed by a .c, the program does not continue. I need to type a second time .c so that the program continues.

Yes indeed:
1. skip just goes to the 'end of offending command'
1. continue or .s (or .return) steps out the MAIN routine and back to the debugged one
1. from there, normal debugging: .c to continue, .s to step etc.

**Comment by alaingdl** [comment]
Could we summarize those informations somewhere ? (in the Wiki ?) 
I know it is not widely known.

**Comment by brandy125** [comment]
No problem if it works like that but I agree with Alain that it should be dokumented somewhere.
