### ISSUE TITLE
/isotropic keyword not working after resizing the plot window

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1405]
```
GDL> window,xsize=1024,ysize=768
GDL> plot,findgen(100),findgen(100),/isotropic
```
The above plot is correct. The inclination of the plot line is 45 degree as it should be.
If we now stretch the window with the mouse horizontally and make it bigger (or smaller) then the following plot line is inclined less ( or more) than 45 degree and this is not correct.

```
GDL> plot,findgen(100),findgen(100),/isotropic
```

Remark: The plot line must be always at 45 degree, independent of the window size.

**Comment by alaingdl** [comment]
with the PR #1407 and the X11 output, it seems to be OK for me.
To simplify the test, what I did : 
```
window,xsize=1024,ysize=400
plot, findgen(10)
plot, findgen(10),/iso,/noera
```
both axis of the 2 plots overplot well in the left part. And GDL and IDL outputs are very similar (except details in the slope,
better anti-alias in IDL ?)

It is OK too (same behavior) when resizing the window.

**Comment by brandy125** [comment]
yes, I saw this as well today.

**Comment by GillesDuvert** [comment]
No, indeed, the whole plots are stretched when a resize is performed. Including hershey (vector) fonts but not symbols.
(with !P.FONT=1 the font is not vector so the charaters are not strectched).
This seems to be due to a lack of update of values between plplot and gdl.
bug report accepted!

**Comment by GillesDuvert** [comment]
This does not happen with the X11 driver (that reports consitent values after a resize).
We use the fast but unreliable old wxWidgets driver and need to patch it.
A workaround is provided in #1420
