### ISSUE TITLE
Regression in test_axis.pro

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1410]
As mentioned in #1407 outputs of test_axis are not OK for horizontal axis 
(position, and the color line should cover the white line (e.g. the purple line in third plot))

All was OK still Git version of Sept. 5
Version on Oct 10 is broken
(large changes in between)

**Comment by GillesDuvert** [comment]
works for me on all platforms. ?

**Comment by alaingdl** [comment]
Do you need I make screenshots ?  On third window the purple line is not here
and the numbers are in bad location ... On the second window 3 green lines are missing

Most of horizontal AXIS are not at the rigth location

I have that issue for Debian 10 (remote), OSX (remote) and Ubuntu 22.04 (local)

**Comment by alaingdl** [comment]
IDL & old GDL ![idl88_axis](https://user-images.githubusercontent.com/38264661/203661546-e21f3888-f176-4130-ae25-0051966a2ff3.png)

curernt GDL 
![gdl_axis](https://user-images.githubusercontent.com/38264661/203661592-51e8c12a-fbf1-4d92-ab93-12dd6888a4e1.png)

**Comment by GillesDuvert** [comment]
OK, my bad, now I see it.
It looks like only the supplementary horizontal (green) axis are drawn at y=0 everytime, and without the axis line and ticks, only the labels. Probably a line of code was erased by error.

**Comment by GillesDuvert** [comment]
oops corrected in #1407
