### ISSUE TITLE
Debian 9 & plplot 5.10

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1411]
Current PR1407 cannot be compiled on Debian 9.13 (up-to-date) due to the version of plplot-5.10 packaged.
Cmake & build script did failed at the compilation step.

When using plplot-5.12 locally compile, it is OK (with cmake)

Just to say something is missing in the detection of plplot version in our CMake file

**Comment by GillesDuvert** [comment]
GDL uses a very minimal subset of plplot and should not be so dependent from a plplot number version. What is exactly the compilation error?
