### ISSUE TITLE
in plot, yrange is not working well in some specific cases

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1416]
(As far as I tested, /ystyle is well enforced)

```
GDL> plot, shift(fft(80*sin(findgen(8000)/100*!dpi)), 4000), yrange=[-.001, .001]
GDL> print, !y.crange
   -0.0015000000    0.0010000000

IDL> plot, shift(fft(80*sin(findgen(8000)/100*!dpi)), 4000), yrange=[-.001, .001]
IDL> print, !y.crange
   -0.0010000000   0.00099999995
```

This case seems to be very basic ...  but not fine :(
And it is working fine in others cases (`plot, 0.00001*findgen(100), yrange=[-.01, .001] & print, !y.crange`)

Good news ! We can make some automatic tests on that ! (even with no graphical mode SET_PLOT, 'z')

**Comment by GillesDuvert** [comment]
IDL modifies the [XYZ]RANGE also and  only by using ysty=1 are you  assured that the range is exactly the one asked for.
Respecting this rule is one of the recent improvements of GDL, that adds another rule atop of AutoIntv() in plotting.cpp
However, the adjustement may not always be the same as IDL as the algorithms obviously differ.
But indeed, there was a missing line in the code, corrected now.
