### ISSUE TITLE
bugs in test_surface_basic

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1418]
in current Git version (yes after PR #1407 thanks @GillesDuvert ) I do have various troubles when calling test_surface_basic.pro

```
Start of tests with high difficulties (working since GDL 0.9)
X, Y and Z and all 2D arrays with same size
% SURFACE: Sorry, plplot cannot handle 2D X coordinates in its 3D plots.
[...]
*** PLPLOT ERROR, ABORTING OPERATION ***
plot3dcl: Y array must be strictly increasing, aborting operation
```
obviously, as usual, the results & problems are not the same on U2204 and Debian 10.13

**Comment by GillesDuvert** [comment]
>obviously, as usual, the results & problems are not the same on U2204 and Debian 10.13

This comes from the driver used, that is not the one patched by us and installed in the special location `/usr/local/share/gnudatalanguage/drivers`.

**Comment by GillesDuvert** [comment]
See #1438 plplot imposes severe restrictions on  `surface` and `shade_surf`
