### ISSUE TITLE
plots reports erroneously "Not enough valid and unique points specified" 

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1432]
This simple plot generates an error message different to IDL where it works normally:
```
GDL> a=[[0,1,2],[2,3,4]]
GDL> plot,findgen(10)
GDL> plots,a
% PLOTS: Not enough valid and unique points specified.
% Execution halted at: $MAIN$          
GDL> 
```

**Comment by alaingdl** [comment]
Thanks for this bug report, confirmed here.

See from here, this bug appeared after Sep 26 and before Oct 18. HTH 
Unfortunately most of the plotting_*pp & gdl*stream.?pp have been changed at that time !

Could we consider to have some plotting tests in Z mode to detect such problems ?

A.

**Comment by alaingdl** [comment]
In fact TEST_PLOT_USERSYM is also broken since this time

**Comment by GillesDuvert** [comment]
ALL should be OK now with #1437

**Comment by GillesDuvert** [comment]
... And thanks for the tests!

**Comment by GillesDuvert** [comment]
Argh corrected the TEST_PLOT_USERSYM problem but not the "Not enough valid and unique points specified".
One problem, one issue...

**Comment by GillesDuvert** [comment]
thanks for your patience!

**Comment by brandy125** [comment]
Thanks to you!!!
