### ISSUE TITLE
Regression in basic PLOT + xrange

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1433]
I discovered that incidentally because I am exploring block by block a time series with thousands of points.

in current git version, if I do :  offset=2400 & plot, b, xrange=[offset, offset+24*24-1]
the x-axis does start at 2200 ! It should start at 2400 ! (as it did till before Dec 6, 2022)

```
GDL> plot, randomu(seed, 100000) , xrange=[2400, 2400+24*24-1]
GDL> print, !x.crange
       2200.0000       3000.0000
```

IDL and GDL prior Dec 06 give : `2400.0000 3000.0000`

I notice that we have to rework and merge two old fashioned tests which should detect such problems :
_test_plotting_ranges.pro_ & _test_plot_ranges.pro_
I can do that.

**Comment by alaingdl** [comment]
In PR #1434 I add some cases but they are not working with current git version ...

**Comment by GillesDuvert** [comment]
ALL should be OK now with https://github.com/gnudatalanguage/gdl/pull/1437
