### ISSUE TITLE
XINTERANIMATE crash at the end 

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1442]
```
GDL> XINTERANIMATE, /KEEP_PIXMAPS
GDL> terminate called after throwing an instance of 'GDLException'
Abandon (core dumped)
```

Running the basic example https://www.l3harrisgeospatial.com/docs/xinteranimate.html

**Comment by GillesDuvert** [comment]
very ambitious as several needed functions are absent from GDL.
In may cases it does not work as expected, but no crash.
This will not be a priority I guess.

**Comment by alaingdl** [comment]
No priority on my side too. Just discovering a functionality in IDL during tests for t3d !

**Comment by GillesDuvert** [comment]
works4me as of today's GDL state
