### ISSUE TITLE
pixmap keyword in windows routine is not working any more? 

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1456]
The command

```
GDL> window,1,/pixmap
```

opens a window while it should not.

**Comment by GillesDuvert** [comment]
Normally this regression was found and fixed in #1450

**Comment by brandy125** [comment]
Sorry, i missed that. Thanks!!Sent from my iPhoneOn 28 Dec 2022, at 13:41, Giloo ***@***.***> wrote:﻿
Normally this regression was found and fixed in #1450
