### ISSUE TITLE
SHADE_SURF broken

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1466]
(playing with graphics_times3 & graphics_times4)
with the current git version (today, after #1464 ), with X11 or WxWidgets, 
SHADE_SURF is broken (with wx or X11)

**Comment by GillesDuvert** [comment]
Something different from #1438 ?

**Comment by alaingdl** [comment]
Sorry not to put the basic code which is enough to make it !

```
SHADE_SURF, dist(128)
```

The output was perfect in GDL 1.0.0 in X11 mode (I don't have the wx driver but I can recompile if needed)

And yes I have this message, but I do no understand why ;)
(% SHADE_SURF: due to plplot restrictions, shaded surface is not entirely visible. Please try with zvalue=0.5 or greater.)

**Comment by GillesDuvert** [comment]
yes, that is exactly as it is said in the message. Either you use plplot and have no 3D, except for some special cases of projection and only for surface and shade_surf , or you go over plplot, get all the 3D features, but encounter an internal restriction of plplot in shade_surf.
This will be resolved in due time.

**Comment by GillesDuvert** [comment]
solved in https://github.com/gnudatalanguage/gdl/pull/1515 , this is the maximum one can do with plplot shading/surface functions.
