### ISSUE TITLE
current file pointer jumps to the end when file grows after it has been opened

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1474]
The current file pointer must stay at position 100000 even if the file grows:

```
GDL> openw,1,'eraseme'
GDL> line1=bytarr(1000)
GDL> for i=0,99 do writeu,1,line1
GDL> flush,1
GDL> 
GDL> openr,2,'eraseme'
GDL> line2=bytarr(1000)
GDL> for i=0,99 do readu,2,line2
GDL> print,fstat(1)
{ 1 eraseme   1   0   0   0   0   0   1   1  1673731066 1673731024 1673731024 0 100000 100000  0}
GDL> print,fstat(2)
{ 2 eraseme   1   0   0   0   0   0   1   0  1673731066 1673731024 1673731024 0 100000 100000  0}
```
up to here it is correct. But if we increase the file size then the current pointer must stay at position 100000 as it is in IDL. It must not jump to 200000 which is the size of the file.
```
GDL> for i=0,99 do writeu,1,line
GDL> flush,1
GDL> print,fstat(2)
{ 2 eraseme   1   0   0   0   0   0   1   0 1673731066 1673731087 1673731087 0 200000 200000 0}
```

**Comment by brandy125** [comment]
Can anybody help here? I would need a solution for this since I am working with realtime data right now and this is a "no go".
Thanks!

**Comment by alaingdl** [comment]
1/ reproduced
2/ seems to be related to method Tell(p in `io.cpp` which does not distinguish between reading and writing case

**Comment by alaingdl** [comment]
I changed your code in such a way : 

```
pro test_issues1474, maxi=maxi

if ~keyword_set(maxi) then maxi=99

close,1, 2

openw,1,'eraseme'
line1=bytarr(1000)
for i=0,99 do writeu,1,line1
flush,1

openr,2,'eraseme'
line2=bytarr(1000)
for i=0,maxi do readu,2,line2
f1=fstat(1) & print, 'f1 :', f1.unit, f1.cur_ptr, f1.size
f2=fstat(2) & print, 'f2 :', f2.unit, f2.cur_ptr, f2.size
;print,fstat(1)
;print,fstat(2)

for i=0,99 do writeu,1,line1
flush,1
f1=fstat(1) & print, 'f1 :', f1.unit, f1.cur_ptr, f1.size
f2=fstat(2) & print, 'f2 :', f2.unit, f2.cur_ptr, f2.size
;print,fstat(2)

stop
end

```

What is really strange is that if maxi is less than 99 the code is OK :(

May be a problem in the line 
`if (actUnit.Eof()) pos=buffer.st_size; else pos=actUnit.Tell()` because we play with the limit ?

**Comment by GillesDuvert** [comment]
please try patch #1502

**Comment by alaingdl** [comment]
Ok, thanks @GillesDuvert 

On my side I arrived to that fact that the 
`bool AnyStream::Eof() {` is not OK, and just removing 
```
    //    fStream->clear(); // clear old EOF	
    //    fStream->peek(); // trigger EOF if at EOF
```
is enough to solve the problem (but with which side effect ?)

I will check tomorrow you patch

**Comment by GillesDuvert** [comment]
solved.

**Comment by brandy125** [comment]
Hi guys, I just came back from a journey and would like to test this version but I do not succeed in compiling.
It is complaining with this error message:


bash$ cmake ..
CMake Error at CMakeLists.txt:13 (message):
  The src/whereami git submodule is not initialised.

   Please run `git submodule update --init`


-- Configuring incomplete, errors occurred!


How can I compile the latest version?

**Comment by alaingdl** [comment]
yes, you have to do that : 
`git submodule update --init`
it will add the files needed in the src/whereami sub-dir

**Comment by brandy125** [comment]
In which directory I have to stay?

I tried already and got this messages:

bash$ pwd
/home/chris/Downloads/gdl-master-5

bash$ git submodule update --init
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
bash$

**Comment by alaingdl** [comment]
where you have the `.gitmodules` & `.gitignore` files.

or, after, in the path where you did `git pull`

**Comment by brandy125** [comment]
This is where I am already:

bash$ pwd
/media/psf/Home/Downloads/gdl-master-6
bash$ ls -al
total 288
drwxr-xr-x 1 chris users   960 Feb 10 18:51 .
drwx------ 1 chris users  4480 Feb 10 18:17 ..
-rw-r--r-- 1 chris users  1507 Feb 10 03:51 AUTHORS
drwxr-xr-x 1 chris users   128 Feb 10 18:51 build
-rw-r--r-- 1 chris users 45810 Feb 10 03:51 CMakeLists.txt
drwxr-xr-x 1 chris users   736 Feb 10 03:51 CMakeModules
-rw-r--r-- 1 chris users  2369 Feb 10 03:51 config.h.cmake
-rw-r--r-- 1 chris users 15131 Feb 10 03:51 COPYING
drwxr-xr-x 1 chris users   160 Feb 10 03:51 doc
-rw-r--r-- 1 chris users  8196 Feb 10 18:51 .DS_Store
drwxr-xr-x 1 chris users   960 Feb 10 18:21 gdl
drwxr-xr-x 1 chris users    96 Feb 10 03:51 .github
-rw-r--r-- 1 chris users    84 Feb 10 03:51 .gitignore
-rw-r--r-- 1 chris users   107 Feb 10 03:51 .gitmodules
-rw-r--r-- 1 chris users 14388 Feb 10 03:51 HACKING
-rw-r--r-- 1 chris users  3463 Feb 10 03:51 INSTALL.CMake
-rw-r--r-- 1 chris users  1373 Feb 10 03:51 INSTALL.plplot
-rw-r--r-- 1 chris users  4511 Feb 10 03:51 MAP_INSTALL
-rw-r--r-- 1 chris users 45497 Feb 10 03:51 NEWS
drwxr-xr-x 1 chris users   512 Feb 10 03:51 obsolete
drwxr-xr-x 1 chris users   128 Feb 10 03:51 paper
-rw-r--r-- 1 chris users  3979 Feb 10 03:51 PYTHON.txt
-rw-r--r-- 1 chris users 15050 Feb 10 03:51 README
-rw-r--r-- 1 chris users  5234 Feb 10 03:51 README.GRIB
-rw-r--r-- 1 chris users 10537 Feb 10 03:51 README.md
-rw-r--r-- 1 chris users  3144 Feb 10 03:51 README.THREADPOOL
drwxr-xr-x 1 chris users   256 Feb 10 03:51 resource
drwxr-xr-x 1 chris users   160 Feb 10 03:51 scripts
drwxr-xr-x 1 chris users 10976 Feb 10 03:51 src
drwxr-xr-x 1 chris users 10112 Feb 10 03:51 testsuite
bash$ git submodule update --init
fatal: not a git repository (or any parent up to mount point /media/psf)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
bash$

**Comment by alaingdl** [comment]
Very strange ! Could you create a new dir, then make : 
```
git clone https://github.com/gnudatalanguage/gdl
cd gdl
git submodule update --init
```
That is working for me

**Comment by brandy125** [comment]
your instructions work for me as well.
The problem is when we download the .zip, this does not contain the .git folder just the .github folder.

Try to do the same in the downloaded .zip file and you will encounter the problem I faced.

**Comment by GillesDuvert** [comment]
Ouch, GitHub does not know about submodules?
I created https://github.com/gnudatalanguage/gdl/wiki/Cloning-gnudatalanguage-gdl but this is not satisfactory.
GitHub should support 'submodules' fully in this 
![image](https://user-images.githubusercontent.com/33936193/218254221-f4321280-2572-4d4a-bbcf-c8ce359a14c4.png)
button

Strange that nobody complained to GH since it is so frequent.

**Comment by slayoo** [comment]
The lack of submodule content in source archives is the topic of #1496.
We will workaround it by creating our own archives within the weekly and main releases.
This was reported to GitHub long long time ago, but seems to be tricky to solve (due to security reasons?): https://github.com/dear-github/dear-github/issues/214
