### ISSUE TITLE
undefined reference to `MyPaths::getExecutableDir()'

### ISSUE THREAD

**Issue by thierry-FreeBSD** [gnudatalanguage/gdl#1475]
Trying v1.0.2, compilation is OK, but linkage fails:
```
gdl.cpp:(.text+0x987): undefined reference to `MyPaths::getExecutableDir()'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** [src/gdl] Error code 1

```

**Comment by alaingdl** [comment]
OK, which OS do you use ? (a BSD like ?) On my side I only have a warning.

lines 281 & 287 in _gdl.cpp_

```
/home/alaingdl/GDL/gdl-1.0.2/src/gdl.cpp: In function 'std::string MyPaths::getExecutablePath()':
/home/alaingdl/GDL/gdl-1.0.2/src/gdl.cpp:281:12: warning: ignoring return value of 'char* realpath(const char*, char*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  281 |    realpath(PROC_SELF_EXE, rawPathName);
      |    ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by alaingdl** [comment]
linked to changes made by @GillesDuvert two weeks ago ...

**Comment by alaingdl** [comment]
around lines 247+ in `gdl.cpp` we do have calls which are OS-dependant (and do not take into account BSD)

see also https://stackoverflow.com/questions/1023306/finding-current-executables-path-without-proc-self-exe

**Comment by GillesDuvert** [comment]
Analysis exact. We need the real path of the executable. Do not know how to get it on FreeBSD. Any hints, @thierry-FreeBSD ? 
In the absence of this code, the drivers, projection data and probably many other dependencies will not be found and GDL will crash.

**Comment by alaingdl** [comment]
at the end of the discussion in StackOverFlow a lib. seems to manage that reliably
https://github.com/gpakosz/whereami

**Comment by GillesDuvert** [comment]
OK, so try to understand what is in all the #ifdef that contain "BSD".

**Comment by thierry-FreeBSD** [comment]
Yes, https://github.com/gpakosz/whereami seems a good and portable solution.

**Comment by GillesDuvert** [comment]
Done in #1477 . @thierry-FreeBSD could you test?

**Comment by thierry-FreeBSD** [comment]
Just tested on FreeBSD: everything is fine!
Thanks.
