### ISSUE TITLE
FILE_CHMOD under Windows

### ISSUE THREAD

**Issue by Albom** [gnudatalanguage/gdl#1476]
FILE_CHMOD under Windows generates an exception (Line 19):

```idl
if !VERSION.OS_FAMILY ne 'unix' then MESSAGE,"FILE_CHMOD is only available on Unix Operating Systems (help!)"
```

This exception can halt an execution of a script calling FILE_CHMOD. A temporary solution can be printing message and return:

```idl
if !VERSION.OS_FAMILY ne 'unix' then begin
    print,"FILE_CHMOD is only available on Unix Operating Systems."
    return
endif
```

But of course, using of icacls (https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/icacls) is needed.

**Comment by GillesDuvert** [comment]
Hi @Albom thanks,
To be perfectly sure: the icalcs commands seem a bit too numerous, the procedure will be a mess to set up for the windows case, yes?
Probably FILE_CHMOD shoudl be implemented in C/C++ with the standard chmod() function.
