### ISSUE TITLE
Cmake error in latest (the whereami git submodule)

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1489]
When trying to build the latest GIT (https://github.com/gnudatalanguage/gdl/commit/b8aeafcae677e565bbed0ce7af93ccd0ccb6d237), I get a failure during the `cmake` phase:
````
CMake Error at src/CMakeLists.txt:200 (add_library):
  Cannot find source file:

    /data/software/AUR/gnudatalanguage-git/src/gnudatalanguage-git/src/whereami/src/whereami.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at src/CMakeLists.txt:200 (add_library):
  No SOURCES given to target: whereami

````
There is an empty `whereami` directory in the `src` directory but nothing else.

Does anyone have any suggestions? (GDL's cmake code is way over my head).

**Comment by slayoo** [comment]
Hello @jtappin, thanks for reporting.
This is caused by the introduction of a git submodule to gdl git repo (with the whereami lib source code).
One solution is to do `git clone --recurse-submodules` when cloning the repo.

**Comment by alaingdl** [comment]
mandatory :( 

I do consider this is a temporary work-around, too complex for new users (or very clear messages)

**Comment by slayoo** [comment]
Certainly, we need to improve and clarify instructions for developers, but I'd say that with so many third-party files in the repo, we will greatly benefit from introducing multiple other submodules to keep track of the origins of these files, facilitate updates and make life easier for packagers who need to check licensing and often prefer to replace our convenience copies with upstream code dependencies.

**Comment by slayoo** [comment]
If not cloning from scratch, but updating an existing clone, please try doing `git submodule update --init --recursive` after a pull/fetch.

**Comment by GillesDuvert** [comment]
I've added last saturday the minimal documentation in the README.md and the WIKI.
But unless GH or git makes it easy, we're going to get many more remarks.

**Comment by slayoo** [comment]
Perhaps we could make CMake issue a meaningful hint if any of the submodule files are not present?

**Comment by slayoo** [comment]
Something like this: https://github.com/gnudatalanguage/gdl/pull/1491 ?
(inspired by https://github.com/iree-org/iree/issues/6434)

**Comment by GillesDuvert** [comment]
yes, clever! (IMHO)
