### ISSUE TITLE
gdlde failed download crashes Windows Continuous Integration

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#1493]
https://github.com/gnudatalanguage/gdlde/releases/download/v1.0.0/gdlde.product-win32.win32.x86_64.zip is not downloaded by our Windows continous integration ???

**Comment by pjb7687** [comment]
It randomly fails, I don't know exactly why, but perhaps this is due to the DDoS protection or something similar.

**Comment by pjb7687** [comment]
I reran the most recent release build and it seems to work well.
