### ISSUE TITLE
include submodule content in source code release files

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#1496]
@pjb7687 Let me ask you for help in adding to our Github Actions scripts a logic to prepare custom source code release files which would include submodule content (currently the `src/whereami` files, but likely more in the future). It seems this is what we would need but I have little experience with the current GDL workflows, and it's a bit tricky for me to locate a place where to add it: https://github.com/pytorch/pytorch/commit/6c75027f7e4806d02c27c5c8a723b9c3de1414bd

Thanks

**Comment by slayoo** [comment]
Indeed, in this week's GDL weekly build files, the source archives have an empty `whereami` folder instead of the submodue content: https://github.com/gnudatalanguage/gdl/releases/tag/weekly-release

**Comment by pjb7687** [comment]
It is currently impossible:
https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release

And it seems the Pytorch team release their own source code tarball in parallel. Should we also do this?

**Comment by slayoo** [comment]
@pjb7687 yes, this is exactly what I had in mind: to make a custom source artifact and publish it along our binary releases. Thanks

**Comment by pjb7687** [comment]
Added. I will fix it if it won't work out:
https://github.com/gnudatalanguage/gdl/commit/a14333498e4ffd5dc93463d3e1108b3753b8b855

**Comment by slayoo** [comment]
Thank you!

**Comment by pjb7687** [comment]
Uh-oh, seems it needs to be fixed. I think I am going to have some time to fix it tomorrow

**Comment by slayoo** [comment]
@pjb7687 there are still three issues now (visible, e.g., here: https://github.com/gnudatalanguage/gdl/releases/tag/weekly-release):
- [x] the archive is a tarbomb, i.e. it does not include a `gdl` root folder, and unpacking it clutters local directory
- [x] the `gdl-unstable-...tar.gz` file contains the unneeded `.git` folder (70 megabytes!)
- [ ] the incomplete "normal" zip and tar.gz archives are sitll being provided for the release
Thanks!

**Comment by pjb7687** [comment]
It should be fixed now. The third point is inevitable as it is a default behaviour of Github... See this: https://github.com/pytorch/pytorch/releases/tag/v1.13.1

**Comment by slayoo** [comment]
Thank you!
