### ISSUE TITLE
Remove headless build on Windows?

### ISSUE THREAD

**Issue by pjb7687** [gnudatalanguage/gdl#1499]
Currently, the build fails due to the recent patches by @GillesDuvert that require wxWidgets installed for GDL on Windows.

As there is no "command line only" environment on Windows, I think it does make sense to keep them as they are and drop the headless build.

Is there anyone who needs a headless build on Windows? Otherwise, I suggest we should remove it.

**Comment by slayoo** [comment]
+1 for removing headless Windows builds.

**Comment by GillesDuvert** [comment]
same here ... Did not realize there would be an headless build on windows :blush:

**Comment by pjb7687** [comment]
https://github.com/gnudatalanguage/gdl/commit/4c1a4b4d6b6af17d71f835d7d71d04125abfc643 should remove the build. Thanks!
