### ISSUE TITLE
Foreach code does not mess up count variable as IDL

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#1500]
... But it should if we want to respect IDL's behaviour. Or do we?

```
IDL> a = INDGEN(15)& foreach i, a, ind do begin & if i lt 14 then a[i+1]=0 & print,i & end    
       0
       0
       2
       0
       4
       0
       6
       0
       8
       0
      10
       0
      12
       0
      14
GDL> a = INDGEN(15)& foreach i, a, ind do begin & if i lt 14 then a[i+1]=0 & print,i & end  
       0
       1
       2
       3
       4
       5
       6
       7
       8
       9
      10
      11
      12
      13
      14

```
IDL sort of use a[i] for its counter (each other value), but GDL kindly uses a copy of a (that is not mangled during the foreach loop). This is safer, but slower. See #1498 for an extreme case.

**Comment by jtappin** [comment]
IMHO, we should not reproduce IDL's bugs. The documentation on the subject is (by their standards) fairly clear, if clunky.

[FOREACH](https://www.l3harrisgeospatial.com/docs/FOREACH.html)

When iterating over an ordinary array the original array is not altered.
With lists and hashes the elements may be altered, as the item is a pointer to the real object in the heap.

So the case you have is a bug in IDL.

**Comment by GillesDuvert** [comment]
Indeed, and, besides, it would be complicated to reproduce this bug :smile: 

Closing as invalid.

**Comment by GillesDuvert** [comment]
For the record, another idiosyncrasy that GDL does not reproduce:
```
IDL> a=lindgen(10) & b=0& foreach i,a,ind do begin & print,ind & if i gt 5 then a=bytarr(23) & end 
                     0
                     1
                     2
                     3
                     4
                     5
                     6
                     7
                     8
                     9
                    10
                    11
                    12
                    13
                    14
                    15
                    16
                    17
                    18
                    19
                    20
                    21
                    22

```
GDL stops at 9 ...

**Comment by fawltylanguage** [comment]
> When iterating over an ordinary array the original array is not altered. 

I think this means that the array is not altered through the variable i. Explicitly changing an array element should work.

**Comment by jtappin** [comment]
The more I think about this, the more I think that it's a very grey area. I very much doubt if "side effects" like this were properly thought through when `foreach` was implemented in IDL.

In a well-designed high level language, a loop like `foreach` would prohibit the alteration of any of the control variables inside the body of the loop. A `for` loop can alter an array since the array is not a part of the loop control.

Consider for example this:
````
for i = 0, 30 do begin & print, i & i-- & end
````
which is in IDL & GDL perfectly legal, and behaves the same way—an infinite loop.

I think that these cases are very much corner cases, outside the normal and intended use of `foreach` so my inclination would be to leave well alone.

**Comment by jtappin** [comment]
This on the other hand is quite telling:
````
n=12 & for i = 0, n do begin & print, i & if i gt 9 then n = 16 & end
````
Both IDL and GDL stop at 12 in this case, which IMHO is the proper thing to do. After the loop `n` is 16

**Comment by GillesDuvert** [comment]
closing (that's already way too much issues open for GDL) but pls open a new if necessary.
