### ISSUE TITLE
how to crash REPLICATE ? 

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1501]
`z=replicate(3,!values.f_nan)`

`z=replicate(3,!values.f_infinity)` is OK

OK, I made a typo :smiling_face_with_tear:  (interverting first and second arg.)

(I am not sure to be able to look at that today)

**Comment by alaingdl** [comment]
What I was afraid of is confirmed :cry: 

```
IDL> B = BYTARR(2, !values.f_nan)
% Array dimensions must be greater than 0.
```
versus
```
GDL> B = BYTARR(2, !values.f_nan)
GDL> help, b
B               BYTE      = Array[2, 9223372036854775808]
```

We do face a serious problem, protecting all the inputs

**Comment by alaingdl** [comment]
`identity( !values.f_nan)` and  `z=findgen(3,!values.f_nan)` crashed too ...

**Comment by jtappin** [comment]
````
IDL> B = BYTARR(2, !values.f_nan)
% Array dimensions must be greater than 0.
````
Isn't exactly suggestive of elegant handling of the case in IDL either.
A quick investigation suggests that when encountering a floating point dimension argument IDL computes `LONG64`, while GDL computes `ULONG64`. And `long64(!values.f_nan) = -9223372036854775808` while 
`ulong64(!values.f_nan) = 9223372036854775808`.

I don't think that's really the proper way to handle the situation though.

**Comment by GillesDuvert** [comment]
I believe we should use LONG64 .

**Comment by alaingdl** [comment]
I think we have an opportunity to deliver a clever message than IDL

It is not urgent, less urgent that "operational" bugs or regressions. Then we can think on solutions.
(if e->ParamIsNotFinite(2) then ...)

**Comment by GillesDuvert** [comment]
the patch will be sufficient for the time being I believe.
