### ISSUE TITLE
surface, array, shades=shades has problems.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1507]
I was actually quite surprised that this even attempted to do anything, but the shades keyword to colour a surface plot clearly has problems.
````
r = [0b, 255b, 255b, 0b, 0b]
g = [0b, 255b, 0b, 255b, 0b]
b = [0b, 255b, 0b, 0b, 255b]

device, decomp = 0
tvlct, r, g, b

pattern = hanning(120, 120)

shades = replicate(1b, 120, 120)

locs = where(pattern gt 0.3)
shades[locs] = 3b
locs = where(pattern gt 0.5)
shades[locs] = 4b
locs = where(pattern gt 0.7)
shades[locs] = 2b

surface, pattern, shades = shades, charsize = 2

end
````
IDL produces: ![idl_surf](https://user-images.githubusercontent.com/658624/217594900-69c0668f-8475-4f55-bded-091b63d72283.png)
GDL produces: ![gdl_surf](https://user-images.githubusercontent.com/658624/217594904-f359e70f-dd57-448e-9cb3-e1849d35dee1.png)
and a lot of error messages like:
````
*** PLPLOT WARNING ***
plcol1: Invalid cmap1 index
Further information relevant to this warning:
Invalid index = -4.993116e-01
Corrected index = 0.000000e+00
````
I'm guessing that we're pushing plplot over the edge again!

**Comment by GillesDuvert** [comment]
Yes... And no, plplot pretends to be able to colorize surfaces, too. Due to clunky documentation the passing of arguments to the plplot function may not be OK. looks like it is related to an ancient plplot's problem with colormaps.

**Comment by GillesDuvert** [comment]
@jtappin in fact plplot proposes to colorize the mesh, but only as a function of z, in a undescribed manner, but roughly from color0 (bottom) to color255 (top).
try:
```
 tvlct, r, g, b
(...)
surface, pattern, shades = shades = [0,3,2,4,6,8,20], charsize = 2,zv=0.5
```

the zv=0.5 is to prevent the plplot errors, themselves related to the shade_surf problem  #1438 , that I hope to solve soon.

**Comment by GillesDuvert** [comment]
OK, found a workaround (yet another)...
#1515 provides now a better shade_surf and surface (not in all cases though, due to inherent limitation of plplot),
but I've removed the SHADE option as it is absolutely impossible to reproduce with plplot at all.

**Comment by jtappin** [comment]
> OK, found a workaround (yet another)... #1515 provides now a better shade_surf and surface (not in all cases though, due to inherent limitation of plplot), but I've removed the SHADE option as it is absolutely impossible to reproduce with plplot at all.

That's a pity, though I did rather suspect from the results that I was getting that that would be the case. Thanks for investigating.
