### ISSUE TITLE
PIXMAP not working

### ISSUE THREAD

**Issue by rdimeo** [gnudatalanguage/gdl#1509]
I have not been able to get PIXMAPs working in GDL. Running the code below should display a plot in the window by drawing it first to the PIXMAP and then copying it to the window. However the window remains blank.

pro test01
; Test program for GDL and PIXMAPS
device,decomposed = 0
loadct,0,/silent
xsize = (ysize = 500)
winvis = 0 & winpix = 1
window,winvis,xsize = xsize, ysize = ysize
window,winpix,/pixmap,xsize = xsize, ysize = ysize

wset,winpix
plot,randomn(s,100),psym = -4
wset,winvis
device,copy = [0,0,!d.x_size,!d.y_size,0,0,winpix]

wdelete,winpix
end

**Comment by GillesDuvert** [comment]
worksforme (since it is heavily in use in the IDLAstro 'atv' widget, a problem with pixmap is rapidly reported).
What version of gdl do you use? please give the outputs of:
`GDL> !version` and `GDL> !gdl`

**Comment by alaingdl** [comment]
tested on U22.04, ok for me

Are you on MSwin ?

**Comment by rdimeo** [comment]
Here's the result of !version and !gdl:

GDL> !version
{
    "ARCH": "x64",
    "OS": "Windows",
    "OS_FAMILY": "Windows",
    "OS_NAME": "Windows",
    "RELEASE": "8.2",
    "BUILD_DATE": "Feb  7 2023",
    "MEMORY_BITS": 64,
    "FILE_OFFSET_BITS": 64
}

GDL> !gdl
{
    "RELEASE": "1.0.2 Git",
    "BUILD_DATE": "Feb  7 2023",
    "EPOCH": 1675746000,
    "GDL_USE_DSFMT": 1,
    "GDL_USE_WX": 1,
    "GDL_POSIX": 0
}

**Comment by jtappin** [comment]
On Manjaro Linux, I did find I needed to click on or cover and uncover the visible window (or part thereof) to get it to update

**Comment by GillesDuvert** [comment]
@jtappin this may be another issue, but "normally" the last version since #1492 should not have this problem.

**Comment by GillesDuvert** [comment]
@rdimeo thanks for the information.
You are on Windows
Did you retrieve a Windows installer from our [GitHub weekly releases](https://github.com/gnudatalanguage/gdl/releases)  or did you rebuild GDL yourself, and if the case, what did you use [according to the very poor (apologies) documentation](https://github.com/gnudatalanguage/gdl/wiki/GDL-on-Windows)?

**Comment by rdimeo** [comment]
I used the installer. Thanks!

**Comment by GillesDuvert** [comment]
OK, I confirm the bug, and not only on Windows.
The plot is here, but no 'blitted' on the screen. (plot eventloop not activated)
Pending a patch, you can do:
instead of 
```
wset,winpix
plot,randomn(s,100),psym = -4
wset,winvis
device,copy = [0,0,!d.x_size,!d.y_size,0,0,winpix]
```
do
```
wset,winpix
plot,randomn(s,100),psym = -4
a=tvrd()
wset,winvis
tv,a
```
because `'tv'` triggers the plot event, not '`device,copy'` (at the moment)

**Comment by GillesDuvert** [comment]
Note: this happens only with the wxWidgets driver, not X11 driver (the latter absent on Windows)

**Comment by rdimeo** [comment]
> OK, I confirm the bug, and not only on Windows. The plot is here, but no 'blitted' on the screen. (plot eventloop not activated) Pending a patch, you can do: instead of
> 
> ```
> wset,winpix
> plot,randomn(s,100),psym = -4
> wset,winvis
> device,copy = [0,0,!d.x_size,!d.y_size,0,0,winpix]
> ```
> 
> do
> 
> ```
> wset,winpix
> plot,randomn(s,100),psym = -4
> a=tvrd()
> wset,winvis
> tv,a
> ```
> 
> because `'tv'` triggers the plot event, not '`device,copy'` (at the moment)

Thanks much for looking into this and your rapid reply and workaround! I uninstalled 1.0.2 and installed 1.0.1 and then the double buffering worked, with the caveat that I had to move the window prior to getting the graphics to appear in it.

**Comment by GillesDuvert** [comment]
This will be a one-liner patch. Now done. Thanks.

**Comment by GillesDuvert** [comment]
BTW, may take some time to propagate to a fresh Window installer since we have a bug with the windows compiler...

**Comment by rdimeo** [comment]
> BTW, may take some time to propagate to a fresh Window installer since we have a bug with the windows compiler...

Thanks. I look forward to using it when the next Windows installer is released.
