### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by rdimeo** [gnudatalanguage/gdl#1531]
I have a large IDL application (that currently works in IDL) that I'm trying to get running in GDL. In this application I create a class that inherits the IDL_CONTAINER object. However when I try to create this new object, it crashes when trying to invoke the INIT method of the IDL_CONTAINER object. It cannot find the INIT method of the IDL_CONTAINER object. The test code below is a short description and shows the error whenever you try to create the object TEST_CONT via o = obj_new('test_cont').  Note that this test code works fine in IDL. Any ideas would be greatly appreciated. Thanks in advance!

; ************************** ;
pro test_cont::cleanup
self->IDL_CONTAINER::cleanup
end
; ************************** ;
function test_cont::init
; Initialize superclass
if not self->IDL_CONTAINER::Init() then return,0B
return,1B
end
; ************************** ;
pro test_cont__define
define = {TEST_CONT, INHERITS IDL_CONTAINER}
end

**Comment by alaingdl** [comment]
Thanks you for the very clear bug report.

Unfortunately I am totally ignorant in such way to use IDL :(

I was only able to reproduce your problem : 

```
GDL> .r test_cont.pro 
% Compiled module: TEST_CONT::CLEANUP.
% Compiled module: TEST_CONT::INIT.
% Compiled module: TEST_CONT__DEFINE.
GDL> o = obj_new('test_cont')
% TEST_CONT::INIT: Attempt to call undefined method: GDL_CONTAINER::INIT
% Execution halted at: TEST_CONT::INIT      9 /home/alaingdl/GDL/test_cont.pro
%                      $MAIN$          
```

**Comment by GillesDuvert** [comment]
Hi, as the whole sswidl nasa software works with GDL, (sort of, but that's another topic), GDL is seemingly able to deal with objets in general, as they have tons of them. The only difference is IMHO the use of IDL_CONTAINER inside the functions (e.g.: `self->IDL_CONTAINER::cleanup`, where `self->cleanup` would have worked) .

 GDL creators avoided to use the term IDL in their code, but that's becoming difficult. I suspect there is a mismatch in the GDL code somewhere. This does not look too complicated, but may take time.

Would removing all references to  IDL_CONTAINER:: in a copy of the IDL application may save the day? After all, inheritance concept makes `self->IDL_CONTAINER::cleanup` and `self->cleanup` equivalent in all reasonably well programmed cases?
The example below works
```
function myobj::Init
  return, 1
end
function myobj::get
  return, 'Ok'
end
pro myobj::help
  help,/objects
end

pro myobj__define
  struct = {myobj, inherits IDL_CONTAINER}
end

```
giving:
```
GDL> o=obj_new("myobj")
% Compiled module: MYOBJ__DEFINE.
GDL> o->init()
       1
GDL> o->help
** Object class GDL_CONTAINER, 0 direct superclasses, 8 known methods
   Known Function Methods:
      GDL_CONTAINER::GET
      GDL_CONTAINER::COUNT
      GDL_CONTAINER::EQUALS
      GDL_CONTAINER::ISCONTAINED
   Known Procedure Methods:
      GDL_CONTAINER::ADD
      GDL_CONTAINER::CLEANUP
      GDL_CONTAINER::MOVE
      GDL_CONTAINER::REMOVE
** Object class GDL_OBJECT, 0 direct superclasses, 8 known methods
   Known Function Methods:
      GDL_OBJECT::_OVERLOADISTRUE
      GDL_OBJECT::INIT
      GDL_OBJECT::_OVERLOADBRACKETSRIGHTSIDE
      GDL_OBJECT::_OVERLOADEQ
      GDL_OBJECT::_OVERLOADNE
      GDL_OBJECT::_OVERLOADPLUS
      GDL_OBJECT::_OVERLOADMINUS
   Known Procedure Methods:
      GDL_OBJECT::_OVERLOADBRACKETSLEFTSIDE
** Object class HASH, 1 direct superclass, 17 known methods
   Superclasses:
      GDL_OBJECT  <Direct>
 (etc, two pages)
```

**Comment by rdimeo** [comment]
> Hi, as the whole sswidl nasa software works with GDL, (sort of, but that's another topic), GDL is seemingly able to deal with objets in general, as they have tons of them. The only difference is IMHO the use of IDL_CONTAINER inside the functions (e.g.: `self->IDL_CONTAINER::cleanup`, where `self->cleanup` would have worked) .
> 
> GDL creators avoided to use the term IDL in their code, but that's becoming difficult. I suspect there is a mismatch in the GDL code somewhere. This does not look too complicated, but may take time.
> 
> Would removing all references to IDL_CONTAINER:: in a copy of the IDL application may save the day? After all, inheritance concept makes `self->IDL_CONTAINER::cleanup` and `self->cleanup` equivalent in all reasonably well programmed cases? The example below works
> 
> ```
> function myobj::Init
>   return, 1
> end
> function myobj::get
>   return, 'Ok'
> end
> pro myobj::help
>   help,/objects
> end
> 
> pro myobj__define
>   struct = {myobj, inherits IDL_CONTAINER}
> end
> ```
> 
> giving:
> 
> ```
> GDL> o=obj_new("myobj")
> % Compiled module: MYOBJ__DEFINE.
> GDL> o->init()
>        1
> GDL> o->help
> ** Object class GDL_CONTAINER, 0 direct superclasses, 8 known methods
>    Known Function Methods:
>       GDL_CONTAINER::GET
>       GDL_CONTAINER::COUNT
>       GDL_CONTAINER::EQUALS
>       GDL_CONTAINER::ISCONTAINED
>    Known Procedure Methods:
>       GDL_CONTAINER::ADD
>       GDL_CONTAINER::CLEANUP
>       GDL_CONTAINER::MOVE
>       GDL_CONTAINER::REMOVE
> ** Object class GDL_OBJECT, 0 direct superclasses, 8 known methods
>    Known Function Methods:
>       GDL_OBJECT::_OVERLOADISTRUE
>       GDL_OBJECT::INIT
>       GDL_OBJECT::_OVERLOADBRACKETSRIGHTSIDE
>       GDL_OBJECT::_OVERLOADEQ
>       GDL_OBJECT::_OVERLOADNE
>       GDL_OBJECT::_OVERLOADPLUS
>       GDL_OBJECT::_OVERLOADMINUS
>    Known Procedure Methods:
>       GDL_OBJECT::_OVERLOADBRACKETSLEFTSIDE
> ** Object class HASH, 1 direct superclass, 17 known methods
>    Superclasses:
>       GDL_OBJECT  <Direct>
>  (etc, two pages)
> ```

Thank you for your reply. I will admit that I am dealing with a large-ish code library that I developed around 20 years ago for spectroscopic line fitting and I suspect that one or two of my poor coding practices are contributing to my problems. It seems that IDL may be a bit more forgiving of these practices. I am going to have to spend more than the few hours looking into this. If I get it resolved and it seems to be of general use, I'll post what I find out. Thanks again!

**Comment by GillesDuvert** [comment]
was due to a missing entry in the code -- solved and soon proposed in a PR.
