### ISSUE TITLE
regression in CONTOUR, /iso

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1543]
A regression appeared in CONTOUR between Feb 16 & 19 
```
CONTOUR, dist(50,25),/iso
```

To avoid regressions of such kind, I suggest : 
1/ we generalize what I did for the Coyote test suite 
(having references, generating outputs in PNG using TVRD(), generating a PDF through LaTeX, giving a look to the PDF) 
2/ working in branch(es) and testing in branch before merging to avoid to put regression(s) in the main code (it is difficult for me to recommend to colleagues to use the Git Version if the quality of the Git version is oscillating too much)

**Comment by GillesDuvert** [comment]
works for me, apparently.
More details?

**Comment by alaingdl** [comment]
old (as is 2023-02-15)
![old230215](https://user-images.githubusercontent.com/38264661/224304769-4ee69fbf-375e-4b10-842b-e1c5fd2e941c.png)

new (as is today 2023-03-10)
![new230310](https://user-images.githubusercontent.com/38264661/224304777-164e1487-b371-44fd-8e9f-b7354f9cfe1d.png)

I have the same result on three different machines , all compilations done with the script.

And sorry, maybe I did not checked enough the corrections for #1495 but we need to improve the way to check consequences of changes in graphical outputs --> production of list of figures + processing of PDF

**Comment by GillesDuvert** [comment]
Still, worksforme, I do not have this.
However, I cannot find the PR with the patch
https://github.com/gnudatalanguage/gdl/commit/539100cbef88e371a2c55076dec3e8667749255a
that solve it indicated in #1495
Wonder if this patch has really been merged

**Comment by alaingdl** [comment]
re-tested, same problem, it is broken for Y between 17 and 26 but ok below 16 (included) and above 27 (incl.)
```
CONTOUR, dist(50,y),/iso
```

The example KO in #1495 is now OK for me

**Comment by alaingdl** [comment]
Another example which was OK in January 2022 but is **not** OK now : 
```
GDL> window, xs=200, ysize=400
GDL> plot, findgen(10),/iso
```
(just for the record, no problem with the title, if any)

**Comment by alaingdl** [comment]
More informations :
* In fact the behavior on 2 different computers is different
* **!d** seems to not be upgrade if the window is resized (by mouse). It should.
* even simpler way to bad plot : 

```
GDL> window, xs=200, ysize=400
GDL> plot, findgen(10),/iso
GDL> plot, findgen(10)^2,/iso
```

**Comment by GillesDuvert** [comment]
indeed.

**Comment by GillesDuvert** [comment]
solved.
quick test:
`window,0, xs=400, ysize=200 & plot, findgen(10),/iso & window,1, xs=400, ysize=200 & plot, findgen(10)^2,/iso &window,2, xs=200, ysize=400 & plot, findgen(10),/iso & window,3, xs=200, ysize=400 & plot, findgen(10)^2,/iso`

**Comment by alaingdl** [comment]
Thanks Gilles, no more energy today to test, but tomorrow ...
