### ISSUE TITLE
GAUSSFIT don't work well whit nterms > 4

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1548]
GAUSSFIT in GDL don't  resist in the presence of polynomial (nterm > 4)

I have no idea today how to fix it, sorry.

**Comment by alaingdl** [comment]
Side effect : POLY_FIT should work with degree =0 (return the mean value ?)

**Comment by GillesDuvert** [comment]
Thnk you @alaingdl to attract attention to this important bug. Gaussian Fitting is a cornerstone of data analysis.

**Comment by alaingdl** [comment]
Important ! :smiling_face_with_tear:  I totally lost control on my pipeline processing JWST MIRI LRS data from some Wasp exo-planet (pid 2783, public data) !
