### ISSUE TITLE
Weekly release DMG does not contain all needed libraries (plplot first of all)

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#1561]
As reported in #1559 the weekly DMG does not contain libplplot.17.dylib, libplplotcxx.15.dylib so is unuseable.

**Comment by slayoo** [comment]
It would be great to include installation of the freshly produced .dmg in the Github Actions workflow, and fail CI in case gdl cannot be executed after installation.

**Comment by GillesDuvert** [comment]
closed by #1584. To be reopened if problems are found (I'm in no position to find them anyway)
