### ISSUE TITLE
wxWidgets compilation error

### ISSUE THREAD

**Issue by meerfrau** [gnudatalanguage/gdl#1569]
I'm using wxwidgets-gtk3 3.2.2.1:
```
./gdl/src/plplotdriver/deprecated_wxwidgets.cpp:128:1: Error: expected primary-expression before »;« token
  128 | ;
      | ^

```

**Comment by slayoo** [comment]
Seems neither `PLD_wxwidgets` nor `PLD_wxpng` are defined

**Comment by meerfrau** [comment]
Do I have to rebuild my wxwidgets with `PLD_wxwidgets` set?

**Comment by GillesDuvert** [comment]
@meerfrau Indeed, GDL uses the wxWidgets driver of plplot by default, so plplot must be compiled with -DENABLE_wxwidgets:BOOL=ON and -DPLD_wxwidgets:BOOL=ON which is curiously not the default on distributions where wxWidgets is otherwise present.
