### ISSUE TITLE
 idlffxmlsax ::startelement does not fill AttrName and AttrValue properly.

### ISSUE THREAD

**Issue by bonekamp** [gnudatalanguage/gdl#1570]
The problem is in  idlffxmlsax::startelement.  It does not seem to fill the AttrName and AttrValue  arrays with all the attributes available in the XML element. Attached a very basic test case run with GDL 1.01 to demonstrate it.

[idlffxmlsax_test.tar.gz](https://github.com/gnudatalanguage/gdl/files/11277040/idlffxmlsax_test.tar.gz)

Would be nice if IDLffxmlxsax can be updated so that  all the XML attributes can be obtained

HB

**Comment by GillesDuvert** [comment]
solved in #1581

**Comment by GillesDuvert** [comment]
BTW, thanks for the reports, it was a big bug in the code.
