### ISSUE TITLE
idlffxmlsax::startdocument  does not define xml_string in case of a overwriting (user made) startdocument function

### ISSUE THREAD

**Issue by bonekamp** [gnudatalanguage/gdl#1571]
idlffxmlsax::startdocument  does not define xml_string in case of a overwriting (user made) startdocument function

this can be demonstrated with the same test case as for the just issued idlffxmlsax::startelement  issue

but with the user made startdocument  uncommented. see  

[idlffxmlsax_test.tar.gz](https://github.com/gnudatalanguage/gdl/files/11277172/idlffxmlsax_test.tar.gz)

run output:

GDL - GNU Data Language, Version 1.0.1
- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): /usr/share/gnudatalanguage/lib
- Using WxWidgets as graphics library (windows and widgets).
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

% Compiled module: OBJCT__DEFINE.
objct::init
% IDLFFXMLSAX::PARSEFILE: Variable is undefined: XML_STRING
% Execution halted at: IDLFFXMLSAX::PARSEFILE    33 <INTERNAL_LIBRARY>
%                      OBJCT::PARSEFILE    28 /home/bonekamp/sif/info/gdl/idlffxmlsax_test/objct__define.pro
%                      $MAIN$          
GDL> ^Z

**Comment by GillesDuvert** [comment]
Thanks will have a look

**Comment by GillesDuvert** [comment]
solved in #1581
