### ISSUE TITLE
Magnificently obscure axis labelling issue.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1582]
I just noticed a really odd axis labelling problem.
````
x = [.1,.5,3,1.5]*1e-10
y = [.1,.5,1,3]*1e-10
plot, x, y, charsize=2
````
The label at 2e-10, omits the 2.
![Screenshot_20230427_104333](https://user-images.githubusercontent.com/658624/234825095-43a3398f-87b5-429d-a41f-eb00ade2b0a8.png)

The error only seems to occur with plot ranges that default to a major tick interval of 5e-11, and include 2e-10 in the range. So far as I can tell no other power of 10 is affected.

**Comment by GillesDuvert** [comment]
solved
