### ISSUE TITLE
[xyz]tckv has no effect

### ISSUE THREAD

**Issue by AstroArtie** [gnudatalanguage/gdl#1585]
[xyz]tickv should distribute the tick marks on an axis, but GDL always distribute them equidistantly across the axis, regardless of [xyz]tickv - the size of the [xyz]tickv array does not matter to GDL either:
`plot, findgen(3), xticks=2L,xtickname=['one','two','three']`
is identical (as it should be) to:
`plot, findgen(3), xticks=2L,xtickname=['one','two','three'],xtickv=[0,1,2],xr=[0,2]`
but gives the same result as this ludicrous example:
`plot, findgen(3), xticks=2L,xtickname=['one','two','three'],xtickv=[5,1.5,2,2],xr=[0,2]`
[xyz]tickv  is there to enable non-equidistant labeling.
Your help will be most appreciated!
Regner

**Comment by GillesDuvert** [comment]
tick positions on axes are made by plplot, that do not provide arbitrary postions for ticks (as well as a number of other deficiencies compared to IDL numerous plotting options).
TICKV is essentially ignored by GDL and may be introduced when plplot 'useful' code will be incorporated in GDL.

**Comment by GillesDuvert** [comment]
Actually there may be an ugly workaround

**Comment by AstroArtie** [comment]
Ooooh - I like the sound of that :-)
