### ISSUE TITLE
!P.TICKLEN < 0 does not make space for axis labels

### ISSUE THREAD

**Issue by AstroArtie** [gnudatalanguage/gdl#1587]
Dear GDL developers,
I like to use !P.TICKLEN = -0.02 so that the tick marks point out of the plot, and do not get confused with the plotted data (I really think it should be the default ;-)
But the axis labels are not moved by this change, so tickmarks and labels collide:
`!P.TICKLEN = 0.02& plot,[0,1],[0,5],xtitl='!8x!x values', ytitl='!8y!x values', chars=1`
vs.
`!P.TICKLEN =-0.02& plot,[0,1],[0,5],xtitl='!8x!x values', ytitl='!8y!x values', chars=1`
The problem goes away with large enough character size(!):
`!P.TICKLEN =-0.02& plot,[0,1],[0,5],xtitl='!8x!x values', ytitl='!8y!x values', chars=3`

Your help will be most appreciated!
Cheers,
Regner

**Comment by GillesDuvert** [comment]
Closed by #1603 hopefully
