### ISSUE TITLE
Bug in WRITE_TIF: /short missing in interface

### ISSUE THREAD

**Issue by mattrenderedai** [gnudatalanguage/gdl#1594]
I need to write 16 bit output from my pro scripts, ultimately these need to be .tif format. The write_tif.pro script appeats to support doing short, but the parameter is not exposed in the interface.

GDL> n_e = fltarr( 5, 2 )
GDL> write_tiff, 'test.tif', n_e
GDL> write_tiff, 'test.tif', n_e, /short
% WRITE_TIFF: Keyword parameter <SHORT> not allowed in call to: WRITE_TIFF
% Execution halted at: WRITE_TIFF          78 /usr/share/gnudatalanguage/lib/write_tiff.pro
%                      WRITE_TIFF          78 /usr/share/gnudatalanguage/lib/write_tiff.pro
%                      WRITE_TIFF          78 /usr/share/gnudatalanguage/lib/write_tiff.pro
%                      $MAIN$    

@GillesDuvert, can this be fixed with the open PR?

**Comment by GillesDuvert** [comment]
made a 1-liner patch in the pro/write_tiff.pro file on GH, please test.

**Comment by mattrenderedai** [comment]
I haven't been able to build gdl from source, I use the apt package on ubuntu 20.04 (which provides gdl v 0.9.9).

When attempting build (please let me know if there a better place to dig into this) ...

I use the `build_gdl.sh` script as described at https://github.com/gnudatalanguage/gdl/wiki/GDL-on-Linux#script 

The config step threw a warning that there is miniconda in the path and some libs might not be found. The build threw some warnings at about 31% but completed without error. However running the check script leads to 

```
1% tests passed, 198 tests failed out of 199

Total Test time (real) =   7.33 sec

The following tests FAILED:
          2 - test_angles.pro (Failed)
          3 - test_arg_present.pro (Failed)
          4 - test_array_equal.pro (Failed)
...
```

**Comment by GillesDuvert** [comment]
Sorry about the build problem, I suppose the miniconda issue may be the culprit (see wiki topic "known issues") but have no experience with that.
You can however download the last version of src/pro/write_tiff.pro on GH and put it in /usr/local/share/gnudatalanguage/lib/ (if GDL libraries are installed there?)

**Comment by mattrenderedai** [comment]
That't not going to work as I need it in a docker container.  The issue I am running into is to build from source, one must choose a keyboard layout. I cannot get past this when installing in "noninteractive" mode, either with the package, or with the build_gdl script.

I just found the weekly binary buiilds, but I don't see the gdl binary in the tar.gx file.

**Comment by GillesDuvert** [comment]
@mattrenderedai perhaps you could just compile the new version of write_tiff.pro once gdl is started (eventually put that comand in IDL_STARTUP). Or, get the build_gdl.sh to work...

**Comment by GillesDuvert** [comment]
closed as working for me with the patch above.
