### ISSUE TITLE
Missing link to PLPLOT drivers

### ISSUE THREAD

**Issue by mattrenderedai** [gnudatalanguage/gdl#1596]
I am building gdl in a docker container from the build_gdl script. The result is the repo downloaded into the root /gdl directory and as sudo I can run through prep, configure, and build. I add /gdl/build/src to my path and, in the container then I can run gdl and only 15 or 200 checks fail.

My issue is gdl is not finding the PLPLOT drivers.  I have tried to set an environment variable PLPLOT_DRV_DIR=/gdl/build/src/plplotdriver but still I get this

```
$ gdl -e "<script>"

*** PLPLOT ERROR, ABORTING OPERATION ***
plInitDispatchTable: Could not open drivers directory, aborting operation

(gdl:898): dbind-WARNING **: 22:28:02.530: Couldn't connect to accessibility bus: Failed to connect to socket /run/user/1000/at-spi/bus_1: No such file or directory

(gdl:898): Gtk-WARNING **: 22:28:02.814: Error loading theme icon 'text-x-generic' for stock: Icon 'text-x-generic' not present in theme Pop

(gdl:898): Gtk-WARNING **: 22:28:02.815: Error loading theme icon 'folder' for stock: Icon 'folder' not present in theme Pop

(gdl:898): Gtk-WARNING **: 22:28:02.815: Error loading theme icon 'folder' for stock: Icon 'folder' not present in theme Pop
  GDL - GNU Data Language, Version 1.0.2 Git
- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): /gdl/install/share/gnudatalanguage/lib
- Using WxWidgets as graphics library (windows and widgets).
- Local drivers not found --- using default ones. 
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl
```
Note there is no such folder at /gdl/install/share/gnudatalanguage/lib

**Comment by alaingdl** [comment]
Did you did a `make install` at the end ? (or `./scripts/build_gdl.sh install`)

**Comment by mattrenderedai** [comment]
Yes that fixed it. Running `./scripts/build_gdl.sh install` created the missing libs.  Now running `./scripts/build_gdl.sh install` passes all but 6/200 - probably due to no access to and X server.  

Closing this, my script runs, thank you!
