### ISSUE TITLE
Keyword parameter SHADES not supported in call to: SHADE_SURF

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1605]
The error message says all:

% Warning: Keyword parameter SHADES not supported in call to: SHADE_SURF. Ignored.

Any chance to implement this?

**Comment by jtappin** [comment]
My understanding is that PLPLOT is incapable of supporting it.
See closed issue [1507](https://github.com/gnudatalanguage/gdl/issues/1507)

**Comment by GillesDuvert** [comment]
closed by #1886 , although a better version of shading MUST be implemented, not the dumb plplot one.
