### ISSUE TITLE
The CURSOR routine crashes GDL

### ISSUE THREAD

**Issue by StefanU13** [gnudatalanguage/gdl#1607]
I would like to report a bug and make a help request:
I am using GDL version 1.0.1 on Ubuntu Linux and would like to measure x any y values from plots of stellar spectra using the cursor routine. For this, I type in the command line:
cursor,x,y
or
cursor,x,y & print,x,y
Unfortunately, since a recent update, this completely crashes GDL. Here is a screenshot of what happens:

![Screenshot from 2023-07-13 18-24-19](https://github.com/gnudatalanguage/gdl/assets/139489247/1d596834-22d8-4f2f-8246-d9fcfd627535)

I am using GDL on two different machines (an Ubuntu-only laptop and in a Virtual Machine on a Windows laptop), it is the same on both.

Question: Is this a known issue? Is there a simple way of dealing with it? If not, can somebody fix it?
Indeed, the cursor routine is highly versatile and I got stuck with my work since it does not work anymore.

Looking forward to your esteemed help!
Stefan

**Comment by GillesDuvert** [comment]
@StefanU13 thanks for the report. I (for example) do not have any problem with cursor, but my version is (perforce) more recent than yours (1.0.1 almost 2 years ago, but you would then be the first to report a problem with cursor for this version in 2 years). Would that be an issue specific to this version of Ubuntu ?  There seem to be lots of trouble with cursors and the new Wayland screen manager. Could you try with 'Ubuntu on Xorg' if this option is present at login?

**Comment by StefanU13** [comment]
@GillesDuvert thank you. Indeed there is a new version, but when I try updating with sudo apt upgrade gnudatalanguage, it says that it is already the newest version (1.0.1-3build1) and does nothing.
Let me try changing the display server.

**Comment by alaingdl** [comment]
For me, the best way is to compile the current git version in local directory, using the script it is really simple and fast. Please look in the Wiki

Yes, not sure an upgrade will be done in older Ubuntu version

**Comment by StefanU13** [comment]
@GillesDuvert, I tried the login via 'Ubunto on Xorg' and the cursor routine works again! Thank you so much!!!

**Comment by GillesDuvert** [comment]
Quoting google:
**"Ubuntu shipped with Wayland by default in Ubuntu 17.10 (Artful Aardvark). However, Ubuntu 18.04 LTS reverted to X.Org by default due to several issues."**

Indeed, there is no cursor 'per se' on Wayland. This register as an issue I believe.
Between Wayland and other compositers the 'old' code using cursors and byte logical functions (XOR etc) will progressively stop to work...
