### ISSUE TITLE
compilation error when program contains for-loop with begin and endfor in one line

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1608]
I thought this was solved already but I am not sure any more.

This simple program does not compile any more:

```
pro test
   for i=0,5 do begin print,i & endfor
end
```

It only compiles when there is a "&" after the "begin":

```
pro test
   for i=0,5 do begin & print,i & endfor
end
```

or when the commands are in different lines:

```
pro test
   for i=0,5 do begin 
      print,i
   endfor
end
```

**Comment by GillesDuvert** [comment]
@brandy125 I'm afraid its a consequence of #1588 as reported in #1599 . Will be solved, even if it means reverting to previous behaviour.

**Comment by brandy125** [comment]
Is see…thanks!
