### ISSUE TITLE
openmp & OSX 13.5

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1609]
Hi

The script to compile GDL on OSX 13.5 does work perfectly, on a machine with 12 cores, and on my old laptop with 4 cores and U2204.
But after that, performances issues : time to run _test_all_basic_functions_ is about 8 times slower on Mac than on my Linux. I suspect OpenMP is not activated on OSX (but the cope number is detected in !CPU). Any hope for improvement in the way to really trun on OpenMP with Clang on OSX ? 

```
Mac (12 cores) % Time elapsed ALL TESTS:       0.91960096 seconds.
Linux (4 cores) % Time elapsed ALL TESTS:       0.16531396 seconds.
```

**Comment by GillesDuvert** [comment]
Nothing really new, eh?
See https://github.com/gnudatalanguage/gdl/issues/1498#issuecomment-1411218901
by linking with the library provided by R folks, openmp is enabled.

**Comment by GillesDuvert** [comment]
As of today, the DMG (valid for Intel 64 bits Macs) prepared by a (weekly) release (so, compiled with optimization) seems to have all libraries inside and thus **can be installed on any mac** without need of Brew, compile etc, and actually runs well.
-> This has to be tested, I've only a MacOS Catalina 10.15.7 in a VM for devel and test, pity me.
-> But parallellism is included, as setting CPU,TPOOL_NTHREADS=1 and CPU,TPOOL_NTHREADS=4 display accelerated times in the latter case. Of course in a VM, probably not exciting times.
-> #1498 on the contary show that on M1, more work is needed.

As this eases terribly the maintainance, I plan to remove all explanations on how to install GDL on Mac in favor of just installing the DMG, so it is important to test it in real life.

**Comment by GillesDuvert** [comment]
please follow this discussion on #1675
