### ISSUE TITLE
spawn command needs huge amount of RAM for executing a simple program

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1611]
In my case the spawn command needs 25GB of RAM for executing this simple program:

```
bash$ cat ./doit 
gdl -e "a=1 & while 1 do b=a"
bash$ 
```

The execution under GDL needs 25GB of RAM:

```
bash$ gdl <<< "spawn,'./doit'"
```

```
bash$ grep Vm[PS][ei] /proc/14939/status
VmPeak: 26314948 kB
VmSize: 26314948 kB
VmPin:         0 kB
```

while executing under IDL needs almost nothing of RAM:

```
bash$ idl <<< "spawn,'./doit'"
```

```
bash$ grep Vm[PS][ei] /proc/15044/status
VmPeak:   527944 kB
VmSize:   527944 kB
VmPin:         0 kB
```

My GDL version:

```
GDL> !gdl
{
    "RELEASE": "1.0.2 Git",
    "BUILD_DATE": "May 15 2023",
    "EPOCH": 1684119600,
    "GDL_USE_DSFMT": 1,
    "GDL_USE_WX": 1,
    "GDL_POSIX": 1
}
```
I tested as well with the latest version of last week.

Who can help?

**Comment by GillesDuvert** [comment]
@brandy125 I'm sorry I cannot reproduce.
running your example I get a constant CPU and 15Mo memory, stable.
![image](https://github.com/gnudatalanguage/gdl/assets/33936193/16080205-21bd-46ce-b5e2-816e2212fa51)

**Comment by brandy125** [comment]
@GillesDuvert Thank you for testing it.
Are you sure that you are looking at the spawned gdl process and not at the spawning one?
The spawning gdl indeed does not need much memory but the spawned one does.
Could you please verify again and check the memory consumption of both?

Thanks

**Comment by GillesDuvert** [comment]
Hi, I checked, the caller is 0% cpu and the spawned is what I said, 13% cpu (on a 8 threads).

**Comment by brandy125** [comment]
Ok, which OS are you using? Which distribution?
Could you do a test on a different machine? 
I will do as well on other machines.

**Comment by GillesDuvert** [comment]
Old I7 (HP notebook G2 17") 32 gig ram, Mageia 8. Unfortunately no other machines around right now.

**Comment by brandy125** [comment]
For now no problem any more. After update no problem any more
