### ISSUE TITLE
bad yrange when plot with reverse yrange ...

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1612]
This is in fact a minor bug ! the calls to : 
```
plot, findgen(1000), xrange=[500,400]
plot, findgen(1000), xrange=[500,400],/yno
```

don't give the same outputs in IDL & GDL. It seems that the ymin & ymax
are not recalculated in GDL

Yes I checked that :
```
plot, findgen(1000), xrange=[400,500]
plot, findgen(1000), xrange=[400,500],/yno
```
do give same plots in IDL & GDL

**Comment by GillesDuvert** [comment]
indeed.
