### ISSUE TITLE
Apple M1 GDL definitely slow in creating/deleting GDL objects

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#1635]
Consider this, on a M1:
```
GDL> a=3 & b=4 & tic & for i=1,100000L do a=b & toc ; 1 operation
% Time elapsed :       0.83448601 seconds.
GDL> a=3 & b=4 & tic & for i=1,100000L do begin & b=i & a=b & end & toc ; 2 operations
% Time elapsed :        1.6230509 seconds.
GDL> a=3 & b=4 & tic & for i=1,100000L do begin & b=i & a=temporary(b) & end & toc ; 2 operations but done differently.
% Time elapsed :       0.83446503 seconds.
```
For the reference, the same command on an old intel64 machine gives:
```
GDL> a=3 & b=4 & tic & for i=1,100000L do a=b & toc
% Time elapsed :     0.0053741932 seconds.
GDL> a=3 & b=4 & tic & for i=1,100000L do begin & b=i & a=b & end & toc
% Time elapsed :      0.039531946 seconds.
GDL> a=3 & b=4 & tic & for i=1,100000L do begin & b=i & a=temporary(b) & end & toc
% Time elapsed :      0.037281990 seconds.

```
We see that the use of temporary() divides the time by 2 on the M1, giving back the same time as `a=b` that uses 2 times less GDL variable creation/destruction than the others. On intel architecture, the time is not spent like that.
incidentally, the loop time (void loop) is the same on both machines,` for i=1,100000L do begin & end & toc` gives `0.0046200752 seconds` (i386_64) and `0.0058410168 seconds` (arm64) . For what those time measurement are worth, of course.

So, there is **something very strange happening on creation/destruction of GDL variables** (essentially memory allocation?) on arm64 architecture. 

This is bad as GDL seems very fast on parallel work on arm64 (OpenMP, Eigen::) and would be a valuable ressource  for serious computing on those architectures.

HELP WANTED

**Comment by brandy125** [comment]
Very nice observation and in adition very important as it enters everywhere.On 9 Sep 2023, at 13:14, Giloo ***@***.***> wrote:﻿
Consider this, on a M1:
GDL> a=3 & b=4 & tic & for i=1,100000L do a=b & toc ; 1 operation
% Time elapsed :       0.83448601 seconds.
GDL> a=3 & b=4 & tic & for i=1,100000L do begin & b=i & a=b & end & toc ; 2 operations
% Time elapsed :        1.6230509 seconds.
GDL> a=3 & b=4 & tic & for i=1,100000L do begin & b=i & a=temporary(b) & end & toc ; 2 operations but done differently.
% Time elapsed :       0.83446503 seconds.

For the reference, the same command on an old intel64 machine gives:
GDL> a=3 & b=4 & tic & for i=1,100000L do a=b & toc
% Time elapsed :     0.0053741932 seconds.
GDL> a=3 & b=4 & tic & for i=1,100000L do begin & b=i & a=b & end & toc
% Time elapsed :      0.039531946 seconds.
GDL> a=3 & b=4 & tic & for i=1,100000L do begin & b=i & a=temporary(b) & end & toc
% Time elapsed :      0.037281990 seconds.


We see that the use of temporary() divides the time by 2 on the M1, giving back the same time as a=b that uses 2 times less GDL variable creation/destruction than the others. On intel architecture, the time is not spent like that.
incidentally, the loop time (void loop) is the same on both machines, for i=1,100000L do begin & end & toc gives 0.0046200752 seconds (i386_64) and 0.0058410168 seconds (arm64) . For what those time measurement are worth, of course.
So, there is something very strange happening on creation/destruction of GDL variables (essentially memory allocation?) on arm64 architecture.
This is bad as GDL seems very fast on parallel work on arm64 (OpenMP, Eigen::) and would be a valuable ressource  for serious computing on those architectures.
HELP WANTED

**Comment by dirteat** [comment]
I am may be stating some trivialities here but on different arches, tests should be first done by compiling with the least possible compiler optimizations. I would not be surprised it is optimizer-related, and thus, compiler related. Otherwise, it may help to find some real problems in the code.

NB: I still remember codes running on SGI-origin 3K (RISC arch, R16000 at 800Mhz) not running faster after porting them on the freshly new intel x86 processor at that time (P4 running 2.5 GHz). Young processors, young compilers, bad optimizations :)
