### ISSUE TITLE
cw_bgroup base-sizing issue (and fix)

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1637]
When deeply embedded in a complex widget structure, `cw_bgroup` can fail to size correctly and only show a faction of its contents. It turns out that this occurs when there is no `label_*` keyword set, in which case the container base that contains the label and the menu base and handles the user-facing event handling etc. has neither the `column` nor the `row` attribute.

The following patch ensures that if there is no label, then the outer base has the column attribute and results in correct sizing.

```
diff --git a/src/pro/cw_bgroup.pro b/src/pro/cw_bgroup.pro
index 1b28c12d..159823d2 100644
--- a/src/pro/cw_bgroup.pro
+++ b/src/pro/cw_bgroup.pro
@@ -171,7 +171,8 @@ function cw_bgroup, parent, labels, $
   else issens = 1
   
   b0 = widget_base(parent, $
-                   column = keyword_set(label_top), $
+                   column = keyword_set(label_top) || $
+                   ~keyword_set(label_left), $
                    row = keyword_set(label_left) && $
                    ~keyword_set(label_top), $
                    map = ismap, $
```

Before
![bgroup_bad](https://github.com/gnudatalanguage/gdl/assets/658624/ba6ac937-77c2-4056-a890-4e306d69b4c2)
After
![bgroup_good](https://github.com/gnudatalanguage/gdl/assets/658624/6cac4df3-8662-468d-bb67-4886cc208165)

**Comment by GillesDuvert** [comment]
Thanks @jtappin , changes made.
