### ISSUE TITLE
OSX Silicon M1 Installation Issue

### ISSUE THREAD

**Issue by astro-c** [gnudatalanguage/gdl#1658]
Hello,

I have been trying to install GDL onto my Macbook for a while and tried the DMG method as I'm not very good at installing things, but I get errors.

When I try to open the GNU Data Language app, I get the following error:
```
/var/folders/nk/7x03lqzs08v_4s9vtd9m7ppc0000gn/T/AppTranslocation/F48D8B3B-8339-4CF6-BAC7-4BF5759CCD94/d/GNU\` Data\ Language.app/Contents/Resources/bin/gdl ; exit;
zsh: killed     

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

Meanwhile, when I open the GDL Workbench app, I get "GDL Workbench is damaged and can’t be opened. You should move it to the Bin."

If there is something I'm doing incorrectly, I'm not too sure as I'm following the instructions on the website.

Specs: M1 Pro chip and Sonoma 14.0

**Comment by alaingdl** [comment]
It is not an answer to your question, but did you try to compile GDL on the same machine ?
The script "build_gdl.sh" is quite robust and I used to use it on some OSX I have access on.
(It takes time the first time but quite fast after first compilation & Brew)

**Comment by astro-c** [comment]
> It is not an answer to your question, but did you try to compile GDL on the same machine ? The script "build_gdl.sh" is quite robust and I used to use it on some OSX I have access on. (It takes time the first time but quite fast after first compilation & Brew)

I just tried to install GDL through the script you mentioned, however, I am met with the exact same error for the GNU Data Language app

**Comment by GillesDuvert** [comment]
@astro-c We have issues on M1 machines, and apparently the installer does not work ok on M1 too. 
And, the workbench is for intel machines only, I'm afraid.
However I've successfully compiled gdl on a m1 from scratch using the build_gdl.sh script. The thing is, the gdl thus built has to be installed correctly following the guidelines in the Wiki. Did you use build_gdl.sh up to the point you created a .dmg file and used this .dmg file to copy the gdl app in the Applications folder?

**Comment by GillesDuvert** [comment]
checked on an M1. Impossible to make a correct DMG within Apple's new (closed) framework. Apparently other problems.

**Comment by GillesDuvert** [comment]
please go for now on #1675
