### ISSUE TITLE
regrssion within revised TIC & TOc on OSX intel

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1661]
with current GIT version, on OSX 14.0 with intel proc I have : 
```
GDL> tic & TEST_TIC_TOC,/no & toc
Time elapsed in loop  0 :       0.13500881 seconds.
Time elapsed in loop  1 :       0.13453913 seconds.
Time elapsed in loop  2 :       0.13385391 seconds.
Time elapsed in loop  3 :       0.13280582 seconds.
Cumulative Time elapsed :       0.53620768 seconds.
Total Time elapsed      :       0.56858802 seconds.
% TEST_TIC_TOC: ====================================================
% TEST_TIC_TOC: =                                                  =
% TEST_TIC_TOC: =  1 errors encountered during TEST_TIC_TOC tests  =
% TEST_TIC_TOC: =                                                  =
% TEST_TIC_TOC: ====================================================
% Time elapsed : 1.6992762e+09 seconds.
```

2 problems. Last line  is wrong on OSX (OK on Linux). And the new version on OSX triggered a error.
Those 2 problems did not exist on the Mac with the previous version (before PR #1646 )

None of those problems arise on Linux (before and after change in TIC/TOC)

**Comment by GillesDuvert** [comment]
The test is not precise enough , now. On OSX the overhead of loops seems to be greater that 10-2 for the test. Which may be another issue. It is better to check that the variance of the val_times is better than 1e-3.
