### ISSUE TITLE
Badly needed:  SPRSAB, SPRSAX, SPRSIN and SPRSTP.

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#1693]
Badly needed in SSW: the 4 routines to use sparse matrixes, namely SPRSAB, SPRSAX, SPRSIN and SPRSTP. All copyright-protected because published by Knuth. I note that the gnu scientific library has equivalent routines, and Eigen:: also . Adding an interface for these routines would be easy for the knowledgeable people.

**Comment by alaingdl** [comment]
Thanks @GillesDuvert for the super fast add of those 4 functions.

They are tested in 'test_sparse_matrix.pro'

Please report any problem, and extension to the test cases are as always very welcome
