### ISSUE TITLE
Cannot compile 1.0.4 & git version on Debian due to Apple include in SAVE/RESTORE

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1696]
But compilation is ok on Ubuntu 22.04
(may be trick related to CMake ?)

(a lot more similar messages)

```
[...]
/home/alaingdl/GDL/gdl-1.0.4git231218CMake/src/saverestore.cpp:2309:8: error: ‘xdr_u_int32_t’ was not declared in this scope
   if (!xdr_u_int32_t(xdrs, &ptr_high)) break;
        ^~~~~~~~~~~~~
/home/alaingdl/GDL/gdl-1.0.4git231218CMake/src/saverestore.cpp:2309:8: note: suggested alternative: ‘xdr_uint32_t’
   if (!xdr_u_int32_t(xdrs, &ptr_high)) break;
        ^~~~~~~~~~~~~
        xdr_uint32_t
[...]

**Comment by alaingdl** [comment]
In fact it is clear, before the code was with *xdr_uint16_t* which is defined in 
/usr/include/rpc/xdr.h 

both  *xdr_uint16_t*  and *xdr_u_int16_t*  are defined in
/usr/include/tirpc/rpc/xdr.h

**Comment by GillesDuvert** [comment]
PR submitted.

**Comment by alaingdl** [comment]
Sorry to re-opened it, but I cannot compile on Debian 10 the new version after changes by @GillesDuvert 

I found a way to succeed with U2204, Debian 10 & OSX 12.3, now (unfortunately hidden) in PR #1702

We may have to consider to maintain an older GNU/Linux in CI, because I had no time last week to detect such problem :(
