### ISSUE TITLE
regression when SURFACE in multiplot (!p.multi)

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1701]
Position of Surface extends outside the sub-box ...

This regression was introduced in GDL between 2022-09-26 and 2022-10-18

```
GDL> !p.multi=[0,1,2]
GDL> plot, findgen(10) & surface, dist(10)
GDL> !p.multi=[0,2,1]
GDL> plot, findgen(10) & surface, dist(10)
```
(this regression was found running *test_gammas.pro*)

**Comment by GillesDuvert** [comment]
replicate of #1521

**Comment by alaingdl** [comment]
@GillesDuvert well seen ! (one time again we do have to prepare a way to make visual checks  to detect changes ... maybe SVG is also a way ? since they are txt files with XML tags)

When #1702 will be merged + stabilization of #1696 (my changes were unfortunately automatically included in #1702) I do consider we will be OK for a new release (1.0.5) !
And may be in January a 1.0.6 or 1.1 including any reports + this bug solved + SHMMAP #860 if Gilles succeed on that !

**Comment by alaingdl** [comment]
the quantities of changes (diff) between the two versions of _plotting_surface.cpp_ between 2022-09-26 and 2022-10-18 are that larges that I go back to hibernation !

**Comment by GillesDuvert** [comment]
Ah, yes, I'm afraid I've rewritten almost all of the graphic functions 2 or 3 times since 2012... :smile: 
FYI the 3D plot positioning is now 'just' a problem of 4x4 transform matrix which is applied _inside_ the (ours) plplot drivers.

**Comment by GillesDuvert** [comment]
#1798 should close this ticket.
