### ISSUE TITLE
Something amiss with widget event handling

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1710]
In the most recent GIT versions (last few days) there seems to a problem with the handling of events from compound widgets. I need to do some more rooting around to get the details, but a first impression is that the events returned by the internal event handler are not getting propagated back the the main handler.

I need to do some more investigation to try to characterize and isolate the problem, but I thought I'd just drop a heads up at this stage.

**Comment by jtappin** [comment]
I think my initial diagnosis is correct. 
The "top level" handler is never getting called when an event is generated in compound widget, it should get called with the event structure returned by the compound widget's internal handler. See the attached test codes for CW_BGROUP, other compound widgets show the same behaviour.

Demo routines
Main test code: [test_bg_events.pro](https://github.com/gnudatalanguage/gdl/files/13844820/test_bg_events.pro.txt)
CW_BGROUP modified to print event diagnostics: [cw_bgroup_test.pro](https://github.com/gnudatalanguage/gdl/files/13844821/cw_bgroup_test.pro.txt)

The regression occurs between commits 44a497bc and 33ea0c95.

**Comment by GillesDuvert** [comment]
Ah yes, there was this change after finding a problem with HESSI plot panels (https://github.com/gnudatalanguage/gdl/discussions/1659#discussioncomment-7871316), that were not called by the right hander.
To be continued...

**Comment by GillesDuvert** [comment]
@jtappin you have demonstrated a problem with the current WIDGET_EVENT function. It does not obey the logic described in the documentation. This needs to be rewritten...
In the meantime you can comment out "`return ev;`" at line 389 in `widget.cpp` .

**Comment by alaingdl** [comment]
@GillesDuvert if you could fix that I really think it will be time for a 1.0.5, before a 1.1 !

**Comment by GillesDuvert** [comment]
#1716 will do the job, letting SSW's 'PLOTMAN' draw widget work and still have compound widgets working.
However this is not satisfactory, according to the documentation the 'plotman' event handling should not work...
but it works... The code used by plotman is reproduced in test_widgets (1st draw panel).
