### ISSUE TITLE
The size of the title in a plot window can not be adjusted using the "charsize" keyword

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1717]
Seems that the size of the title in a plot window can not be adjusted with the "charsize" keyword

```
GDL> plot,findgen(10),title='I can not adjust the size of the title',charsize=5
```

**Comment by alaingdl** [comment]
ha ! see from here, seems to appear between 231020 and 231114. "just" 24 have been changed ...

**Comment by GillesDuvert** [comment]
...And other variations of [XY]charsize are wrong too.

**Comment by GillesDuvert** [comment]
thanks, corrected now!

**Comment by alaingdl** [comment]
Yes, solved. 
But the exact sizes of the plot/titles may help to fix few regressions we can see when running test_coyote
(gdl surface of the plotting region is smaller by 20% and the charsize is ~20% bigger )

**Comment by GillesDuvert** [comment]
No, that's not true on my machine. The sizes are OK within 1% even with test_coyote.
