### ISSUE TITLE
WIDGET_TEXT regression

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1720]
I just found that the WIDGET_TEXT issue #1064 problem of not inserting newlines into a multiline text widget has resurfaced.

I don't think it's related to the latest event handling changes as I can reproduce it back till the packages are not runnable owing to changes in the blas libraries on Manjaro/Arch last summer, but I'm pretty sure I've been able to use the `graffer` dataset editor more recently than that. This make me think that something has changed in wxwidgets (or possibly gtk3).

My current wxwidgets libraries are:
```
$ pacman -Qs wxwidgets
local/wxwidgets-common 3.2.4-3
    Common libraries and headers for wxwidgets
local/wxwidgets-gtk3 3.2.4-3
    GTK+3 implementation of wxWidgets API for GUI
$ pacman -Q gtk3 
gtk3 1:3.24.39-2
```
The wxwidget libs were built 12-Dec-2023, gtk3 on 26-Dec-2023.

Test routine:  [test_text.pro](https://github.com/gnudatalanguage/gdl/files/13873906/test_text.pro.txt)

**Comment by GillesDuvert** [comment]
Thanks @jtappin now corrected (strange effect, due to a change in library?)

**Comment by jtappin** [comment]
Thanks.

BTW, while chasing this one into a corner I realized that a couple of entry box widgets that I have written do not originate from IDL's CW_FIELD codebase[*] so I'm tidying  one of them up to be a CW_FIELD for GDL.

[*] Probably because that codebase is vile.
