### ISSUE TITLE
segfault when using cw_fslider

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1724]
I am getting segfaults with recent GDL versions when using this lines:

```
base     = Widget_base(/COLUMN)
addvalue = Cw_fslider(base,title=' ')
```

This version does not segfault:

```
GDL> !gdl
{
    "RELEASE": "1.0.2 Git",
    "BUILD_DATE": "Mar 18 2023",
    "EPOCH": 1679108400,
    "GDL_USE_DSFMT": 1,
    "GDL_USE_WX": 1,
    "GDL_POSIX": 1
}
```

**Comment by frankmri** [comment]
Hi,
I've come across the same issue. 
Maybe helpful for you guys, it seems related to WIDGET_SLIDER producing a segfault when instantiated with TITLE="..." and subsequently using WIDGET_CONTROL, myslider, SET_VALUE=...

Doesn't work:

GDL> base=widget_base()
GDL> sli=widget_slider(base, title="test")
GDL> widget_control, sli, set_value=0
Segmentation fault (core dumped)

Works:

GDL> base=widget_base()
GDL> sli=widget_slider(base)
GDL> widget_control, sli, set_value=0
GDL>

Thanks for making GDL!
Frank

**Comment by brandy125** [comment]
Thanks @GillesDuvert !
