### ISSUE TITLE
shmmap variable does not hold the value given to it 

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1726]
Can anybody explain this?

```
GDL> shmmap,'test',/double,1
GDL> tmp=shmvar('test')
GDL> tmp(0)=double(156275001)
GDL> print,tmp,f='(D20.5)'
     156275008.00000
```

**Comment by GillesDuvert** [comment]
@brandy125 indeed this is pretty strange, and I have the same issue.

**Comment by alaingdl** [comment]
@GillesDuvert as I mentionned in #1715 the types in SHMMAP are not OK. Eg : 

```
IDL> shmmap,'test',/ulong, 1
IDL> tmp=shmvar('test')
IDL> help, tmp
TMP             ULONG     = SharedMemory<TEST> Array[1]

[...]
GDL> shmmap,'test',/ulong, 1
GDL> tmp=shmvar('test')
GDL> help, tmp
TMP             FLOAT     = SharedMemory<test> Array[1]
```

If you try to put a too long number into a float, you don't know what may happen. Eg : 

```
GDL> x=156275001.  ; please note the "." : a float
GDL> help, x
X               FLOAT     =   1.56275e+08
GDL> print, x
  1.56275e+08

GDL> print, long(x)
   156275008
```

Then for me, it is not a surprise, we have to fix the definition of type in SHMMAP
(and we all have had this problem somewhere in a code : [the sky is falling](http://www.idlcoyote.com/math_tips/sky_is_falling.html))

**Comment by GillesDuvert** [comment]
@alaingdl you're right this is most probaby a duplicate of #1715.

**Comment by GillesDuvert** [comment]
should work with #1736
