### ISSUE TITLE
Windows installer does not ship UDUNITS XML files

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#1732]
CC: @pjb7687, @jdtreffert, @GillesDuvert, @acoulais   

reported here: https://github.com/gnudatalanguage/gdl/discussions/1723

the installer does not ship XML definition files which are needed to use UDUNITS routines.

errors happen at runtime, e.g. when trying to use `IMSL_CONSTANT`

things that are needed to be done:
- include these XML files with the installer
- add CI test logic that would be running GDL unit tests with the installer-installed GDL

**Comment by GillesDuvert** [comment]
somebody with Windows pls. provide the windows path for this or these files.
