### ISSUE TITLE
GDL segfaults when dividing by 0

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1746]
Just noticed that the latest version segfaults when dividing by 0:

```
GDL> 5/0
Floating point exception (core dumped)
```

Can anybody confirm?

**Comment by frankmri** [comment]
Yes I can confirm

`GDL> print, 5/0
Floating point exception (core dumped)
`
But,
`GDL> print, 5./0
          Inf
% Program caused arithmetic error: Floating divide by zero
`
works as expected...

Best
Frank

**Comment by brandy125** [comment]
ok, thanks!

**Comment by alaingdl** [comment]
I confirm. I am sorry for that. I think it is related to #1683  @GillesDuvert 
(before I have no crash)

That's also mean we don't test enough. sorry.

A question to @GillesDuvert : more details on speed improvement mentioned in the discussion  ? thanks !

**Comment by GillesDuvert** [comment]
This is not about speed improvements, it is about catching divide by zero and other exceptions and report them, as described in #1683. Sorry for the inconvenience, will patch ASAP.

**Comment by GillesDuvert** [comment]
actually, FPE (Floating Point Exceptions) are well handled (so my own tests passed)
GDL> a=3./0.
% Program caused arithmetic error: Floating divide by zero

The untested behaviour here is integer division, which is NOT catcheable and has an undefined behaviour.
It comes from a code line that has been lost in... changes related to speed improvements (argh... :blush: ) where it was painfully tested for each cases of integer division. To be patched soon.

**Comment by GillesDuvert** [comment]
I'm glad to announce that #1747 closes this (hopefully minor) incident.
A new test procedure has been installed to avoid futur problems.
Thanks!
