### ISSUE TITLE
WIDGET_TABLE no longer emits "CELL_SELECT" events upon mouse click since rework

### ISSUE THREAD

**Issue by frankmri** [gnudatalanguage/gdl#1748]
Hi,
this is probably a super rare case, but believe it or not I was actually using the 'CELL_SELECT' mouse events generated by WIDGET_TABLE to locate user-selected cells. Since the last rework they got swallowed (are no longer generated). I think it is the wxGridGDL::OnTableCellSelection function in the event handler (line 1784).
If you want I can send a pull request, but you will probably have a better one (since this is recent).

Let me know

Best
Frank

**Comment by GillesDuvert** [comment]
@frankmri this (CELL_SELECT events) works on my machine (linux). 
tested with `testsuite/interactive_tests/test_widgets.pro` called with 
`test_widgets,/col,present="TABLE"` 
What is your OS?

**Comment by GillesDuvert** [comment]
Ok, nevermind, this should work #1750

**Comment by frankmri** [comment]
@GillesDuvert thanks and sorry for the late answer, I am on linux, too. My description was, unfortunately, not precise enough. The events are (and probably were) sent correctly, but the structure didn't contain the right values for event.sel_top and event.sel_left. Also now (after #1750, these "coordinate" values are always "-1" when I click on the different table cells. 

To get that behavior back I had changed the following:

And the same in the next function.


[WIDGET_TABLE_SELECT_EVENTS.txt](https://github.com/gnudatalanguage/gdl/files/14309100/WIDGET_TABLE_SELECT_EVENTS.txt)

**Comment by frankmri** [comment]
Sorry again @GillesDuvert , this diff is not the right one, I'm unable to find the changes I made in my local stash.
They were basically restoring the select event being pushed in the 

void  wxGridGDL::OnTableCellSelection(wxGridEvent & event) function of gdlwidgeteventhandler.cpp

the corresponding lines were commented before your latest changes.

Thanks again
Frank

**Comment by GillesDuvert** [comment]
@frankmri I'm confused. With the #1750 patch, there are 2 events produced by a (left)click in a cell:
- a WIDGET_TABLE_CELL_SEL reporting all -1 values
- next, a WIDGET_TABLE_CELL_SEL reporting the position (CELL_TOP, etc) of the newly selected cell.

This IMHO corresponds to the IDL behaviour for "normal" mode, the doc says "This means that two WIDGET_TABLE_CELL_SEL events are generated when an existing selection is changed to a new selection. "
**But, I see that in DISJOINT_SELECTION mode, where clicking when CTRL is held down, is not properly handled.**

**Comment by GillesDuvert** [comment]
should be OK now.

**Comment by frankmri** [comment]
Probably yes, thanks ! I'll reconfirm after the pull request is merged in ( ! I realize that this is probably why I still saw no change in behavior even previously!)

Sorry for the noise then
Frank

**Comment by frankmri** [comment]
I confirm it works now! 
Many thanks

**Comment by GillesDuvert** [comment]
#1761 provides correct handling of all (numerous) table-related commands, creation, modification, editing, events but for a few exceptions, and is correct for tables showing structures. PLS open new issues (with small examples) on this topic if neede.
