### ISSUE TITLE
disallow non-squash merge modes on GitHub?

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#1754]
GitHub has the "Generate release notes" button on the release creation page which fills the text panel with a list of commits since last  release. This is great, and would help fill with contents the "Release notes" for users, packagers and developers alike. However, in practice it requires the project to shift to "Squash" mode when merging PRs (otherwise, the release notes are cluttered with numerous minor commits done while polishing PRs and also with the merge commits). Squash merging results in each PR - even if it contains 100 commits - being merged as one single commit bearing the name of the PR. I'd say it would likely be worth embracing for GDL. 

Currently it is an option while merging. Probably the most robust way to embrace it project wise would be to disallow any other merge modes at: https://github.com/gnudatalanguage/gdl/settings#merge-button-settings (currently we allow: merge commits; squash merges; rebase merges).

@GillesDuvert, @pjb7687, @alaingdl, any thoughts?

**Comment by pjb7687** [comment]
Hi, for me it sounds good to me. Should we do this?

**Comment by GillesDuvert** [comment]
As I often save many intermediate version to GH, this "squash merge" mode seems indeed preferable.

**Comment by slayoo** [comment]
OK, just made this change in the repo settings:
![image](https://github.com/gnudatalanguage/gdl/assets/89685/d7153e36-363c-4fa3-bad9-4a41e7c9cb29)
In case, this needs to be reverted, these settings are at: https://github.com/gnudatalanguage/gdl/settings#merge-button-settings
