### ISSUE TITLE
xpos and ypos have no effect on windows procedure

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1759]
I experience that on my installation the xpos and ypos keywords have no effect on the windows procedure.

```
GDL> !gdl
{
    "RELEASE": "1.0.4 git",
    "BUILD_DATE": "Feb 12 2024",
    "EPOCH": 1707706800,
    "GDL_USE_DSFMT": 1,
    "GDL_USE_WX": 1,
    "GDL_POSIX": 1
}
GDL> 
```

System: Opensuse Tumbleweed with fvwm2 window manager

**Comment by GillesDuvert** [comment]
works ok for me. Apparently fvwm2 is not very much wxWidgets/GTK compatible (ggogled a bit). I bet the X window (gdl -X)   works OK.

**Comment by GillesDuvert** [comment]
... but of course gdl -X does have its own defects (e.g. no window larger than the screen)

**Comment by brandy125** [comment]
Exactly…and the fonts are…ugly.Thanks for testing!I need to figure out how to get it working in fvwm2.On 28 Feb 2024, at 15:42, Giloo ***@***.***> wrote:﻿
... but of course gdl -X does have its own defects (e.g. no window larger than the screen)

**Comment by alaingdl** [comment]
On my laptop running U22.04 I am on xfce4 and I have no problem in X11 or WsWidgets drivers to have the 
`window, xpos=..., ypos=...` exactly where they should be located !

**Comment by GillesDuvert** [comment]
shall we close this issue, and mention that fvwm2 (and probably fvwm, and probably all "old, but fast and reliable" WMs) may not be exactly, uh..., recommended?

**Comment by brandy125** [comment]
Sure!
Thanks!

**Comment by brandy125** [comment]
Just for completeness.

I commented following lines in my .fvwm2rc and now the xpos and ypos keywords work fine and everything else is as it was before.
I am happy!

```
Style * WindowShadeSteps 64p, SloppyFocus, CenterPlacement
Style * NoPPosition
StubbornIconPlacement
Style "*" RandomPlacement
Style "*" SmartPlacement
```

Long live FVWM2!
