### ISSUE TITLE
Regression: WIDGET_TABLE segfaults when no value set at instatiation and then setting value 

### ISSUE THREAD

**Issue by frankmri** [gnudatalanguage/gdl#1771]
Hi, unfortunately there is a regression since @GillesDuvert s latest and full implementation:

GDL> base=widget_base()
GDL> table=widget_table(base)
GDL> widget_control, table, set_value=[["A", "B", "C"],["D", "E", "F"]]
Segmentation fault (core dumped)

On the other hand this:

GDL> table=widget_table(base, value=[["A", "B", "C"],["D", "E", "F"]])
GDL> widget_control, base, /realize
GDL> widget_control, table, set_value=strarr(2,2)
GDL> widget_control, table, set_value=[["A", "B", "C"],["D", "E", "F"]]
GDL> widget_control, table, set_value=strarr(2,2)

works without crashing

Thanks!
Frank

**Comment by GillesDuvert** [comment]
oops case wxWidgets wxGrid not initialized (no value=xx in widget_table()) of course hangs.

**Comment by GillesDuvert** [comment]
corrected in #1772 !
Thanks for the quick bug report!

**Comment by frankmri** [comment]
Thanks for the quick fix, works here now!
