### ISSUE TITLE
GDL without Eigen3 is (again) no more compilable (on Debian 22.04)

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1787]
OK, in #1741 I made few changes to be able to compile GDL without Eigen3
(eg : `cmake .. -DX11=off -DWXWIDGETS=OFF -DMAGICK=OFF -DTIFF=OFF -DNETCDF=OFF -DHDF=OFF -DHDF5=OFF -DFFTW=OFF -DLIBPROJ=OFF -DUDUNITS2=OFF -DEIGEN3=OFF -DGRIB=OFF -DGLPK=OFF -DQHULL=OFF -DPYTHON=off -DSHAPELIB=off -DEXPAT=off`)

It was OK but no more today on Ubuntu 22.04 (but -DEIGEN3=ON is OK)

A detail : 
not OK on Ubuntu 22.04 with gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
but OK on Debian 10 with gcc version 8.3.0 (Debian 8.3.0-6) 
and also Clang on OSX ...

I suspect that #1776 by @GillesDuvert changed something related to that (this is what I see in the `diff -r -q`

I know the great goal of those changes is to be able to compile GDL with true GNU GCC on OSX but my last tests failed too :(

Soon we will face the c++14 versus c++11 ...

**Comment by GillesDuvert** [comment]
works4me with your example.
Would need to see the log to understand better.

**Comment by alaingdl** [comment]
It has been solved in #1816  just an include was missing

I suspect in a indefinite future we will have to refactoring all the include ...
(and compiling with some flags cxx14 ... would help. clang on OSX complains a lot)
