### ISSUE TITLE
"wdelete" deletes window but does not "free the handle" when window was created with "/free" keyword

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1809]
Creating 69 windows with "/free" keyword works as expected. 
Creating one more window fails because the maximum number is reached: ok
Delteing all windows: ok
Creating one more window fails even if there is no window open and the "device,window_state=win" confirms this: not ok

```
GDL> for i=0,68 do window,/free
GDL> window,/free
% WINDOW: No more window handles left.
% Execution halted at: $MAIN$          
GDL> for i=0,68 do wdelete
GDL> window,/free
% WINDOW: No more window handles left.
% Execution halted at: $MAIN$          
GDL> device,window_state=win
GDL> print,max(win)
   0
```

**Comment by GillesDuvert** [comment]
Hm already seen #1342. Would this be a régression ?
