### ISSUE TITLE
our LABEL_DATE is broken

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1813]
OK, I made the correction for format='(c())' (mentioned in #1799 and solved in #1810) and tests are OK in test_formats.pro and (new) test_format.pro

but the side effect is that our LABEL_DATE is broken, as shown by `test_label_date.pro`

(I don't plan to spend now time on that, busy by other problems in GDL !)

(again and again, having tests is the way to deter tricky bugs !)

**Comment by GillesDuvert** [comment]
corrected now.

**Comment by GillesDuvert** [comment]
... in commit 5bb971d
