### ISSUE TITLE
Cannot open window, PLPLOT ERROR

### ISSUE THREAD

**Issue by nick-san** [gnudatalanguage/gdl#1817]
Sorry for horrible English and newbie issue, I need someone's help :(

I have to use this software in university class, but it seems to be won't works well.
I've installed gdl-language which is provided by [openSUSE official science repository.
](http://download.opensuse.org/repositories/science/)
And I've tried clone this repository and build it, but it also says same error.(maybe something wrong with what I did)

My environment is: 
- Thinkpad X13 gen1 (AMD, Ryzen) 32GB RAM
- openSUSE Tumbleweed with all latest packages

Here is error log:
```
rlysleepynick@x13suse ~> gdl --version
GDL - GNU Data Language, Version 1.0.4
rlysleepynick@x13suse ~> gdl
  GDL - GNU Data Language, Version 1.0.4
- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): /usr/bin/../share/gnudatalanguage/lib
- Using WxWidgets as graphics library (windows and widgets).
- Using local drivers in /usr/lib64/gnudatalanguage
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

GDL> window

*** PLPLOT WARNING ***
Unable to open cmap0 file cmap0_default.pal


*** PLPLOT WARNING ***
Unable to open cmap0 file cmap0_default.pal


*** PLPLOT WARNING ***
Unable to open cmap1 .pal file cmap1_default.pal


*** PLPLOT ERROR, IMMEDIATE EXIT ***
Unable to either (1) open/find or (2) allocate memory for the font file
Program aborted
```

Someone teach me what I should to solve this...
Thank you. # #

**Comment by nick-san** [comment]
Self resolved.
These errors caused by didn't setting path to plplot colormaps, so I tested this:
```
cd /usr/share/plplot5.15.0
gdl
window # It works
```

**Comment by GillesDuvert** [comment]
@nick-san it looks like the plplot library we use in gdl is not well packaged in openSuze. The library should find its (unused by gdl!) palette (.pal) files all by itself. Perhaps adding "/usr/share/plplot5.15.0" in your PATH may avoid the need to 'cd' to this particular directory. It is the 1st time we hear about such an inconvenience.
Another possibility is that another software (like the anaconda python installer) has messed with the environment variables, path etc.

**Comment by brandy125** [comment]
I faced the same problem today on my new installation and adding the path /usr/share/plplot5.15.0 to any environment variable does not resolve it for me.

**Comment by brandy125** [comment]
...but what resolved for me was to remove the plplot package with sudo zypper rm plplot and then download and install plplot by hand. 
After this gdl works normal
