### ISSUE TITLE
gshhs mess

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#183]
- [ ] GDL includes in the src folder a modified convenience copy of the gshhg.h file from the GMT package, which is also outdated (also in comparison with the Debian-packaged one from libgmt-dev_5.4.3),
- [ ] Would be great to help the packagers to depend on the header file in a GMT-related package (here is a relevant exchange with GSHHS author: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753614),
- [ ] The MAP_INSTALL file clearly need an update as well.

**Comment by GillesDuvert** [comment]
For sure.
But GDL does not need all gshhs files. It even needs shorefiles at the 2 same resolution levels as IDL, which are both not-so-raw and not-so-precise as gshhs files. (IDL shorefiles are visually better)
Code should be smarter also as it is way slower than IDL's.

**Comment by GillesDuvert** [comment]
removed gshhs
