### ISSUE TITLE
plot of array with only NaN hangs session

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#1839]
This simple one-liner hangs my session. Can anybody confirm?

```
GDL>plot,fltarr(10)*'NAN'
```

**Comment by jaymurthy** [comment]
Yes. GDL - GNU Data Language, Version v1.0.6-1-gf84626e7 OSX

**Comment by alaingdl** [comment]
Thanks ! :disappointed: 

I confirm this regression which appeared between 2024-03-22 and 2024-04-03. 6 files have been changed in this period, including 4 files related to plotting ... (the changes are quite large in these 4 files : i think the expert is @GillesDuvert )
(plotting_axis.cpp, plotting_contour.cpp, plotting.cpp, plotting.hpp)

```
plot,replicate(!values.f_nan,3)
```

**Comment by GillesDuvert** [comment]
Thanks, behaviour now is consistent with IDL:
```
IDL>  plot,replicate(!values.f_nan,3)
% PLOT: Not enough valid and unique points specified.

```
and
```
IDL> contour, replicate(!values.f_nan,10,10)
% CONTOUR: Warning: Infinite plot range.

```
