### ISSUE TITLE
No Legend procedure 

### ISSUE THREAD

**Issue by ChunkyPanda03** [gnudatalanguage/gdl#1856]
there is no legend procedure... I can add this.... maybe

**Comment by GillesDuvert** [comment]
@ChunkyPanda03 there are numerous 'legend.pro' around, no need to write one.
All AFAIK start from a legend.pro written  "24-25 Aug 92, F K Knight (knight@ll.mit.edu)", various modified versions lie around, IDLAstro has al_legend.pro, SSW has ssw/gen/idl/display/legend2.pro that seems very complete.
coyote has cglegend, but it is not standalone.
Given the copyrights, we could just add one of these in GDL and create a 'legend.pro" stub pointing to it.

**Comment by ChunkyPanda03** [comment]
ah ok I see now It just isn't included with GDL
