### ISSUE TITLE
Plotting infinity cause gdl to hang

### ISSUE THREAD

**Issue by jaymurthy** [gnudatalanguage/gdl#1859]
t=1./intarr(1000)
plot,t

I have to kill gdl using Ctrl-Z

 GDL - GNU Data Language, Version v1.0.6-1-gf84626e7
OSX Sonoma 14.5

**Comment by alaingdl** [comment]
Hi. this is a duplicate of #1839 and I am happy to say it is already solved by @GillesDuvert 
Nevertheless I tested just now in recent Version v1.0.6-10-g8a156724
and it is fine : `% PLOT: Not enough valid and unique points specified.`

**Comment by alaingdl** [comment]
(I forgot to close, sorry)
