### ISSUE TITLE
cmake/testusuite: possibility to pass VERBOSE=1 to make check

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#186]
As reported by @opoplawski and registered at SF.net (https://sourceforge.net/p/gnudatalanguage/bugs/394/):

When running "make check" using cmake (CTest) the VERBOSE=1 option is not passed to "make test".

**Comment by slayoo** [comment]
@opoplawski How to reproduce it?

**Comment by opoplawski** [comment]
I think this can be closed at this point
