### ISSUE TITLE
GDL 1.04 on Ubuntu 24.04: HDF5 functions not available

### ISSUE THREAD

**Issue by liamgumley** [gnudatalanguage/gdl#1871]
I'm running GDL 1.04 on Ubuntu 24.04, installed from the package available at
https://packages.ubuntu.com/search?keywords=gnudatalanguage

The HDF5 library is not available as shown below:

  GDL - GNU Data Language, Version 1.0.4
- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): /usr/bin/../share/gnudatalanguage/lib
- Using local drivers in /usr/lib/x86_64-linux-gnu/gnudatalanguage
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

GDL> $ls data
GATMO_j01_d20240807_t0929096_e0936053_b34817_c20240807093848329385_cspp_dev.h5	SATMS_j01_d20240807_t0929096_e0936053_b34817_c20240807093848313260_cspp_dev.h5
NPR-MIRS-SND_v11r8_n19_s202408071410410_e202408071418304_c202408071432510.nc
GDL> file = 'data/GATMO_j01_d20240807_t0929096_e0936053_b34817_c20240807093848329385_cspp_dev.h5'
GDL> file_id = h5f_open(file)
% Ambiguous: Variable is undefined: H5F_OPEN or: Function not found: H5F_OPEN
% Execution halted at: $MAIN$          
GDL> exit

Do I need to install HDF5 separately with apt-get? What am I missing here?

**Comment by slayoo** [comment]
Thank you for reporting, @liamgumley! 

It seems that despite depending on libhdf5-dev (https://salsa.debian.org/debian-astro-team/gnudatalanguage/-/blob/master/debian/control?ref_type=heads#L18), Debian package does not build HDF5 support in GDL (https://salsa.debian.org/debian-astro-team/gnudatalanguage/-/blob/master/debian/rules?ref_type=heads#L27)

@olebole, is it something related to this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915207

> * Temporarily disable HDF-5 support. Closes: #[915207](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915207)

**Comment by alaingdl** [comment]
The bad new : yes, it seems that this package is compile without HDF5. (I have the same situation with the older package on U2404 but never use this one). You can check calling GDL_STATUS in GDL

The good new : you can compile by yourself GDL in few minutes using the script in `scripts/build_gdl.sh` within HD5 support. But you need to add packages during the fist step (being sudo)

Any feedback on HDF5 is welcome !

**Comment by liamgumley** [comment]
Thanks for the update.

I switched to installing the Fedora package in a Podman container. HDF5 is supported.

From: Alain ***@***.***>
Date: Wednesday, August 7, 2024 at 12:21 PM
To: gnudatalanguage/gdl ***@***.***>
Cc: Liam Gumley ***@***.***>, Mention ***@***.***>
Subject: Re: [gnudatalanguage/gdl] GDL 1.04 on Ubuntu 24.04: HDF5 functions not available (Issue #1871)

The bad new : yes, it seems that this package is compile without HDF5. (I have the same situation with the older package on U2404 but never use this one). You can check calling GDL_STATUS in GDL

The good new : you can compile by yourself GDL in few minutes using the script in scripts/build_gdl.sh within HD5 support. But you need to add packages during the fist step (being sudo)

Any feedback on HDF5 is welcome !

**Comment by olebole** [comment]
HDF5 support in Debian got disabled in 2018 as a consequence of [debian#915207](https://bugs.debian.org/915207). However, after this I forgot to re-enable it later, sorry.
I'll investigate this and upload a new version.

**Comment by slayoo** [comment]
Thanks @olebole !

**Comment by olebole** [comment]
I now uploaded version 1.0.6 with HDF5 support to Debian unstable.

**Comment by liamgumley** [comment]
Thanks.

From: Ole Streicher ***@***.***>
Date: Thursday, August 8, 2024 at 10:03 AM
To: gnudatalanguage/gdl ***@***.***>
Cc: Liam Gumley ***@***.***>, Mention ***@***.***>
Subject: Re: [gnudatalanguage/gdl] GDL 1.04 on Ubuntu 24.04: HDF5 functions not available (Issue #1871)

I now uploaded version 1.0.6 with HDF5 support to Debian unstable.
