### ISSUE TITLE
OSX problem with hdf5

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#1883]
See the logs for, e.g. : https://github.com/gnudatalanguage/gdl/pull/1879/checks (MacOS)
test_hdf5 fails.
`TEST_HDF5_ATTR:   1 errors encountered during TEST_HDF5_ATTR tests  `
woud it be related to a spawn command that is not supported on OSX ?

**Comment by GillesDuvert** [comment]
@ogressel if you find the time...

**Comment by ogressel** [comment]
The `spawn` functionality is used more than once in the HDF5 testsuite, so that's unlikely.

**Comment by GillesDuvert** [comment]
Actually, since a recent  fix on 'spawn', the error disappeared. Happy to remove this one. But this i not the end of HDF5 issues :frowning_face:
