### ISSUE TITLE
logarithmic plot does not format tick values with decimal point

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1887]
(tested with the current Git version)

```
a=ABS(randomn(101, 1000))
plot_io, a, yr=[0.1, 10],/yst     ; (same as plot,/ylog, a, yr=[0.1, 10],/yst)
```

In IDL, the legend for yrange go from 0.1 to 10.0, What is displayed : 0.1, 1.0, 10.0 

In GDL, it seems that digits are missing : 0, 1, 10 are displayed

![idl_Capture d’écran du 2024-10-15 13-04-38](https://github.com/user-attachments/assets/6f817216-ad66-4bad-8f2a-d85d719c47b9)
![GDL_Capture d’écran du 2024-10-15 13-05-00](https://github.com/user-attachments/assets/314222ca-5f61-43d0-92dc-ced4f27043c2)

**Comment by GillesDuvert** [comment]
a bug indeed!

**Comment by GillesDuvert** [comment]
`a=ABS(randomn(101, 1000)) & plot_io, a, yr=[0.1, 10]` plots correctly. This is weird.

**Comment by alaingdl** [comment]
In fact, I did not realize that without /ystyle it was OK, because we are trying to make a large set of figures with a given fixed range. :smile:

**Comment by GillesDuvert** [comment]
this is a classic: IDL uses floats, we use doubles.  This should do the trick. Needs to be well tested, though, as it may have consequences elsewhere...
