### ISSUE TITLE
READ_ASCII Data Structure -- recent GDL behaviour change?

### ISSUE THREAD

**Issue by Barney-9000** [gnudatalanguage/gdl#1889]
Until recently, GDL behaved the same as IDL -- example following a READ_ASCII:

```
IDL> help, d1                                                                                                                    
** Structure <53e136e8>, 1 tags, length=40, data length=40, refs=1:
   FIELD01         FLOAT     Array[10]
```

But recently with GDL (Version v1.0.6-26-gfa8a808a-dirty) the 0 in the variable name is omitted:

```
GDL> help, d1, /Structure
** Structure <Anonymous>, 1 tags,memsize =40, data length=40/40:
   FIELD1          FLOAT     Array[10]
```

Of course, easy to fix, if a tad bothersome when regularly switching between IDL & GDL.  Has this been spotted?
Cheers

**Comment by GillesDuvert** [comment]
@Barney-9000 strange, how far in time would be the last 'good' version? any idea?

**Comment by Barney-9000** [comment]
@GillesDuvert Apologies, can't recall exactly. It was certainly working OK for a build created 09/03/24 (March, that is) found on a backup disc. Possibly later.

**Comment by GillesDuvert** [comment]
@Barney-9000 it is possible that you used 'another' read_ascii.pro file (the IDL one?) as the 'feature' was present in the read_ascii.pro file since its creation (line 147 in read_ascii.pro).
Now patched directly in main trunk.
I understand the problem is present only when no "template" is used (type `?ascii_template` in GDL) (this IDL procedure is working but is not part of GDL)

**Comment by Barney-9000** [comment]
Wow -- that fixed it!  (Just downloaded and recompiled.)  It also fixed the verbose 'warning' messages that all previous GDL READ_ASCIIs used to give.  The procedure is often used on a 10K line (very ugly) ASCII file -- the warning messages slowed things down a little.  My GDL_PATH was set with the gdl/src/pro & utilities directories at the beginning of the path, so no changes there.

Many thanks! 

PS. No "template" was ever used.
