### ISSUE TITLE
Another labelling anomaly.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1905]
I've just found another plotting anomaly. When the plot range is `0` to `1.5 × 10^n`, the minor ticks are placed at `0.4, 0.8, 1.2, 1.6`, when it would be more sensible to put them at `0.5, 1.0, 1.5`. 

e.g
```
plot, findgen(14), charsize=2
```
Which gives the attached plot.
![Screenshot_20241105_165015](https://github.com/user-attachments/assets/6817cf66-977c-4200-8fe6-528064f842eb)

**Comment by GillesDuvert** [comment]
indeed. The 'autotick' algorithm has never been very clever...

**Comment by GillesDuvert** [comment]
closed with #1930
