### ISSUE TITLE
IDLffXMLSAX

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#191]
As requested by @kriztioan at SF.net (https://sourceforge.net/p/gnudatalanguage/feature-requests/135/):

With the implementation of LIST and HASH, the basic framework to add internal-lib-object-classes has become available, for example IDLffXMLSAX.

IDLffXMLSAX offers (almost?) an one-on-one mapping of libxml2's (already required for PLPlot+SVG) SAX API. Hence, implementation might(?) be relative straightforward.

From my understanding of the GDL-code-base, what is required is the following (IDLffXMLSAX as a useful example):

objects.cpp: Add IDLffXMLSAX description to InitStructs()
overload.cpp: Add methods to SetupOverloadSubroutines()
xmlsax.cpp/hpp (new): Implementation of the actual code - the interesting thing here is that the methods are to be overloaded by a GDL-subclass, so (most of them) initially do nothing.

I am particularly interested in getting IDLffXMLSAX working, as it will allow important compatibility of the AmesPAHdbIDLSuite with GDL - see www.astrochem.org/pahdb/

I am interested on hearing you thoughts.

**Comment by GillesDuvert** [comment]
https://github.com/GillesDuvert/gdl/tree/test_ideas_idlffxmlsax is a branch soon to be commited that implements IDLffXMLSAX.
