### ISSUE TITLE
Missing NetCDF4 data types

### ISSUE THREAD

**Issue by rsiddans** [gnudatalanguage/gdl#1922]
GDL does not allow read/write o several basic datatypes allowed by netcdf4. E.g. NC_STRING, and unsigned integer types in general (NC_UINT, NC_ULONG, NC_ULONG64). 

Furthermore, GDL reports EC_RANGE error if signed bytes are attempted to be read (whereas IDL will read these into its byte type, leaving the user to interpret the values).

These issues prevent use of GDL for several applications we have which depend on netcdf4 i/o.

I have been able modify my local copy of ncdf_att_cl.cpp and ncdf_var_cl.cpp to allow these to be read/written (although only scalar values/atts in the case of NC_STRING).

This is the first time I have attempted to modify code in an open source project like GDL, so am not sure what would be the best way for me to help get these changes into the repository going forward. Would be happy to share my modified code, but have very limited time for the kind of testing I imagine might be required before it would be appropriate to include the modifications in the repo.

**Comment by GillesDuvert** [comment]
Submitting a PR ( or telling where to find the modified code ) will certainly speed up things --- as nobody else around is apparently "maintaining" the NetCDF-related code. I would suppose the ultimate "testing" would be to get GDL run the, I quote,   " several applications we have which depend on netcdf4 i/o."

**Comment by rsiddans** [comment]
Pull request #1926 has my modified code (also covers issue #1923)

**Comment by GillesDuvert** [comment]
merged and closing
