### ISSUE TITLE
Bug for _F32 and _F64 datatypes in hdf5_fun.cpp

### ISSUE THREAD

**Issue by rsiddans** [gnudatalanguage/gdl#1923]
There appears to be a bug in hdf5_fun.cpp in which GDL_ integer types are associated with various H5T_*_F32 and H5T_*_F64 data types via definitions of type_map like this...
/* GDL_LONG64 */
        { H5T_NATIVE_LLONG, H5T_IEEE_F64BE, H5T_IEEE_F64LE, H5T_INTEL_B64,
          H5T_INTEL_F64, H5T_INTEL_I64, H5T_MIPS_B64, H5T_MIPS_F64,
          H5T_MIPS_I64, H5T_NATIVE_B64, H5T_NATIVE_INT64, H5T_NATIVE_INT_FAST64,
          H5T_NATIVE_INT_LEAST64, H5T_STD_B64BE, H5T_STD_B64LE, H5T_STD_I64BE,
          H5T_STD_I64LE, H5T_UNIX_D64BE, H5T_UNIX_D64LE, H5T_ALPHA_B64,
          H5T_ALPHA_F64, H5T_ALPHA_I64 },

The types ending _F64 should be associated with GDL_DOUBLE instead e.g change code from
          /* GDL_DOUBLE */
       { H5T_NATIVE_DOUBLE },
to
          /* GDL_DOUBLE */
        { H5T_NATIVE_DOUBLE,H5T_IEEE_F64BE,H5T_IEEE_F64LE,H5T_INTEL_F64,H5T_MIPS_F64,H5T_ALPHA_F64},
(and remove the F64 types from the lines defining integer types below)

Similarly types ending F32 should be associated with GDL_FLOAT.

The effect of this bug is for double precision data in an HDF5 to be wrongly returned as an integer data type.
(I guess this only happens when the file being read uses a type other than H5T_NATIVE_FLOAT/DOUBLE)
(I have an e.g. hdf5 file which can be correctly read only after fixing hdf5_fun.cpp as suggested above)

**Comment by GillesDuvert** [comment]
Hello, thanks for the report! The last HDF5-related changes were done by @ogressel , may be he can help? If you can clone gdl on GH and create a pull request all by yourself we will be more than happy to use your contribution to improve GDL.

**Comment by rsiddans** [comment]
OK thanks for quick reply.
I've not used git much and not at all github...
I got the source (to a linux machine) via command line by doing
"git clone --recursive https://github.com/gnudatalanguage/gdl.git" 
(as per https://github.com/gnudatalanguage/gdl/wiki/Cloning-gnudatalanguage-gdl)
I have then modified code in src and have done a local "git commit -a"

Can you give me some indications how to go from that to making a pull request ?
(ideally via linux command line)

**Comment by slayoo** [comment]
@rsiddans, to make a pull reqeust, the first step is to "fork" the GDL repository on GitHub, so you get your own in-the-cloud copy of the repo with write permissions. This can be done by clicking the "Fork" button in the top right:
![image](https://github.com/user-attachments/assets/41f2d5db-3f7e-421d-b7e4-77a84192f20e)

Then, you should be able to do on your machine:
```
$ git remote add my_fork git@github.com:rsiddans/gdl.git
$ git fetch my_fork
$ git push my_fork HEAD:new_branch
``` 
Following which, you can create the pull request online at https://github.com/gnudatalanguage/gdl/compare

**Comment by rsiddans** [comment]
Great - many thanks -I think pull request now done.

**Comment by GillesDuvert** [comment]
excellent!
I've merged this, closing.
