### ISSUE TITLE
% POLY_2D: Complex values not supported (FIXME)

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1927]
(I am sorry to always report bugs and not helping to solve then :sob: )

Thanks and bravo to @GillesDuvert for solving the ROT() issue. I tested with success on three machines, including OSX on M2.

Just to mention the POLY_2D don't accepting complex inputs.

`% POLY_2D: Complex values not supported (FIXME)`

I don't know is the real parts and the imaginary parts are processed independently. I hope so ! 

And also, any idea to extend the new but very limited `test_rot.pro` are very welcome.

**Comment by GillesDuvert** [comment]
will be closed by #1936
