### ISSUE TITLE
file_search does not expand shell variables

### ISSUE THREAD

**Issue by rsiddans** [gnudatalanguage/gdl#1932]
On our linux system, GDL file_search does not expand environment variables (unlike IDL)
E.g. directory "vm" in home dir not found with GDL:
GDL> ff=file_search('$HOME/vm',count=nf)&print,nf
           0
But found by IDL
IDL> ff=file_search('$HOME/vm',count=nf) & print,nf   
           1

Is there a known fix for this (e.g. shell / compiler setting) perhaps ?
If not then I suppose code could be probably be fixed wither at low level by replacing "glob()" calls with "wordexp()" or at high level by replacing the env-vars in the input string. Any opinion on that ?

**Comment by GillesDuvert** [comment]
This looks like a possible regression.
Under unix it is easier to type `ff=file_search('~/vm',count=nf) & print,nf`
and indeed this works with IDL (Mac and Linux, possibly even Windows). 
But I see:
```
GDL> ff=file_search('~/Documents',count=nf)&print,nf
           1
GDL> ff=file_search('$HOME/Documents',count=nf)&print,nf
           0
```
and on my machine GDL is supposed to use wordexp() so it should work!

**Comment by rsiddans** [comment]
As far as I can see in file.cpp, unless its win32, file_search uses function FileSearch which uses glob not wordexp.
(I see other fns which use wordexp in str.cpp)

**Comment by GillesDuvert** [comment]
I looked into the code. It seems glob() permits, through its modifiers (GLOB_TILDE, GLOB_MARK ...) to easily implement several options ("EXPAND_TILDE", "MARK_DIRECTORY" ...) that are not present (?) in wordexp.
I would even risk the opinion that the IDL command so mimicks the glob() options that IDL must use glob() internally.
I bet a few lines of C could handle efficently the `$HOME, ${HOME}` things.

**Comment by rsiddans** [comment]
...bear in mind its not just $HOME, any env.var should be recognised and replaced, so would need to parse path for any occurence of "$" and pull out the following variable name, dealing correctly with the curly brackets which might or might not be there etc. I see getenv works so once a variable is identified it could be strreplace with getenv(variable). I'm not familiar enough with the code to know if there are more fns which would make that easy to implement in a few lines.

**Comment by GillesDuvert** [comment]
#1935 should do it.

**Comment by GillesDuvert** [comment]
> ...bear in mind its not just $HOME, any env.var should be recognised and replaced, so would need to parse path for any occurence of "$" and pull out the following variable name, dealing correctly with the curly brackets which might or might not be there etc. I see getenv works so once a variable is identified it could be strreplace with getenv(variable). I'm not familiar enough with the code to know if there are more fns which would make that easy to implement in a few lines.

I bet there are tons of places a code review followed by a few lines more or less will make a difference!
Issues indicated with the 
![image](https://github.com/user-attachments/assets/055e7729-8e0c-45c7-9ec2-f318da26e69a)
tag are an example.
