### ISSUE TITLE
READF fails reading comma separated values

### ISSUE THREAD

**Issue by rsiddans** [gnudatalanguage/gdl#1939]
READF does not correctly read values from an ascii file which are only separated by comma.
E.g. given file with single line
"1,2,3,4,5"
IDL can read all 5 values via
IDL> d=fltarr(5) & readf,lun,d

GDL only reads the first value and then reports end of file.
(If spaces are added after each comma then GDL will work)
(If spaces are replaced by comma then GDL will work)

Note that GDL can read the 5 values from the same string. E.g. the following works fine...
GDL> str="1,2,3,4,5"
GDL> d=fltarr(5) & reads,str,d

The attached code+file can be used to reproduce this.[
[gdl_test_readf.tar.gz](https://github.com/user-attachments/files/18036932/gdl_test_readf.tar.gz)
](url)

**Comment by GillesDuvert** [comment]
This was, if I remeber well, working. And there should be a test in the testsuite. strange. Possibly related to a somewhat old change aiming at supporting (much needed) windows-like end-of-lines in such files.
Unfortunately I cannot look at this in the next few days.

**Comment by GillesDuvert** [comment]
It is just that nobody realized comma separated values should be handled by READF naturally, I.e., without a FORMAT. Blank or tab are OK. I was confused with READS where the comma are already accepted.
