### ISSUE TITLE
Insure  ANTLR - created files (GDL*.[c|h]pp files) are compatible with their ANTLR sourcefiles (*.g)

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#198]
Sometimes one make patches to GDL*.[c|h]pp files *ONLY*
These patches should not be accepted if they are not present also in the parent *.g files, as the GDL* files are bound to be recreated by `for i in *.g; do antlr $i; done;`
It is necessary to add (in Travis?) a test to check that such a situation does not happen.

**Comment by slayoo** [comment]
A relevant comment from @opoplawski suggesting to remove the generated files from the repo:
https://github.com/gnudatalanguage/gdl/pull/274#issuecomment-394369044

**Comment by slayoo** [comment]
+ we need also to ensure that the convenience-copy antlr headers are replaced upon regeneration! Should we then remove these (the whole antlr directory) from the repo @opoplawski?

**Comment by slayoo** [comment]
This is addressed here: https://github.com/gnudatalanguage/gdl/pull/529
The question of removal of antlr-generated files and the headers is in fact part of the still open: https://github.com/gnudatalanguage/gdl/issues/45
