### ISSUE TITLE
In windows SPAWN command in procedure starts at the home directory (not the CWD)

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#208]
In Linux, SPAWN begins a shell process the starts in the current working directory (CWD).
This is not the case for the windows version, which nevertheless can do that for the "$"
 invocation method.
The behavior should follow that of the linux implementation as much as possible.

**Comment by maynardGK** [comment]
This feature will come when PR branch_pro includes commit 3ba4c43b2533d7d144d40d9e60092aa90f8e1817
"Refurb of launch_cmd (called from spawn_pro fror Windows)", pushed soon.

**Comment by slayoo** [comment]
@maynardGK It would be really really great to have a single commit, single branch, single PR and single test for such issues! Thanks
