### ISSUE TITLE
Coyote progress bar

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#21]
(moved from https://sourceforge.net/p/gnudatalanguage/bugs/729/)
As reported on SF by Alain:

Coyote proposes two verisons of a progress bar based on Widgets.
http://www.idlcoyote.com/widget_tips/show_progress.php

both are not working perfectly :(

I t may help to improve details in Widgets for GDL ?!

lets remark one is already packaged in the git Debian Coyote
with an example (you can downlod it :
git clone https://anonscm.debian.org/git/debian-astro/packages/coyote.git
)

```
GDL> .r cgprogressbar__define
GDL> PROGRESSBAR_EXAMPLE
```

**Comment by GillesDuvert** [comment]
actually it is a bug of OBJ_NEW().
which is still a bug!

**Comment by slayoo** [comment]
Gilles, if possible please post here an example calling sequence for obj_new() that depicts the problem.

**Comment by GillesDuvert** [comment]
Sorry. I wish I could! Object support in GDL is untested and confidential. We'll stumble on this bug at some point when time comes.
