### ISSUE TITLE
in-tree assumptions in tests (cleanup needed)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#213]
There are several places where the tests assume in-tree execution/compilation, e.g.:
- spawn commands with ../src/gdl as argument
- file opening (e.g. example.grib)
- formats.idl file
Cleanup needed.

See also: 
- https://sourceforge.net/p/gnudatalanguage/bugs/393/
- https://sourceforge.net/p/gnudatalanguage/bugs/684/

**Comment by GillesDuvert** [comment]
test_formats was buggy and clearly untested. It has been rewritten recently to make a complete test of all possible cases and replaces test_format.pro
Closing as "fixed".
