### ISSUE TITLE
enable PSLIB for travis OSX tests

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#214]
As reported here: https://sourceforge.net/p/gnudatalanguage/bugs/578/
PSLIB was causing linking trouble on OSX, while it is now OFF on travis.

**Comment by GillesDuvert** [comment]
We should completely remove PSLIB which is not needed.

**Comment by slayoo** [comment]
closing then (PR to remove pslib is here: https://github.com/gnudatalanguage/gdl/pull/781)
