### ISSUE TITLE
DIALOG_MESSAGE crashes without a widget base (on Windows)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#218]
As reported by @pjb7687 on SF.net (https://sourceforge.net/p/gnudatalanguage/bugs/652/):

Below crashes:

```
a = dialog_message("")
```

However, below does not crash:

```
a = widget_base()
b = dialog_message("")
```

Maybe some extra initialization is needed for wxMessageDialog. And this only occurs with DIALOG_MESSAGE. DIALOG_PICKFILE does not have the issue.

I am investigating the issue, and found that the error occurs at wx/src/msw/msgdlg.cpp, line 433. The file is Windows specific one, so it should be a Windows-only issue.

Also found that closing a newly created widget (not dialog) also causes crash. However, the problem does not occur if XMANAGER is called after the widget realization.

In my opinion, it looks like both of the two problems are related to the message loop of wxWidgets..

**Comment by GillesDuvert** [comment]
works on linux.
