### ISSUE TITLE
LIST::_OVERLOADBRACKETSLEFTSIDE (internal): Incorrect number of elements for Values (1 NE 3)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#222]
As reported by @maynardGK on SF.net (https://sourceforge.net/p/gnudatalanguage/feature-requests/144/):

```
GDL> ll=list(length=8)
GDL> for k=0,5 do ll[k]=float(2*k)
GDL> ll[3]="three
GDL> ll[6]=indgen(3)
% LIST::_OVERLOADBRACKETSLEFTSIDE (internal): Incorrect number of elements for Values (1 NE 3).
% Execution halted at: $MAIN$ 
```

**Comment by maynardGK** [comment]
This bug was left un-fixed in legacy_list https://github.com/gnudatalanguage/gdl/pull/239 but is already fixed (as well as most other features) for future integration.
