### ISSUE TITLE
List::Swap not available

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#224]
As reported by @maynardGK at SF.net (https://sourceforge.net/p/gnudatalanguage/feature-requests/144/):

```
GDL> list4 = LIST(3, 7, 9, 12, [4, 33, 9, 64, 43], 'alpha')
GDL> list4.swap,1,4
% Attempt to call undefined method: LIST::SWAP
% Execution halted at: $MAIN$
```

See also: http://www.harrisgeospatial.com/docs/LIST.html#SwapMethod

**Comment by maynardGK** [comment]
LIST::swap is implemented in https://github.com/gnudatalanguage/gdl/pull/239

`$ legacy_list

  GDL - GNU Data Language, Version 0.9.8 svn

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at:
  http://sourceforge.net/projects/gnudatalanguage/

% Compiled module: PATH_SEP.
GDL> list4 = LIST(3, 7, 9, 12, [4, 33, 9, 64, 43], 'alpha')
GDL> list4.swap,1,4
GDL> print,list4
       3
       4      33       9      64      43

       9
      12
       7
alpha`

**Comment by slayoo** [comment]
this works as of now and seems covered by the test_list.pro
