### ISSUE TITLE
Add variable !GDL.options to show how GDL was built.

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#226]
As proposed by @maynardGK on SF.net (https://sourceforge.net/p/gnudatalanguage/patches/81/):

To document the packages and options attached to a running GDL, encode themacros in the system variable !GDL.

I'm using this in my builds, here's how it looks in .gdl_startup, where I define a
new system variable to hold the readable options the program was built for:

```
if(n_elements(!gdl) && n_elements(!gdl.options)) then begin &   O=!gdl.options &  $
   if(~n_elements(!bldopt)) then $
   defsysv,'!bldopt',  { win32: (O and 1) ne 0, msvc: (O and 2) ne 0, $
            cygwin: (O and 4) ne 0, is64bit: (O and '40'xul) ne 0, $
     noreadline: (O and '100'xul) ne 0, gfxmagick: (O and '200'xul) ne 0, $
             eigen3: (O and '400'xul) ne 0, libwx: (O and '800'xul) ne 0, $
             python: (O and '1000'xul) ne 0, netcdf: (O and '2000'xul) ne 0, $
             hdf5: (O and '1000'xul) ne 0}, 1 &$
    endif
```

```
% Compiled module: PATH_SEP.
D:/home/greg/.gdl_startup: Exception: basic_string::substr: __pos (which is 4294967295) > this->size() (which is 0)
GDL> help,/st,!bldopt
** Structure <Anonymous>, 11 tags,memsize =88, data length=11:
   WIN32           BYTE         1
   MSVC            BYTE         0
   CYGWIN          BYTE         0
   IS64BIT         BYTE         1
   NOREADLINE      BYTE         0
   GFXMAGICK       BYTE         1
   EIGEN3          BYTE         0
   LIBWX           BYTE         0
   PYTHON          BYTE         0
   NETCDF          BYTE         0
   HDF5            BYTE         0
```

[diffinit.ls.gz](https://github.com/gnudatalanguage/gdl/files/1927781/diffinit.ls.gz)

**Comment by GillesDuvert** [comment]
same issue as #232 : get more information as the wherebaouts of this particular GDL build.
list of build options must be variable since the number of external libraries we need varies. Points to a LIST IMHO. To be one of the tags of !GDL when we make it a struct. (soon!)
