### ISSUE TITLE
FindEditline.cmake looks for editline/readline.h, Debian provides editline.h

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#227]
https://github.com/gnudatalanguage/gdl/blob/master/CMakeModules/FindEditline.cmake#L17
https://packages.debian.org/sid/amd64/libeditline-dev/filelist

**Comment by slayoo** [comment]
@olebole this seems similar in scope to your today's #532 - any hints what would be the correct way to go?

**Comment by olebole** [comment]
We link to readline; therefore libeditline may not be relevant.

**Comment by slayoo** [comment]
No more editline (#762)
