### ISSUE TITLE
Allow run-time behavioral option: Win32 path separator ("/" or "\")

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#228]
As reported by @maynardGK on SF.net (https://sourceforge.net/p/gnudatalanguage/feature-requests/140/):

Recently we have added win32 support for file_search(). Internally it now does this by hooking into the same path-search routine used in the posix code, i.e. with a forward-slash "/" separating subdirectory names. In GDL-win32 these names get doctored by replacing '/' <-- '\'. In modern windows systems, forward slash -is- allowed for path specification: D:/top/path/level.exe is supposed to be legible as well as D:\top\path\level.exe. In posix
systems, however, the backslash is eaten up so the second form will look like D:\toppathlevel.exe.

Why does this matter in windows? Some situations will require filenames be formatted to be posix-compatible. So having "/" in pathnames is a valid preference, especially in projects
that will mingle with posix-based systems - some of which may themselves be hosted under windows.

Mechanism? since path_separator() can be a heavily used item in filename processing. In fact, to maintain the '/' separator requires no work: swapping them to '\' is a code block that could be defaulted one way and switched at runtime.

**Comment by maynardGK** [comment]
I have been developing file.cpp without the use of path_separator, except as a lib:: host as used in dialog.cpp.  In the routines of file.cpp, either "/" or "\" are viewed as path_separators, and I tend to stick in a forward slash when composing names. 
 I run over an msys posix-style shell and issue spawn commands such as 
`ls ../../*.pro` successfully - the legacy file_move, file_delete, and file_copy work ok.

If a user is spawning to a raw CMD.exe shell there may be issues with the filenames having forward slashes, and so perhaps in these cases a filename cleanup/converter could be used that can do the desired conversion.
  Also, the disk drive lettering is another pain.  WIN32 full paths include the "drive letter": but the MSYS shell would rather see /"drive letter"/.

**Comment by GillesDuvert** [comment]
see #654 #635
