### ISSUE TITLE
test simplex fails with: glp_load_matrix: ja[1] = 1072693248; column index out of range

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#233]
As captured here: https://travis-ci.org/slayoo/gdl/jobs/368905277

```% Compiled module: TEST_SIMPLEX.
glp_load_matrix: ja[1] = 1072693248; column index out of range
Error detected in file glpapi01.c at line 1001
TEST EXITED FROM SIGNAL 6
```

**Comment by alaingdl** [comment]
How to know if it related to OSX only ? 

For me, it is a bug related to GLPK on OSX "only" !

**Comment by alaingdl** [comment]
GDL> test_simplex
on OSX only, complied with GLPK (provided by Brew)

% Compiled module: TEST_SIMPLEX.
glp_load_matrix: ja[1] = 1072693248; column index out of range
Error detected in file api/prob1.c at line 1009

**Comment by alaingdl** [comment]
I think I found the bug ... See PR #739 
I also added a new test from GLPK doc.
