### ISSUE TITLE
Empty list or hash references don't survive an array placement.

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#236]
As reported by @maynardGK on SF.net (https://sourceforge.net/p/gnudatalanguage/bugs/696/):

Empty lists (or hashes) become nullObject when stuck into an array

This may be happening because somewhere a "p->N_Elements == 0" symptom
implies a null object. But N_Elements is overloaded to be # list/table elements (=0).
So when the object reference of an empty list is put into an (OBJ)array, its identity is lost.

```
Below, "L" is a populated list and "k" is empty:
GDL>L=list(indgen(4)) & k=list()
GDL> print,obj_isa(L,'list')
1
GDL> print,obj_isa([L,L,L],'list')
1 1 1
GDL> print,obj_isa([L,L,L,k],'list')
1 1 1 0
GDL> print,obj_isa(k,'list')
0
GDL> help,k
K LIST <ID=4 N_ELEMENTS="0">
GDL> ii=objarr(3)
GDL> ii[0]=L & ii[1]=k & ii[2]=L
GDL> help,ii[0],ii[1],ii[2]
<Expression> LIST <ID=3 N_ELEMENTS="1">
<Expression> OBJREF = <NullObject>
<Expression> LIST <ID=3 N_ELEMENTS="1">
```

Probably the main answer is that the LIST() routine doesn't make a proper object;
the object pointer isn't assigned to the array because it is malformed in some manner.

This is probably specific to LIST and HASH types?
```
GDL> tt=objarr(4)
GDL> for k=0,3 do help,tt[k]
<Expression>    OBJREF    = <NullObject>
<Expression>    OBJREF    = <NullObject>
<Expression>    OBJREF    = <NullObject>
<Expression>    OBJREF    = <NullObject>
GDL> for k=0,3 do tt[k]=l
GDL> for k=0,3 do help,tt[k]
<Expression>    LIST      <ID=10  N_ELEMENTS=1>
<Expression>    LIST      <ID=10  N_ELEMENTS=1>
<Expression>    LIST      <ID=10  N_ELEMENTS=1>
<Expression>    LIST      <ID=10  N_ELEMENTS=1>
GDL> help,lgdl
LGDL            LIST      <ID=1  N_ELEMENTS=4>
GDL> for k=0,3 do tt[k]=lgdl
GDL> for k=0,3 do help,tt[k]
<Expression>    LIST      <ID=10  N_ELEMENTS=1>
<Expression>    LIST      <ID=10  N_ELEMENTS=1>
<Expression>    LIST      <ID=10  N_ELEMENTS=1>
<Expression>    LIST      <ID=10  N_ELEMENTS=1>
```

Either 1. 0 elements or 2. object produced in the LIST() routine seem to be where the handling fails:
```
GDL> lgdl=obj_new('list',length=2)
GDL> help,lgdl
LGDL LIST <ID=11 N_ELEMENTS="0">
GDL> for k=0,3 do tt[k]=lgdl
GDL> for k=0,3 do help,tt[k]
<Expression> OBJREF = <NullObject>
<Expression> OBJREF = <NullObject>
<Expression> OBJREF = <NullObject>
<Expression> OBJREF = <NullObject>
GDL> lgdl.add,1
GDL> for k=0,3 do tt[k]=lgdl
GDL> for k=0,3 do help,tt[k]
<Expression> LIST <ID=11 N_ELEMENTS="1">
<Expression> LIST <ID=11 N_ELEMENTS="1">
<Expression> LIST <ID=11 N_ELEMENTS="1">
<Expression> LIST <ID=11 N_ELEMENTS="1">
GDL> lgdl.add,2
GDL> for k=2,3 do tt[k]=lgdl
GDL> for k=0,3 do help,tt[k]
<Expression> LIST <ID=11 N_ELEMENTS="2">
<Expression> LIST <ID=11 N_ELEMENTS="2">
<Expression> LIST <ID=11 N_ELEMENTS="2">
<Expression> LIST <ID=11 N_ELEMENTS="2">
GDL> newl=obj_new('list',1)
GDL> help,newl
NEWL LIST <ID=12 N_ELEMENTS="0">
GDL> newl.add,1
GDL> for k=0,1 do tt[k]=newl
GDL> for k=0,3 do help,tt[k]
<Expression> LIST <ID=12 N_ELEMENTS="1">
<Expression> LIST <ID=12 N_ELEMENTS="1">
<Expression> LIST <ID=11 N_ELEMENTS="2">
<Expression> LIST <ID=11 N_ELEMENTS="2">
GDL> l=list(indgen(3),/extract)
GDL> for k=2,3 do tt[k]=l
GDL> for k=0,3 do help,tt[k]
<Expression> LIST <ID=12 N_ELEMENTS="1">
<Expression> LIST <ID=12 N_ELEMENTS="1">
<Expression> LIST <ID=11 N_ELEMENTS="2">
<Expression> LIST <ID=11 N_ELEMENTS="2">
GDL> help,l
L LIST <ID=13 N_ELEMENTS="3">
```

Good news: problem is understood ( at least, solution is possible).
Bad news: solution requires some surgery.

As I suspected in OP, changing the meaning of ->N_Elements() for the LIST and HASH
object cases is why these objects do not behave like other objects. This specification is what
the code should return when one does N_ELEMENTS( <list or="" hash="" object="">) and also the answer in the return from SIZE( <list or="" hash="" object="">). However it was implemented internally at a fundamental level - in the definition routine (datatypes.cpp) itself - which breaks the behavior
of these objects when run through the generalized code.

In my code I've experimentally reverted the N_Elements() method to be the standard as for any object, and implemented the IDL functions N_ELEMENTS() and SIZE() such that the special cases of list or hash objects induce a modified result. Since the help procedure already looked directly at the count parameter it was already correct.

list.cpp
hash.cpp
prognode_expr.cpp
basic_fun.cpp
basic_fun_jmg.cpp

```
GDL> .rnew
Interactive RUN not implemented yet.
GDL> tt=objarr(4)
GDL>  lgdl=obj_new('list')
 gdl_OBJECT_Init!
GDL> help,lgdl
LGDL            LIST      <ID=40  N_ELEMENTS=0>
GDL> for k=0,3 do tt[k]=lgdl
GDL> for k=0,3 do help,tt[k]
<Expression>    LIST      <ID=40  N_ELEMENTS=0>
<Expression>    LIST      <ID=40  N_ELEMENTS=0>
<Expression>    LIST      <ID=40  N_ELEMENTS=0>
<Expression>    LIST      <ID=40  N_ELEMENTS=0>
GDL> lgdl.add,1
GDL> for k=0,3 do tt[k]=lgdl
GDL> for k=0,3 do help,tt[k]
<Expression>    LIST      <ID=40  N_ELEMENTS=1>
<Expression>    LIST      <ID=40  N_ELEMENTS=1>
<Expression>    LIST      <ID=40  N_ELEMENTS=1>
<Expression>    LIST      <ID=40  N_ELEMENTS=1>
GDL> lgdl.add,2
GDL> for k=2,3 do tt[k]=lgdl
GDL> for k=0,3 do help,tt[k]
<Expression>    LIST      <ID=40  N_ELEMENTS=2>
<Expression>    LIST      <ID=40  N_ELEMENTS=2>
<Expression>    LIST      <ID=40  N_ELEMENTS=2>
<Expression>    LIST      <ID=40  N_ELEMENTS=2>
GDL> newl=obj_new('list')
 gdl_OBJECT_Init!
GDL> help,newl
NEWL            LIST      <ID=41  N_ELEMENTS=0>
GDL> newl.add,1
GDL> for k=0,1 do tt[k]=newl
GDL> for k=0,3 do help,tt[k]
<Expression>    LIST      <ID=41  N_ELEMENTS=1>
<Expression>    LIST      <ID=41  N_ELEMENTS=1>
<Expression>    LIST      <ID=40  N_ELEMENTS=2>
<Expression>    LIST      <ID=40  N_ELEMENTS=2>
GDL> l=list(indgen(3),/extract)
GDL> for k=2,3 do tt[k]=l
GDL> for k=0,3 do help,tt[k]
<Expression>    LIST      <ID=41  N_ELEMENTS=1>
<Expression>    LIST      <ID=41  N_ELEMENTS=1>
<Expression>    LIST      <ID=42  N_ELEMENTS=3>
<Expression>    LIST      <ID=42  N_ELEMENTS=3>
GDL> help,l
L               LIST      <ID=42  N_ELEMENTS=3>
GDL> tt[0].count()
           1
GDL> help,l
L               LIST      <ID=42  N_ELEMENTS=3>
GDL> jj=list()
GDL> help,jj
JJ              LIST      <ID=43  N_ELEMENTS=0>
GDL> jj.count()
           0
```

**Comment by maynardGK** [comment]
My next PR, called "legacy_list", will include the N_elements() change.  Also, some of the new code will be added to list.cpp, so that a difference should show mostly large blocks of new material.   Because the added functionality in the new version is extensive, immediate comparisons at this stage will be difficult to browse.

**Comment by slayoo** [comment]
thanks, if possible please do split it into as small chunks as possible (i.e. one new test + relevant code change per PR / branch)

**Comment by maynardGK** [comment]
Yes as much as possible, small changes; no PR even until the pending PRs are through since there is some co-mingling.  It has been waiting for a few years now and the first change will be big by necessity.  The pre-existing routines of list.cpp will be much the same at the start, and the test routine will sense the legacy build and not exercise the more difficult tests.

**Comment by slayoo** [comment]
thanks

**Comment by maynardGK** [comment]
The changes outlined in the first comment are implemented in legacy_list https://github.com/gnudatalanguage/gdl/pull/239

**Comment by slayoo** [comment]
@maynardGK any updates here - is it fixed and covered in tests? Thanks

**Comment by maynardGK** [comment]
Yes I believe the <list>->N_Elements() aspect of the code fixes that.
There are probably tests in test_list that checks it.

On Fri, Jun 15, 2018 at 12:28 AM, Sylwester Arabas <notifications@github.com
