### ISSUE TITLE
SURFACE with array at zero !

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#247]
SURFACE, FLTARR(10,10) 
crashed since mid of June 2017 if not plot run before
OK before June 03
KO since June 23
(few changes, including "plotting_plot.cpp" & "plotting.cpp"

reproducible on OSX & Linux (u14.04 & u16.04)

SURFACE, FLTARR(10,10) +1 
does not crash

A.

**Comment by GillesDuvert** [comment]
Dies on plplot error... Thanks for this nice (easy) bug.
