### ISSUE TITLE
Better integrate graphics device WIN with new plotting code.

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#249]
In its current state (version 0.9.8) GDL built on windows has problems with the deviceWIN usage
when wxWidgets is also present.
Over the past few years a lot of effort has been given to developing the plot and widget code, and test requirements have been satisfied on Linux machines - a windows build being rare. I recalled a build from July 2016 and the WIN plotting at that point is very robust.  Working from this base I then gradually
add modern improvements until it break again, whereby I debug to find the offensive condition.

To test the robustness of a GDL build w.r.t. plots, I run the following script:
`fs=findgen(40) & !prompt="" & iw=-1
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
wshow,iw,0
wshow,iw-1,0
wshow,iw-2,0
wshow,iw-2,/icon
wshow,iw-2,0
wshow,iw-3,0
wshow,0,0,/icon
wshow,0
end`

ending up with 6 plots on screen.  Following this I can test how well WSHOW command works.  Also,
deleting the windows with the top-right button is a good tell as to the program stability.
The picture given in issue 113 https://github.com/gnudatalanguage/gdl/issues/113 shows my screen for this process.   
Initially a "fix" can be made to the GDLWidget:: HandleEvents() routine which tests if a flag has been set internally (false if there have been no widgets) and skips a loop if not.  I suppose the added delay is appreciated, or the HandleEvents() call is too short, but removing this flag check improves the results.
This, and re-instatement of deviceWIN::WShow comprise the first commit on this road.

**Comment by maynardGK** [comment]
After this second commit I can now plot as good as ever in GDL, -and- put up the demo_widgets bundle (with /NOCANVAS keyword set).

![gdlf-testfocus demo_widgets](https://user-images.githubusercontent.com/7710053/39402885-31f1baa8-4b21-11e8-96d9-88ff8c140221.PNG)

**Comment by maynardGK** [comment]
Now back in Linux the Focus is also not being reassigned to the console window, this is simply
repaired by re-activating the "UnsetFocus()" call from GraphicsMultiDevice::WShow. The picture below
shows the remaining problem, that "WShow" from WX windows does not work.

![screenshot_2018-04-29_15-55-59](https://user-images.githubusercontent.com/7710053/39412604-f1c2b7da-4bd3-11e8-884f-d4960b6ac0ef.png)

**Comment by maynardGK** [comment]
So that's where we are.  Everything should be as good as it can get once the https://github.com/gnudatalanguage/gdl/pull/252 (maynardGK/win_plots) branch is implemented.

**Comment by maynardGK** [comment]
All is well for Linux but in windows I notice another quirk, after testfocus puts up the five windows,
wshow,5
wshow,5,0
wshow,5
   Now window #5 WShow is inoperable.  It will come to the front if a CURSOR routine is called for it.
Ok I had disabled the "remember me" aspect of iconization for windows.  previous behavior was to always de-iconize before any WShow,  now a WSHOW may not show you a window if it is iconized.

That fixed, remaining issue is, that an initial Wshow to lower the window actually raises it.
.run testfocus
wshow,5,0        ; ,--- window 5 actually comes up from background
wshow,5,0        ; Now it operates as anticipated.

**Comment by GillesDuvert** [comment]
WIN is obsoleted.
