### ISSUE TITLE
bad graphical output with sequence PLOT then SURFACE

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#264]
Since the current Vanilla 0.9.8 is affected ! I vote for a 0.9.8-1 ASAP !

The sequence was OK until March 5, 2018. After large change done mid-March, the _sequence_ PLOT then SURFACE gives a bad output for SURFACE

As far as I tested, the sequence PLOT then CONTOUR is not affected.

Case 1 : bad position and aspect ratio
plot, findgen(10)
surface, dist(10,10) ; <-- bad position and aspect ratio

Case 2 : broken output. when a xrange is added to the previous call, the second "plot" is even worse : 
plot, findgen(1000)+2000, xrange=[500, 1000]     
surface, dist(10,10)  ; <2-- minuscule output in lower left corner
surface, dist(10,10) ; <3-- no output at all
surface, dist(10,10) ; <4-- yes, the output (correct position and aspect ration)

In fact I joined the two cases because when we complete case 1, we have same behaviour than case 2: 
case 1 revised : 
plot, findgen(10)
surface, dist(10,10) ; <-- bad position and aspect ratio
surface, dist(10,10)  ; <-- quite good but not perfect !
surface, dist(10,10) ; <-- same output than case 2 step 4.

Alain

**Comment by slayoo** [comment]
For the record, I've created a github "milestone" for tracking things we would like to have in for the upcoming release: https://github.com/gnudatalanguage/gdl/milestone/1

**Comment by GillesDuvert** [comment]
solved with most recent push request, along with #247 and  #265
