### ISSUE TITLE
traceback lines are unavailable in $MAIN program

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#270]
As example of a $MAIN program, testsuite/test_container.pro has its procedure commented
in order to keep an interactive dialog intact.  Currently a snag is being hit and the line number
where the stop occurs is not displayed:
#239 
'
GDL> test=1
GDL> .run  test_container
% Compiled module: MYMESS.
% Compiled module: $MAIN$.
 stop 0
% Stop encountered: $MAIN$
GDL> .c
 stop 1: testing ::GET(/ALL,POSITION)
% Stop encountered: $MAIN$
GDL> .c
InterpreterLoop: Unhandled Error.
GDL> help,lc[0]
InterpreterLoop: Unhandled Error.
'

**Comment by GillesDuvert** [comment]
unable to reproduct
