### ISSUE TITLE
a possible speed enhancement for make_array/*indgen function family

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#279]
In a recent change that added support for START and INCREMENT keywords to the *INDGEN function family, there is potentially room for speed improvement by introducing separate code paths for the cases where these keywords are not specified, see:

https://github.com/gnudatalanguage/gdl/pull/272/files#diff-5725c7e54915ffe15baf6d1e8f02acfdL403

**Comment by GillesDuvert** [comment]
I believe that's done!
