### ISSUE TITLE
pb 2 with wx3.0 on Debian : 

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#300]
when running "test_widgets.pro", 

if clicking on "complicated menu" then "submenu1" then any option, I received : 

% EVENT_IN_BASE: Struct expression not allowed in this context: ID
% Execution halted at: EVENT_IN_BASE       27 /home/coulais/GDL/gdl-0.9.8git180606CMake/testsuite/test_widgets.pro

**Comment by maynardGK** [comment]
#304 includes repair for this item, which was in GDL code of the test program.
