### ISSUE TITLE
lonarr(3,1) = long[3] - top dimension is removed

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#302]
I notice that the last dimension, if 1, is destroyed for lonarr, fltarr, etc.  and also from the replicate function.
I don't have an IDL to run and compare, but I believe the correct behavior is to preserve the # of dimensions.

**Comment by slayoo** [comment]
```
IDL> help, lonarr(3,1)
<Expression>    LONG      = Array[3]
IDL> help, lonarr(3,1,1)
<Expression>    LONG      = Array[3]
IDL> help, replicate(3,1,1,1)
<Expression>    INT       = Array[1]
```

False alert then? (and anyhow thanks!)

**Comment by maynardGK** [comment]
OK!
