### ISSUE TITLE
should add the mandatory <rpc/rpc.h> in CMake ...

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#306]
on a "clean" Fedora 28, after adding many devel rpm indicated by the script : 
" scripts/rpm4gdl.sh", the missing header  <rpc/rpc.h> remainds ...

this is mandadory for save/restore

A.

In file included from /home/acoulais/GDL/gdl-0.9.8git180608/src/str.hpp:25,
                 from /home/acoulais/GDL/gdl-0.9.8git180608/src/envt.hpp:26,
                 from /home/acoulais/GDL/gdl-0.9.8git180608/src/FMTIn.hpp:14,
                 from /home/acoulais/GDL/gdl-0.9.8git180608/src/FMTIn.cpp:5:
/home/acoulais/GDL/gdl-0.9.8git180608/src/basegdl.hpp:27:12: fatal error: rpc/rpc.h: No such file or directory
 #  include <rpc/rpc.h>
            ^~~~~~~~~~~

**Comment by alaingdl** [comment]
The problem is also I found no related package in Fedora !

maybe libtirpc-devel ? or mingw64-portablexdr.noarch ??

dnf repoquery -l libtirpc-devel
giving /usr/include/tirpc/rpc/rpc.h

dnf repoquery -l mingw64-portablexdr.noarch
/usr/x86_64-w64-mingw32/sys-root/mingw/include/rpc/rpc.h


And do we need <rpc/rpc.h> or <rpc/xdr.h> ??

A.

**Comment by opoplawski** [comment]
Use libtirpc-devel and -I/usr/include/tirpc  and -ltirpc.  Done it the appropriate way of course.  There is a libtirpc pkgconfig file.

**Comment by GillesDuvert** [comment]
@alaingdl , xdr and rpc seems a mess for me. No two distro use the same, and nothing make me crazier when an obvious dependency is not found by my package installer.
I note that on my mageia 5,  /usr/include/rpc/xdr.h is provided by glibc-devel-2.20-27.mga5 
Aside that I cannot help.

**Comment by alaingdl** [comment]
@GillesDuvert : that is the point ! rpc (and xdr) will be removed in the future because of IPV6 pbs ...
F28 is ready, we are not ! [f28 SunRPC removal] (https://fedoraproject.org/wiki/Changes/SunRPCRemoval)

@opoplawski : I am very sorry but I did not succeed to compile : linking failed :(

And sorry also to create a new issue : this issue it totally related to issue #278

**Comment by maynardGK** [comment]
There are two xdrs, portable XDR is not the one we use, but BSD-xdr.

**Comment by alaingdl** [comment]
@opoplawski sorry Orion, it is not clear for us (Sylvain and me) where/what to modify (in CMakeList.txt or adding a file in CMakeModules/)
(and we don't know what to do with a _pkgconfig_ file !)

**Comment by rexso** [comment]
I suppose #338 fixes this?

**Comment by opoplawski** [comment]
Yes
