### ISSUE TITLE
cmake not finding OpenMP library on OSX

### ISSUE THREAD

**Issue by sflinois** [gnudatalanguage/gdl#307]
The default OSX Clang does not have had built-in support for OpenMP and cmake don't activate the OpenMP support.
A quick solution for now is to use the latest Clang compiler using 'brew install llvm' and to run cmake like so :

cmake .. -DCMAKE_CXX_COMPILER="/usr/local/Cellar/llvm/6.0.0/bin/clang++"  -DCMAKE_C_COMPILER="/usr/local/Cellar/llvm/6.0.0/bin/clang"

Using this compiler, find_package(OpenMp) in the CMakeList.txt will not fail and GDL will support OpenMP

A good idea might be to add a message if find_package(OpenMP) failed that inform the user about this issue ?

I also don't know what is the impact of using the last OSX Clang on GDL.

**Comment by slayoo** [comment]
1. perhaps it's would be worth to suggest it to brew packagers?
2. concerning CMake warning, I would even suggest to require explicit OpenMP=OFF ?

**Comment by sflinois** [comment]
Adding this to CMakeLists.txt should clarify the problem to the user.

```
  else(OPENMP_FOUND)
    if (APPLE)
     message(FATAL_ERROR "Your compiler does not support OpenMP or OpenMP was not found\n"
     "Use -DCMAKE_CXX_COMPILER=PATH and -DCMAKE_C_COMPILER=PATH to specify the compiler path.\n"
     "Use -DOPENMP=OFF to not use it.\n"
     "(suitable Debian/Ubuntu compiler: llvm (brew install llvm))\n")
    endif(APPLE)
  endif(OPENMP_FOUND)
```

When you are on OSX and find_package(OpenMP QUIET) fail, it will output :

```
CMake Error at CMakeLists.txt:329 (message):
  Your compiler does not support OpenMP or OpenMP was not found

  Use -DCMAKE_CXX_COMPILER=PATH and -DCMAKE_C_COMPILER=PATH to specify the
  compiler path.

  Use -DOPENMP=OFF to not use it.

  (suitable Debian/Ubuntu compiler: llvm (brew install llvm))
```

What do you think ?

**Comment by slayoo** [comment]
Thanks! I would't use "if (APPLE)" - generally I suggest forcing users to consciously switch off OpenMP, regardless if they use OSX, Windows or Linux.

Also, "suitable Debian/Ubuntu compiler" should likely be "suitable homebrew compiler package" or alike.

Thanks again!

**Comment by alaingdl** [comment]
@slayoo OpenMP was not used on OSX since years because it's missing (deactivated) in default Clang. Today it is still not used in the Brew package (TBC on the MacPort side). We have to help end-users to activate it.

we make great progress last days on the technical aspects, and I think the logic now is clear : 

* allowing any compiler if externaly setup (CXX=  CC=)
* else if the LLVM + OpenMP are present, using it instead of default Clang
* if LLVM present but explicitly deactivated (-DLLVM=off), using default Clang
* if, at the end, CLang used, adding a clear message at the end than OpenMP is not ON and advice to setup LLVM+OpenMP

A.

**Comment by slayoo** [comment]
Alain,

In macports OpenMP is enabled if using gcc: https://github.com/macports/macports-ports/blob/master/math/gnudatalanguage/Portfile#L173

I don't understand the rationale behind -DLLVM=off 
Moreover, the name is misleading - it's all not about LLVM present/enabled, but simply if one has a new enough version of LLVM ecosystem installed (including clang). And this is in principle not OSX-specific.

Of course, I fully agree that it is essential to change the situation where OSX users miss all the multithreading capabilities of GDL! Thank you for working on it!

S.

**Comment by slayoo** [comment]
For the record, #322 landed in - users using non-openmp compilers are now required to explicitly turn OpenMP off being informed about the performance penalty

**Comment by sflinois** [comment]
I found another problem with OpenMP and Apple Clang
Apple LLVM version 9.1.0 (clang-902.0.39.2) does not support OpenMP

Using Apple Clang, cmake detect OpenMP
but during the link I get the error :

     _.omp_outlined..1369 in datatypes.cpp.o
      ...
  "_omp_set_dynamic", referenced from:
      SysVar::InitSysVar() in initsysvar.cpp.o
  "_omp_set_num_threads", referenced from:
      lib::cpu(EnvT*) in basic_pro.cpp.o
      SysVar::InitSysVar() in initsysvar.cpp.o
      InitOpenMP() in gdl.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/gdl] Error 1
make[1]: *** [src/CMakeFiles/gdl.dir/all] Error 2
make: *** [all] Error 2


Again, compiling with clang version 6.0.1 (tags/RELEASE_601/final) works great

**Comment by slayoo** [comment]
Closing as addressed in https://github.com/gnudatalanguage/gdl/pull/322
