### ISSUE TITLE
[plot] position of plot is incorrect in PS output

### ISSUE THREAD

**Issue by cschreib** [gnudatalanguage/gdl#339]
See following code:

    set_plot, 'ps'
    device, filename='plot_pos.ps', xsize=9, ysize=6
    plot, [0,1], pos=[0.0,0.0,0.5,1.0]
    device, /close

This produces the following plot:
![screenshot from 2018-06-14 17-04-16](https://user-images.githubusercontent.com/2236577/41424091-01fe1e42-6ff5-11e8-9636-b56696cd198a.png)

Note how the plot is centered horizontally, while the ``pos`` keyword was meant to produce a plot aligned to the left. Playing with the last two values of the ``pos`` keyword, I found that these values seem to be interpreted as the width and height of the plot, rather than the position of the left and top edges. Changing the first two values of the ``pos`` keyword to values other than zero produces even weirder results (even changing the size of the plot area).

The code behaves correctly in ``set_plot, 'x'`` mode, but not in ``set_plot, 'ps'``. I am running GDL 0.9.8 freshly cloned from git, and the 0.9.7 in the Ubuntu repository suffers from the same issue. I am viewing the resulting ``.ps`` file with either Okular or gv, both produce the same output.

**Comment by slayoo** [comment]
Thank you for the report!

For the record, here is what is output with current git revision and PSLIB=OFF
![image](https://user-images.githubusercontent.com/89685/41508079-5febf1c4-7247-11e8-8103-65b8e7c52386.png)

With PSLIB=ON same as in the report.

**Comment by GillesDuvert** [comment]
clearly a bug!

**Comment by GillesDuvert** [comment]
closed by #1022 now. Please open a new issue if any problems.
