### ISSUE TITLE
testsuite subfolders (and dropping the testsuite/Makefile.am)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#357]
Something that came out of discussion here: #356

Let's separate the test files into:
- testsuite/helpers (data files, common .pro files, etc)
- testsuite/release (to be executed with "make check")
- testsuite/sandbox (to be executed with "make check-sandbox" or alike)

This would cause less confusion to users and packagers, and also enable us to at last get rid of the Makefile.am file and simply create list of files in CMake by searching the folder contents.

**Comment by alaingdl** [comment]
I do agree that some cleaning in this testsuite is now welcome.

large number of tests can not run on MSwin now (spawn, X11 ...)

but I am not sure it good to have too many subdirs 
(I am ok for sandbox !)

I would also advocate not to enlarge the numbers of files inside the testsuite : e.g.
for me "test_wordexp_null_string.pro" should be include in "test_wordexp.pro",
"test_plot_ranges.pro" and "test_plotting_ranges.pro" will be merged ...

some tests are also unclear, outdated, or did not return useful informations
(test_voigt, test_usersym, ...) and/or are not in the Makefile.am
(but , in future, should be transform in useful tests)

$cd testsuite

$ wc Makefile.am
222

$ ls test_* | wc
278

**Comment by slayoo** [comment]
Closing as duplicate of #765
