### ISSUE TITLE
add proper plplot version check to CMake

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#383]

**Comment by alaingdl** [comment]
it would be great ! it was a nightmare at that time !

but maybe only in the CMakeList.txt file ?
(setting it only to no)

**Comment by GillesDuvert** [comment]
yes and probably a few other oldies too

**Comment by slayoo** [comment]
Thanks! I will create a PR right away, I vote for removing all relevant code - I would argue that it's easier to bring it back looking at a single diff than searching through commented out code that might "degrade" over time.

**Comment by GillesDuvert** [comment]
Would bet that the PLPLOT_SLABELFUNC is always true now. Idem for PLPLOT_HAS_PLCALLBACK .

**Comment by slayoo** [comment]
here it is: https://github.com/gnudatalanguage/gdl/pull/391

**Comment by slayoo** [comment]
nope... PLPLOT_DOES_NOT_HAVE_PLCALLBACK in Ubuntu trusty (Travis machines) :(

**Comment by GillesDuvert** [comment]
Hm. probably worth testing PLPLOT_VERSION_xxxx instead of the poorly hacked Cmake test. Appeared around oct 2014.

**Comment by slayoo** [comment]
It's ready for merging, @alaingdl please confirm if it's OK to drop the code (and not only CMake option), thanks

re PLPLOT_VERSION, I'm renaming this ticket

**Comment by GillesDuvert** [comment]
plplot is part of gdl main build now
