### ISSUE TITLE
drop the DYNDRIVERS=OFF hints from CMake, README?

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#388]
@alaingdl do we have a workflow to reproduce this vintage issue? were there any recent reports?

**Comment by GillesDuvert** [comment]
I remember it was related to plplot not finding the "drivers", as @maynardGK  noted elsewhere . This can be seen as a packaging problem, and to work properly plplot-in-gdl needs to know also where the colortable files are, not only the drivers. To be investigated.
