### ISSUE TITLE
bug(s) and features in GET_SCREEN_SIZE()

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#389]
years ago, I wrongly understood the doc. of GET_SCREEN_SIZE() !
(this bug was found via Travis, with -DX11=off & test_resolve_routine !)

we also have to manage keyword display_name=   when 
a=get_screen_size(disp='localhost:0')
% Cannot connect to X server
(should return 0 0)

Sylvain & me will work on it now

**Comment by slayoo** [comment]
BTW, perhaps we could also try to uninstall all the X packages on the travis MINI builds to actually check if don't depend on anything related to X... added to a TODO list :)

**Comment by slayoo** [comment]
The DISPLAY-not-set case is currently not tested on Travis/codecov, see comments in: https://github.com/gnudatalanguage/gdl/pull/415
