### ISSUE TITLE
Intel icpc compiler 18.0.0 : 1 warning & pb with LD_LIBRARY_PATH (CMake openmp lib issue?)

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#394]
pb1 : linking : just providing path to CXX et CC in non-standard place : cannot start "gdl" without providing the full path to "libiomp5.so" : can be provided by LD_LIBRARY_PATH

pb2 : compilation : we do receive mainy warnings, all related to the line

/home/coulais/GDL/gdl-0.9.8git180621CMake_icpc/src/nullgdl.hpp(55): warning #873: function "NullGDL::operator new(size_t={unsigned long}, char *)" has no corresponding operator delete (to be called if an exception is thrown during initialization of an allocated object)
  	instance = new (NullGDL::buf) NullGDL();

**Comment by slayoo** [comment]
The nullGDL warning is covered here: https://github.com/gnudatalanguage/gdl/issues/63

**Comment by slayoo** [comment]
and pb 1 is either a cmake findopenmp bug or our wrong use of it: https://cmake.org/cmake/help/v3.9/module/FindOpenMP.html

**Comment by slayoo** [comment]
indeed we don't seem to use cmake's OpenMP_CXX_LIBRARIES in CmakeLists.txt
