### ISSUE TITLE
SF -> github migration

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#4]
- [x] svn -> git migration (there is a button for it on github!)
- [ ] recommit things that has been commited to svn after migration: https://github.com/gnudatalanguage/gdl/issues/127
- [ ] disable SF repo
- [x] README.md
- [x] redirect old website -> README.md
- [x] Travis integration (Linux and Debug/Release modes still missing)
- [x] release archive
- [ ] SF forum comments into .pro files with bug-related tests
- [ ] remove old docs folder (archiving the TOC and some examples)
- [x] migrate issues and patches from SF
- [ ] relate SF users to github users (if this is feasible at all, was possible in the github import tool)
- [ ] create list of SF resolved bugs without tests
- [ ] archive forums / mailing lists /... (or create a FAQ/Wiki???)
- [ ] migrate release notes

**Comment by olebole** [comment]
Website: you may also use github pages: https://pages.github.com/ to host a web site

**Comment by slayoo** [comment]
Good point, I was however thinking of replacing the website with a rewritten README.md - expecting this might make it easier to maintain it. Let me first prepare this updated REAMDE.md and then we could decide in the team what to do with the website.

**Comment by GillesDuvert** [comment]
probably not the best place to note it:
IDL has a !help_path inherited from old days. ---> we should add it. (#164)
W. Landsman has made in the old days a 'man.pro' that prints a help in the form of manpages. The help is a file in the subdirectory landsman/help distributed by [idlastro](https://idlastro.gsfc.nasa.gov/).
At lot of lines of help are already there...

**Comment by slayoo** [comment]
all tickets migrated! :)

**Comment by olebole** [comment]
Congratulations! You really did a great job! :+1:

**Comment by GillesDuvert** [comment]
Congrats!

**Comment by slayoo** [comment]
found out that SF supports a "migrated project" category - enabled which resulted in adding a big blue button redirecting to github to every page:

![image](https://user-images.githubusercontent.com/89685/45689255-2f50a600-bb5c-11e8-802a-e211fec53336.png)
