### ISSUE TITLE
cmake 3.0.2

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#401]
Hi

I agreed we removed CentOS 5.11 from the landscape (great system ! RIP :( no systemd !)

I really would like we go back to cmake 3.0.2 for Linux in Cmake. On one 1000+ core cluster where GDL was more than 1/3 of computation last year, I cannot compile :(
I cannot ask to the admins to change or update the system, they did it last year after months of negotiations with Scientists ! Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux 
gcc (Debian 4.9.2-10+deb8u1) 4.9.2
(gcc 5 and 7 available in modules, but no choice for cmake !)

**Comment by slayoo** [comment]
Alain, Gilles described how to workaround it here:
https://github.com/gnudatalanguage/gdl/blob/master/INSTALL.CMake#L87

**Comment by maynardGK** [comment]
@alaingdl can you make a user-mode Cmake to use? Install in /usr/local/ and use that in place of the system's cmake? I've run the bootstrap cmake script a few times, it was quite robust even if it took a long time.

**Comment by alaingdl** [comment]
sorry for the delay.

on this login node (where I have to install GDL for the nodes) I can compile with cmake 3.0.2 & gcc 4.9.2 with the command : 

cmake .. -DPYTHON=off -DCMAKE_CXX_FLAGS="-std=c++11"

and I think this configuration is still frequent. Could we change the CMakeLists.txt accordingly ? 
Thanks !

**Comment by slayoo** [comment]
Alain, yes.
I'll submit a pull request today or max tomorrow.
S.

**Comment by alaingdl** [comment]
not that urgent ! the most urgent issue _today_ is to decide what we will do for next ADASS conf'
http://adass2018.astro.umd.edu/
Deadline is coming !

**Comment by slayoo** [comment]
would this work: https://github.com/gnudatalanguage/gdl/pull/409 ?

**Comment by slayoo** [comment]
closing this issue - let's move the discussion to the PR issue: #409
