### ISSUE TITLE
Travis/OSX builds end with shell_session_update: command not found (with no effect)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#402]
https://github.com/travis-ci/travis-ci/issues/6307

**Comment by slayoo** [comment]
Actually we have two symptoms described here: https://github.com/travis-ci/travis-ci/issues/9454
- /Users/travis/.travis/job_stages: line 475: yarn: command not found
- /Users/travis/.travis/job_stages: line 166: shell_session_update: command not found
(only on OSX, harmless)

**Comment by ThomasWaldmann** [comment]
/Users/travis/.travis/job_stages: line 373: shell_session_update: command not found

Can we get rid of this? If one sees this as the last line of a build that failed to setup correctly, one assumes that this is the problem. But it isn't, in my case, there was another serious problem before that (brew update not working).

**Comment by slayoo** [comment]
As noted in the referenced travis issue, this is no longer happening.
Confirmed in most recent master-branch OSC build log: https://api.travis-ci.org/v3/job/450526278/log.txt
