### ISSUE TITLE
submit plplot windows patches upstream

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#405]

**Comment by slayoo** [comment]
- scripts/patch/drivers_wingcc.c.patch:
  https://github.com/gnudatalanguage/gdl/pull/386/files#diff-e90cd25b4671effb372d1e30e6527aa3

- scripts/patch/drivers_wingdi.c.patch:
  https://github.com/gnudatalanguage/gdl/pull/386/files#diff-6c173dcb62d681a41998efa02b9f8e9e

**Comment by maynardGK** [comment]
The wingcc patch is a one-line substitution of "BringWindowToTop" for "SetForegroundWindow".  The person responsible for that says that it would interfere with the way others have been using it.
The patch, to wingdi.c effects the same change in the wingcc, and it also disables some added features
that GDL doesn't use and that require more libraries to link with, when plplot is built and when gdl links.

 As it is, the artifact installation should run until a plot is needed: all of the supporting shareable images are located in the directory where GDL.EXE resides (install/gdl/bin).  To make a plot, the files from
share/plplot5.13.0 need to be found under "PLPLOT_LIB" and "PLPLOT_HOME"/lib will do for that, also (tested).  The drivers require an ascii file that is located in lib/plplot5.13.0/drivers which should logically be accessible via "PLPLOT_HOME"/drivers but, curiously, it can't do -this- conversion and the user is forced to carry another environment variable, PLPLOT_DRV_DIR.  
   The directories PLPLOT_LIB and PLPLOT_DRV_DIR are specific to the plplot version but in fact don't change as you go, say, from 5.11 to 5.13.  In my usage I simply create a C:\usr\plplot5.13.0 directory with
drivers/ and lib/ subdirectories, and set variable PLPLOT_LIB when an MSYS shell starts up.

  This scheme creates inevitable confusion to the person running GDL for the first time but, ...

**Comment by slayoo** [comment]
Being dependant on custom plplot patches will make it tricky to package GDL (cygwin or alike). Perhaps we could propose an extension to the plplot API so that both types of behaviour (with the old being the default) could be supported?

**Comment by maynardGK** [comment]
Yes I put that back on my wish list  as in "I wish someone would fix that" :) The mods to the drivers do not need to bleed over into another PLPLOT usage; driver dll's need to also be in the directory that gdl.exe resides.
