### ISSUE TITLE
Cmake: make "library not found" result non-fatal

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#412]
The way the appveyor build goes, some things work and some things don't, even though they should.
In my appveyor builds I made CMakeLists.txt such that, when non-essential libraries are -not- found,
that aspect is turned off and a STATUS message is given instead of a FATAL_ERROR. 
A gradual addition of packages will be undertaken - when a package is not to be included, it will be only
a single section requiring modification (the download/unpack) while the cmake command still says "ON" it gets turned OFF when not found.

   So, the question is, is this a feature that should stay or should I remove it before the PR gets pulled?
~~~~cmake
    else(TIFF_FOUND)
        message(STATUS
        "libtiff v4.0.3 or newer is required for TIFF support but was not found.\n"
        "Use -DTIFFDIR=DIR to specify the libtiff directory tree.\n"
        "Use -DTIFF=OFF to not use it.")
        set(TIFF OFF)
    endif(TIFF_FOUND)
endif(TIFF)
~~~~

**Comment by slayoo** [comment]
I vote for keeping the existing behaviour.

Please note that warning messages (i.e. not errors) are hidden from users by packaging tools on Gentoo, macports, etc. This would mean that despite users's instruction to enable something, the compilation could result in this feature disabled - without any warning.

Also, I believe that it could very easly be missed if some third-party package update would break something for Debian, Fedora or this kind of packages - in such cases package rebuilds are triggered by non-maintainers and most likely one would not see any reason to browse through compilation log when no error was generated. This would result in GDL features not being in line with package manifest.

Finally, I would simply try to always adhere to the least-surprise principle - I believe the error-if-requested-and-not-found is the behaviour people assume.

IIUC, the rationale here is to avoid unrelated broken-download-caused failures failing a build on Appveyor, but in principle we do want to catch such errors as they might actually be our fault (url changed, obsoleted package, changed API, etc).

To sum up, please NO :)

**Comment by maynardGK** [comment]
Ok then I'll revert that file when its over.
