### ISSUE TITLE
Dangling Symlinks not detected by file_test

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#420]
```
files=file_search("directory_with_dangling_symlinks","*")
a=file_test(files,/dangling_symlink)
print,where(a)
-1
```
/symlink gives the 'good' symlinks, ignoring the dangling ones (correct behaviour).
/dangling_symlink does not report the dangling symlinks.

**Comment by maynardGK** [comment]
I have one counter-example here on opensuse.  
Excluding the windows' case, which is also sick wrt links.
 ...
It is file_Search which will not return a dangling symlink in its list. 
"// it appears glob is incapable of returning a symlink.!" - not true, it will return
symlinks, but not dangling symlinks.

**Comment by alaingdl** [comment]
I have to finish a revised version of "test_file_test" but : 


; Testing dangling symlink
;
tdirsym1='test_dangling_Symlink_Dir_for_FILE_TEST_1'
tdirsym2='test_dangling_Symlink_Dir_for_FILE_TEST_2'
; cleaning to avoid unwanted message
FILE_DELETE, tdirsym1, tdirsym2, /allow_nonexistent
;
FILE_MKDIR, tdirsym1
FILE_LINK, tdirsym1, tdirsym2
FILE_DELETE, tdirsym1


if FILE_TEST(tdirsym2) then ERRORS_ADD, nb_errors, 'Test Dangling : f2 not removed' 
if FILE_TEST(tdirsym2, /regular) then ERRORS_ADD, nb_errors, 'Test Dangling : f2 still regular'
if FILE_TEST(tdirsym2, /symlink) then ERRORS_ADD, nb_errors, 'Test Dangling : f2 still symlink' 
if ~FILE_TEST(tdirsym2, /dangling) then ERRORS_ADD, nb_errors, 'Test Dangling : f2 NOT see as dangling'

don't behave for 1 & 3 as IDL on my Linux ...

**Comment by maynardGK** [comment]
Here is how that looks on my suse system:
```
 GDL> tdirsym1='test_dangling_Symlink_Dir_for_FILE_TEST_1'                                                                           
GDL> tdirsym2='test_dangling_Symlink_Dir_for_FILE_TEST_2'
GDL> FILE_DELETE, tdirsym1, tdirsym2, /allow_nonexistent
GDL> ;
GDL> FILE_MKDIR, tdirsym1
GDL> FILE_LINK, tdirsym1, tdirsym2
GDL> print,file_test(tdirsym2),FILE_TEST(tdirsym2, /regular),FILE_TEST(tdirsym2, /symlink),FILE_TEST(tdirsym2, /dangling)
           1           0           1           0
GDL> FILE_DELETE, tdirsym1
GDL> print,file_test(tdirsym2),FILE_TEST(tdirsym2, /regular),FILE_TEST(tdirsym2, /symlink),FILE_TEST(tdirsym2, /dangling)
           1           0           1           1
GDL> 

```

**Comment by alaingdl** [comment]
a revised version of TEST_FILE_TEST is now in master #474 

we do have problems in FILE_TEST() for dangling symlink files on Unix family, and also trouble in FILE_SEARCH() to detect such files

**Comment by maynardGK** [comment]
Test_file_test.pro
On my system (linux suse looking at NTFS as well as unix driver) Saturn.jpg has a mode (chmod) of 511.  So:

```
expected_mode=511L
alternative_mode=436L
exist=FILE_TEST(file, get_mode=mode)
if ~exist then begin
   ERRORS_ADD, nb_errors, mess+'should exist !'
endif else begin
   if (mode ne expected_mode) and (mode ne alternative_mode) then $
        ERRORS_ADD, nb_errors, mess+'has a bad mode !'
endelse
```

When the directory is deleted, the symlink is still a symlink, also a dangling symlink. So:

```
if FILE_TEST(tdirsym1) then ERRORS_ADD, nb_errors, 'dir 1 not removed !!' 
;
if ~FILE_TEST(tdirsym2) then ERRORS_ADD, nb_errors, 'dir. 2 (a symlink) was removed' 
if FILE_TEST(tdirsym2, /regular) then ERRORS_ADD, nb_errors, 'dir. 2 is now regular'
if ~FILE_TEST(tdirsym2, /symlink) then ERRORS_ADD, nb_errors, 'dir. 2 is not a symlink' 
if ~FILE_TEST(tdirsym2, /dangling) then ERRORS_ADD, nb_errors, 'dir. 2 NOT seen as dangling'
;
; removing dangling file 2
FILE_DELETE, tdirsym2
;
; we redo all the test because something wrong may happen 
; on dangling symlink ! (not being well done as expected !)
if FILE_TEST(tdirsym2) then ERRORS_ADD, nb_errors, 'dir. 2 not removed (after)' 
```
% TEST_FILE_TEST: =  NO errors encountered during TEST_FILE_TEST tests  =
