### ISSUE TITLE
basic Colon Operator not OK

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#424]
GDL does have : 

GDL> a = [0: 0.5: 0.1]
GDL> a
      0.00000     0.100000     0.200000     0.300000     0.400000     0.500000

but, unfortunately,  as reported here https://sourceforge.net/p/gnudatalanguage/discussion/338691/thread/f5951dec/

we don't have the "basic" : 

GDL> a=[1:4]
% Illegal array creation syntax.
GDL> [1:4]
% Parser syntax error: unexpected token: [

**Comment by alaingdl** [comment]
since Gilles implemented implicit print  & [] operator ...

**Comment by alaingdl** [comment]
I am not sure it is a regression ! 

colon is working for [a] and [a: b :c] but not for [a:b]

**Comment by rexso** [comment]
Interesting. There are indeed missing some tests for the colon operator. Tests for the colon operator has been added to [test_indgen.pro](https://github.com/gnudatalanguage/gdl/blob/master/testsuite/test_indgen.pro) but only when an *increment* value is provided.

For reference, some examples are given [here](https://harrisgeospatial.com/docs/Creating_Arrays.html).

**Comment by GillesDuvert** [comment]
to be closed I presume?
