### ISSUE TITLE
operation '+' with string and !null  (+side effect on !path)

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#428]
a='aa'
b=!null
c=a+b

no message in GDL ...

IDL>  c=a+b
% Variable is undefined: B.
% Execution halted at: $MAIN$          

string should behave as other numerical types with !null

side effect :

!path=!path+!null      give : 
IDL> !path=!path+!null
% Variable is undefined: <UNDEFINED>.

GDL> !path

GDL> !path=!path+!null
GDL> !path
!NULL

**Comment by GillesDuvert** [comment]
closed by #1174
