### ISSUE TITLE
HELP, /path_cache crash gdl in windows build 

### ISSUE THREAD

**Issue by SIAMAR** [gnudatalanguage/gdl#429]
help, /path crashed in the Windows build
we found out that it came from the struc dirent *dp in file.cpp
it's declared in a define win32 but it does not work with this declaration
to fix this error we removed the struct dirent declaration and included dirent.h in if def win32 

Is there any reasons why this struct was not included from dirent.h when in Windows ?
i work with win 10

**Comment by maynardGK** [comment]
In file.cpp there is a top section devoted to making MSVC compiles look like posix; whether it still works
(or ever did completely) hasn't been tested in years.  For all compilers that don't set _MSC_VER,
dirent.h is included:

#ifndef _MSC_VER
\#   include <dirent.h>
#else
\#   include <io.h>
\#   define access _access
 .. etc  Linux/mingw shared definitions ...
endif

Then when the _MSC_VER functions are defined, a "dirent" is defined.  
#ifdef _MSC_VER
\/*
    Implementation of POSIX directory browsing functions and types for Win32.
    Author:  Kevlin Henney (kevlin@acm.org, kevlin@curbralan.com)
    History: Created March 1997. Updated June 2003 and July 2012.
    Rights:  See end of file.
*/

#include <errno.h>
#include <io.h> /* _findfirst and _findnext set errno iff they return -1 */
#include <stdlib.h>

#include <string.h>

struct dirent
{
    char *d_name;
};

Then in the body of file.cpp, all of the WIN32 distinctions are devoted to the Multiwide conversion for going to native file names and such.

in gdlhelp, the condition is mysteriously changed to _WIN32 from _MSC_VER and I suspect it will work correctly once line 45 is changed from 
#ifndef _WIN32
to 
#ifndef _MSC_VER
  Note in edit: this DOES fix it - I re-did the edit and didn't press the update.
GDL> help,/path
!PATH (no cache management --now-- in GDL, 26 directories)
F:/github/gdlgit/src/pro/dicom (10 files)
F:/github/gdlgit/src/pro/envi (3 files)
F:/github/gdlgit/src/pro/obsolete (4 files)
F:/github/gdlgit/src/pro/utilities (7 files)
F:/github/gdlgit/src/pro (137 files)
F:/github/gdlgit/src (1 files)
D:/home/greg/gdlpro/aacmlib/arrays (15 files)
D:/home/greg/gdlpro/aacmlib/cmsvlib/new (17 files)
D:/home/greg/gdlpro/aacmlib/cmsvlib (17 files)
D:/home/greg/gdlpro/aacmlib (132 files)
D:/home/greg/gdlpro/astronv61/fits/new (1 files)
D:/home/greg/gdlpro/astronv61/fits (21 files)
D:/home/greg/gdlpro/astronv61/fits_bintable (28 files)
D:/home/greg/gdlpro/astronv61/fits_table (18 files)
D:/home/greg/gdlpro/astronv61/obsolete (18 files)
D:/home/greg/gdlpro/astronv61/pro/debug (6 files)
D:/home/greg/gdlpro/astronv61/pro (391 files)
D:/home/greg/gdlpro/doc (5 files)
D:/home/greg/gdlpro/misc (7 files)
D:/home/greg/gdlpro/new (19 files)
D:/home/greg/gdlpro/objects (2 files)
D:/home/greg/gdlpro/testing (9 files)
D:/home/greg/gdlpro (1 files)
F:/github/gdlgit/testsuite/benchmark (13 files)
F:/github/gdlgit/testsuite/file_etc (6 files)
F:/github/gdlgit/testsuite (301 files)
GDL> help,/path,output=pathc
GDL> help,pathc
PATHC           STRING    = Array[27]
GDL> for k=0,26 do print,pathc[k]
!PATH (no cache management --now-- in GDL, 26 directories)

I also spot the lack of a "struct dirent" in the MSC_VER code block; this should probably be copied more
faithfully from file.cpp (its source).

I think the help_path_cached section was composed without access to a windows' machine of any sort, and so what "looked right" didn't work.

**Comment by alaingdl** [comment]
@maynardGK   my students know now how to compile GDL on MSwin (I am pressing them to deliver the how to or a script) and we begin to play with some codes ...

one serious problem saw today : readline seems to broken some chars (#, [, ], ...)
should we turn it off ? il editline or wineditline better ?

**Comment by maynardGK** [comment]
@alaingdl
If you are compiling with mingw-w64 compiler you should stick with readline.  If using MSVC/Studio, I think the wineditline may be the way to go,  pdcurses was the earlier alternative.
  Download the latest artifact build from #408 , to get a comparison. This artifact is only 32 MB and has only the executables in gdl/bin but there is an earlier one, about 200 MB, that includes the mingw/ and win32libs/ directories that has the dependency download.
  The behavior from clicking on bin/gdl is to create no shell behind the program - I don't use it much like that, but it seems to be ok for what I do.  More often I invoke GDL from the MSYS bash login shell directly from a desktop shortcut.   If GDL is invoked from the CMD.exe shell there may be other problems with the keyboard.
  Once you get beyond version 5 of readline then a shuffling of the provided routines occurs.  I was compensating with the use of -lgnurx in the link line, lately I've posted systre as the library to get in place of PCRE (see #408 ).  pcre is however required for graphicsMagick so we can't get rid of it altogether.

Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\cmd>set MSYSTEM=MINGW32

D:\cmd>C:\msys64\usr\bin\bash.exe -login -i
C:/msys64/home/greg/.bashrc invoked with OLDPWD=/d/cmd

greg@Homerw7 MINGW32 ~
$ echo $PATH
/mingw32/bin:/opt32/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows:/c/Windows/system32:/c/Window

greg@Homerw7 MINGW32 ~
$ /f/github/bld556/install/gdl/bin/gdl
bash: /f/github/bld556/install/gdl/bin/gdl: No such file or directory

greg@Homerw7 MINGW32 ~
$ /f/github/bld556/install/gdl/bin/gdl.exe
bash: /f/github/bld556/install/gdl/bin/gdl.exe: No such file or directory

greg@Homerw7 MINGW32 ~
$ ls /f/github
alias.sh    cmake.out                gdl-olebole/         modified-mingw-w64/  src/
amend/      consolez/                gnugdlgit/           msys2.ls             str.cpp
bld556/     Distinguishing-MSYS.txt  gtk-mingw-code/      msys2-packages/      update.sh
bld556.ls   fltk-1.4-test/           helplog.ls           patches/             vlc/
bld556.zip  gdlgit/                  idlastro/            plplot-HB/           vmsbackup/
bld564/     gdlgit-err.txt           insert.h             products/            windw2/
bld564.zip  gdlgit-saves/            LandTrendr/          pslib-0.4.5/         wrtouchsrc.pro
bsd-xdr/    gdlgvj/                  mingw-w64-packages/  readline5/           wrtouchts.pro

greg@Homerw7 MINGW32 ~
$ export PATH=/f/github/bld564/install/gdl/bin:$PATH

greg@Homerw7 MINGW32 ~
$ /f/github/bld564/install/gdl/bin/gdl.exe

  GDL - GNU Data Language, Version 0.9.8 git

- For basic information type HELP,/INFO
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

% Compiled module: PATH_SEP.
GDL> pwd
C:/msys64/home/greg

**Comment by SIAMAR** [comment]
#ifndef _MSC_VER solution at line 45 worked fine
