### ISSUE TITLE
normalization issue in CORRELATE()

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#433]
I also have poor benchmarks ... (TBC)

x=findgen(10)
y=0.5*x+randomn(1, 10)
A = TRANSPOSE([[X],[Y]])

GDL> PRINT, CORRELATE(A)
     0.111111    0.0974515
    0.0974515     0.111111
IDL> PRINT, CORRELATE(A)      
      1.00000     0.877064
     0.877064      1.00000

**Comment by alaingdl** [comment]
Please notice the complex computation of CORRELATE() is -still- no ready

Help welcome !

**Comment by alaingdl** [comment]
in fact, the performance issue is much stronger than expected !
on my laptop, i7 4 cores : 

a=randomu(1, 1000, 1000)

GDL> tic & res=CORRELATE(a) & toc
% Time elapsed :        15.322006 seconds.

IDL> tic & res=CORRELATE(a) & toc
% Time elapsed: 0.40128899 seconds.

**Comment by GillesDuvert** [comment]
with IDL's procedure correlate.pro, GDL time plunges to 0.6 s
The problem is within the GDL procedure.

**Comment by alaingdl** [comment]
With my intern Max, we try to improve that (and also allowing Complex inputs)
