### ISSUE TITLE
Unexpected behaviour of PRINTF

### ISSUE THREAD

**Issue by tolgahank** [gnudatalanguage/gdl#437]
**test01.pro**:
```
PRO test01

openw,lun,'test01.out',/GET_LUN
printf,lun,1,FORMAT='(I8)'
FREE_LUN,lun

END
```

GDL> test01
**test01.out**:
`_______1` (i.e., right aligned number as expected)

**test02.pro**:
```
PRO test02

openw,lun,'test02.out',/GET_LUN
printf,lun,'dummytext'
printf,lun,1,FORMAT='(I8)'
FREE_LUN,lun

END
```

GDL> test02
**test02.out**:
`dummytext`
`1_______` (i.e., left aligned number!)

Note:
GDL> print,!gdl 
{ 0.9.8 May 22 2018  1526936400}
GDL> print,!version
{ x86_64 linux unix linux 8.2 May 22 2018      64      64}

**Comment by alaingdl** [comment]
we are unable to reproduce this problem (various OS : linux & OSX; various versions of GDL)
(Is it difficult for you to move to current git version ?)

Could you give more information(s) ? e.g. :

GDL> !gdl
{ 0.9.8 svn Jun  5 2018  1528149600}
GDL> !version
{ x86_64 linux unix linux 8.2 Jun  5 2018      64      64}

**Comment by tolgahank** [comment]
Sorry, my simple example is not reproducing the problem indeed, as you said. I've updated my question above and tested. I think the issue is more weird than I think. Could you please check it again?

**Comment by alaingdl** [comment]
I can reproduced it with the YGZ of 0.9.8

this is corrected in the current GIT version (since beginning of April)

**Comment by slayoo** [comment]
btw, do we have it covered with a test?

**Comment by alaingdl** [comment]
yes, we should have it already, in the test_formats.pro

but we can have it because it is very simple and direct
