### ISSUE TITLE
implicit print & structures

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#438]
implicit print is a great functionality, but the outputs are not as expected for structures. E.g. :

GDL> !cpu
{           0           0           8           8                100000                     0}

IDL> !cpu
{
    "HW_VECTOR": 0,
    "VECTOR_ENABLE": 0,
    "HW_NCPU": 8,
    "TPOOL_NTHREADS": 8,
    "TPOOL_MIN_ELTS": 100000,
    "TPOOL_MAX_ELTS": 0
}

**Comment by GillesDuvert** [comment]
Indeed, will be OK only when GDL knows about JSON_SERIALIZE.
