### ISSUE TITLE
bug in POLYFILLV()

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#439]
POLYFILLV( [2,4,4], [4,4,2], 6, 6 )

return 15 instead of         15          20          21

**Comment by slayoo** [comment]
Here is a test routine written by Reto and uploaded to SF some time ago (https://sourceforge.net/p/gnudatalanguage/users-contributions/11/)
[test_polyfillv.pro.gz](https://github.com/gnudatalanguage/gdl/files/2259215/test_polyfillv.pro.gz)

**Comment by alaingdl** [comment]
at the end we catch the original edition of the book at ENS' library and Sylvain solved it.

I have to put it in the depository ASAP but the tests are not finished on my side, sorry
