### ISSUE TITLE
APPLEMAN fractal does not display in black-red palette by default

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#44]
Running freshly installed 0.9.8 (from Debian package), the graphical output of APPLEMAN is displayed in white-and-black palette. I'm pretty sure it was not the case previously - as depicted in various GDL screenshots.

```
GDL> appleman
% Compiled module: APPLEMAN.
% Compiled module: LOADCT.
% LOADCT: Loading table BOW SPECIAL
```

![image](https://user-images.githubusercontent.com/89685/38456224-e45877ce-3a8a-11e8-9ccb-69034a87326c.png)

**Comment by GillesDuvert** [comment]
IDL and GDL have the same color behaviour now: grey
To get the reddish color, have device,decomp=0 first.

**Comment by slayoo** [comment]
should we add it to APPLEMAN?
After all, it's just a GDL demo/logo
(also, resising the window would be needed to preserve the original behaviour)
See e.g.: https://hesperia.gsfc.nasa.gov/colinux/ :)

**Comment by GillesDuvert** [comment]
IDL window resizing erases the plot.
plplot permits to keep the colors, at the expense of a terribly slow X11 graphics interface. It was chosen to speedup the plots. It can be done with wxWidgets, see "atv.pro"

**Comment by slayoo** [comment]
I was just thinking of adding, before involation of TV in APPLEMAN, something along the lines of:
```
device, decomp=0
window, xsize=xS, ysize=yS
```

as there already is:
```
if ~keyword_set(xS) then xS = 640 
if ~keyword_set(yS) then yS = 512
```

Well... this is genuinely minor :)
