### ISSUE TITLE
Bug in POINT_LUN with negative LUN, possible fix included

### ISSUE THREAD

**Issue by pstrub** [gnudatalanguage/gdl#441]
POINT_LUN, lun, position

 is used to set or get the current position within an open file. When a negative number is used as a lun, the procedure returns the current position inside the file, and should use a 64 bit variable when necessary (the IDL documentation on this reads: "The returned type will be a longword signed integer if the position is small enough to fit, and a 64-bit longword integer otherwise.") 

GDL's version of POINT_LUN however always returns a 32 bit long as a position. This makes it impossible to correctly obtain the current position beyond 2GiByte file size, the returned position gets truncated to 32 bits. 

I found a fix that resolves the issue for me, and to my knowledge should not have any side-effects. As I'm not familiar with the way the development of GDL is organised, nor with the prerequisites of contributing/submitting changes to the repository, I post my suggestion here.

In basic_pro_jmg.cpp, version 5a970cd  on Apr 16, lines 66 and 67 read:

``` cpp
    *retPos = new DLongGDL( actUnit.Tell());
    return;
```
These lines invariably return the position inside the file as a 32-bit integer, truncationg the 64 bit integer returned by actUnit.Tell().
I therefore replaced it with the following code:

``` cpp
    DLong64 pos = actUnit.Tell();
    if (pos > std::numeric_limits<DLong>::max()) {
      *retPos = new DLong64GDL( pos);
    } else {
      *retPos = new DLongGDL( pos);
    }
    return;
```

for numeric_limits to work, make sure to add `#include <limits>` to the top of the file.

Edit: Setting the file position beyond 2 GiByte works fine with the current version of POINT_LUN.

Please let me know if you need any further information.

**Comment by alaingdl** [comment]
Thanks for the bug report and the suggested patch ! (see PR #442)

You are very welcome to participate. I am not sure myself to fully understand the whole frame work
but first may be you have to go here https://github.com/orgs/gnudatalanguage/teams/gdlteam/members
After being registered as a member, you can make pull requests.

best regards
A.

**Comment by slayoo** [comment]
Anyone can make a pull request, but please do join the team so you can get instant notifications on new GDL-related discussions.

**Comment by pstrub** [comment]
Thanks for the invitation! Not sure though how much I'm going to contribute though, but I'll do what I can do! 

On another note, shouldn't we reopen the issue, as the pull request has been cancelled due to a regression?
