### ISSUE TITLE
logical operators (GT, LT, EQ, OR, AND) do not accept COMPLEX (and DCOMPLEX)

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#447]
GDL> a=complex(10) & b=WHERE(a GT 1)
% Cannot apply operation to datatype COMPLEX.

**Comment by alaingdl** [comment]
sorry for the first initial wrong title !

a=COMPLEX(10)
all the following commands are rejected by GDL

a GT 0.1
a LT 0.1
a EQ 0.1
a EQ 10    
a OR 10 
a AND 10

The only exception I noticed up to now : XOR
IDL> a XOR 10
% Operation illegal with complex type.
% Execution halted at: $MAIN$

**Comment by GillesDuvert** [comment]
closed by #1326
