### ISSUE TITLE
triggering of plvpor: in PLOT (improvment request)

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#455]
I consider it is not urgent but it would be good to avoid messages from plplot !

Some time ago I received a test case containing unusual ranges for plotting. I reduced the case to the following example :

GDL> wdelete
GDL> !P.REGION=[0.0,0.2,1,0.80]
GDL> y =[0,1] & plot, y,y, charsize=7

*** PLPLOT ERROR, ABORTING OPERATION ***
plvpor: Invalid limits, aborting operation

and the plot covers the whole window (in X11) (margins are lost ?!)

When the !p.region is not provided, PLOT resists much better to big charsize !
and messages appear

GDL> wdelete
GDL> !P.region=0   ; reset
GDL> y =[0,1] & plot, y,y, charsize=15
% XMARGIN to large (adjusted).
% YMARGIN to large (adjusted).

It would be great to have something similar in the first case and avoid wrong range
--even using such big char is not a good idea !--

**Comment by GillesDuvert** [comment]
should be OK now (since #1275)
