### ISSUE TITLE
Add support for creating hdf5 files 

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#46]
(https://sourceforge.net/p/gnudatalanguage/feature-requests/142/)

As reported by @opoplawski on SF.net:

The hdf5 functions appear to only implement reading hdf5 files.

Further comment by @maynardGK on 2015-06-06:

```
HDF5 interface is very immature but that provided in IDL has 125
call points! This is a perfect candidate to get LINKIMAGE operational
so that the functionality can be added without bloating the program (when run without hdf5).
```

**Comment by slayoo** [comment]
@ogressel could you please comment on this one given the recent updates? Thanks!

**Comment by ogressel** [comment]
I had a first glance at important missing functionality yesterday. High-level read/write (H5_...) and low-level writes (H5A_WRITE/H5D_WRITE) are the most obvious. There are also many trivial wrappers that could be created in a semi-automated way through a clever script.

**Comment by slayoo** [comment]
thank you @ogressel

**Comment by slayoo** [comment]
Well, given all the progress in #1223, let's close this issue and move any discussion to the PR.
Thank you @ogressel !!!
