### ISSUE TITLE
remove save.pro and restore.pro from the repo?

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#462]

**Comment by alaingdl** [comment]
I moved them two (+ file_delete) in pro/obsolete, jsut in case we have a regression in the future or would to test within [CMSVlib](https://cow.physics.wisc.edu/~craigm/idl/cmsave.html) (thanks to Craig !)

we still have to remove few comments around !

**Comment by slayoo** [comment]
Fixed by #466
