### ISSUE TITLE
Code regression issue when loading multiple colour tables

### ISSUE THREAD

**Issue by dschnitzeler** [gnudatalanguage/gdl#471]
Hi,

After updating to the latest version of GDL it is no longer possible to load two colour tables at the same time. For example:

PRO TEST
loadct,0,ncolors=100,bottom=0
loadct,39,ncolors=100,bottom=100

erase
plot,[0,10],[0,10],/nodata
polyfill,[4,6,6,4,4],[2,2,3,3,2],color=50
polyfill,[4,6,6,4,4],[2,2,3,3,2]+2,color=150
END

The bottom rectangle should be filled with a shade of grey, but instead it uses a rainbow colour. If I swap the order of the two calls to loadct, then the bottom rectangle is in grey but the top rectangle is now shown in grey when it should use a rainbow colour. This suggests that the keywords ',ncolors=N1,bottom=N2' that are passed to loadct are not being used correctly. I didn't get much further with understanding where in loadct this problem arises. I'm using GDL v.0.9.7_3, installed (including all dependencies) on MacOS using Macports. 

Regards,

  Dominic

**Comment by alaingdl** [comment]
Hi

maybe something is missing in your example (device,/dec ??), 
because I do have the same output (red & grey red)
in IDL & GDL (git version of today)

A.
PS: could you please print !GDL ?! thanks !
(I tested older versions in 0.9.7, all giving the same outputs)

**Comment by dschnitzeler** [comment]
Hi,

I use device,decomposed=0: in the past this would have shown the bottom rectangle in grey, and the top rectangle in red. Instead I get the following colours:
![screen shot 2018-09-25 at 18 36 07](https://user-images.githubusercontent.com/32900311/46028845-ebc4e180-c0f1-11e8-8e5a-73bf664edb05.png)
With device,decomposed=1 I get dark red colours for both rectangles.

!GDL contains the following: { 0.9.7 Aug 25 2018  1535148000}

Dominic

**Comment by alaingdl** [comment]
Ok, thanks ! the bug appeared between  gdl-0.9.6cvs160303 and gdl-0.9.6cvs160307

diff gdl-0.9.6cvs160307CMake/src/pro/loadct.pro gdl-0.9.6cvs160303CMake/src/pro/loadct.pro
132,134c132
```
< ; loadct_gdlinternal has already changed all colormaps. Calling TVLCT will
< ; only double the load (very slow on X11).
< ;TVLCT, r_curr, g_curr, b_curr

> TVLCT, r_curr, g_curr, b_curr
```

**Comment by dschnitzeler** [comment]
Thanks for the fix! Also, thanks for getting back to me so quickly.

**Comment by slayoo** [comment]
@alaingdl just to confirm - is the bug still in the repo?

**Comment by alaingdl** [comment]
unfortunately yes ! for several reasons : 
- no time to finish tests (it is inside an huge batch of changes ... side effect ?)
- it is mention that it will slow down remote display : it is an important issue I need to check
- how to put it in the testsuite ? (to anticipate any related change)

**Comment by GillesDuvert** [comment]
Calling twice tvlct will indeed slow the remote display (because of less-than-optimum plplot color handling), unless tvlct does not actually send color to a remote display when option /get is present. To be checked.

**Comment by alaingdl** [comment]
because of a discussion with a colleague today, I discovered this code
https://www.davidpace.com/contour-plotting-routine-for-idl/

```
$ wget http://www.davidpace.com/wp-content/uploads/2015/11/conmake.txt
$ gdl
GDL> .r  conmake.txt
GDL> conmake, dist(123,111), 20
% LOADCT: Loading table Rainbow + white
```

with the current *loadct.pro* code, the color map is broken. With the old version (line TVLCT, r_curr, g_curr, b_curr) the output is perfect !

**Comment by GillesDuvert** [comment]
actually the comment in loadct is wrong, as tvlct,/get does not change the X11 colortable. I'll patch that asap.

**Comment by GillesDuvert** [comment]
change done (directly on GH)

**Comment by GillesDuvert** [comment]
we close, OK?

**Comment by alaingdl** [comment]
Please wait a few I commit a test, just to avoid any future regression !
(It seems that I have a way to check it, I "just" need to clean my draft)
