### ISSUE TITLE
symsize not working properly (code regression issue)

### ISSUE THREAD

**Issue by dschnitzeler** [gnudatalanguage/gdl#472]
Hi again,

I think the keyword 'symsize' is not working properly. The plot produced by this example

PRO TEST
    device, decompose=0
    loadct,39,/silent
    plot,[0,2],[0,2],/nodata,/iso
    vsym,20
    oplot,[1,1],[1,1],psym=8,symsize=1,thick=1,color=80
    oplot,[1,1],[1,1],psym=8,symsize=3,thick=2,color=245
END

should show two nested circles, blue (inner circle) and red (outer circle). However, the red circle lies on top of the blue circle, which means that symsize is not working properly. I checked that the problem is not due to vsym in combination with psym=8. I'm using GDL v. 0.9.7_3 installed using Macports. !GDL contains the following: { 0.9.7 Aug 25 2018 1535148000}.

Regards,

  Dominic

**Comment by alaingdl** [comment]
thanks (again missing : device, dec=0 )

I was able to reproduce your bug, it has been corrected in current version (0.9.8 vanilla & git). I will try to do it ASAP but busy.

good and bad news : I forgot to push in Git a "test_plot_usersym.pro" I already written

I also have to check why the output of vsym.pro (provided by AstroLib) is different in IDL & GDL

**Comment by dschnitzeler** [comment]
Could you tell me how I can update the code to fix this? Then I don't have to download new code.

Dominic

**Comment by alaingdl** [comment]
I don't know ! for me you have to move to the git version ! Compilation is straightforward on OSX 10.12, 10.13

A simple way to compile it is to use the script https://raw.githubusercontent.com/gnudatalanguage/gdl/master/scripts/minimum_script4gdl.sh

```
wget https://raw.githubusercontent.com/gnudatalanguage/gdl/master/scripts/minimum_script4gdl.sh
chmod 755 minimum_script4gdl.sh
./minimum_script4gdl.sh     (do have plplot)
./minimum_script4gdl.sh 6    (do have git gdl)
```

(if you need pref', don't forgot that, by default, on OSX, clang don't use openmp ...)

**Comment by alaingdl** [comment]
FYI, I just put in #474 the file "test_plot_usersym.pro"

**Comment by GillesDuvert** [comment]
> FYI, I just put in #474 the file "test_plot_usersym.pro"

... that show all this works beautifully.
