### ISSUE TITLE
assert warning from test_delvarrnew.pro ((i<sz), function operator[], file datalistt.hpp, line 124)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#481]
on current master:

```
"test_delvarrnew.pro" start time: Oct 13 12:00 GMT

Output:

----------------------------------------------------------

% Compiled module: TEST_DELVARRNEW.

Assertion failed: (i<sz), function operator[], file /Users/travis/build/gnudatalanguage/gdl/src/datalistt.hpp, line 124.
```

see here: https://api.travis-ci.org/v3/job/440977990/log.txt

**Comment by slayoo** [comment]
and why the test still passes???

**Comment by maynardGK** [comment]
test_delvarrnew spawns src/gdl in order to use DELVAR and .RNEW from $MAIN.
  The calling routine simply looks in stdout for a few lines of chatter that don't end in 'FAILURE'
