### ISSUE TITLE
double call to ROUTINE_INFO() crash ...

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#492]
```
GDL> a=routine_info(/sou)
GDL> a=routine_info(/sou)
```
gives a segfault ...

(tested on various versions on Linux)

**Comment by maynardGK** [comment]
It looks like routine_info needs a non-zero number of procedures when called like this.
  If there are none, it will in any case call 
```
stru = new DStructGDL( stru_desc, dimension(  0));
```
and return the result (probably hosed at this point).
