### ISSUE TITLE
add keyword L64 to SORT() 

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#51]
(https://sourceforge.net/p/gnudatalanguage/users-contributions/13/)

As reported by @alaingdl on SF.net:

we need to add this keyword for compatibility
and also check whether the change Long/Long64
is well done now in GDL

A. + René + Ors @ miri meeting ;)

**Comment by alaingdl** [comment]
SORT(/L64) & WHERE( /L64)

need machines with very large memory to test it !

**Comment by slayoo** [comment]
WHERE has been addressed here: https://github.com/gnudatalanguage/gdl/commit/2ea29e9d7a92d4e3cd0ee5ef12ada2b092ec8f63#diff-bfbb2627b2f82c76121edae6b379ac32

Renaming so that only SORT is mentioned

**Comment by GillesDuvert** [comment]
PR #542 does the job. Enjoy.
