### ISSUE TITLE
create Release Notes for v0.9.9

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#517]
@gnudatalanguage/gdlteam please post here any remainders what should be included and highlighted in release notes for 0.9.9 (pre-released yesterday). Thanks

**Comment by maynardGK** [comment]
Some new features of help:
   (keyword) Output=<variable> is implemented in many more places.
   (keyword) names = <reg expression> used with other output forms to restrict the matches found.
   HELP,/HEAP enumerates object and pointer heap.
        more detail if FULL is specified, listing the first 15 items to be found on the heap.
   HELP,/COMMON will list all common blocks anywhere in program
   OBJECT, METHODS keywords for use with objects.
Other behavior changes:
 - For undefined variables, no output is generated unless /FULL keyword is also present.
 - the /STRUCT keyword, which is in effect if a structure is the sole parameter, will 
  invoke a recursive description of any sub-structures.  The one-line description
  will always be present, before the detailed structure listing.

**Comment by maynardGK** [comment]
Many more of the properties of HASH and LIST are now implemented with this release.

**Comment by GillesDuvert** [comment]
@slayoo , by release notes, you mean NEWS?

**Comment by GillesDuvert** [comment]
a few points:
performance:
WHERE() function speedup 
RANDOM functions (RANDOMUn RANDOMN etc) rewritten using dSFMT, both simd-accelerated and parallelized.
language:
Auto-print feature (experimental)
implicit array generation, ex: array=[0.1:3.5:0.33]
better TIFF support
GEOTIFF support
LINFIT
DILATE
ERODE
SOBEL
PREWITT
ROBERTS
FILE_LINES FILE_LINK, FILE_COPY, FILE_MOVE now in C++

**Comment by alaingdl** [comment]
TOTAL improved to preserve types
FIX & ROUND improved

@slayoo please remember we have to change in __CMakeLists.txt__ the line 
```
set(VERSION "0.9.8 git") into set(VERSION "0.9.9")
```
then increment again this version number

**Comment by slayoo** [comment]
C++11 requirement

**Comment by slayoo** [comment]
@GillesDuvert I meant both the NEWS file and the description field that github offers. 

I'll update these, change the CMake version number and look around for other release-cleanups next week (most likely not before Friday).

**Comment by GillesDuvert** [comment]
MAX and MIN now with /ABSOLUTE.

**Comment by slayoo** [comment]
Version number changed: https://github.com/gnudatalanguage/gdl/commit/649f3e7c684f13c331a1dbd2a86ae7c01c3e6689

Ticket added to add git suffix after release: https://github.com/gnudatalanguage/gdl/issues/525

**Comment by slayoo** [comment]
Here is the NEWS file update: https://github.com/gnudatalanguage/gdl/commit/72b6434364a853252c70d18858456f715f2bf5e0

Comments welcome!
