### ISSUE TITLE
bugs in triangulate and trigrid

### ISSUE THREAD

**Issue by danehkar** [gnudatalanguage/gdl#536]
I found that [`triangulate`](https://www.harrisgeospatial.com/docs/TRIANGULATE.html) and [`trigrid`](https://www.harrisgeospatial.com/docs/TRIGRID.html) in GDL have some bugs, and not work correctly in [_interp2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp2d.pro) in the older version of my function [`gamma_hb_4861.pro`](https://github.com/equib/proEQUIB/blob/45fe736f1bae247ede2cfd70bf208bb66b4de21a/pro/gamma_hb_4861.pro) in my repository [equib/proEQUIB](https://github.com/equib/proEQUIB):

lines 77:79 in [_interp2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp2d.pro):

    triangulate, xx, yy, tr
    if n_elements(quintic) eq 0 then quintic = 0  ; Make sure quintic is define
    zz = trigrid(xx, yy, A, tr, gs, quintic=quintic)

I had to replace [_interp2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp2d.pro) with [_interp_2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp_2d.pro). 

You can reproduce this bug by cloning the older version `45fe736f1b`:

    git clone --recursive https://github.com/equib/proEQUIB.git
    cd proEQUIB
    git checkout 45fe736f1b

And set `.gdl_startup`:

    !PATH=!PATH + ':/home/proEQUIB/proEQUIB/'
    !PATH=!PATH + ':/home/proEQUIB/proEQUIB/pro/'
    !PATH=!PATH + ':/home/proEQUIB/TEST/proEQUIB/externals/atomneb/pro/'
    !PATH=!PATH + ':/home/proEQUIB/TEST/proEQUIB/externals/astron/pro/'
    !PATH=!PATH + ':/home/proEQUIB/proEQUIB/externals/misc/'

Then, make this test file `test.pro` in `proEQUIB` folder:

    base_dir = '.'
    data_dir = ['externals', 'atomneb', 'atomic-data', 'chianti70']
    data_rc_dir = ['externals', 'atomneb', 'atomic-data-rc']
    Atom_Elj_file = filepath('AtomElj.fits', root_dir=base_dir, subdir=data_dir )
    Atom_Omij_file = filepath('AtomOmij.fits', root_dir=base_dir, subdir=data_dir )
    Atom_Aij_file = filepath('AtomAij.fits', root_dir=base_dir, subdir=data_dir )
    Atom_RC_SH95_file= filepath('rc_SH95.fits', root_dir=base_dir, subdir=data_rc_dir )
    
    atom='h'
    ion='ii' ; H I Rec
    hi_rc_data=atomneb_read_aeff_sh95(Atom_RC_SH95_file, atom, ion)
   
    atom='o'
    ion='iii' ; [O III]
    o_iii_elj=atomneb_read_elj(Atom_Elj_file, atom, ion, level_num=5) ; read Energy Levels (Ej)
    o_iii_omij=atomneb_read_omij(Atom_Omij_file, atom, ion) ; read Collision Strengths (Omegaij)
    o_iii_aij=atomneb_read_aij(Atom_Aij_file, atom, ion) ; read Transition Probabilities (Aij)
    
    levels5007='3,4/'
    temperature=double(10000.0)
    density=double(5000.0)
    iobs5007=double(1200.0)
    Abb5007=double(0.0)
    
    Abb5007=calc_abundance(temperature=temperature, density=density, $
                           line_flux=iobs5007, atomic_levels=levels5007,$
                           elj_data=o_iii_elj, omij_data=o_iii_omij, $
                           aij_data=o_iii_aij, h_i_aeff_data=hi_rc_data[0].Aeff)
    
    print, 'N(O^2+)/N(H+):', Abb5007
  
    exit

By running IDL:

    idl test.pro

It gives:

    % IDL Version 8.3 (linux x86_64 m64). (c) 2013, Exelis Visual Information Solutions, Inc.
    % Licensed for use by: Harvard University (MAIN)
    % Compiled module: ATOMNEB_READ_AEFF_SH95.
    % Compiled module: ATOMNEB_READ_AEFF_SH95_LIST.
    % Compiled module: FTAB_EXT.
    % Compiled module: FITS_OPEN.
    % Compiled module: SXPAR.
    % Compiled module: GETTOK.
    % Compiled module: SXDELPAR.
    % Compiled module: VALID_NUM.
    % Compiled module: FITS_READ.
    % Compiled module: TAG_EXIST.
    % Compiled module: FITS_CLOSE.
    % Compiled module: TBINFO.
    % Compiled module: TBGET.
    % Compiled module: ATOMNEB_READ_ELJ.
    % Compiled module: ATOMNEB_READ_ELJ_LIST.
    % Compiled module: ATOMNEB_READ_OMIJ.
    % Compiled module: ATOMNEB_READ_OMIJ_LIST.
    % Compiled module: ATOMNEB_READ_AIJ.
    % Compiled module: ATOMNEB_READ_AIJ_LIST.
    % Compiled module: CALC_ABUNDANCE.
    % Compiled module: GAMMA_HB_4861.
    % Compiled module: FIND_AEFF_SH95_COLUMN.
    % Compiled module: NINT.
    % Compiled module: _INTERP2D.
    % Compiled module: CALC_EMISSIVITY.
    % Compiled module: _STRNUMBER.
    % Compiled module: CALC_POPULATIONS.
    N(O^2+)/N(H+):   0.00041108740

But, by running GDL:

    gdl test.pro 

It gives:

    GDL - GNU Data Language, Version 0.9.8 git
    
    - For basic information type HELP,/INFO
    - Please report bugs, feature or help requests and patches at:
      https://github.com/gnudatalanguage/gdl
    
    %** Personal settings are loaded and active **
    % Compiled module: FILEPATH.
    % Compiled module: PATH_SEP.
    % Compiled module: ATOMNEB_READ_AEFF_SH95.
    % Compiled module: ATOMNEB_READ_AEFF_SH95_LIST.
    % Compiled module: FTAB_EXT.
    % Compiled module: FITS_OPEN.
    % Compiled module: SXPAR.
    % Compiled module: GETTOK.
    % Compiled module: SXDELPAR.
    % Compiled module: VALID_NUM.
    % Compiled module: FITS_READ.
    % Compiled module: TAG_EXIST.
    % Compiled module: FITS_CLOSE.
    % Compiled module: TBINFO.
    % Compiled module: TBGET.
    % Compiled module: STRMATCH.
    % Compiled module: ATOMNEB_READ_ELJ.
    % Compiled module: ATOMNEB_READ_ELJ_LIST.
    % Compiled module: ATOMNEB_READ_OMIJ.
    % Compiled module: ATOMNEB_READ_OMIJ_LIST.
    % Compiled module: ATOMNEB_READ_AIJ.
    % Compiled module: ATOMNEB_READ_AIJ_LIST.
    % Compiled module: CALC_ABUNDANCE.
    % Compiled module: GAMMA_HB_4861.
    % Compiled module: FIND_AEFF_SH95_COLUMN.
    % Compiled module: NINT.
    % Compiled module: _INTERP2D.
    % Warning: Keyword parameter QUINTIC not supported in call to: TRIGRID. Ignored.
    % Compiled module: CALC_EMISSIVITY.
    % Compiled module: _STRNUMBER.
    % Compiled module: CALC_POPULATIONS.
    N(O^2+)/N(H+):            -NaN

lines 77 in [_interp2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp2d.pro):

    triangulate, xx, yy, tr

The value of `tr` calculated by GDL is not similar to `tr` calculated by IDL.

lines 79 in [_interp2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp2d.pro):

    zz = trigrid(xx, yy, A, tr, gs, quintic=quintic)

The value of `zz` is equal to [-NaN -NaN ... -NaN] in GDL while `zz` has some values  (not any -NaN) in IDL

lines 77 in [_interp2d.pro](https://github.com/equib/proEQUIB/blob/master/externals/misc/_interp2d.pro):

    triangulate, xx, yy, tr

The value of `tr` calculated by IDL is (216 rows with 3 columns):

           0           1          11
           0          11          10
          10          11          21
          10          21          20
          20          21          31
          20          31          30
          30          31          41
          30          41          40
          40          41          50
          50          41          51
          50          51          60
          60          51          61
          60          61          70
          70          61          71
          70          71          80
          80          71          81
          80          81          90
          90          81          91
          90          91         100
         100          91         101
         100         101         110
         110         101         111
         110         111         120
         120         111         121
           1           2          11
          11           2          12
          11          12          21
          21          12          22
          21          22          31
          31          22          32
          31          32          42
          31          42          41
          41          42          52
          41          52          51
          51          52          62
          51          62          61
          61          62          72
          61          72          71
          71          72          81
          81          72          82
          81          82          91
          91          82          92
          91          92         101
         101          92         102
         101         102         111
         111         102         112
         111         112         121
         121         112         122
           2           3          12
          12           3          13
          12          13          22
          22          13          23
          22          23          32
          32          23          33
          32          33          42
          42          33          43
          42          43          52
          52          43          53
          52          53          62
          62          53          63
          62          63          73
          62          73          72
          72          73          83
          72          83          82
          82          83          93
          82          93          92
          92          93         103
          92         103         102
         102         103         112
         112         103         113
         112         113         122
         122         113         123
           3           4          13
          13           4          14
          13          14          23
          23          14          24
          23          24          33
          33          24          34
          33          34          43
          43          34          44
          43          44          53
          53          44          54
          53          54          63
          63          54          64
          63          64          73
          73          64          74
          73          74          83
          83          74          84
          83          84          93
          93          84          94
          93          94         104
          93         104         103
         103         104         114
         103         114         113
         113         114         124
         113         124         123
           4           5          14
          14           5          15
          14          15          24
          24          15          25
          24          25          34
          34          25          35
          34          35          44
          44          35          45
          44          45          54
          54          45          55
          54          55          64
          64          55          65
          64          65          74
          74          65          75
          74          75          84
          84          75          85
          84          85          94
          94          85          95
          94          95         104
         104          95         105
         104         105         114
         114         105         115
         114         115         124
         124         115         125
           5           6          16
           5          16          15
          15          16          26
          15          26          25
          25          26          36
          25          36          35
          35          36          46
          35          46          45
          45          46          55
          55          46          56
          55          56          65
          65          56          66
          65          66          75
          75          66          76
          75          76          85
          85          76          86
          85          86          95
          95          86          96
          95          96         105
         105          96         106
         105         106         115
         115         106         116
         115         116         125
         125         116         126
           6           7          16
          16           7          17
          16          17          26
          26          17          27
          26          27          36
          36          27          37
          36          37          47
          36          47          46
          46          47          57
          46          57          56
          56          57          67
          56          67          66
          66          67          77
          66          77          76
          76          77          86
          86          77          87
          86          87          96
          96          87          97
          96          97         106
         106          97         107
         106         107         116
         116         107         117
         116         117         126
         126         117         127
           7           8          17
          17           8          18
          17          18          27
          27          18          28
          27          28          37
          37          28          38
          37          38          47
          47          38          48
          47          48          57
          57          48          58
          57          58          67
          67          58          68
          67          68          78
          67          78          77
          77          78          88
          77          88          87
          87          88          98
          87          98          97
          97          98         108
          97         108         107
         107         108         117
         117         108         118
         117         118         127
         127         118         128
           8           9          18
          18           9          19
          18          19          28
          28          19          29
          28          29          38
          38          29          39
          38          39          48
          48          39          49
          48          49          58
          58          49          59
          58          59          68
          68          59          69
          68          69          78
          78          69          79
          78          79          88
          88          79          89
          88          89          98
          98          89          99
          98          99         109
          98         109         108
         108         109         119
         108         119         118
         118         119         129
         118         129         128

The value of `tr` calculated by GDL is (224 rows with 3 columns):

           0           9           8
           0           8           7
           0           7           6
           0           6           5
           0           5           4
           0           4           3
           0           3           2
           0           2           1
           0           1          11
           0          11          10
           1           2          11
           2          12          11
           2           3          12
           3          13          12
           3           4          13
           4          14          13
           4           5          14
           5          15          14
           5           6          15
           6          16          15
           6           7          16
           7          17          16
           7           8          17
           8          18          17
           8           9          18
           9          19          18
          10          11          20
          11          21          20
          11          12          21
          12          22          21
          12          13          22
          13          23          22
          13          14          23
          14          24          23
          14          15          24
          15          25          24
          15          16          25
          16          26          25
          16          17          26
          17          27          26
          17          18          27
          18          28          27
          18          19          28
          19          29          28
          20          21          30
          21          31          30
          21          22          31
          22          32          31
          22          23          32
          23          33          32
          23          24          33
          24          34          33
          24          25          34
          25          35          34
          25          26          35
          26          36          35
          26          27          36
          27          37          36
          27          28          37
          28          38          37
          28          29          38
          29          39          38
          30          31          40
          31          41          40
          31          32          41
          32          42          41
          32          33          42
          33          43          42
          33          34          43
          34          44          43
          34          35          44
          35          45          44
          35          36          45
          36          46          45
          36          37          46
          37          47          46
          37          38          47
          38          48          47
          38          39          48
          39          49          48
          40          41          50
          41          51          50
          41          42          51
          42          52          51
          42          43          52
          43          53          52
          43          44          53
          44          54          53
          44          45          54
          45          55          54
          45          46          55
          46          56          55
          46          47          56
          47          57          56
          47          48          57
          48          58          57
          48          49          58
          49          59          58
          50          51          60
          51          61          60
          51          52          61
          52          62          61
          52          53          62
          53          63          62
          53          54          63
          54          64          63
          54          55          64
          55          65          64
          55          56          65
          56          66          65
          56          57          66
          57          67          66
          57          58          67
          58          68          67
          58          59          68
          59          69          68
          60          61          70
          61          71          70
          61          62          71
          62          72          71
          62          63          72
          63          73          72
          63          64          73
          64          74          73
          64          65          74
          65          75          74
          65          66          75
          66          76          75
          66          67          76
          67          77          76
          67          68          77
          68          78          77
          68          69          78
          69          79          78
          70          71          80
          71          81          80
          71          72          81
          72          82          81
          72          73          82
          73          83          82
          73          74          83
          74          84          83
          74          75          84
          75          85          84
          75          76          85
          76          86          85
          76          77          86
          77          87          86
          77          78          87
          78          88          87
          78          79          88
          79          89          88
          80          81          90
          81          91          90
          81          82          91
          82          92          91
          82          83          92
          83          93          92
          83          84          93
          84          94          93
          84          85          94
          85          95          94
          85          86          95
          86          96          95
          86          87          96
          87          97          96
          87          88          97
          88          98          97
          88          89          98
          89          99          98
          90          91         100
          91         101         100
          91          92         101
          92         102         101
          92          93         102
          93         103         102
          93          94         103
          94         104         103
          94          95         104
          95         105         104
          95          96         105
          96         106         105
          96          97         106
          97         107         106
          97          98         107
          98         108         107
          98          99         108
          99         109         108
         100         101         110
         101         111         110
         101         102         111
         102         112         111
         102         103         112
         103         113         112
         103         104         113
         104         114         113
         104         105         114
         105         115         114
         105         106         115
         106         116         115
         106         107         116
         107         117         116
         107         108         117
         108         118         117
         108         109         118
         109         119         118
         110         111         120
         111         121         120
         111         112         121
         112         122         121
         112         113         122
         113         123         122
         113         114         123
         114         124         123
         114         115         124
         115         125         124
         115         116         125
         116         126         125
         116         117         126
         117         127         126
         117         118         127
         118         128         127
         118         119         128
         119         129         128

What are those 8 extra lines at the beginning of `tr` calculated by GDL (8 rows and 3 columns)?

           0           9           8
           0           8           7
           0           7           6
           0           6           5
           0           5           4
           0           4           3
           0           3           2
           0           2           1

I think that there are some issues in `triangulate` in GDL (maybe also in `trigrid` after fixing the above bug).

**Comment by GillesDuvert** [comment]
Hi @danehkar 
Thanks a lot for this very precise bug analysis. One known issue is that the historical code by Renka used now (it's the same as IDL's according to their documentation) does not like very much duplicate points. Tests show that IDL filters them silently, we do not (yet). But this is probably irrelevant. We'll have a serious look into this!
