### ISSUE TITLE
antlr warnings (format.g)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#538]
warning: found optional path in nextToken()
format.g:169:11: warning:nondeterminism between alts 1 and 2 of block upon
format.g:169:11:     k==1:COMMA,RBRACE,SLASH
format.g:259:7: warning:nondeterminism between alts 1 and 2 of block upon
format.g:259:7:     k==1:COMMA,RBRACE,SLASH,E,SE

**Comment by GillesDuvert** [comment]
not a problem.
