### ISSUE TITLE
FILE_COPY,/OVERWITE issue

### ISSUE THREAD

**Issue by smaled** [gnudatalanguage/gdl#549]
Hi there, 
I'm using GDL 0.9.7 on:
Linux version 3.10.0-957.1.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 29 14:49:43 UTC 2018

Issue: when i use the FILE_COPY,/OVERWRITE command the file does not overwrite, it makes another file. 
Example, 
There is a file called 'dan.dat'
i use FILE_COPY,/OVERWRITE to overwrite dan.dat with another file.
When i do this GDL makes a new file: 'dan\.dat'. the original file is not overwritten. 
If repeated, then 'dan\.dat' is overwritten , not the original file 'dan.dat'. 
If 'dan.dat' is not present, then all is ok.

Cheers
dan

**Comment by smaled** [comment]
dan.dat should be dan\.dat

**Comment by smaled** [comment]
dan.dat should be dan\\.dat

**Comment by smaled** [comment]
redo request:
Hi there,
I'm using GDL 0.9.7 on:
Linux version 3.10.0-957.1.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 29 14:49:43 UTC 2018

Issue: when i use the FILE_COPY,/OVERWRITE command the file does not overwrite, it makes another file.
Example,
There is a file called 'dan.dat'
i use FILE_COPY,/OVERWRITE to overwrite dan.dat with another file.
When i do this GDL makes a new file: 'dan\\.dat'. the original file is not overwritten.
If repeated, then 'dan\\.dat' is overwritten , not the original file 'dan.dat'.
If 'dan.dat' is not present, then all is ok.

**Comment by maynardGK** [comment]
Hi.
  To see how far gone your GDL version is, "Help,!gdl" will show you the release ID and build date.
A significant change to file_copy was made in the git source improved from the release GDL0.9.8. 
If you pick up a GDL0.9.8 version it needs to have been built from git after April 14, 2018:
```
commit e128ca8be0cb0ee5cc477406bd33226210218623
Author: Greg Jung <gvjung@gmail.com>
Date:   Sat Apr 14 01:06:43 2018 -0700

    Update legacy code of file.cpp. Commit 4:

    This commit adds the file_copy, file_move, file_link routines as compiled procedures.
    File_copy will preserve creation time of the files it copies.
     test_file_link.pro is added to testsuite, but tries nothing so far.

    The commands are powerful modifiers to a filesystem, which needs to be safe if it fails.

    Greg Jung (aka maynardGK)
    gvjung@gmail.com
```
 GDL0.9.8 release has latest sources Mar 26, 2018 so the modification to file.cpp, which implements file_copy correctly in this respect, had not been made but it will be found in the current release, GDL0.9.9
found here https://github.com/gnudatalanguage/gdl/archive/v0.9.9.tar.gz

```
greg@Homerw7  D:/bld/gdl/mingw64-gvj
$ touch dan.dat

greg@Homerw7  D:/bld/gdl/mingw64-gvj
$ ext
bash: ext: command not found

greg@Homerw7  D:/bld/gdl/mingw64-gvj
$ exit
exit
GDL> file_copy,'make.out','dan.dat',/overwrite
GDL> $ head dan.dat
Scanning dependencies of target antlr
[  0%] Building CXX object src/antlr/CMakeFiles/antlr.dir/ANTLRUtil.cpp.obj
[  1%] Building CXX object src/antlr/CMakeFiles/antlr.dir/ASTFactory.cpp.obj
[  1%] Building CXX object src/antlr/CMakeFiles/antlr.dir/ASTNULLType.cpp.obj
[  2%] Building CXX object src/antlr/CMakeFiles/antlr.dir/ASTRefCount.cpp.obj
GDL> file_copy,'make.out','dan.dat'
 FILE_COPY0: we FAILED to copy make.out to dan.dat
GDL> file_copy,'makefile','dan.dat',/overwrite
GDL> $ head dan.dat
# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
GDL> $ls -lat
total 141
drwxr-xr-x 1 greg None     0 Dec 11 18:16 .
drwxr-xr-x 1 greg None     0 Dec 11 12:33 CMakeFiles
drwxr-xr-x 1 greg None     0 Dec 11 12:33 src
drwxr-xr-x 1 greg None     0 Nov 28 11:19 ..
-rw-r--r-- 1 greg None 12885 Nov 26 00:38 make.out
-rw-r--r-- 1 greg None  2195 Nov 26 00:31 config.h
-rw-r--r-- 1 greg None  8040 Nov 26 00:31 cmake.out
drwxr-xr-x 1 greg None     0 Nov 26 00:31 testsuite
-rw-r--r-- 1 greg None   285 Nov 26 00:31 CTestTestfile.cmake
-rw-r--r-- 1 greg None  3038 Nov 26 00:31 cmake_install.cmake
-rw-r--r-- 1 greg None  8880 Nov 26 00:31 Makefile
-rw-r--r-- 1 greg None 39254 Nov 26 00:31 CMakeCache.txt
-rw-r--r-- 1 greg None  8880 Nov 26 00:31 dan.dat
```

**Comment by smaled** [comment]
Hi Greg, 

Many thanks for the reply, and that the problem/issue is resolved in later versions. 
Much appreciated.

Cheers
Dan
