### ISSUE TITLE
Long running tests on non-x86 architectures (Debian)

### ISSUE THREAD

**Issue by olebole** [gnudatalanguage/gdl#557]
On architectures other than x86 32 or 64 bit, some tests take really long, as seen from the following table, which lists all test durations with 0.9.9 bigger than 1000 sec:

Test                | F| time| arch   | machine
--------------------|--|-----|--------|------------------
test_angles         | F| 6480| ppc64el| ppc64el-osuosl-01
test_bug_3104209    |  | 6483| ppc64el| ppc64el-osuosl-01
test_bug_3104209    |  | 7268| arm64  | arm-conova-02
test_bug_3104326    |  | 1360| s390x  | zandonai
test_bug_3104326    |  | 4797| ppc64el| ppc64el-osuosl-01
test_bug_3104326    |  | 5495| arm64  | arm-conova-02
test_bug_3147733    |  | 1431| s390x  | zandonai
test_bug_3147733    |  | 4800| ppc64el| ppc64el-osuosl-01
test_bug_3147733    |  | 5161| arm64  | arm-conova-02
test_bug_n000720    | F| 6475| ppc64el| ppc64el-osuosl-01
test_bug_n000720    | F| 7818| arm64  | arm-conova-02
test_contour        |  | 1033| mips   | mips-aql-04 
test_fft            |  | 5356| mips   | mips-aql-04 
test_indgen         | F| 6498| ppc64el| ppc64el-osuosl-01
test_indgen         | F| 7752| arm64  | arm-conova-02
test_matrix_multiply|  | 1558| mipsel | eberlin
test_matrix_multiply| |>21600| mips   | mips-aql-04 
test_random         | F| 6486| ppc64el| ppc64el-osuosl-01
test_step           |  | 4367| arm64  | arm-conova-02
test_step           |  | 8250| ppc64el| ppc64el-osuosl-01

The "F" columns shows here whether the test failed ("F") or not (empty).The machine name is the name of the Debian build machine and just for reference. The architectures are

* "mips" MIPS 32 bit big endian
* "mipsel" MIPS 32 bit little endian
* "arm64" ARM 64 bit little endian
* "ppc64el" PowerPC 64 bit litte endian (Altivec optimization switched off due to #530)
* "s390x" IBM zSystems 64 bit big endian

On x86, this all is a matter of seconds.

Most of the long-running tests appeared only on 0.9.9. Interestingly, there seems to be no pattern; some tests run only within seconds on one platform and really long on others. If the tests run too long, our build daemons will just terminate the packaging with a failure. So, I currently see no other option than to disable these tests. However things like `test_angle` looks useful to me.

So, could someone look through these tests and see which could be easily omitted? Some, like `test_angle` could probably get shorter loops, right?

A table of all build logs (inclusive tests) is [here](https://buildd.debian.org/status/logs.php?pkg=gnudatalanguage). The build time there mainly comes from the tests.

**Comment by GillesDuvert** [comment]
Solved by #662 ?? Please give feedback

**Comment by slayoo** [comment]
@olebole @GillesDuvert how to proceed here?

**Comment by olebole** [comment]
For the ppc64el tests, I would re-add them when #530 is solved. I also could re-add the "mips" (32 bit big endian) related ones, sinc e this architecture was removed from Debian. For the others, I would continue to exclude them by a patch in the Debian package unless we get them shorter.

**Comment by GillesDuvert** [comment]
See  #761

**Comment by GillesDuvert** [comment]
#1755

**Comment by GillesDuvert** [comment]
@olebole there is a 1.0.5 coming, we expect to have closed a number of issues you reported. (last is covered by #1776) 
Please open new issues if necessary, and thanks for your dedication!
