### ISSUE TITLE
Problem compiling GDL Linux

### ISSUE THREAD

**Issue by kailenking** [gnudatalanguage/gdl#566]
Hi again,

I gave up on trying to get GDL to compile on my Mac, and instead I am now trying on a linux machine. This has lead to another problem. Im using the minimum script which is slightly modified :

$CmakeEXE .. \
   -DREADLINEDIR=$READLINE_PATH -DGEOTIFF=off \
   -DGSLDIR=$GSL_PATH -DOPENMP=$flag_openmp \
   -DPLPLOTDIR=$RACINE/$PLPLOT_DIR/Compilation/ \
   -DWXWIDGETS=off -DMAGICK=OFF -DNETCDF=OFF -DHDF=OFF \
   -DHDF5=off -DFFTW=OFF -DEIGEN3=OFF -DPSLIB=OFF -DPYTHON=OFF \
   -DX11=ON -DX11DIR=/usr/lib64/ \
   -DTIFF=off -DGRAPHICMAGICK=OFF 

I also had to enforce using wget not curl. The error message is pasted below, any thoughts?

Thanks,
Kailen

[ 25%] Building CXX object src/CMakeFiles/gdl.dir/libinit_gm.cpp.o
In file included from /home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:18:
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx:65: error: ‘nullptr’ was not declared in this scope
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx:65: error: ISO C++ forbids initialization of member ‘desc_’
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx:65: error: making ‘desc_’ static
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx:65: error: invalid in-class initialization of static data member of non-integral type ‘DStructDesc*’
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx: In member function ‘void DStructFactory::Add(const char*, const Vs& ...)’:
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx:34: error: ‘constexpr’ was not declared in this scope
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx:34: error: expected ‘;’ before ‘auto’
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx:35: error: ‘N’ was not declared in this scope
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx:37: error: ‘desc_’ was not declared in this scope
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx: In member function ‘void DStructFactory::AddArr(const char*, size_t, const V*)’:
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx:47: error: ‘desc_’ was not declared in this scope
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx: In member function ‘void DStructFactory::AddMat(const char*, size_t, size_t, const V*)’:
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.hxx:57: error: ‘desc_’ was not declared in this scope
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx: In constructor ‘DStructFactory::DStructFactory()’:
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:21: error: class ‘DStructFactory’ does not have any field named ‘desc_’
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx: In destructor ‘DStructFactory::~DStructFactory()’:
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:27: error: expected initializer before ‘:’ token
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:29: error: expected primary-expression before ‘}’ token
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:29: error: expected ‘;’ before ‘}’ token
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:29: error: expected primary-expression before ‘}’ token
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:29: error: expected ‘)’ before ‘}’ token
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:29: error: expected primary-expression before ‘}’ token
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:29: error: expected ‘;’ before ‘}’ token
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx: In member function ‘DStructGDL* DStructFactory::Create()’:
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:34: error: ‘nullptr’ was not declared in this scope
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:36: error: ‘desc_’ was not declared in this scope
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:36: error: unable to deduce ‘auto’ from ‘<expression error>’
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:37: error: expected initializer before ‘:’ token
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:41: error: could not convert ‘((DStructFactory*)this)->DStructFactory::vals_.std::map<_Key, _Tp, _Compare, _Alloc>::clear [with _Key = const char*, _Tp = BaseGDL*, _Compare = std::less<const char*>, _Alloc = std::allocator<std::pair<const char* const, BaseGDL*> >]()’ to ‘bool’
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:42: error: expected primary-expression before ‘return’
/home/kking/Downloads/gdl-master-2/scripts/gdl-0.9.9/src/dstructfactory.cxx:42: error: expected ‘)’ before ‘return’
make[2]: *** [src/CMakeFiles/gdl.dir/dstructfactory.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/CMakeFiles/gdl.dir/all] Error 2
make: *** [all] Error 2

It seems a problem occured during the compilation of GDL
Please check carrefully the outputs
[kking@bucc scripts]$

**Comment by slayoo** [comment]
Please try pointing CMake to a newer compiler that would support C++11
