### ISSUE TITLE
HDF4

### ISSUE THREAD

**Issue by kailenking** [gnudatalanguage/gdl#570]
Hello again I have been following the suggestion to use a newer c compiler and now gdl compiles. But HDF4 support in gdl, but if I turn it on it does not seem to work. In the script I have: 

 -DHDF=ON  -DHDFDIR=/home/kking/hdf4/ -DJPEGDIR=/home/kking/libjpeg/ \

but when running the script I get the message which is pasted below.

The hdf4 has been installed in /home/kking/hdf4:
$ ls -l /home/kking/hdf4
total 16
drwxrwxr-x 2 kking kking 4096 Feb  6 10:11 bin
drwxrwxr-x 2 kking kking 4096 Feb  6 10:11 include
drwxrwxr-x 2 kking kking 4096 Feb  6 10:11 lib
drwxrwxr-x 4 kking kking 4096 Feb  6 10:11 share

what does it expect to find in the hdf4 directory? any suggestions?
Thank You,

Kailen

CMake Error at CMakeLists.txt:697 (message):
  HDF4 libraries were not found.

  Use -DHDFDIR=DIR to specify the HDF directory tree.

  Use -DHDF=OFF to not use it.

  (suitable Debian/Ubuntu package: libhdf4-alt-dev)

  You can use -DJPEGDIR=DIR to specify the JPEG directory tree.  You can also
  use -DSZIPDIR=DIR to specify SZip directory tree if HDF was compiled with
  SZip support.

-- Configuring incomplete, errors occurred!
See also "/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/build/CMakeFiles/CMakeOutput.log".
See also "/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/build/CMakeFiles/CMakeError.log".
make: *** [cmake_check_build_system] Error 1

Compilation of GDL is finished
Please remember it does not reflect the full capabilities of GDL

You can run GDL calling : 

	sh gdl-0.9.9/quick_start_GDL.sh

**Comment by alaingdl** [comment]
1/ If you are the administrator of the machine, I strongly suggest you add the hdf package

on Ubuntu, it is : 
ii  libhdf4-alt-dev     4.2r10-0ubuntu amd64          Hierarchical Data Format 4 library -- devel

2/ and my script is very limited ! as long as you installed the basic packages it is better not to used it

3/ don't forgot to remove build/ dir content before re-runing "cmake" to avoid any cache effect

4/ look at the other scripts to see which packages to add ...

**Comment by kailenking** [comment]
Hi

Thanks for all your help with this, I finally got gdl to work with HDF. In the end I had to change some paths in the CMakeCache.txt file as giving them as a parameter to cmake did not seem to work.


Thanks,
Kailen

**Comment by alaingdl** [comment]
Hi

don't forgot to run "make check" at the end

and you can see was is really activated by running "gdl_status"
(to be improved soon)
