### ISSUE TITLE
graphicsmagick

### ISSUE THREAD

**Issue by kailenking** [gnudatalanguage/gdl#576]
Hello

It turns out that I need graphicsmagick. I have installed that and I am trying to compile gdl with that, but the linking fails.
this part works fine:
[kking@bucc build]$ ../../cmake-3.2.3/bin/cmake ../ -DCMAKE_INSTALL_PREFIX=/home/kking/gdl/ -DCMAKE_CXX_COMPILER=/home/kking/mesasdk/bin/gcc -DGEOTIFF=off -DGSLDIR=../../gsl-1.16/Compilation/ -DX11=on -DX11DIR=/usr/lib64/ -DOPENMP=NO -DHDF=ON -DHDFDIR=/home/kking/yt-conda/ -DPNG=OFF -DPLPLOTDIR=/home/kking/Downloads/gdl-master-3/scripts/plplot-5.12.0/Compilation -DGRAPHICSMAGICK=ON -DGRAPHICSMAGICKDIR=/home/kking/graphicsmagick/ -DMAGICK=ON -DMAGICKDIR=/home/kking/imagemagick/ -DWXWIDGETS=OFF -DTIFF=OFF -DNETCDF=OFF -DPYTHON=OFF -DEIGEN3=OFF -DGSHHS=OFF -DPNGLIB=OFF -DZLIB_LIBRARYDIR=/home/kking/yt-conda/lib/ -DPSLIB=OFF -DFFTW=off

but when I run make the linking fails

[kking@bucc build]$ make -j 3

this is the beginning of the error message:

Linking CXX executable gdl
CMakeFiles/gdl.dir/magick_cl.cpp.o: In function `lib::magick_open(EnvT*)':
magick_cl.cpp:(.text+0x3ed): undefined reference to `Magick::Image::read(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/gdl.dir/magick_cl.cpp.o: In function `lib::magick_readindexes(EnvT*)':
magick_cl.cpp:(.text+0x974): undefined reference to `Magick::Image::write(int, int, unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MagickLib::StorageType, void*)'
magick_cl.cpp:(.text+0xc74): undefined reference to `Magick::Image::write(int, int, unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MagickLib::StorageType, void*)'
CMakeFiles/gdl.dir/magick_cl.cpp.o: In function `lib::magick_read(EnvT*)':
magick_cl.cpp:(.text+0x1654): undefined reference to `Magick::Image::write(int, int, unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MagickLib::StorageType, void*)'
CMakeFiles/gdl.dir/magick_cl.cpp.o: In function `lib::magick_write(EnvT*)':
magick_cl.cpp:(.text+0x24fe): undefined reference to `Magick::Image::read(unsigned int, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, MagickLib::StorageType, void const*)'

the whole thing is very long, any suggestions?

Thank You

Kailen

P.S I also tried with imagemagick but then make gives the following error:

**[ 15%] Building CXX object src/antlr/CMakeFiles/antlr.dir/CharBuffer.cpp.o
Linking CXX static library libantlr.a
[ 15%] Built target antlr
Scanning dependencies of target gdl
[ 16%] [ 16%] [ 17%] Building CXX object src/CMakeFiles/gdl.dir/CFMTLexer.cpp.o
Building CXX object src/CMakeFiles/gdl.dir/FMTIn.cpp.o
Building CXX object src/CMakeFiles/gdl.dir/FMTLexer.cpp.o
In file included from /home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/CFMTLexer.cpp:3:0:
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp: In function 'int currentNumberOfThreads()':
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:101:10: error: 'omp_get_num_threads' was not declared in this scope
   return omp_get_num_threads();
          ^~~~~~~~~~~~~~~~~~~
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:101:10: note: suggested alternative: '__builtin_omp_get_num_threads'
   return omp_get_num_threads();
          ^~~~~~~~~~~~~~~~~~~
          __builtin_omp_get_num_threads
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp: In function 'int maxNumberOfThreads()':
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:104:10: error: 'omp_get_num_procs' was not declared in this scope
   return omp_get_num_procs();
          ^~~~~~~~~~~~~~~~~
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp: In function 'int currentThreadNumber()':
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:107:8: error: 'omp_get_thread_num' was not declared in this scope
 return omp_get_thread_num();
        ^~~~~~~~~~~~~~~~~~
In file included from /home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/FMTLexer.cpp:3:0:
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp: In function 'int currentNumberOfThreads()':
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:101:10: error: 'omp_get_num_threads' was not declared in this scope
   return omp_get_num_threads();
          ^~~~~~~~~~~~~~~~~~~
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:101:10: note: suggested alternative: '__builtin_omp_get_num_threads'
   return omp_get_num_threads();
          ^~~~~~~~~~~~~~~~~~~
          __builtin_omp_get_num_threads
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp: In function 'int maxNumberOfThreads()':
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:104:10: error: 'omp_get_num_procs' was not declared in this scope
   return omp_get_num_procs();
          ^~~~~~~~~~~~~~~~~
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp: In function 'int currentThreadNumber()':
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:107:8: error: 'omp_get_thread_num' was not declared in this scope
 return omp_get_thread_num();
        ^~~~~~~~~~~~~~~~~~
In file included from /home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/FMTIn.cpp:3:0:
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp: In function 'int currentNumberOfThreads()':
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:101:10: error: 'omp_get_num_threads' was not declared in this scope
   return omp_get_num_threads();
          ^~~~~~~~~~~~~~~~~~~
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:101:10: note: suggested alternative: '__builtin_omp_get_num_threads'
   return omp_get_num_threads();
          ^~~~~~~~~~~~~~~~~~~
          __builtin_omp_get_num_threads
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp: In function 'int maxNumberOfThreads()':
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:104:10: error: 'omp_get_num_procs' was not declared in this scope
   return omp_get_num_procs();
          ^~~~~~~~~~~~~~~~~
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp: In function 'int currentThreadNumber()':
/home/kking/Downloads/gdl-master-3/scripts/gdl-0.9.9/src/includefirst.hpp:107:8: error: 'omp_get_thread_num' was not declared in this scope
 return omp_get_thread_num();
        ^~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/gdl.dir/CFMTLexer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/gdl.dir/FMTLexer.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/gdl.dir/FMTIn.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/gdl.dir/all] Error 2
make: *** [all] Error 2
**

**Comment by alaingdl** [comment]
-DGRAPHICSMAGICK=ON -DMAGICK=ON 
are mutually exclusive !
you have to select only one on the two.

please note IM was much less stable than GM

another advice : please cleanup (\rm * in the build dir)  before recompile 

A.

**Comment by maynardGK** [comment]
The (custom) compiler version may be the issue but I don't know enough to help any further than the suspicion.

It is ok to set -DMAGICK=ON and -DGRAPHICSMAGICK=ON will already be set by default and so is not needed.  Having -DMAGICKDIR=...> may be confusing and should not be there unless imagemagick is requested but graphicsmagic package should supersede based on your CMAKE commands.  To verify this you would find in the cmake output the message
````
"INFO: We prefer to use GraphicsMagick than ImageMagick"
````
which will confirm that graphicsmagick has been found.

My own linux builds uses the system installation so in that case I don't use GM directives at all - it will find GM in either /usr/lib or in /usr/lib64.  In windows I do re-direct to a custom build and it works.

(-DX11DIR=/usr/lib64 should not be needed.)

**Comment by GillesDuvert** [comment]
closed as should be ok with 1.0
