### ISSUE TITLE
CURSOR is no interuptable by ctrl-C

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#58]
As reported by @alaingdl back in 2010 on SF.net (https://sourceforge.net/p/gnudatalanguage/bugs/205/):

When X11 mode active, CURSOR is not interuptable

I do try to add to add
if( sigControlC) return;
in while loops (3 loops)
without effects ...

Further comments:

by Marc on 2010-03-14:
```
Fixing would be difficult as plGetCursor waits.
Maybe in a future plplot version...
```

by @GillesDuvert on 2013-03-20:
```
It is now. I have rewritten cursor.
BTW, using cursor, one can move the cursor also with the keyboard arrows and speed it using modifiers combinations (ctrl,shift,alt).
```

**Comment by GillesDuvert** [comment]
Still open, as the interruption does not go back all the way.
