### ISSUE TITLE
mod giving incorrect answers

### ISSUE THREAD

**Issue by jaymurthy** [gnudatalanguage/gdl#586]
for i=0l,1e8 do if ((i mod 1e6) eq 0)then print,i

 98000000
    98000001
    98000002
    98000003
    98000004
    98999996
    98999997
    98999998
    98999999
    99000000
    99000001
    99000002
    99000003
    99000004
    99999996
    99999997
    99999998
    99999999
   100000000

**Comment by alaingdl** [comment]
could you explain the point ?

I just compared IDL (8.4) & GDL (git) and the outputs are exactly the same on my laptop

(we already had a "test_modulo.pro")

**Comment by jaymurthy** [comment]
I would have expected (i mod 1e6) to give 99,000,000 and then 100,000,000. I suppose it is just round off error.

**Comment by alaingdl** [comment]
should be 
for i=0l,1e8 do if ((i mod long(1e6)) eq 0)then print,i
but not
for i=0l,1e8 do if ((i mod fix(1e6)) eq 0)then print,i

...

as usual ...
and we need to fit with IDL outputs
