### ISSUE TITLE
make_array not able to make array of structures?

### ISSUE THREAD

**Issue by markdconner** [gnudatalanguage/gdl#587]
I am a somewhat novice user of GDL (and brand new to github) after using IDL for many years.  I have been using GDL on Amazon Web Services for a few months now.  Several days ago I ran 'sudo yum update' after login which made an update to GDL which I believe brings it to version 0.9.9.

The make_array() function no longer will make an array of structures for me.  I only found this out because one of my library functions I use stopped working after the recent update.  

` z=make_array(5,value={a:0,b:1})`
`% MAKE_ARRAY: Invalid type specified for result.`
`% Execution halted at: $MAIN$`

- Mark

**Comment by alaingdl** [comment]
OK, thank you for reporting it, I was able to reproduce it, it does appear
between June 12 & 13, 2018

and the code involved  : 
 ./gdl-0.9.8git180613CMake/src/basic_fun_jmg.cpp ./gdl-0.9.8git180612CMake/src/basic_fun_jmg.cpp
which is a large change in template for make_array 

if it may help, I put the two files here
http://aramis.obspm.fr/~coulais/GDL/issue587/

A.

**Comment by alaingdl** [comment]
and reading the difference, we also have non working keywords : 
(ok in 180612)

```
GDL> z=make_array(5,value={a:0,b:1},/int)
GDL> z=make_array(5,value={a:0,b:1},/float)
```

both give now (>=180613)
% MAKE_ARRAY: $MAIN$: Struct expression not allowed in this context: <Expression> <STRUCT    Array[5]>
% Execution halted at: $MAIN$

**Comment by GillesDuvert** [comment]
PR #583 shoudl have done the job... but still some problems:
z=make_array(5,value={a:0,b:1},/int) : should say: 
`% MAKE_ARRAY: Struct expression not allowed in this context: <STRUCT    Array[1]>.`
Besides, and more annoying:

```
GDL> t=make_array(5,value={a:0,b:1})
GDL> help,t
% Program caused arithmetic error: Integer divide by 0
```

**Comment by GillesDuvert** [comment]
closed.
