### ISSUE TITLE
Problem installing gdl-0.9.7, 0.9.8, 0.9.9

### ISSUE THREAD

**Issue by ghost** [gnudatalanguage/gdl#588]
Using gdl-0.9.7.tgz, VirtualBox 6.0, CentOS 7-x86_64-Minimal.  After unpacking, it looks like you execute the following command to install:  ./quick_start_GDL.sh .  It complains about line 90, " no file gdl in folder src."  What am I doing wrong?

**Comment by alaingdl** [comment]
the idea behind : 
```
sh ./quick_start_GDL.sh
```
or
```
$ chmod 755 quick_start_GDL.sh
$ ./quick_start_GDL.sh
```
it to help new end-users to start *gdl* with some PATH activated.

You can search for the *gdl* executable using something like : 
```
find . -name gdl
```

**Comment by alaingdl** [comment]
we strongly encourage you to move to the 0.9.9 vanilla or, even better, the current git version.
