### ISSUE TITLE
Installing GDL 0.9.9

### ISSUE THREAD

**Issue by jmanuelfuentes** [gnudatalanguage/gdl#598]
Hi,

I have an error when I try to install GDL on cmake in CENTOS 7:

`cmake .. -DCMAKE_INSTALL_PREFIX=/homes/aplic/noarch/software/GDL/0.9.9/ -DNCURSESDIR=/homes/aplic/noarch/software/ncurses/6.0-foss-2016b -DREADLINEDIR=/homes/aplic/noarch/software/libreadline/6.3-foss-2016b -DPNGLIBDIR=/homes/aplic/noarch/software/libpng/1.6.2-foss-2016b -DGSLDIR=/homes/aplic/noarch/software/GSL/2.1-foss-2016b -DPLPLOTDIR=/homes/aplic/noarch/software/PLplot/5.12.0-foss-2016b-Java-1.8.0_92-Python-2.7.12  -DWXWIDGETS=OFF  -DNETCDFDIR=/homes/aplic/noarch/software/netCDF/4.4.1-foss-2016b  -DHDF=OFF -DFFTWDIR=/homes/aplic/noarch/software/FFTW/3.3.4-gompi-2016b -DEIGEN3=OFF -DPSLIB=OFF -DX11DIR=/homes/aplic/noarch/software/X11/20160819b-foss-2016b -DMAGICKDIR=/aplic/noarch/software/ImageMagick/7.0.8-44-foss-2016b -DGRAPHICSMAGICK=OFF`

```
CMake Error at CMakeLists.txt:547 (message):
  ImageMagick is required but was not found.

  Use -DMAGICKDIR=DIR to specify the ImageMagick directory.

  Use -DMAGICK=OFF to not use it.

  (suitable Debian/Ubuntu package: libmagick++-dev)

  (suitable Fedora package: ImageMagick-c++-devel)


-- Configuring incomplete, errors occurred!
```
But I set the DMAGICKDIR, any idea??
Thanks,

Juanma

**Comment by maynardGK** [comment]
First off I suggest you get the GraphicsMagick library instead; that is what we have been using, I don't think there is recent success using ImageMagick.  See #521 for comments on my previous attempt in windows.
Also see #576
