### ISSUE TITLE
Implement CW_*** compound widgets procedures

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#601]
We have to verify the current version of ATV is still working well on any Linux
https://www.physics.uci.edu/~barth/atv/

this was related to "old" r4136
and also the flag to start Widgets (gdl --use-wx)

ATV should work when GDL is compiled with Widgets
even if we don't explicit set this up when starting GDL

(we had a trouble in the past with *only* ubuntu 14.04)

And the way to test should be written somewhere because its need
at least 2 external libs :(

**Comment by slayoo** [comment]
for the record: https://github.com/gnudatalanguage/gdl/issues/127#issuecomment-504649355

**Comment by maynardGK** [comment]
For this to operate, GDL needs also the routines ,CW_PDMENU and CW_FIELD.
Once I found those the atv widget came up ok, using manjaro linux distro.

**Comment by GillesDuvert** [comment]
yes, CW_*** procedures, particularly CW_PDMENU, CW_FORM, CW_BGROUP and CW_FIELD are almost everywhere in ATV and other "serious" widget-based applications.
Apparently David Fanning has written a better cw_field (as FSC_FIELD) .
CW_BGROUP is in GDL (cw_bgroup_donotuseyet.pro) but needs some work to be OK.
The others need to be written for GDL.
An interesting subject for enthusiast volunteers...

**Comment by GillesDuvert** [comment]
look also for cw_bgroup in testsuite/*.pro .

**Comment by maynardGK** [comment]
I looked at FSC_FIELD as a possible drop-in.  It makes use of an object FSC_FIELD.
trying the example with GDL (bring up the widget then click the "close" on everything) exposes
a vulnerability somewhere:
````
% Compiled module: FSC_FIELD.
% Compiled module: EXAMPLE_EVENT.
% Compiled module: EXAMPLE.
GDL> example
% Warning: Keyword parameter TAB_MODE not supported in call to: WIDGET_CONTROL. Ignored.
% Compiled module: CGDBLTOSTR.
% Warning: Keyword parameter TAB_MODE not supported in call to: WIDGET_CONTROL. Ignored.
% Warning: Keyword parameter TAB_MODE not supported in call to: WIDGET_CONTROL. Ignored.
% Compiled module: XMANAGER.
GDL> % FSC_FIELD_KILL_NOTIFY: Variable is undefined: MESSAGE
% Execution halted at: FSC_FIELD_KILL_NOTIFY  1463 /d/home/greg/gdlpro/atv/fsc_field.pro
%                      $MAIN$          
GDL> Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Aborted (core dumped)
````
Widget_Control, textID, Get_UValue=message
Obj_Destroy, message.object

When a "quit" is invoked the first time through, the widget is still there after the first IDL error.
if message is tested and OB_destroy not called if invalid, the problem goes away:
````
PRO FSC_Field_Kill_Notify, textID

; This widget call-back procedure makes sure the self object is
; destroyed when the widget is destroyed.

COMPILE_OPT hidden
Widget_Control, textID, Get_UValue=message
if n_elements(message) ne 0 then $
    Obj_Destroy, message.object
END 
````

**Comment by GillesDuvert** [comment]
I've googled a copy of the original work by  David Fanning, named coyote_field.pro, can be used as a drop-in replacement, provided two cw_field options are added (and silently ignored?:RETURN_EVENTS, FLOATING), and CW_FIELD_KILL_NOTIFY is properly modified. I've added some new tags...

**Comment by jtappin** [comment]
[cw_bgroup.pro](https://github.com/gnudatalanguage/gdl/files/7015644/cw_bgroup.txt)
A possible CW_BGROUP, clean implementation, I think it has most of the capabilities (other than some that are not supported by the basic widgets.

Demo code [test_bg.pro](https://github.com/gnudatalanguage/gdl/files/7015654/test_bg.txt)

**Comment by GillesDuvert** [comment]
Freshly added, cannot say how we are grateful, this was much needed. Hopefully an example for other contributors annoyed by the lack of compund widgets!

**Comment by slayoo** [comment]
@jtappin, we are drafting a paper on GDL v1.0.0 to be submitted to JOSS (https://joss.theoj.org/), see post here: https://github.com/gnudatalanguage/gdl/discussions/1072
We would like to acknowledge contributors by listing as co-authors. Please confirm if it's OK to add you to the author list and please indicate the affiliation to give. Thanks, Sylwester
