### ISSUE TITLE
make an installer for Windows version

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#602]
the title says all..

**Comment by pjb7687** [comment]
I have no idea this would be still useful:
https://sourceforge.net/projects/gnudatalanguage-win32/files/NSIS%20script/

**Comment by GillesDuvert** [comment]
+ include gdlde and Jupyter kernel?

**Comment by pjb7687** [comment]
Added initial script: https://github.com/gnudatalanguage/gdl/pull/865

**Comment by slayoo** [comment]
WOW!

**Comment by GillesDuvert** [comment]
needs probably a bit of polishing as the gdl.exe must find external libraries files (plplot, plplot drivers, proj...).
Plus documentation (or, rather, advertising).
I leave open.
