### ISSUE TITLE
Homebrew: enable WXwidgets

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#605]
Currently the gnudatalanguage homebrew formula:
https://github.com/brewsci/homebrew-science/blob/master/Formula/gnudatalanguage.rb

does not use wx widgets which are available for homebrew:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/wxmac.rb

**Comment by GillesDuvert** [comment]
problem is not in wxwidgets, but in homebrew plplot that has no wxwidgets driver.
#882 last comments on how to do that. Also in https://github.com/gnudatalanguage/gdl/discussions/889#discussioncomment-494916
