### ISSUE TITLE
make an "installer" (.dmg) for OSX

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#606]
with Jupyter kernel and idlde?

**Comment by Steve-Albers** [comment]
Is there a recommended procedure at this time to install or build GDL on OSX? It seems to be deprecated from HomeBrew.

**Comment by slayoo** [comment]
there is a continuesly maintained Macports port: https://www.macports.org/ports.php?by=name&substr=gnudatalanguage

**Comment by GillesDuvert** [comment]
see #604...

**Comment by slayoo** [comment]
thanks to @pjb7687, we now have generation of a .dmg file for OSX done as a part of CI and binaries ready for download! 
See discussion in: https://github.com/gnudatalanguage/gdl/pull/1074
Closing here, please post comments in #1074
