### ISSUE TITLE
Issue when doing simple operation

### ISSUE THREAD

**Issue by allepet** [gnudatalanguage/gdl#607]
During the development of a project using GDL we have tried to make a simple math operation that in Matlab, Win Calculator,etc. give us 0.31... while in IDL it give us 0.7...

It looks like an issue using parenthesis in a multiplication operation, but for me it doesnt make sense that the order of a multiplication affects somehow the final result.

![image](https://user-images.githubusercontent.com/1734346/60272175-f831d100-98f3-11e9-9dc2-38c3a5d9f84d.png)

**Comment by slayoo** [comment]
It's because of 199*199 being cast down to an int:

```
GDL> print, 0.0026*199.0+0.0756-(0.000007*(199*199))
     0.774545
GDL> print, 0.0026*199.0+0.0756-(0.000007*(199*199L))
     0.315793
```

Nothing to fix I believe - that's how the type defaults are defined for IDL
HTH
