### ISSUE TITLE
FILE_MKDIR isn't recursive

### ISSUE THREAD

**Issue by mpetroff** [gnudatalanguage/gdl#608]
Per the IDL documentation, `FILE_MKDIR` should create all non-existent intermediate directories when parent directories of the specified directory are missing. GDL, however, does not create the intermediate directories and fails silently instead, not creating any directories.

Tested on Ubuntu 18.04 with GDL 0.9.9.

**Comment by maynardGK** [comment]
It was easy enough to add this #610 but I don't have an IDL to see how errors are treated,
I've assumed that an error in one attempt does not stop directory creation for the other passed parameters, and so there is no error signaling except for notes to stdout as they occur.

**Comment by mpetroff** [comment]
Thanks! I don't have IDL either, so I don't know how it handles errors. I found this bug because the IDL code I was trying to run was failing later on because it was trying to use a directory that failed to be created because of the lack of recursive directory creation.

**Comment by slayoo** [comment]
The #610 is now merged, so closing, but please do confirm if it works for you. Thanks

**Comment by mpetroff** [comment]
Yes, it works. Thanks!
