### ISSUE TITLE
% PLOTCoordinate system in error, please report to authors.

### ISSUE THREAD

**Issue by edromzans** [gnudatalanguage/gdl#619]
Hi, 
I am receiving this message:

% PLOTCoordinate system in error, please report to authors.

in my plots, simple "GDL> plot, x, y" in X device.
I am using a compiled GDL in debian 10 amd64 from the git "gdl-master.zip" recently downloaded (August 6, 2019).
Apparently have nothing wrong with the plots, but I had never seen this message in my previous installations.

Is this something dangerous? Anyone else had this message?

Thanks!
-Evandro

**Comment by maynardGK** [comment]
This aspect of the code has been getting a lot of re-work by @GillesDuvert ; it probably hit a code portion that wasn't expected.  If you could re-formulate a simple example of it and re-post, that would be helpful. (supply x, y that makes this happen).

**Comment by alaingdl** [comment]
ok with @maynardGK commnt, could you also indicated whether you turn on or not the mapping capabilities ?

**Comment by edromzans** [comment]
Hi all,
in my installation I turned on mapping capabilities (libproj4 on!) with libproj4 from https://proj.org (proj-4.9.3).

Are some plots in a panel with !p.multi. I am checking that I am using the label_date() function from idl7.0 and the error can be associated with this.

That above is my code to x plot. 

@read_out_sibvars
@ts_avgmonth
@ts_summonth

;devel--------------------
dirdefault = '/home/evandro/SiB2run/'
;-------------------------

dir = '/dados/SiB/sites/Pastagem_Rondonia/run/'

varfile =  'sib2dt.dat'

filedefault = dirdefault+varfile
print, filedefault
read_out_sibvars, filedefault, datetimedefault, varsdefault, varnamesdefault, kvaldefault

file = dir+varfile
print, file
read_out_sibvars, file, datetime, vars, varnames, kval

!p.font = 0
!p.charsize = 3
date_label = LABEL_DATE( DATE_FORMAT=['%Y%N'] )

;default
t0 = min(datetime)
t1 = max(datetime)
;set your own date
;t0 = julday(01, 01, 2005, 00) ; julday(MM, DD, YYYY, HH)
;t1 = julday(01, 01, 2006, 00)

;get daytime hourly resolution
pos1day = where( datetime ge datetime[0] and datetime lt datetime[0]+1d, daytimeres) 
print, 'hourly resolution in the day = ' , daytimeres

nvars = n_elements(varnames)
SiBvar = fltarr(kval)
SiBvardefault = fltarr(kval)

xws = 1800
yws = 900
!p.multi = [0, 3, 3]
window, 0, xsize = xws,  ysize = yws, title = 'Variaveis SiB'
device, decomposed = 0
loadct, 13, ncolors = 11
tvlct, 255, 255, 255, 255

;SiBvars
for k = 0L, nvars - 1L do begin

  SiBvar[*] = vars[k, *]
  SiBvardefault[*] = varsdefault[k, *]
  titlevar =  varnames[k]

  plot, SiBvar, SiBvardefault, title = titlevar, xtitle = 'original', ytitle = 'default', $
        xstyle = 1, ystyle = 1,  psym = 3

  plot, datetime, SiBvar - SiBvardefault, ytitle = 'desvio', xstyle = 1, ystyle = 1, $
        xtickformat = 'LABEL_DATE', xtickunits = 'Time', xrange = [t0, t1] ;,  yrange = [-10, 10]

  plot, datetime, SiBvar , ytitle = titlevar, xstyle = 1, ystyle = 1, $
        xtickformat = 'LABEL_DATE', xtickunits = 'Time', xrange = [t0, t1] ;,  yrange = [-10, 10]
  oplot, datetime, SiBvardefault,  color = 10


  ts_avgday, datetime, SiBvardefault, ts_uniqdaysdefault, SiBvardefault_dayavg
  ts_avgday, datetime, SiBvar, ts_uniqdays, SiBvar_dayavg

  plot, SiBvar_dayavg, SiBvardefault_dayavg, title = titlevar, xtitle = 'original', ytitle = 'default', $
        xstyle = 1, ystyle = 1,  psym = 3

  plot, ts_uniqdays, SiBvar_dayavg - SiBvardefault_dayavg, ytitle = 'desvio', xstyle = 1, ystyle = 1, $
        xtickformat = 'LABEL_DATE', xtickunits = 'Time', xrange = [t0, t1] ;,  yrange = [-10, 10]

  plot, ts_uniqdays, SiBvar_dayavg , ytitle = titlevar, xstyle = 1, ystyle = 1, $
        xtickformat = 'LABEL_DATE', xtickunits = 'Time', xrange = [t0, t1] ;,  yrange = [-10, 10]
  oplot, ts_uniqdays, SiBvardefault_dayavg, color = 10


  ts_avgmonth, datetime, SiBvardefault, ts_uniqmonthsdefault, SiBvardefault_monthavg
  ts_avgmonth, datetime, SiBvar, ts_uniqmonths, SiBvar_monthavg

  plot, SiBvar_monthavg, SiBvardefault_monthavg, title = titlevar, xtitle = 'original', ytitle = 'default', $
        xstyle = 1, ystyle = 1,  psym = 3

  plot, ts_uniqmonths, SiBvar_monthavg - SiBvardefault_monthavg, ytitle = 'desvio', xstyle = 1, ystyle = 1, $
        xtickformat = 'LABEL_DATE', xtickunits = 'Time', xrange = [t0, t1] ;,  yrange = [-10, 10]

  plot, ts_uniqmonths, SiBvar_monthavg , ytitle = titlevar, xstyle = 1, ystyle = 1, $
        xtickformat = 'LABEL_DATE', xtickunits = 'Time', xrange = [t0, t1] ;,  yrange = [-10, 10]
  oplot, ts_uniqmonths, SiBvardefault_monthavg, color = 10

  print, '-----------> ', titlevar
endfor
end

**Comment by GillesDuvert** [comment]
@emanselmo , hello, this is quite strange. I cannot reproduce it. If perchance you could give a simple example (yours cannot run without the data values of course) it may help to go further. 

BTW, the message is not in a code related to "mapping capabilities".
