### ISSUE TITLE
test_deriv random behaviour on Travis/OSX

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#634]
Since recently this test randomly fails or passes on OSX - hard to diagnose, rerunning the build makes it green usually, but it would be great to figure out what is happening. 

Example build log: https://travis-ci.org/gnudatalanguage/gdl/jobs/584032924#L7359

**Comment by alaingdl** [comment]
I can reproduce the problem (a crash in few runs (4/5)) on OSX 10.14.4 (18E226)
Thanks to the other issue #659 I can say that the problem of stability did appear between Aug. 15 and Sept 1st.
I am trying to locate a suspect in more than 20 files changed but nothing obvious up to now

**Comment by alaingdl** [comment]
OK, solved ! this is related to the bug in SORT()

As usual, any issue in testsuite may trace unexpected side effect in the code !
And deserves to be considered.

**Comment by slayoo** [comment]
Let me reopen it just to remember to uncomment the test for OSX in travis.yml:
https://github.com/gnudatalanguage/gdl/blob/master/.travis.yml#L58

**Comment by slayoo** [comment]
re-enabled on master
