### ISSUE TITLE
Linking problem on Ubuntu

### ISSUE THREAD

**Issue by cnsnln** [gnudatalanguage/gdl#646]
Hi, 

I am trying to install GDL on Ubuntu 18.04.  The linking failed with messages about "undefined reference to 'uuid_generate@UUID_1.0'  See error messages below.  Can anyone help me solve the problem?

Thanks.
Chin 
   
[ 15%] Linking CXX executable gdl
/usr/lib/x86_64-linux-gnu/libSM.so: undefined reference to `uuid_generate@UUID_1.0'
/usr/lib/x86_64-linux-gnu/libSM.so: undefined reference to `uuid_unparse_lower@UUID_1.0'
collect2: error: ld returned 1 exit status
src/CMakeFiles/gdl.dir/build.make:2337: recipe for target 'src/gdl' failed
make[3]: *** [src/gdl] Error 1
CMakeFiles/Makefile2:129: recipe for target 'src/CMakeFiles/gdl.dir/all' failed
make[2]: *** [src/CMakeFiles/gdl.dir/all] Error 2
CMakeFiles/Makefile2:141: recipe for target 'src/CMakeFiles/gdl.dir/rule' failed
make[1]: *** [src/CMakeFiles/gdl.dir/rule] Error 2
Makefile:188: recipe for target 'gdl' failed

**Comment by slayoo** [comment]
Seems unrelated to GDL, see e.g.:
https://github.com/vim/vim/issues/1961

**Comment by cnsnln** [comment]
I found the GDL linking problem also appearing in paraview compilation.    
https://discourse.paraview.org/t/pv-compilation-problems-with-libsm-and-uuid/884
Based on their investigations,   I added a command line in the X11 section of CMakelists.txt.  

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -luuid")

This solved my problem when I do cmake .. in building GDL.
Do we need to fix GDL installation procedure?

**Comment by GillesDuvert** [comment]
-luuid adds (yet another...) dependency as it may not exist on the target system. It needs specific detection, otherwise building GDL will fail on other systems. Normally this is done by cmake, that iterrogates each library (X11 should be one) to know what are the dependencies, in this case the uuid library. What is strange is that cmake on your ubuntu does not know about libuuid.

**Comment by slayoo** [comment]
Closing as apparently non-GDL issue
