### ISSUE TITLE
SORT function bug in OSX

### ISSUE THREAD

**Issue by RoxanaLupu** [gnudatalanguage/gdl#659]
It looks like the SORT function has a bug that makes it break once the array reaches 100 elements.

I was trying to sort this array that has 207 elements.
GDL> print,a
   5.6356555e-05    0.0012428325   4.4172928e-24   8.6430912e-11    0.0032652846   1.3983465e-14   3.5495810e-25   4.1673423e-21   9.7646063e-05   1.5297750e-05   1.7620919e-09
    0.0013312443    0.0040781509   0.00049167966      0.59438907   0.00087936392   4.4169251e-05    0.0067046287     0.035086862   4.1007837e-06    0.0071935553   4.7076462e-06
   1.2681432e-06   5.0015178e-06   0.00025119943     0.033003276   0.00023526256    0.0010388059     0.012476496     0.075056774     0.016500761   2.2042113e-06   5.6979412e-08
   1.6142321e-07   0.00067844170   1.2476931e-06   3.8514407e-05   6.3649851e-07   1.0012007e-06   2.0682051e-05   0.00010458282   4.5788690e-05   5.1293158e-09   2.9914390e-10
   2.3739239e-06   2.5845397e-05   7.6235174e-15   1.7877574e-05   6.4622259e-07   2.7640129e-06   1.2109734e-10   6.5429491e-08   5.7389376e-10   5.3041802e-12   4.7644260e-16
   0.00082544993   1.3369622e-09   2.9066794e-15   7.4561471e-09   2.5083053e-09   1.3759036e-15   2.0893952e-08   9.4069289e-10   1.9441657e-13   4.8112203e-13   1.3717108e-12
   3.4721710e-12   7.5313715e-23   2.9585743e-14   1.8642407e-06   2.4192787e-05   7.1062006e-08   4.5516825e-09   9.0620030e-12   6.5756074e-10   4.3085783e-15   3.3774455e-13
   6.6441394e-09   6.4155564e-18   2.4246808e-06   4.9423879e-24   1.1774098e-13   1.4252069e-10   5.7657643e-08   1.2464304e-13   2.1250762e-14   5.0814527e-12   2.7362953e-08
   3.9713631e-09   2.5329662e-16   2.4095093e-16   5.7456328e-14    0.0044253788      0.12142336   1.9126585e-08   5.7273446e-07   1.0396419e-18   5.0566022e-22   3.5703935e-26
   1.6531848e-09   5.5059521e-14   3.1594598e-14   3.6214888e-24   8.3223479e-27   0.00012736812   0.00011455960   8.9810399e-13   1.5563827e-16   1.1454357e-19   7.9165920e-19
   4.0636951e-17   6.1401643e-16   1.5418826e-13   2.5780990e-14   9.3621392e-10   2.1610595e-30   0.00069124822   0.00025923694   4.2252856e-07   9.1158410e-10   2.2624203e-11
   1.2776845e-08   1.9258727e-09   0.00023686629    0.0038132863   6.7174676e-12   7.5052400e-14   2.8330614e-09   1.6637106e-11   1.2247012e-11   1.0962945e-11   9.6025232e-13
    0.0082862706   2.8686829e-08      0.39733366   7.3833160e-09     0.013884954      0.58963464   1.3275697e-06   0.00095721324      0.18881727   2.1322774e-07   4.0995807e-10
   3.8090009e-06   3.5352555e-06   1.4573574e-07   1.0749673e-06     0.011637695   3.3829555e-08   2.7554701e-05   2.7511155e-06   4.4488069e-07    0.0010483063   9.4078514e-09
   9.2001147e-05   1.8539063e-15   1.2995428e-21   1.1980011e-15   2.3287360e-13   4.3654693e-12   1.0348545e-18   3.8025353e-07     0.018736839   5.3022122e-07   3.5187414e-05
   3.1218246e-11    0.0047621566   1.0997040e-06   8.2609171e-12   4.3093412e-09    0.0016314447    0.0012013767   2.3720918e-14   2.2020510e-09   0.00081393143   1.6602357e-09
   1.7716474e-05   0.00013825040     0.017377241   0.00094169229    0.0083948835   3.5677081e-06   1.3210787e-06     0.086035858    0.0051443791    0.0043486199   3.0291926e-05
   4.3743416e-05   0.00037890688   1.7255970e-05   1.5059653e-05   1.6160236e-05   1.2021294e-05   0.00016953691   1.4202177e-05    0.0019658162   9.1092707e-07   2.7029359e-05
   0.00016648238   0.00015482500   0.00076577234   5.7982850e-09   1.9077239e-05   3.5872700e-07   4.5804874e-05   7.3954622e-05   0.00010906261

To see what was going on, I started selecting sub-arrays. It looks like the behavior changes once the array goes from 99 elements to 100 elements:
GDL> b=a[0:98]
GDL> print,b(sort(b))
   3.5703935e-26   3.5495810e-25   4.4172928e-24   4.9423879e-24   7.5313715e-23   5.0566022e-22   4.1673423e-21   1.0396419e-18   6.4155564e-18   2.4095093e-16   2.5329662e-16
   4.7644260e-16   1.3759036e-15   2.9066794e-15   4.3085783e-15   7.6235174e-15   1.3983465e-14   2.1250762e-14   2.9585743e-14   5.7456328e-14   1.1774098e-13   1.2464304e-13
   1.9441657e-13   3.3774455e-13   4.8112203e-13   1.3717108e-12   3.4721710e-12   5.0814527e-12   5.3041802e-12   9.0620030e-12   8.6430912e-11   1.2109734e-10   1.4252069e-10
   2.9914390e-10   5.7389376e-10   6.5756074e-10   9.4069289e-10   1.3369622e-09   1.7620919e-09   2.5083053e-09   3.9713631e-09   4.5516825e-09   5.1293158e-09   6.6441394e-09
   7.4561471e-09   1.9126585e-08   2.0893952e-08   2.7362953e-08   5.6979412e-08   5.7657643e-08   6.5429491e-08   7.1062006e-08   1.6142321e-07   5.7273446e-07   6.3649851e-07
   6.4622259e-07   1.0012007e-06   1.2476931e-06   1.2681432e-06   1.8642407e-06   2.2042113e-06   2.3739239e-06   2.4246808e-06   2.7640129e-06   4.1007837e-06   4.7076462e-06
   5.0015178e-06   1.5297750e-05   1.7877574e-05   2.0682051e-05   2.4192787e-05   2.5845397e-05   3.8514407e-05   4.4169251e-05   4.5788690e-05   5.6356555e-05   9.7646063e-05
   0.00010458282   0.00023526256   0.00025119943   0.00049167966   0.00067844170   0.00082544993   0.00087936392    0.0010388059    0.0012428325    0.0013312443    0.0032652846
    0.0040781509    0.0044253788    0.0067046287    0.0071935553     0.012476496     0.016500761     0.033003276     0.035086862     0.075056774      0.12142336      0.59438907

GDL> b=a[0:99]
GDL> print,b(sort(b))
   2.4192787e-05   2.0682051e-05   1.5297750e-05    0.0013312443   2.3739239e-06   2.5083053e-09     0.035086862    0.0040781509   2.9914390e-10   7.4561471e-09   6.4622259e-07
    0.0044253788   4.4169251e-05   4.3085783e-15   1.9126585e-08   1.0012007e-06   1.9441657e-13   0.00049167966   0.00023526256   4.8112203e-13   4.7076462e-06   1.7620919e-09
    0.0012428325    0.0010388059   4.9423879e-24   5.7273446e-07   6.6441394e-09   2.0893952e-08   5.1293158e-09   4.5516825e-09   2.5845397e-05   2.4095093e-16   5.3041802e-12
   9.7646063e-05   3.5703935e-26   3.5495810e-25   4.3085783e-15   2.4095093e-16   2.5329662e-16   4.1673423e-21   2.9066794e-15   4.7644260e-16   1.3759036e-15   5.0814527e-12
   8.6430912e-11   1.1774098e-13   5.7456328e-14   9.0620030e-12   7.6235174e-15   4.8112203e-13   1.3983465e-14   2.9585743e-14   2.1250762e-14   3.3774455e-13   9.7646063e-05
   4.5788690e-05    0.0013312443   0.00010458282     0.012476496   0.00023526256    0.0032652846     0.035086862   2.5083053e-09   2.0893952e-08   1.2681432e-06   1.0012007e-06
   6.5429491e-08   7.1062006e-08   3.9713631e-09   5.1293158e-09   4.7076462e-06   5.6979412e-08   2.4192787e-05   2.2042113e-06   5.6979412e-08   1.3983465e-14   1.2476931e-06
   4.4172928e-24   3.4721710e-12   4.5788690e-05   1.3717108e-12   5.0015178e-06   1.1774098e-13   6.3649851e-07   1.3369622e-09   1.2681432e-06   1.4252069e-10    0.0032652846
   4.1007837e-06   1.0396419e-18   6.5429491e-08   1.2109734e-10   6.5756074e-10   2.7640129e-06   3.5495810e-25   0.00082544993   4.1673423e-21   5.7389376e-10     0.033003276
   2.1250762e-14

Is there a cap for the array size for the sort function, or is there another sort function specific for large arrays?

**Comment by maynardGK** [comment]
That certainly looks haywire!  I can't analyse the issue myself but to save time when Gilles sees this tomorrow, could you provide more info on the GDL version you are running - whether it is built on-site or a build was downloaded from a distribution, and the output of "hash(!GDL)" (or of "help,!gdl") and of !version.  Also the particular hardware, and a more convenient way to get the data set.

   PS - If your computer has a windows simulation program it would interest me if the the artifacts built here on appveyor run OK (they do when downloaded to a native windows system). Download 
here: https://ci.appveyor.com/api/buildjobs/yo39qgo6n2rr24ga/artifacts/gdl_build.zip for the 64-bit version.

````
a = randomu(seed, 1000)
b=a[0:150]
sb=b[sort(b)]
ii=where(sb[1:*] le sb,ni) & print,ni ; (0)
sa=a[sort(a)]
ii=where(sa[1:*] le sa,ni) & print,ni ; (0)
````

**Comment by RoxanaLupu** [comment]
The output for the version and platform is:
`GDL> hash(!GDL)
EPOCH:  1572418800
RELEASE:0.9.9 git
BUILD_DATE:Oct 30 2019
GDL_USE_WX:   0
MAP_QUALITY:CRUDE
GDL_NO_DSFMT:   0
GDL> hash(!VERSION)
OS:darwin
ARCH:x86_64
OS_NAME:Mac OS X
RELEASE:8.2
OS_FAMILY:unix
BUILD_DATE:Oct 30 2019
MEMORY_BITS:      64
FILE_OFFSET_BITS:      64
GDL> exit
`
Unfortunately I don't have a windows machine or emulator...

**Comment by RoxanaLupu** [comment]
I just built the app from the github source. Actually, I built it yesterday, saw the problem, then re-built it today after cleaning up my paths a bit. Same result.
I just built it with 
`cmake -DOPENMP=OFF -DHDF=OFF -DX11=OFF ..`
 and I got some errors during the make check:
```
The following tests FAILED:
	 98 - test_fft_leak.pro (Failed)
	106 - test_file_search.pro (Failed)
	107 - test_file_test.pro (Failed)
	110 - test_fix.pro (Failed)
	121 - test_hdf5.pro (Failed)
	128 - test_image_statistics.pro (Failed)
	141 - test_make_dll.pro (Failed)
	185 - test_resolve_routine.pro (Failed)
```
The other dependencies were installed using homebrew.
Trying to build gdl with homebrew crashes completely because it cannot seem to find the math functions (e.g. `/Library/Developer/CommandLineTools/usr/include/c++/v1/cmath:316:9: error: no member named 'isinf' in the global namespace`). Building from source does not have this problem.

**Comment by maynardGK** [comment]
Since you can build it ok there, I suggest you download the release 0.9.9 (https://github.com/gnudatalanguage/gdl/releases) and build with that.
The issue you see will probably be in the cmath used to speed things up, as that is where so many changes have been effected lately.

**Comment by alaingdl** [comment]
Thank you @RoxanaLupu  so much to report this critical bug.
Very quickly, I can report I can reproduce it on Mac OS X 10.12.2 (16C68) and cannot reproduce it on various Linux (with & without OpenMP on / Eigen3 on)

Thank you @maynardGK to provide a simple way to trigger the bug (to be put ASAP in the test suite for sure)

**Comment by alaingdl** [comment]
I tested various Git versions of GDL (since 0.9.9)  on Linux and OSX using a code derived from @maynardGK  one. (to be put ASAP in Git)

No problem on Linux up-to-now. 
Problems on OSX 10.12 & 10.14 confirmed with current Git version, with and without OpenMP & Eigen3 (4 versions)
No problem on OSX 10.12 & 10.14 for February Git version (and before) 
Unfortunately I have a lack on Git versions on OSX between Feb. & Oct ...
((it would be a great test case for the git-bisec but I don't know how to apply in that case.)

Concerning @maynardGK  code, I am not sure to understand the tests in WHERE() :
```
ii=where(sb[1:*] le sb,ni)
```
why not comparing just with sb[0] ?!

Since WHERE() is also a tricky code, I used TOTAL() in my test_sort.pro

**Comment by RoxanaLupu** [comment]
Thank you for looking into this! In the mean time, I put together my own sort routine for my use, but of course I cannot know which other gdl routines call the original sort, so other thinks might be broken, too... Is it possible for you to share an earlier git working git version?... Thank you so much for your work!

**Comment by maynardGK** [comment]
@alaingdl The where() test compares each element of the sorted array with the previous element: if any are le 0 then the sort failed (it is float format, and only 1000 in array, so no repeats expected)

git bisect merely provides commit values between what you say is good and what is bad.  You still have to rebuild from a full commit.
The latestsorting code overhaul is on Aug24, commit 19085267881a58b9208f5abff1b3ed4dbb100016 where a merge  from PR #542 happened.  (Using git log) I see the previous commit was 
 4b90d5fbd24966ba1b051520564573059fe434f9

  There are however several other commits mentioning sorting code
````
$ git checkout 5e6643246e5d92fb905de1120f6763ffe8649d12
Note: checking out '5e6643246e5d92fb905de1120f6763ffe8649d12'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 5e664324 Merge branch 'master' into faster_sorting_code
greg@i7Wx MSYS /d/f/github/gdlgit
$ git log
commit 5e6643246e5d92fb905de1120f6763ffe8649d12 (HEAD)
Merge: acbdcad6 6d60d640
Author: GillesDuvert <33936193+GillesDuvert@users.noreply.github.com>
Date:   Thu Aug 15 21:05:15 2019 +0200

    Merge branch 'master' into faster_sorting_code

commit 6d60d64079294fc396e46d5bbe2604dde5557109
Merge: 72f78e74 7fa9e917
Author: Sylwester Arabas <sylwester.arabas@uj.edu.pl>
Date:   Thu Aug 8 19:37:36 2019 +0200
````
So I'm guessing that last commit will definitely be "good" and the changes to sort begin at the next.
If you start out using bisect, it will remember the git commit you are currently at, so you can get back to your start point with "git bisect reset" - (according to the man page).

**Comment by alaingdl** [comment]
I used another method : 
```
git clone https://github.com/gnudatalanguage/gdl/
cd gdl
git checkout `git rev-list -n 1 --first-parent --before="2019-08-15 12:00" master`
```
then compiling GDL and running "test_sort.pro" (your script as a program)

the version on Aug. 15 is OK related to your test. Version of Sept. 1st is KO.
Which correspond to the change in sorting codes.

diff -r -q gdl190815/gdl/src/ gdl190901/gdl/src/
[...]
Only in gdl190901/gdl/src/: sorting.cpp
Only in gdl190901/gdl/src/: sorting.hpp

the _sorting.cpp_ does contain \_\_APPLE\_\_ directive

**Comment by alaingdl** [comment]
ok, just correcting the _bad_ conditional  \_\_APPLE\_\_ (old 32b ?!) is enough to solve the bug

```
diff sorting.cpp~ sorting.cpp
58c58
< #if defined(__APPLEold__) || defined(_XBOX) //IEEE little_endian in fact --> should use a better ifdef.
---
> #if defined(__APPLE__) || defined(_XBOX) //IEEE little_endian in fact --> should use a better ifdef.
```

**Comment by maynardGK** [comment]
So the __APPLE__ condition there assumes an architecture/IEEE format that isn't valid for Apple machines.  So that whole block should simply be an #if 0 until an XBOX version is successfully built.

**Comment by alaingdl** [comment]
We can see around (eg [detecting-endianness](https://stackoverflow.com/questions/8978935/detecting-endianness)) that detecting big/little endianness is not so easy at \#define level

help welcome !

**Comment by alaingdl** [comment]
:| gcc -dM -E -x c - |grep -i endian

no success with CMake 
https://docs.w3cub.com/cmake~3.12/module/testbigendian/

**Comment by GillesDuvert** [comment]
PR #662 by @maynardGK solves the problem, at least on the "travis" OSX machine.
Note that unsolved endianess problems should affect RANDOM numbers also.
As this is apparently not the case, the simple #ifdefs in dSFMT.h should do the job.

**Comment by alaingdl** [comment]
should be OK now with this #662 

We do have few places sensitive to big & little Endian but we have no VM to test the BIG Endian case :(

**Comment by GillesDuvert** [comment]
@RoxanaLupu could you confirm the bug is not present after a rebuild with the last github sources?

Many thanks, and yes, the sort algorithm changes depending on the number of elements to be sorted :smiley:

**Comment by RoxanaLupu** [comment]
Seems to work fine now! :-)
Thanks for all your work, this is great! 
If you need other things tested in OSX, let me know!

**Comment by slayoo** [comment]
Note that @opoplawski just reported in #705 that this test still fails on s390x architecture in Fedora build system. Should we reopen?
