### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#672]
I received a question, where can we get a compiled Win version ?

Thanks !

A.
(unable to find a space to share this question :(

**Comment by slayoo** [comment]
>  (unable to find a space to share this question :(

So let's have a wiki: https://github.com/gnudatalanguage/gdl/wiki

**Comment by slayoo** [comment]
And here's answer to the actual windows build location question on the wiki:https://github.com/gnudatalanguage/gdl/wiki/GDL-on-Windows
