### ISSUE TITLE
POLYFILL and log axes

### ISSUE THREAD

**Issue by rampante** [gnudatalanguage/gdl#674]
The POLYFILL procedure appears to ignore when (x|y)log is set (also, PLOT appears to ignore (x|y)tick_get ?), at least in macOS High Sierra (gdl 0.9.9) and Ubuntu 18.04 (gdl 0.9.8).

There's of course an easy workaround, but that would make the code behave differently when run with IDL.

**Comment by GillesDuvert** [comment]
long lasting bug, this! I hope it is solved in PR #684 . Thanks for the report!
