### ISSUE TITLE
plot : linestyle +psym problem when NaN in data

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#678]
```
a=findgen(10)
a[4]=!values.f_nan
a[7]=!values.f_nan
plot, a, psym=-4, line=3
```

everywhere the line should line type 3 (dash-dot) but now is continuous for segments 2 & 3 in GDL :(

this effect appeared  between Vanilla 0.9.8 & 0.9.9, more exactly between 2018-10-29 (OK) and 2018-11-05 (KO)

**Comment by alaingdl** [comment]
I do suspect these changes (additions in 2018-11-05 (KO)) in :
coulais@planck4:~/GDL$ diff ./gdl-0.9.8git181105CMake/src/plotting.cpp ./gdl-0.9.8git181029CMake/src/plotting.cpp
850d849
<             a->styl(0, NULL, NULL); //symbols drawn in continuous lines
875d873
<           a->styl(0, NULL, NULL); //symbols drawn in continuous lines
929d926
<           a->styl(0, NULL, NULL); //symbols drawn in continuous lines
955d951
<           a->styl(0, NULL, NULL); //symbols drawn in continuous lines

**Comment by GillesDuvert** [comment]
please check and merge!
