### ISSUE TITLE
smooth causes segmentation fault if one array dimension is bigger than 2558 elements

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#682]
GDL> hash(!GDL)
EPOCH:  1574132400
RELEASE:0.9.9 git
BUILD_DATE:Nov 19 2019
GDL_USE_WX:   0
MAP_QUALITY:CRUDE
GDL_NO_DSFMT:   0
GDL> a=fltarr(2000, 2000) & b=smooth(a,3)
GDL> a=fltarr(2000, 2558) & b=smooth(a,3)
GDL> a=fltarr(2000, 2559) & b=smooth(a,3)
Segmentation fault (core dumped)

**Comment by alaingdl** [comment]
I can confirm I do have similar "glitches".
since the sizes are not *huge*, maybe it is just a free which is missing ?

**Comment by GillesDuvert** [comment]
thanks for the bug report! Will be patched ASAP.

**Comment by GillesDuvert** [comment]
solved by PR #684
