### ISSUE TITLE
smooth does not work correctly with complex array

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#685]
GDL>line=exp(complex(0,randomu(seed,100)))
GDL>plot,atan(imaginary(line),float(line)) ; this plots correctly the phase
GDL>plot,atan(imaginary(smooth(line,0)),float(smooth(line,0))) ; this should give the same result but plots a constant phase

**Comment by GillesDuvert** [comment]
Hi, clever! 
Thanks, this was a nice typo!
Solved in #687
