### ISSUE TITLE
T3D usage is still not working correctly.

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#688]
A lot of the 3D graphics depends on  usage of T3D, and I believe GDL is still lacking in that aspect.
I am still failing to complete the examples found on http://www.exelisvis.com/docs/T3D_Procedure.html
For reference, the "house" procedure is copied from the webpage:
````
PRO HOUSE
   ; X coordinates of 10 vertices. First 5 are front face,
   ; second 5 are back face. The range is 0 to 16.
   house_x = [0, 16, 16, 8, 0, 0, 16, 16, 8, 0]
   ; The corresponding y values range from 0 to 16.
   house_y = [0, 0, 10, 16, 10, 0, 0, 10, 16, 10]
   ; The z values range from 30 to 54.
   house_z = [54, 54, 54, 54, 54, 30, 30, 30, 30, 30]
   ; Define max and min xy values to scale.
   ; Slightly larger than data range.
   min_x = -4 & max_x = 20.
   ; Set x data scale to range from -4 to 20.
   !X.S = [-(-4), 1.]/(20 - (-4))
   ; Same for y.
   !Y.S = !X.S
   ; The z range is from 10 to 70.
   !Z.S = [-10, 1.]/(70 - 10)
   ; Indices of front face.
   face = [INDGEN(5), 0]
   ; Draw front face.
   PLOTS, house_x[face], house_y[face], $
      house_z[face], /T3D, /DATA
   ; Draw back face.
   PLOTS, house_x[face + 5], house_y[face + 5], $
      house_z[face + 5], /T3D, /DATA
   ; Connecting lines from front to back.
   FOR I = 0, 4 DO PLOTS, [house_x[i], house_x[i + 5]], $
      [house_y[i], house_y[i + 5]], $
      [house_z[i], house_z[i + 5]], /T3D, /DATA
   ; Annotate front peak.
   XYOUTS, house_x[3], house_y[3], Z = house_z[3], 'Front', $
      /T3D, /DATA, SIZE = 2
   ; Annotate back.
   XYOUTS, house_x[8], house_y[8], Z = house_z[8], 'Back', $
      /T3D, /DATA, SIZE = 2
END
````
Here is a sample session, showing that !p.t itself is converted correctly but that its usage isn't well supported in XYOUTS.
````
GDL> print,!p.t
       1.0000000       0.0000000       0.0000000     -0.50000000
       0.0000000       1.0000000       0.0000000     -0.50000000
       0.0000000       0.0000000       1.0000000     -0.50000000
       0.0000000       0.0000000       0.0000000       1.0000000
GDL> t3d,rot=[30,30,0]
GDL> print,!p.t
      0.86602540      0.25000000      0.43301270     -0.77451905
       0.0000000      0.86602540     -0.50000000     -0.18301270
     -0.50000000      0.43301270      0.75000000     -0.34150635
       0.0000000       0.0000000       0.0000000       1.0000000
GDL> t3d,tr=h
GDL> print,!p.t
      0.86602540      0.25000000      0.43301270     -0.27451905
       0.0000000      0.86602540     -0.50000000      0.31698730
     -0.50000000      0.43301270      0.75000000      0.15849365
       0.0000000       0.0000000       0.0000000       1.0000000
GDL> house
% Using Illegal 3D transformation, continuing. (FIXME)
% Using Illegal 3D transformation, continuing. (FIXME)
% Using Illegal 3D transformation, continuing. (FIXME)
% Using Illegal 3D transformation, continuing. (FIXME)
% Using Illegal 3D transformation, continuing. (FIXME)
% Using Illegal 3D transformation, continuing. (FIXME)
% Using Illegal 3D transformation, continuing. (FIXME)
% XYOUTS: Illegal 3D transformation. (FIXME)
% Execution halted at: HOUSE               32 D:/home/greg/gdlpro/new/house.pro
%                      $MAIN$
GDL>
````

**Comment by GillesDuvert** [comment]
Yes 3D transformations are very buggy, in some measure because the transformations are handled by plplot. My impression was that 3D in GDL (*not* perspective boxes, that "work", see demo_graphics3) should wait using wxWidget's MESA while dropping plplot, quite a long task however.

**Comment by DerPit** [comment]
> Yes 3D transformations are very buggy, in some measure because the transformations are handled by plplot. 
Is this also the reason that surface does weird things?  I've tried one of my programs with GDL, and one of the things it does is a surface call in a small area of the window (with POSITION keyword set).  And the result _substantially_ deviates from what IDL produces.

**Comment by GillesDuvert** [comment]
SURFACE ad SHADE_SURF behave grossly as in the examples given in the IDL help.
But things like reversing the axes (x from from max to min or setting POSITION) makes a mess because it is difficult to define the wiewing box in plplot's coordinates correctly in all the possible cases. (any idea?)

**Comment by DerPit** [comment]
No, no idea at all - I'm only a user and have no real idea about plplot at all :o 
But also IDL has its issues there, the surface plot exceeds the area defined by POSITION.

**Comment by AstroArtie** [comment]
/T3D does indeed still not work.
Setting a coordinate system with:
  `GDL> surface, z, x, y, ax=20, az=50, /SAVE`
sets up the 3D coordinate system correctly.
But a call to:
  `GDL> plots, x, y, z, /T3D`
produces nothing. Without the `/T3D` it plots the line, but in the default 3D coordinate system, it seems.
Since the coordinate system _does_ work, I would think it straightforward to make the transformation. I do a lot of 3D visualization and this capability is very important for my work.

Thanks for all your work, developers!

**Comment by GillesDuvert** [comment]
Actually the coordinate sytem does not work correctly, supposedly because the underlying plplot transform matrix is not compatible with the generalized T3D matrix used by IDL.  Only in the restricted case of [SCALE3](https://www.l3harrisgeospatial.com/docs/SCALE3_Procedure.html) and its T3D transformations the 'matrix' can be preserved., since the example works. But no TRANSLATE, PERSPECTIVE or OBLIQUE are possible with plplot. 
May be indeed there is some additional bug in the plots() code.

**Comment by GillesDuvert** [comment]
3D is now OK in #1338
