### ISSUE TITLE
Link issue: rpc/xdr

### ISSUE THREAD

**Issue by DerPit** [gnudatalanguage/gdl#689]
Hi,
I'm trying to compile latest git checkout on my openSUSE Tumbleweed.
For now I've disabled PSLIB and SHAPELIB, as I didn't have those available from standard repos.
Compile goes fine until the link stage, then it bails out with tons of undefined references to xdr_** types.  Googling for that suggested I need -ltirpc, and indeed with that it links.
Not sure if that is an error in the distribution files, or in the FindRPC.cmake.
But I see it looking for tirpc in the path name, which I don't have:
```
woodstock:~# rpm -qf /usr/include/rpc/rpc.h
libtirpc-devel-1.1.4-1.1.x86_64
```
/usr/lib64/pkgconfig/libtirpc.pc does exist, and would include the needed link flag, so the config ends up with
RPC                    ON (libs:; headers:/usr/include)

**Comment by maynardGK** [comment]
I am using opensuse LEAP 15.1 and don't have an issue at all with xdr - no tirpc here.
 I see from YAST that rpc.h comes from glibc-devel, tirpc is newer alternate in a separate rpm.
It appears that FindRPC.cmake tries to accomodate tirpc but it may be failing
````
find_path(RPC_INCLUDE_DIR NAMES "rpc/rpc.h" PATH_SUFFIXES "tirpc")

if(RPC_INCLUDE_DIR MATCHES "/tirpc/?$")
        find_library(RPC_LIBRARY NAMES tirpc)
        set(RPC_LIBRARIES ${RPC_LIBRARY})
        find_package_handle_standard_args(RPC DEFAULT_MSG RPC_INCLUDE_DIR RPC_LIBRARY RPC_LIBRARIES)
else()
        find_package_handle_standard_args(RPC DEFAULT_MSG RPC_INCLUDE_DIR)
endif()
````

PSLIB is still in primitive status but shapelib can be found via libshp.

**Comment by GillesDuvert** [comment]
... and PSLIB is not really used in GDL.

**Comment by DerPit** [comment]
@maynardGK: Yes, it expects it as .../tirpc/rpc.h, but that seems to be distribution dependent.  Likely you'll get the same problem in Leap 15.2, once that is out.
And thanks for the libshp tip - 'zypper search shapelib' didn't show that one :p 

@GillesDuvert: Now that's fun.  Maybe it should be disabled then by default?  Right now cmake stops with an error if it is not installed...

As for the actual problem - wouldn't it be possible to do the find_library before the if clause, and base that one on whether it found something or not? (I have no real clue about cmake syntax....)

**Comment by maynardGK** [comment]
> As for the actual problem - wouldn't it be possible to do the find_library before the if clause, and 
> base that one on whether it found something or not? (I have no real clue about cmake syntax....)

First it finds an rpc.h under directory rpc. The NAMES "tIrpc" parameters indicates that rpc/rpc.h might be found under /usr/include tirpc if /usr/include didn't work out.  (on my system there's no tirpc, only /usr/include/rpc). If so then it will need the tirpc library and the successive commands should propagate that to the build files.
  Otherwise it expects to get the xdr from already-linked libraries (glibc).

**Comment by DerPit** [comment]
> First it finds an rpc.h under directory rpc. The NAMES "tIrpc" parameters indicates that rpc/rpc.h might be found under /usr/include tirpc if /usr/include didn't work out. 

Yes, that I understood.

> (on my system there's no tirpc, only /usr/include/rpc). If so then it will need the tirpc library and the successive commands should propagate that to the build files.
> Otherwise it expects to get the xdr from already-linked libraries (glibc).

But this is not true.  Yes, if it is found in /usr/include/tirpc, obviously the tirpc lib is needed.  But not the other way round.  My system (only) has /usr/include/rpc/rpc.h, coming from tirpc. So this filename is **not** sufficient to conjecture that the glibc version is to be used.

`test`

I have now changed the FindRPC.cmake like this:
```
include(FindPackageHandleStandardArgs)
find_path(RPC_INCLUDE_DIR NAMES "rpc/rpc.h" PATH_SUFFIXES "tirpc")
find_library(RPC_LIBRARY NAMES tirpc)

if(RPC_LIBRARY STREQUAL "RPC_LIBRARY-NOTFOUND")
        find_package_handle_standard_args(RPC DEFAULT_MSG RPC_INCLUDE_DIR)
else()
        set(RPC_LIBRARIES ${RPC_LIBRARY})
        find_package_handle_standard_args(RPC DEFAULT_MSG RPC_INCLUDE_DIR RPC_LIBRARY RPC_LIBRARIES)
endif()

mark_as_advanced(RPC_INCLUDE_DIR RPC_LIBRARY RPC_LIBRARIES)
```
This does work on my system, but I cannot check if it also works properly for "glibc systems".  Maybe you can give it a try on your Leap 15.1?

**Comment by maynardGK** [comment]
I have the windows 10 system up, and put it in, and it works fine like that (xdr may be broken on windows, though).
The RPC options available in Mingw are divergent: I'm using bsdxdr which is not "portablexdr"
but uses same-named headers; tirpc is only available in the MSYS distro (cygwin/posix).

````
mingw64/mingw-w64-x86_64-grpc 1.22.0-1
    gRPC - Google's high performance, open source, general RPC framework
    (mingw-w64)
mingw64/mingw-w64-x86_64-jsonrpc-glib 3.32.0-1
    A JSON-RPC library for GLib (mingw-w64)
mingw64/mingw-w64-x86_64-portablexdr 4.9.2.r27.94fb83c-2
    PortableXDR / RPC Library (mingw-w64)
msys/libtirpc 1.1.4-1 (libraries)
    A port of Sun's Transport-Independent RPC library
msys/libtirpc-devel 1.1.4-1 (development)
    Libtirpc headers and libraries

NOTE: My windows'10 build has been broken now, for identical source code, apparently because I have installed msys/libtirpc and caused cmake to find the rpc/ headers for tirpc where it needed those installed and kept under mingw64/include.  I'll be looking into this.  Not a problem for most setups.
