### ISSUE TITLE
The MacOS X homebrew package is way out of date 

### ISSUE THREAD

**Issue by mutanthumb** [gnudatalanguage/gdl#706]
Hi-
I'm not sure where to put this issue but https://github.com/brewsci/homebrew-science/blob/master/Formula/gnudatalanguage.rb is way out of date. 

Thanks,
susan

**Comment by GillesDuvert** [comment]
Certainly on the homebrew project pages?

**Comment by mutanthumb** [comment]
I'll post it over there. Thanks.
