### ISSUE TITLE
it is not possible to open a window with a size bigger than the screen size

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#708]
My monitor has a resolution of 3840 x 2160.

The command  GDL> window,1,xsize=8192,ysize=8192

opens a window with size 3840 x 2160 instead of 8192 x 8192

**Comment by alaingdl** [comment]
It is a feature ;)

I would no say it is a bug, it's the normal way, IDL 7x & 8x gives same behavior (the documentation
[WINDOW_Procedure](https://www.harrisgeospatial.com/docs/WINDOW_Procedure.html) is not clear on that)

Maybe using sliders (?) in Widgets you can circumvent that ?

**Comment by brandy125** [comment]
Hi alaingdl,

 I am working since many years with fvwm2 window manager and since I can remember (since IDL 5.2) it is possible to open a window bigger than the screen size and I really need this.

I would say that this behaviour is still a bug since not even sliders appear. The opened window has no sliders and appears as a window opened with GDL> window,1,xsize=3840, ysize=2160 

Do you agree?

Do you think it is possible to fix this?

**Comment by brandy125** [comment]
Here another behaviour that is not correct and related to this:

GDL> window,1,xsize=8192,ysize=1024,/pix
GDL> plot,findgen(100)
GDL> a=tvrd()
GDL> help,a
A               BYTE      = Array[3840, 1024]

That is not correct.

**Comment by GillesDuvert** [comment]
on a machine with a big screen I have
```
IDL> window,1,xsize=8192,ysize=8192
IDL> a=tvrd()
IDL> help,a
A               BYTE      = Array[3440, 1387]
```
and GDL does the same. So the first issue behaviuor is just like IDL does, that is what GDL is supposed to do. 
But, indeed, the /PIX option changes everything, and /PIX should open a non-mapped window of any size supported by the system, which GDL does not. Yet Another Bug.

**Comment by brandy125** [comment]
I see that beside the BUG there are two different behaviours depending on the used window manager.
On my Suse 15.1 with fvwm installed I get with IDL 7.01:

IDL> window,xsize=8192,ysize=8192
IDL> a=tvrd()
IDL> help,a
A               BYTE      = Array[8192, 8192]
IDL> 

If I start with GDM window manager I get 

IDL> window,xsize=8192,ysize=8192
IDL> a=tvrd()
IDL> help,a
A               BYTE      = Array[3840,2160]
IDL> 

I would suggest to implement the first version that allows the window to be opened with 8k x 8k and let the window manager decide how to handle this big window.

For my personal use I need the window to have a size of 8k x 8k (and more) for editing it in one shot.

Maybe solving the BUG with  /pix  solves this already.

**Comment by brandy125** [comment]
Hi guys, let me ask you if there is any progress on this topic or does anybody know any workaround?

**Comment by GillesDuvert** [comment]
Sure, will work on it.
Just to understand, it's not possible just to make an array of 8000x8000  and work on it?
Otherwise, use a widget:
GDL> a=widget_base()
GDL> plot=widget_draw(a,xsize=8000,ysize=8000,x_scroll=512,y_scroll=512)
GDL> widget_control,a,/realize
GDL> widget_control,plot,get_value=num
GDL> wset,num
here you have a nice scrolled 8000x8000 graphic window that you can access as you want.

**Comment by brandy125** [comment]
Nice! 
Didn't know/think about the widget. This will help me to go ahead.

What you mean with make an array of 8k x 8k and work on it?
I am working usually on arrays (images) with a size of 8k x 32k (up to 8k x 256k).
I need to display the whole contents somehow on the screen, select the part I want to work visually and then cut that part out of the data and so on. In order to display the whole image I do a congrid before to 1k x 4k or so.

Anyway, I will implement your suggestion in the most recent programs and it will help me to go ahead. 
Thanks a lot for your suggestion!

**Comment by GillesDuvert** [comment]
note that cursor,x,y,/dev will return the pixel position in the scrolled 8Kx8K image.
if you use 8bit images and not 'truecolor', [atv](http://www.physics.uci.edu/~barth/atv) is even better.

**Comment by brandy125** [comment]
Hi guys, is there any progress with this topic?
I am working with the workaround suggested by @GillesDuvert but I would need the device, get_window_position=pos for that and it reports that it is not ready yet:

GDL> device,get_window_position=pos
Get Window Position not ready for wxWindow draw panel, please contribute.

**Comment by GillesDuvert** [comment]
Hm, work in (slow) progress. This because of an alredy started project to full rewrite of the whole widget-related part to improve compatibility.  Sorry!

**Comment by GillesDuvert** [comment]
#882 is your friend --- this is now possible with the use of wxWidgets for plots.
