### ISSUE TITLE
write_jpeg creates 3-dim jpg by default instead of 2-dim

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#710]
In IDL we have:

IDL> a=dist(100)
IDL> write_jpeg,'image.jpg',a
IDL> read_jpeg,'image.jpg',b
IDL> help,b
B               BYTE      = Array[100, 100]

while in GDL we get

GDL> a=dist(100)
GDL> write_jpeg,'image.jpg',a
GDL> read_jpeg,'image.jpg',b
GDL> help,b
B               BYTE      = Array[3, 100, 100]

**Comment by GillesDuvert** [comment]
This is an annoying long-lasting bug, soleley due to our lack of subtlety in the use of the imagemagick library. We open all jpeg files with the same imagemagick command, and do not know how to recognize a pseudocolr image from a truecolor one.
Suggestions welcome!

**Comment by brandy125** [comment]
I did not post it but I cross-checked that the problem is not the read_jpeg but the write_jpeg command. Does this change anything in your comment?

**Comment by GillesDuvert** [comment]
Ah, in the write_jpeg? Thank for the hint.

**Comment by alaingdl** [comment]
it is absolutely transparent in the code and documented (see "bad_trick" in src/pro/write_jpeg.pro)

I did that because at that time (11-Aug-2012) I did not found a solution :(

help still welcome

A.

**Comment by brandy125** [comment]
I do not know very well programming, but isn't there a chance to call the "convert" command from ImageMagick to convert the 3-dim jpg to a 2-dim jpg like i.e.:

GDL> im1=dist(500)
GDL> write_jpeg,'image.jpg',im1
GDL> read_jpeg,'image.jpg',im2  
GDL> help,im2
IM2             BYTE      = Array[3, 500, 500]
GDL> spawn,'convert image.jpg image.jpg'
GDL> read_jpeg,'image.jpg',im3
GDL> help,im2,im3
IM2             BYTE      = Array[3, 500, 500]
IM3             BYTE      = Array[500, 500]
GDL> 

What do you think?

**Comment by GillesDuvert** [comment]
solved in #722
