### ISSUE TITLE
rewrite interpol from scratch in C++

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#733]
When the interpol routine attempts to do a extrapolation, there can be errors caused by using an if on an array.

Since the value in question is generated by size(p2, /dim) and p2 can potentially be a 2 (or more) dimensional array, and the check is for a scalar I think the correct solution is to replace line 142 with
`        if p2_info[0] eq 0 then begin
`
and line 158 with:
`        if p2_info[0] eq 0 then tmp=tmp[0]
`
(In the current version, p2_info is used unsubscripted which works fine for 1-D but breaks for 2 or more).

**Comment by GillesDuvert** [comment]
Thanks a lot, will be patched ASAP!

**Comment by GillesDuvert** [comment]
BTW, interpol is false for non-vectors, extrapolation or not. This can be easily demonstrated on any vector by reforming it to some 2D array. My approach would be to use the internal interpol() functions present in GDL and not this error-prone procedure.

**Comment by GillesDuvert** [comment]
last title says all. Interpol as a procedure is too buggy, besides it needs to be fast.

**Comment by GillesDuvert** [comment]
rewritten in C in #9111 . Passes our test. Comments welcome.
