### ISSUE TITLE
A couple of missing library routines. (Supplied)

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#737]
Attached are possible routines for the HANNING and GAUSSIAN_FUNCTION functions.
(I renamed them as .txt since GitHub won't let me attach .pro).

[hanning.txt](https://github.com/gnudatalanguage/gdl/files/4402304/hanning.txt)
[gaussian_function.txt](https://github.com/gnudatalanguage/gdl/files/4402305/gaussian_function.txt)

**Comment by slayoo** [comment]
Thanks! Please do provide even a minimal test routine for inclusion in the test suite (it is automatically executed on Linux, OSX and Windows on every commit to the master branch)

**Comment by alaingdl** [comment]
Thanks. 

Not simple to find no basic test to HANNING() :(
Any idea around ?!

Currently finishing adding /double to GAUSSIAN_FUNCTION()
(I am considering to rename internal GAUSS1 to GDL_GAUSS or any other no trivial name
to avoid conflict in other codes)

Should push it soon (+ other minors changes)

**Comment by alaingdl** [comment]
not so easy to work in lockdown, too much telecons :)

I have cases for tests in GAUSSIAN_FUNCTION() but
I do have some numerical issues :(

ASAP, I will also update the change in POLYWARP by Igor + some tests :)

**Comment by alaingdl** [comment]
OK, I understood ! the output of  GAUSSIAN_FUNCTION() can be Odd or Even, without forcing output size to be Odd ... Finishing the test cases then push it
(other numerical tricks for POLYWARP ;)

**Comment by alaingdl** [comment]
* those two files are now in src/pro. I corrected an issue in GAUSSIAN_FUNCTION()
* I did write a test_gaussian_function.pro but it did now fully cover the code
* I have now clear idea for a test_hanning.pro (just graphical outputs are not useful)
