### ISSUE TITLE
different behaviour in recall_commands()

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#740]
There are two different behaviours in recall_commands() between IDL and GDL.
1) the order of the recalled commands list is reversed in GDL:
    case of IDL:
    IDL> print,1
       1
    IDL> print,2 
       2
    IDL> print,3
       3
    IDL> x=recall_commands()
    IDL> print,x(0:3)
        x=recall_commands() print,3 print,2 print,1

    case of GDL:

     GDL> print,1
       1
     GDL> print,2
       2
     GDL> print,3
       3
     GDL> x=reverse(recall_commands())
     GDL> print,x(0:2)
       print,3 print,2 print,1
2) The very last command is missing in GDL. The command recall_commands() does not return the entry "x=recall_commands()"

Did I miss something or is this a misbehaviour of GDL?

**Comment by alaingdl** [comment]
Thank you, I did not know this command existed !

I confirm the 2 bugs, reproduced here

We will also have to check what happen when history is not activated (through Readline/Editline)
(we may have a side effect)

**Comment by alaingdl** [comment]
OK, three lines to be change in gdlhelp.cpp

TBD with other minors changes ASAP

      DStringGDL* retVal = new DStringGDL(history_length, BaseGDL::NOZERO);
      for (SizeT i = 0; i < history_length; ++i)
        (*retVal)[history_length-i-1] = the_list[i]->line;

**Comment by alaingdl** [comment]
I like the fact we can have a super long history in GDL (eg I have 200 as a default)

but the current 
```
HELP, /recall
```
which is related to RECALL_COMMANDS(), don't stop every N lines (lines number of current terminal)
and I don't know how to manage it :(

**Comment by alaingdl** [comment]
ok, I have a draft working on my linux, TBC on OSX :)

**Comment by alaingdl** [comment]
OK, I think we can close it, which was the opportunity to clean up, years after, the mess I created around Editline (with the hope to use what OSX provided at 10.6 time, with a Readline version we cannnot compile easily on OSX 10.6)

I would like to mention I created a pagination processus for HELP, /recall, we can generalize it
quite easily in _gdlhelp.cpp_ when the output is more than one page of terminal.
