### ISSUE TITLE
pbs related to Readline, Editline & libedit

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#754]
I again have trouble(s) with Readline and Editline on OSX 10.12 & 10.14. I also realized that recent OSX do provide a Readline with _history.h_ (before 10.12, it did not, TBC). And we do have something in 
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/]$ ls -l readline/
total 0
lrwxr-xr-x  1 root  wheel  22 24 jan  2019 history.h -> ../editline/readline.h
lrwxr-xr-x  1 root  wheel  22 24 jan  2019 readline.h -> ../editline/readline.h
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226

Not not _libhistory.dylib_ around ... symbols are in _libreadline.dylib_ :(

Furthermore we can have around a lib. call libedit, which may or not (depending the version) deliver all the internal functions we use in Readline. 

to be check : 
in _readline.h_
\*rl_event_hook()
rl_initialize()
rl_prep_terminal()
rl_deprep_termina()l
rl_set_screen_size (rows, cols);
rl_resize_terminal();
rl_get_screen_size(&rows, &cols);

in _history.h_ 
history_get()  
add_history()
write_history()
read_history()
history_list()
clear_history()
stifle_history()

**Comment by alaingdl** [comment]
*rl_event_hook(),  rl_resize_terminal() and  history_list() are not provided by Editline.
I think rl_resize_terminal() is not important. I don't know what  *rl_event_hook() is for !
I suspect we can emulate history_list() using mechanics inside history() by Editline.

**Comment by GillesDuvert** [comment]
@alaingdl  everything containing 'event' in its name can be suspected to be pretty necessary and pretty difficult to replace as everything related to terminal reading is event-driven.
If readline is a problem with Mac, just remove this dependency on this platform, and instruct people to use 'rlwrap gdl' or use gdlde. The history mechanism should be kept however as it is needed by help,/recall
Note that with gnu readline, the ^R that searches for command in the history is case-sensitive, which is painful... I looked but found no one-liner solution...

**Comment by alaingdl** [comment]
My problem today is that some
```
 #if defined(HAVE_EDITLINE)
```
are not OK on 2 OSX I test GDL time to time. I would like to clarify. 

Worst, it is not stable between versions :(

the good news with another clone libedit available on Debian 10
ii  libedit-dev:amd64               3.1-20181209-1 amd64        BSD editline and history libraries 
ii  libedit2:amd64                  3.1-20181209-1 amd64        BSD editline and history libraries
does provide all what we need ... just some tests to finish :)

**Comment by alaingdl** [comment]
I am considering removing EditLine as a option in GDL (alternative to ReadLine) and I would like to have your feedback. What do you think on that ? 

Why ? because it did not provide _*rl_event_hook()_ and I did not find a simple way to solve that.

I think it is not a problem just to have ReadLine on GNU/Linux & *BSD.
The current versions of Readline are really simple to compile on recent OSX, and are available in Brew.

What is the status on MSwin ? Is that a problem ?

As I said, _rl\_resize\_terminal()_ is not important at all now.

At the end I find a simple solution to have  _history\_list()_ (why EditLine did not did it ? It is not really a problem in fact !)

```
HIST_ENTRY **the_list;
#if defined(HAVE_LIBREADLINE)
    the_list = history_list();
#endif
#if defined(HAVE_LIBEDITLINE)
    for( int h=0;h<history_length; ++h) *the_list[h] = history_get (h);
#endif
```

I also consider LibEdit, a BSD clone. But it would have even more complexyfied the code and still have similar problems.

I also saw that Julia is encapsulating ReadLine to simplified its use (especially for MSwin) but I think we don't need to do that.

Why did I think EditLine was OK in the past ? I suspect our CMake files were wrong and in fact we also also detected and used ReadLine ! (I made some changes and tests and now, when Readline is really off, I cannot compile on OSX, where the situation is quite complex because the SDK is evolving (content & location)  and availability of files also)

**Comment by slayoo** [comment]
likely related: #11, #227, #234, #558, #740

**Comment by GillesDuvert** [comment]
Of course eliminating unnecessary dependencies is very useful and I'm totally in favor of getting rid of editline and keep good ole gnu readline. Especially when we'll probably link GDL with other libraries for new functionalities (e.g., libcurl for networking).

**Comment by alaingdl** [comment]
OK, I will try to finishing that now (today or tomorrow). It is quite clear in my mind !
