### ISSUE TITLE
bizarre results with >print, seed

### ISSUE THREAD

**Issue by centarsirius** [gnudatalanguage/gdl#758]
i started doing some probability work and this code isn't working the way it should
ideal:
```
>seed=0
>rnd=randomu(seed)
>print, rnd, seed
  0.888299                     0    
```     
my problem
```
>seed=0
>rnd=randomu(seed)
>print, rnd, seed
   -0.888299                     0                     4   4607320143500780570   4608142317466048832   4608529006460262309   4608898915596565614   4611071224823271758   4607783394626785596   4607513277055462579
   4611347057865743650   4610077675719863343   4607793368341076124   4609948444713332755   4610599112471776383   4610018225872095171   4608446306433282784   4609210103410051609   4609405667066018682
 
[...]

   4607936706204747431   4610295489407859392   4610488723276619861   4608173060586239641   4607202433527633279   4610000384911431559   4610121367634252706   4608885945278257051   4609783648495938628
   4611103884081322908   4610973867861175147   4608086788605623938   4609316353731459555   4609579594844942652
```
this is a problem with the seed function `print, seed` gives the same output of garbage values
worked well when i was using version 0.9.5

**Comment by alaingdl** [comment]
Hi

for me, the results are similar in IDL & GDL, and do conform with IDL documentation (which is quite complex in this specific case !)
https://www.harrisgeospatial.com/docs/RANDOMU.html

We are in the special case :: 

_A named variable containing a scalar long integer: The scalar value is used to start a new sequence and the resulting state array is returned in Seed._

If you just do : 
```
rnd=RANDOMU(0.)
or
rnd=RANDOMU(0)
```
you will have a different behavior, a random number, the same since the seed will set up to zéro

**Comment by GillesDuvert** [comment]
please note that 'seed' is used to continue a random sequence once started.
(the sequence is 2^19937 long which is tremendously sufficient :smile:)
As we use the last version of the parallel mersenne twister, the sequence is of random numbers will not be the same as IDL;  idem for the seed which is as big as the number of threads in your computer and is recomputed each time one reset the seed ( so , not resetting the seed is a must).

**Comment by centarsirius** [comment]
@alaingdl 
```
GDL> seed=0
GDL> print,randomu(seed)
    0.0305810
GDL> seed=0.0
GDL> print,randomu(seed)
    0.0305810
```
i don't get different results
My professor told me that seed is different in IDL and GDL. He said if seed is undefined, then get random numbers and if seed is defined, we get pseudorandom numbers. So based on my understanding, seed generates a sequence of numbers and when we use `randomu(seed)` it generates pseudorandom numbers and links each pseudorandom number to one number from the seed sequence, right? so everytime we use the same seed we get same 'pseudorandom' numbers according to the nth iteration. 

![image](https://user-images.githubusercontent.com/43680969/82080174-b2474c80-9701-11ea-92a7-ab869bf85709.png)

So my main problem is when he runs the above command, he doesn't get the whole sequence, but i do. How? He's running version 0.9.5 if that helps.

**Comment by alaingdl** [comment]
Wouhaou, too many informations for me in a message !

* 0.9.5 : it is too old !

* for me, _if seed is undefined, then get random numbers and if seed is defined, we get pseudorandom numbers._ is a non sense since (1) a seed is always used (2) we always have pseudorandom numbers
(we use open source codes, you can read the codes)

* if you start recent GDL without SFMT, you we have the same numbers than IDL
(please look at "test_random.pro" too)
```
$ man doc/gdl.1
--no-dSFMT
              Tells  GDL  not  to  use  double  precision  SIMD  oriented Fast
              Mersenne Twister(dSFMT) for random doubles.   Also  disabled  by
              setting  the  environment  variable  GDL_NO_DSFMT  to a non-null
              value.
```

* why do you call : 
```
rnd =randomu(seed)
```
You should call : 
```
rnd =randomu(seed,1)
rnd_array =randomu(seed,nbp)
```
Please read carefully the IDL documentation.

**Comment by GillesDuvert** [comment]
you restarted seed to 0 when you typed seed=0 the 2nd time.
```
GDL> seed=0
GDL> print,randomu(seed)
    0.0305810
GDL> print,randomu(seed)
     0.213140
GDL> print,randomu(seed)
     0.299003
```
no random number in computers are random, they are all nubers taken in a pseudorandom serie.
Each seed number (and it is an integer that is used, even if seed is a real such as !DPI:
```
IDL> seed=!DPI & print,randomu(seed)
     0.550798
IDL> seed=3 & print,randomu(seed)   
     0.550798
```
) starts a sequence of 2^19937 pseudorandom numbers.
The [IDL](https://www.harrisgeospatial.com) site has all the documentation that GDL fails to have.

Incidentally if you want the same results as your professor has with IDL you can call gdl with the option --no-dSFMT:
```
$idl
(...)
IDL> seed=33 & print, randomu(seed)
     0.248510
IDL> print,randomu(seed)           
     0.689683
```
```
$ gdl --no-dSFMT
(...)
GDL> seed=33 & print, randomu(seed)
     0.248510
GDL> print,randomu(seed)
     0.689683
```

**Comment by centarsirius** [comment]
ya i know all random numbers generated by a computer are pseudo random as they follow the clock cycle, i was just saying that each seed has a defined sequence and the so called "random numbers" are mapped 1:1 to the seed number such that if someone initiates seed as x (some int) then the nth value of randomu(seed) will be the same for everyone who uses the same seed in GDL. I guess i understood that now, the no-dSFMT thing was not known to me and the same thing will happen to most of the people who use GDL for the first time, i guess we really need to have documentation.
