### ISSUE TITLE
missing gdl.pdf

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#760]
before we had a PDF file ... as mentioned in gdl.1 
 http://gnudatalanguage.sf.net/gdl.pdf

(an old copy here http://aramis.obspm.fr/~coulais/GDL/gdl.pdf circa 2012)

(I am cleaning up gdl.1 see #750)

**Comment by slayoo** [comment]
monolithic gdl.pdf proved for many reasons to be a wrong way to go...
during almost 20 years of development of GDL we have developed hardly any docs...
one of the key reasons is that GDL is only used by people who anyhow know/use IDL docs...
IDL docs are public and "officially" on the web

what is our realistic goal?

**Comment by GillesDuvert** [comment]
I believe time has passed here also:
```
GDL> ?
% Compiled module: ONLINE_HELP.
% Compiled module: FILE_WHICH.
% Compiled module: PATH_SEP.
% ONLINE_HELP: GDL pdf documentaion not found :(
GDL> xdg-open: unexpected argument 'http://aramis.obspm.fr/~coulais/IDL_et_GDL/Matrice_IDLvsGDL.html'
Try 'xdg-open --help' for more information.
```
We could probably provide a simple access to the official documentation by redirecting to it the rather small amount of IDL commands that GDL supports. Used IDL books from the 6 or 7 series are found everywhere and are also valuable. 
Based on that, the only "extra" information needed would be all the many little details in which GDL is not IDL, sometimes refered to as 'isues' here at GH.
And, I believe our testsuite/ files are very good examples and should be packaged alongside GDL.

**Comment by slayoo** [comment]
@acoulais I suggest we try to remove any leftover gdl.pdf from the web, including: http://aramis.obspm.fr/~coulais/GDL/gdl.pdf

**Comment by slayoo** [comment]
@GillesDuvert @acoulais What about removing online_help.pro and the code for handling "?" in dinterpretter.cpp (https://github.com/gnudatalanguage/gdl/blob/master/src/dinterpreter.cpp#L1026)

**Comment by GillesDuvert** [comment]
Actually `?something` is in IDL.
OK, your mileage may vary:
```
IDL> ?help
IDL> /opt/idl/idl84/bin/online_help_html: line 134: /usr/bin/firefox: No such file or directory
```
But that's the idea.
Our GDL long-forgotten "?" goes awry too:
```
GDL> ?help
% Compiled module: ONLINE_HELP.
% Compiled module: FILE_WHICH.
% Compiled module: PATH_SEP.
% ONLINE_HELP: GDL pdf documentaion not found :(
GDL> xdg-open: unexpected argument 'http://aramis.obspm.fr/~coulais/IDL_et_GDL/known_keywords.html#GDL_HELP'
Try 'xdg-open --help' for more information.
```
But nothing prevents the code to be modified as to go to the official doc.
**At the moment, since it does not work at all, you are right, this functionality should be removed.**

**Comment by alaingdl** [comment]
It is working on my old laptop, opening firefox then two pages : the official doc. & also the link in my page.

**Comment by alaingdl** [comment]
For me, we should not removing it but being preparing to rework on it.
In a todo list ...

**Comment by GillesDuvert** [comment]
never worked for me, actually.

**Comment by alaingdl** [comment]
* concerning _xdg-open_, I made some tests and now understood why is is not working for @GillesDuvert . (I clearly remember I did that long time ago when Debian renamed Firefox to Iceweasel and I had in real time problems with students in TP (testing codes on computers with me.) The online doc. was broken !)

* concerning the problem when Firefox is in the path and already running, I found a fix, could you please try with :
```
SPAWN, 'unset MOZ_NO_REMOTE; '+command
```
instead of 
```
SPAWN, 'unset MOZ_NO_REMOTE; '+command
```
at the end of _online_help.pro_
It also fix the case Firefox is already running

(I do not remember which GETENV always return the SHELL is /usr/bash even I try to start GDL in a _tcsh_ shell (for more tests))

**Comment by GillesDuvert** [comment]
no success. 
I see that the command sent is `browser+space+link1+space+link2+space+link3+background` but xdg-open cannot open 3 links in one command.
sending `command=browser+space+link1+space+background` works.

**Comment by alaingdl** [comment]
Yes I realized it and it was solved in my branch, now in Master. (I also updated  _minimal\_script.sh_)

**Comment by GillesDuvert** [comment]
correct in #882
