### ISSUE TITLE
Please provide a list of non-RC test failures

### ISSUE THREAD

**Issue by olebole** [gnudatalanguage/gdl#765]
As mentioned in #761, it is important for packagers to get a clear, machine readable list of failures that are expected (or accepted) to fail.
There is already something in `.travis.yml`: https://github.com/gnudatalanguage/gdl/blob/5af2bd8fc15b4634d4d3e51a9d0c320782c40cbf/.travis.yml#L273-L294:

This is however not really useful, since one needs to somehow put into the local (f.e. Debian) test structure manually, which currently needs to be done manually. Also, this list seems to be ad-hoc and specific for Travis; there may be more failures acceptable as well.

Therefore, it would be nice to either have the xfails marked directly in the test (if the test framework allows this), or to provide a plain text list that can be used in both Travis-CI and downstream tests.

**Comment by slayoo** [comment]
For the record, we should also phase out the awkward "Makefile.am" file which name is a remnant of autotools.

**Comment by slayoo** [comment]
Quoting #357:

> Let's separate the test files into:
> 
>     * testsuite/helpers (data files, common .pro files, etc)
> 
>     * testsuite/release (to be executed with "make check")
> 
>     * testsuite/sandbox (to be executed with "make check-sandbox" or alike)
> 
> 
> This would cause less confusion to users and packagers, and also enable us to at last get rid of the Makefile.am file and simply create list of files in CMake by searching the folder contents.

**Comment by slayoo** [comment]
@GillesDuvert @acoulais What about simply removing from Makefile.am those tests that are disabled in .travis.yml?

**Comment by alaingdl** [comment]
I don't know and I am busy still Thursday included.

We need to check again what is the real coverage of critical functions in testsuite, and also may be
allowing more _warning_ instead of _fatal_ ... 

And #771 and #775 are typically what we should try to avoid in the future.
(I have two interns/students this summer :)

**Comment by GillesDuvert** [comment]
Hi,
All the testsuite tests are useful and in fact it would be better to pass them all, and just have this list of 'mandatory' tests that authorize a build or not. I believe some of the little-used tests are false, i.e., they do not pass with IDL either. But in their vast majority they will show global improvements and regressions, they are of utmost importance.
Concerning #771 etc this is a classic problem of coverage. Any test should be in principle run not only on the 12 or so basic GDL types from Bytes to Double Precision Complex, but also, given our liberal use of the TPOOL parallelisation, on a series (1,3,7?) of TPOOL_NTHREADS as well as a serie of TPOOL_MIN_ELTS (1,3,17,513,12345667...). Complicated but I believe that using fix() and execute() this can be done rather elegantly.

**Comment by slayoo** [comment]
Just for the record - I consider solving this one essential before going with an rc3 (otherwise, it seems awkward to ask packagers to run tests, and we do want to ask packagers to run tests!).

Hope to make a PR with the above helpers/release/sandbox solution soon...

**Comment by slayoo** [comment]
Here it is: #789

**Comment by slayoo** [comment]
Closing as resolved, of course please report new issues in case we need to brainstorm more
