### ISSUE TITLE
wrong calculations when array size is bigger than 100.000 elements on Debian

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#771]
I noticed very strange behaviour if the array sizes get bigger than 100000 elements:

GDL - GNU Data Language, Version 1.0.0-rc.2 git

GDL> c=dindgen(100000) & print,max(c)
       63749.000

With an array of maximum 100.000 elements I get correct results:
GDL> c=dindgen(100000-1) & print,max(c)
       99998.000

This is on a debian release.
On my suse release I get correct results:
GDL> c=dindgen(100001) & print,max(c)
       100000.00

Can anybody help me?

**Comment by alaingdl** [comment]
Oups ... thanks for this important bug report ...

I can *partially* reproduce it on a debian machine, with different output
```
GDL> c=dindgen(100000) & print,max(c)
       83319.000
```
but not on my old U16.04

could you say which computer is using OpenMP, or not ? And which version of Gcc ??

Which tests fail ? (mack check)

Thanks

**Comment by alaingdl** [comment]
the problem is in MAX() because when I plot DINGEN() or any other INDGEN() I have a full slope to the end.

Why _test\_minmax.pro_ is crashing on all the computers I am testing with current GDL ?! But OK with IDL ?!

**Comment by alaingdl** [comment]
I did not see a good test on MAX() in the testsuite :((

**Comment by slayoo** [comment]
```
GDL> c=dindgen(100001) & print,max(c)
       74999.000
```
(0.9.9 from GDL Debian package)

**Comment by alaingdl** [comment]
Very few machines in my pool have the problem.

On a Debian 10 (buster) one, bad till 0.9.9 vanilla then recompiling 0.9.8 vanilla (26 March 2018)
and a TGZ (gdl-0.9.8svn180426) I have on 26 April 2018. 0.9.8 vanilla is OK, 26 April is KO.

I suspect we have to look in the history of minmax_include.cpp https://github.com/gnudatalanguage/gdl/commits/master/src/minmax_include.cpp introduced on April 5, 2018 ...

Up to now no Ubuntu nor OSX affected :(

**Comment by alaingdl** [comment]
OK, pb is clarify : pb with OpenMP on such debian : cmake .. -DOPENMP=off 
goes to good computations.

gcc version 8.3.0 (Debian 8.3.0-6) 
libgomp1:amd64

compiling with clang 7 give the same kind of problem

**Comment by alaingdl** [comment]
ok ! another point : if I set the number of threads, it is OK again :blush:
```
GDL> c=dindgen(100000) & print,max(c)
       87485.000
GDL> cpu, TPOOL_NTHREADS=45
GDL> c=dindgen(100000) & print,max(c)
       99999.000
```

Then the algo is ok, just we have a pb with OpenMP or passing argument initialization somewhere ...
(in some case, compiler may or not set to zero variables ...)

**Comment by alaingdl** [comment]
OK, I think it is solved. Missing update of    
```
 CpuTPOOL_NTHREADS=suggested_num_threads;
```
at line 102 in _gdl.cpp_

I have to make more checks, to write a test & also to try to understand why this number
is not updated as expected ...

And I succeed to reproduce the problem (and a solution) on a machine with where I created a load

**Comment by alaingdl** [comment]
How to trigger on the bug ? On a multicore machine with more than one core, start GDL with a number of threads lower than the cores number. E.g. on a 4 core computer
```
OMP_NUM_THREADS=3 sh ../quick_start_GDL.sh
```
and the output will be wrong (tests on various Linux)

I think I have a super simple solution (now tested on 3 machines, 4, 4 & 48 cores), in _gdl.cpp_ : 
```
diff gdl.cpp gdl.cpp_in_git  
101,105d100
<     CpuTPOOL_NTHREADS=suggested_num_threads;
<   } else {
< 
<     CpuTPOOL_NTHREADS=omp_get_num_procs();
<     omp_set_num_threads(CpuTPOOL_NTHREADS);
107,109d101
```

I am now writting tests

A.

**Comment by alaingdl** [comment]
Still exploring the code & the tests: _test\_minmax.pro_ which was discarded from the testsuite has several problems : 
* DIMENSION_TEST_MINMAX (inside this code) is running to the end in IDL, is crashing in GDL, apparently to TOTAL() apply on Complex type 
* now the output of the code, store in files (not very convenient :( is different from the outputs from IDL 8.6 on the same machine (yes I started with  --no-dSFMT and I checked that RANDOM() gave the same values)

**Comment by GillesDuvert** [comment]
The parallell computation of Max() is a bit tricky as it cuts the loop in as many chunks as there are threads, compute each local max, then in a second pass takes the max of this nthreads "local max".
If for some reason the number of threads is not  excactly `CpuTPOOL_NTHREADS`, then obviously the max has all chances to be wrong.
It seems I have forgotten to impose the number of threads in the `#pragma omp parallel`: bug!
one should use:
`#pragma omp parallel  num_threads(CpuTPOOL_NTHREADS)`
everywhere instead of `#pragma omp parallel` in `minmax_include.cpp`

**Comment by alaingdl** [comment]
the very small change I made on my side was enough up to now, but I am preparing more tests just in case (but I was diverted by #775 , now solved + tests)

**Comment by thierry-FreeBSD** [comment]
> Up to now no Ubuntu nor OSX affected :(

On FreeBSD-12:
```
  GDL - GNU Data Language, Version 1.0.0-rc.2
- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): /usr/local/share/gnudatalanguage/lib
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

GDL> c=dindgen(100000) & print,max(c)
       99999.000
GDL> c=dindgen(100001) & print,max(c)
       100000.00
```

**Comment by jtappin** [comment]
Just a quick note to say that the issue is also seen (in v0.9.9) on Manjaro with a 6-core AMD cpu:
````
GDL> tmp = dindgen(6000000)
GDL> print, min(tmp, max=mx), mx
       0.0000000       999999.00
GDL> print, min(tmp, max=mx), mx, max(tmp)
       0.0000000       999999.00       999999.00
GDL> rtmp = reverse(tmp)
GDL> print, min(rtmp, max=mx), mx, max(rtmp)
       5000000.0       5999999.0       5999999.0
````
I don't have any non-default thread settings.

**Comment by slayoo** [comment]
@jtappin could you please confirm if the committed solution works - i.e., please confirm if 1.0.0-rc3 or master branch version does not have the issue on the machines you are testing on, thanks

**Comment by jtappin** [comment]
@slayoo It seems to be OK in 1.0.0-rc3 :-)

**Comment by slayoo** [comment]
thanks for feedback!

**Comment by GillesDuvert** [comment]
no test written in 1 year, closing
