### ISSUE TITLE
TOTAL() crashes with input DComplex + Dim param + /double

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#775]
```
dim=indgen(4)+2
a=make_array(dim, /index, type=9)
e=total(a, 2,/double)
```
or, in one line : 
```
e=total(dcomplex(dist(12)),2,/double)
```
The combination of Dcomplex type, dim param and /double is mandatory.

This was previously tested in DIMENSION_TEST_MINMAX which was a procedure in _test\_minmax.pro_ (see #771)

See from my side, this bug was introduced between 2019-10-08 and 2019-10-14

**Comment by alaingdl** [comment]
catch it ! Thanks to 
```
cmake .. -DCMAKE_BUILD_TYPE=Debug -DPYTHON=off
```
then Valgrind : around line 3257 need to be : 
```
        case GDL_COMPLEXDBL: return total_over_dim_template<DComplexDblGDL>(static_cast<DComplexDblGDL*> (p0), srcDim, sumDim - 1, nan);
```

**Comment by alaingdl** [comment]
the basic problem is now solved (#776 ) but I discovered another problem, closely related, but I was not able to set up a small case up to now. Then not closing now :(

**Comment by alaingdl** [comment]
Yes, the problems are now
```
e=total(dcomplex(dist(12)),2,/double,/cumul)
```
(it is OK for /nan ;)
and also : 
```
e=total(dcomplex(1),0,/cumul,/nan,/double)
```

**Comment by GillesDuvert** [comment]
same problem, same solution: a lot of cut/paste and I sometimes forgot to put DComplexDblGDL instead of DComplexGDL everywhere GDL_COMPLEXDBL appears.

**Comment by alaingdl** [comment]
Please do not close it as long as we did not have all the cases again covered in the testsuite
(cleaning up of _test\_minmax.pro_ (thanks @slayoo years ago !), the code which help us to detect these 3 bugs)

**Comment by GillesDuvert** [comment]
no test written in 1 year, closing
