### ISSUE TITLE
Long64 problem in Windows  Version 1.0.0-rc.2

### ISSUE THREAD

**Issue by jaymurthy** [gnudatalanguage/gdl#782]
GDL> print,value
3950000000
GDL> help,value
VALUE           STRING    = '3950000000'
GDL> print,long64(value)
            2147483647
GDL> print,long(value)
  2147483647
GDL>

**Comment by slayoo** [comment]
For the record, here's what happens on 64 bit Linux:

```
GDL> value='3950000000'
GDL> print, long64(value)
            3950000000
GDL> print, long(value)
  -344967296
```

**Comment by slayoo** [comment]
and thanks for reporting it!

**Comment by GillesDuvert** [comment]
on a **32 bit machine**
```
IDL> print, long(value)
  2147483647
```
so @jaymurthy result is identical for 64 bits and 32 bits ... @jaymurthy what is your version of GDL, where did you get it?

**Comment by jaymurthy** [comment]
Here is the version:
GDL - GNU Data Language, Version 1.0.0-rc.2 git
GDL> print,!version
{ x64 Windows Windows Windows 8.2 Jun 10 2020      32      64}
and I got it from Sylwester's build:
https://ci.appveyor.com/project/slayoo/gdl/branch/master

Happy to do what I can to help.
Jayant

**Comment by slayoo** [comment]
>  and I got it from Sylwester's build

Just to give due credit: these are @maynardGK's builds :)

**Comment by GillesDuvert** [comment]
ah, this comes from the use of the built-in function strtol() in this code.
Apparently under linux, strtol() is versatile enough to do better than 32 bits results. The correct function to use id strtoll() (and strtoull() for the ULONG64() version.
Let's see if the windows compiler likes it.

**Comment by GillesDuvert** [comment]
corrected in https://ci.appveyor.com/project/slayoo/gdl/builds/33570264/job/7xkrurok9x7vmpmm/artifacts and soon in main distrib.
for testsuite, we shoudl have the following cases added:
```
GDL> value='-3950000000000'
GDL> print, ulong64(value)
  18446740123709551616
GDL> print, long64(value)
        -3950000000000
```
