### ISSUE TITLE
incorporate Debian patch for ACCEPT_USE_OF_DEPRECATED_PROJ_API_H

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#783]
@olebole @GillesDuvert 
Should we use it in the main repo: https://salsa.debian.org/debian-astro-team/gnudatalanguage/-/blob/master/debian/patches/Add-support-for-PROJ.4.patch

```diff
diff --git a/src/basegdl.hpp b/src/basegdl.hpp
index aba21a7..1d5c148 100644
--- a/src/basegdl.hpp
+++ b/src/basegdl.hpp
@@ -15,6 +15,8 @@
  *                                                                         *
  ***************************************************************************/
 
+#define ACCEPT_USE_OF_DEPRECATED_PROJ_API_H
+
 #ifndef BASEGDL_HPP_
 #define BASEGDL_HPP_

```

**Comment by GillesDuvert** [comment]
Strange, do we really need this? I believe I removed all those old stuff a long time ago.

**Comment by slayoo** [comment]
This patch is no longer in Debians repo, so I assume this is resolved
