### ISSUE TITLE
Can't open windown on 2nd monitor

### ISSUE THREAD

**Issue by jaymurthy** [gnudatalanguage/gdl#785]
window,xs=1200,ys=600,xp=200,yp=1400 opens a window on the top of my first monitor. I can then move it physically so it's all ok. FL works ok on this - I can open a window anywhere.

  ARCH            STRING    'x64'
   OS              STRING    'Windows'
   OS_FAMILY       STRING    'Windows'
   OS_NAME         STRING    'Windows'
   RELEASE         STRING    '8.2'
   BUILD_DATE      STRING    'Jun 10 2020'
   MEMORY_BITS     INT             32
   FILE_OFFSET_BITS
                   INT             64

**Comment by GillesDuvert** [comment]
Works on linux/bsd. The windows driver is a completely different code, so the windows label.

**Comment by GillesDuvert** [comment]
to be tested again with new version that uses only wxwidgets.
