### ISSUE TITLE
Add qhull-library related functions/procedures, such as QHULL

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#79]
As reported by @GillesDuvert at SF.net:

QHULL is partially used in GDL. Several useful functions can be added easily starting from the current implementation. See discussion in (closed) patch: https://sourceforge.net/p/gnudatalanguage/patches/87/

**Comment by slayoo** [comment]
BTW, long long time ago at ftp://modis-atmos.gsfc.nasa.gov/arnold/test_triangulate.tar.gz
there was the attached file - will likely come in handy.
[test_triangulate.tar.gz](https://github.com/gnudatalanguage/gdl/files/1886774/test_triangulate.tar.gz)

**Comment by GillesDuvert** [comment]
... GDL does not pass yet this test, although triangulate has been written recently, using true and tested historical libraries. Reported as bug #141

**Comment by GillesDuvert** [comment]
changed title as QHULL is in fact not used at all now, but will be if womebody writes the QHULL procedure.
