### ISSUE TITLE
OLD_WXWIDGETS (plplot option) issue

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#790]
As pointed out by @opoplawski, GDL README file mentions that:

```
... plplot > 5.11 needs absolutely to be compiled with its "old" wxWidgets driver,
using the Cmake switch -DOLD_WXWIDGETS:BOOL=ON ...
```

The discussion in #761 seems to suggest that it is an outdated statement.
@maynardGK @GillesDuvert please confirm if we can remove this sentence from the README?

Also as pointed out by @opoplawski, in the Appveyor build scripts, this option is actually indeed used: https://github.com/gnudatalanguage/gdl/blob/master/scripts/appveyor_plplot.bat#L5
Would it be OK to remove it?

**Comment by slayoo** [comment]
Actually, @maynardGK just tried it here:
https://github.com/gnudatalanguage/gdl/commit/2f1c402656#diff-595948505a143fc06254261955fc56d2R105

**Comment by GillesDuvert** [comment]
tested [build 1321](https://github.com/gnudatalanguage/gdl/pull/774#issuecomment-646421832) that does not force OLD_WXWIDGETS, works OK except the same (unrelated) issue seen [here](https://github.com/gnudatalanguage/gdl/issues/761#issuecomment-646157080)
Sentence removed in README.

**Comment by slayoo** [comment]
thanks! closing then

**Comment by maynardGK** [comment]
> tested [build 1321](https://github.com/gnudatalanguage/gdl/pull/774#issuecomment-646421832) that does not force OLD_WXWIDGETS, works OK except the same (unrelated) issue seen [here](https://github.com/gnudatalanguage/gdl/issues/761#issuecomment-646157080)
> Sentence removed in README.

build 1321 actually still includes OLD_WXWIDGETS but all after that will not.   If the commit comment says OLD_WIDGWIDGETS=OFF then it should be build 1322 and it is correctly tested.
(begins on commit caf4c27)

**Comment by GillesDuvert** [comment]
identical results with build 1323. OLD_WXWIDGETS is not needed anywhere.
