### ISSUE TITLE
RETALL crash

### ISSUE THREAD

**Issue by fawltylanguage** [gnudatalanguage/gdl#799]
~> echo RETALL > test.pro
~> gdl test.pro
  GDL - GNU Data Language, Version 1.0.0-rc.2 git
- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): /tmp/gdl/share/gnudatalanguage/lib
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

terminate called after throwing an instance of 'GDLInterpreter::RetAllException'
Magick: abort due to signal 6 (SIGABRT) "Abort"...
Aborted (core dumped)

**Comment by alaingdl** [comment]
Hi Lajos ! How do you do ?

Thanks for the bug report, I reproduced it on my side :(

A.

**Comment by alaingdl** [comment]
And this bug existed since a while (going back to 0.9.4 and still here !)

**Comment by GillesDuvert** [comment]
Actually it's here from the start I believe, so it's a feature :smile: .
Patched and soon in the repo.
