### ISSUE TITLE
implement READ_CSV

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#81]
As requested at SF.net: https://sourceforge.net/p/gnudatalanguage/support-requests/37/
GDL would benefit from having the READ_CSV function implemented.
Should be easily doable given there are plenty of open source csv-reading libraries around.

See also: https://www.harrisgeospatial.com/docs/read_csv.html

**Comment by Steve-Albers** [comment]
I found this apparently homegrown version online. It is simpler than the IDL version though perhaps a good start.

http://lcd-www.colorado.edu/~axbr9098/teach/ASTR_3760/SBO_project/idl/read_csv.pro

Another one is here:

https://svn.ssec.wisc.edu/repos/bennartz_group/hiley/cloudsat_project/read_csv2.pro

**Comment by slayoo** [comment]
Thanks! I've just kindly inquired with the owner of the first website if the code could be legally borrowed for GDL.

**Comment by slayoo** [comment]
Today I did the same regarding the second link, thanks again!

**Comment by Steve-Albers** [comment]
Sounds good - it will be interesting to see how these can integrate into the GDL library.

**Comment by alaingdl** [comment]
please note that the READ_ASCII in IDL has an undocumented keyword /CVS ... which is used internally by READ_CSV() when calling READ_ASCII ...

then the current GDL version of READ_ASCII failed on CSV files ...

**Comment by slayoo** [comment]
added in #666 (still needs adding a test - help welcome!)
