### ISSUE TITLE
Assignment to loop variable warning

### ISSUE THREAD

**Issue by astromark** [gnudatalanguage/gdl#811]
I'm testing out some code that works fine on IDL. When compiling one of the modules I get the following warning.

`% Warning: Assignment to loop variable detected.`

The module does function properly, although it does take a long time to compile, which may be related to this. What does this warning mean? Is there an easy way to determine which part of the code triggers it, other than running the code step by step?

**Comment by slayoo** [comment]
Just for clarity: is this warning emitted by both IDL and GDL?

**Comment by astromark** [comment]
The warning is not emitted by IDL, just in GDL.

**Comment by GillesDuvert** [comment]
Normally it means that you use a loop variable other than an index, for example by assigning a new value to it:
```
GDL> for i=0,3 do begin i=4 & print,i & end
% Warning: Assignment to loop variable detected.
       4
```
Which may have dire effects since you  probably expected:
```
GDL> for j=0,3 do begin i=4 & print,i & end
       4
       4
       4
       4
```


note that IDL does the same without warning:
```
IDL> for i=0,3 do begin i=4 & print,i & end
       4
```

**Comment by slayoo** [comment]
So, what we could improve on our side would be to include line/file info in the warning message...

**Comment by GillesDuvert** [comment]
@slayoo certainly.
@astromark Either your 'code that works fine on IDL'  is written in a way that, even if the loop variable is indeed overwritten that does not harm the results (and in this case it would be safer to edit the code to avoid any confusion) OR, and this is my worry, GDL is wrong in deducing that the loop variable is altered. Can you investigate?

**Comment by astromark** [comment]
@slayoo Yes, that would be very useful.
@GillesDuvert Thanks for the help. I had a suspicion that may be the case but couldn't immediately see the line that was the problem. I've managed to track it down and determined that it's written that way as quick way to exit the for loop (although is then also followed by a GOTO statement that does the same thing), so no problem with GDL.

I've also determined that this is not the reason for the code being slow to compile. That's another part of the code - but that's an investigation for another day.

**Comment by GillesDuvert** [comment]
@astromark slowness _in compilation_ comes usually from the overhead in determining if '(' would be perhaps a '[' (old syntax). Removing as much as possible the unneeded '(', adhering to the new syntax with '[]' for arrays and calling gdl with `gdl --fussy` or putting `GDL_IS_FUSSY` in the environment may help. `gdl --fussy` will find all the suspected '()' during compilation, but only one at a time...
