### ISSUE TITLE
Compatibility mode array addressing fails for de-referenced structure

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#812]
This came up in an example from #165.

failure comes after de-referencing the pointer - double indirect is not needed.

````
GDL> readop = {bflux:[2e-3,1.5e-3],wvband:[850.,1300.]}
GDL> wvb=readop.wvband(0)  ;  Works ok like this
GDL> p=ptr_new(readop)
GDL> t=(*p).wvband(0)
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
````

**Comment by GillesDuvert** [comment]
xtetris hangs GDL just for that. :smile:

**Comment by GillesDuvert** [comment]
this is an interpreter bug in the old confusion between ( and [ style : GDL> t=(*p).wvband[0] works.

**Comment by GillesDuvert** [comment]
the ANTLR interpreter must check if X.Y(Z) is X.Y[Z] before trying a function Y of the object X

**Comment by GillesDuvert** [comment]
will be cured by  #1588
