### ISSUE TITLE
GDL multithreading feature

### ISSUE THREAD

**Issue by centarsirius** [gnudatalanguage/gdl#813]
Does GDL have the capability to use multithreading? I think we can change preferences in most apps whether we want it to be able to use multithreading or not. In Ubuntu where i work with GDL, i ran a process to check it and looked at the task manager, it was a long process and i wanted to speed it up but for the whole run, it only used one thread fully, other threads were idling, but at  irregular intervals it used to change to another thread which then ran at 100% while others idled, but GDL was never able to use more than one thread. Can this feature be implemented or is GDL too old to have significant performance boost with multithreading or would it be too much work with not much RoI?

![image](https://user-images.githubusercontent.com/43680969/86523344-cc431700-be88-11ea-8d41-d2063f2da62a.png)

**Comment by slayoo** [comment]
GDL does have significant performance boost with multi-threading, provided it was enabled at the time of compilation. The OpenMP setting is the key. 

GDL's thread pool is generally implemented to follow IDL's: https://www.harrisgeospatial.com/docs/controlling_the_idl_thre.html

In addition, external libraries used by GDL may also feature multi-threaded parallelism, e.g. GraphicsMagick: http://www.graphicsmagick.org/OpenMP.html

**Comment by alaingdl** [comment]
Some (most) internal functionalities already may run on multi-core. You can try the benchmark to see what happen for cores

See also how it is set in  !cpu (HELP, /struct, !cpu)

For sure on loops (for, while, repeat ...) it is not easy !

**Comment by GillesDuvert** [comment]
According to @centarsirius plot, his GDL version never uses more than 1 thread, which should not happen.
What is this version? A recent Ubuntu? A self-compiled version?

**Comment by centarsirius** [comment]
Oh, i dont think i messed with threading option when i compiled, it was about a month ago, so the version would be 1.0.rc2 i guess. So, if i want multithreading, i would have to recompile, but which option should i look out for? Thank you.

**Comment by slayoo** [comment]
The option to look out for is OpenMP (-DOPENMP=ON)
