### ISSUE TITLE
unable to parse string, complaining about right hand brace

### ISSUE THREAD

**Issue by ghost** [gnudatalanguage/gdl#814]
I get the following error message when I try to run the IDL file bcalcstix19i.1stquad.pro through GDL.
STRING: Format parser: expecting RBRACE, found 'h'.   Execution halted at: BCALCSTIX19I       152 /home/pgreninger/IRIout/thesis_driver_programs/NWC/bcalcstix19i.1stquad.pro .
The parentheses are balanced in line 152.  There are 24 data files, which I may not be able to upload. I have provided just the first to see if it can get through the first reading. In the include data file vec.out...remove the .txt label. 
In the include execute file iri35.txt remove the .txt. In the include execute file daymonth remove the .txt label, and put in .exe.  In the GDL .pro file remove the .txt label.

[vec.out_5_year_ave_skip_June_thru_Dec_20072005Jan_0.txt](https://github.com/gnudatalanguage/gdl/files/4880912/vec.out_5_year_ave_skip_June_thru_Dec_20072005Jan_0.txt)

[daymonth.txt](https://github.com/gnudatalanguage/gdl/files/4880978/daymonth.txt)

[bcalcstix19i.1stquad.pro.txt](https://github.com/gnudatalanguage/gdl/files/4881193/bcalcstix19i.1stquad.pro.txt)

[Bmag660+.txt](https://github.com/gnudatalanguage/gdl/files/4880851/Bmag660%2B.txt)

File IRIout.txt may be found in dropbox https://www.dropbox.com/sh/wecyzo9tf5r4otx/AACLiuiipt-q3AGJ-orhTfJIa?dl=0, under DEMETER>DATA>Driver programs.

**Comment by maynardGK** [comment]
My browser gives me this line
````
    title = string(format='("/home/pgreninger/IRIout/thesis_driver_programs/NWC/DEMETER/vec.out_5_year_ave_skip_June_thru_Dec_2007",(I4)(A3),"_"$,(I1))',istartyear,month(istartmonth-1),m) 

````

Which has a "$" embedded.

**Comment by GillesDuvert** [comment]
The '$' is spurious and would not pass with IDL either:
```
 IDL> title = string(format='("/home/pgreninger/IRIout/thesis_driver_programs/NWC/DEMETER/vec.out_5_year_ave_skip_June_thru_Dec_2007",(I4)(A3),"_"$,(I1))',istartyear,month(istartmonth-1),m) 
% Expected comma or slash
  "("/home/pgreninger/IRIout/thesis_driver_programs/NWC/DEMETER/vec.out_5_year_ave_skip_June_thru_Dec_2007",(I4)(A3),"_"$,(I1))"
                                                                                                                        ^
% Execution halted at: $MAIN$          
```
However GDL, before the '$', chokes on `(I4)(A3)`, the correct format would be `(I4),(A3)` or, better `I4,A3` as there is no need for () here.
This is a 'feature', as AFAIK the documentation on formats in IDL never suggests a construction like (I4)(A3) is possible.
A good side of GDL is that the script can be edited. especially this piecewise script that need to be edited each time anyway since all the Paths are written and thus the procedure cannot be run on different files or at other places.

**Comment by ghost** [comment]
The $ sign was my mistaking trying to get it to run.  But you found the error!  Thanks greatly.
