### ISSUE TITLE
PLPLOT and XWIN

### ISSUE THREAD

**Issue by battalio** [gnudatalanguage/gdl#826]
I have successfully built gdl on MacOS 10.13.6 and have scripts running, but I cannot plot anything with the error:  

% PLplot installation lacks the requested driver:  xwin

Even just plot,findgen(10) generates the error.  XQuartz launches when starting gdl.

**Comment by maynardGK** [comment]
The device drivers (eg xwin.so) for plplot are built separately and kept as shareable images.  The file may be present in your system but not where plplot expects. (check /usr/lib and /usr/lib64). 
If you can't find the file, you can build plplot (easily done from Sourceforge source) and install to /usr/local
````
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/  \
 -DDEFAULT_NO_CAIRO_DEVICES=ON -DDEFAULT_NO_QT_DEVICES=ON \
-DDEFAULT_NO_BINDINGS=ON -DENABLE_cxx=ON -DENABLE_wxwidgets=ON \
-DPLD_pdf=OFF -DPLD_psttf=OFF \
<plplot source tree location> >&cmake.out
````
then, after installing (assuming you don't need plplot for other apps), and in a separate directory,
````
cmake -DPLPLOTDIR=/usr/local \
-DNETCDF=ON -DHDF5=ON -DWXWIDGETS=ON \
-DHDF=ON  \
-DGLPK=OFF -DGRIB=OFF \
-DUDUNITS2=OFF \
-DPYTHON=OFF \
-DTIFF=ON -DGEOTIFF=ON -DLIBPROJ4=ON \
-DCMAKE_INSTALL_PREFIX=/usr/local/ \
-DMAGICK=OFF -DGRAPHICSMAGICK=ON \
   <gdl source tree location> >& cmake.out

````
-D<option> OFF/ON  according to your desired build.

**Comment by GillesDuvert** [comment]
Did you build GDL with wxWidgets? If yes, then perchance 'gdl --use-wx' (that uses the plplot-wxwidgets driver for plots) may work?

**Comment by battalio** [comment]
Building plplot from source and pointing to the directory fixed it.  Thanks.
