### ISSUE TITLE
SPLINE function not found

### ISSUE THREAD

**Issue by Titanosaurus** [gnudatalanguage/gdl#827]
I see that the SPLINE function doesn't work as in IDL. Can this be fixed? Is there something I can do about it before the fix?

Example:
```
GDL> X = [2.,3.,4.]
GDL> Y = (X-3)^2
GDL> T = FINDGEN(20)/10.+2
GDL> Z = SPLINE(X, Y, T)
% Ambiguous: Variable is undefined: SPLINE or: Function not found: SPLINE
% Execution halted at: $MAIN$
```

**Comment by GillesDuvert** [comment]
Not in GDl as the function is easily found on the net. However, it seems in this case that [this source](https://github.com/callumenator/idl/blob/master/external/ICUR/icur/spline.pro) is available without licensing problems. Perhaps this can be an easy add.

**Comment by GillesDuvert** [comment]
Spline added.
