### ISSUE TITLE
Record terminator slash (/) in format not supported

### ISSUE THREAD

**Issue by lwymarie** [gnudatalanguage/gdl#830]
IDL input and output: 

IDL>       print,'NOTE: Calling sequence to IFSF_LINELIST has changed. If vacuum',$
IDL>             '      wavelengths are required, or other wavelength units, or ',$
IDL>             '      to suppress this message, use ARGSLINELIST structure in ',$
IDL>             '      initialization procedure. Default is now air waves.',$
IDL>             format='(A0/A0/A0/A0)'
NOTE: Calling sequence to IFSF_LINELIST has changed. If vacuum
      wavelengths are required, or other wavelength units, or 
      to suppress this message, use ARGSLINELIST structure in 
      initialization procedure. Default is now air waves.

GDL output is not as expected: 

GDL> print,'NOTE: Calling sequence to IFSF_LINELIST has changed. If vacuum',$
GDL> '      wavelengths are required, or other wavelength units, or ',$
GDL> '      to suppress this message, use ARGSLINELIST structure in ',$
GDL> '      initialization procedure. Default is now air waves.',$
GDL> format='(A0/A0/A0/A0)'
% PRINT: Infinite format loop detected.
% Execution halted at: $MAIN$

**Comment by GillesDuvert** [comment]
Thanks for the report!
in other terms,
`print,"a","b",format='(a/a)'` is badly handled by the GDL interpreter.
The documentation says that '/' and ',' are both format separators, not only ','. 
To be solved...
 Note that `format='(a/,a)' ` works and is a temporary solution.
