### ISSUE TITLE
Break of API with wx-3.1

### ISSUE THREAD

**Issue by dirteat** [gnudatalanguage/gdl#831]
Just a head-up for some API breakage introduced by wx-3.1, as usual... :(

https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.1.4/docs/changes.txt

gdl-1.0.0-rc.3/src/gdlwidget.hpp:1550:38: error: 'wxPaintEvent::wxPaintEvent(wxWindowBase*)' is private within this context
 1550 |     event = new wxPaintEvent( GetId());
      |                                      ^
In file included from /usr/include/wx-3.1/wx/wx.h:24,
                 from /home/iurt/rpmbuild/BUILD/gdl-1.0.0-rc.3/src/gdlwidget.hpp:26,
                 from /home/iurt/rpmbuild/BUILD/gdl-1.0.0-rc.3/src/dialog.cpp:29:
/usr/include/wx-3.1/wx/event.h:2379:14: note: declared private here
 2379 |     explicit wxPaintEvent(wxWindowBase* window = NULL);
      |              ^~~~~~~~~~~~
In file included from /home/iurt/rpmbuild/BUILD/gdl-1.0.0-rc.3/src/dialog.cpp:29:
/home/iurt/rpmbuild/BUILD/gdl-1.0.0-rc.3/src/gdlwidget.hpp:1550:36: error: invalid conversion from 'wxWindowID' {aka 'int'} to 'wxWindowBase*' [-fpermissive]
 1550 |     event = new wxPaintEvent( GetId());
      |                               ~~~~~^~
      |                                    |
      |                                    wxWindowID {aka int}
In file included from /usr/include/wx-3.1/wx/wx.h:24,
                 from /home/iurt/rpmbuild/BUILD/gdl-1.0.0-rc.3/src/gdlwidget.hpp:26,
                 from /home/iurt/rpmbuild/BUILD/gdl-1.0.0-rc.3/src/dialog.cpp:29:
/usr/include/wx-3.1/wx/event.h:2379:41: note:   initializing argument 1 of 'wxPaintEvent::wxPaintEvent(wxWindowBase*)'
 2379 |     explicit wxPaintEvent(wxWindowBase* window = NULL);
      |                                         ^
gmake[2]: *** [src/CMakeFiles/gdl.dir/build.make:553: src/CMakeFiles/gdl.dir/dialog.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/gdl-1.0.0-rc.3/build'
gmake[1]: *** [CMakeFiles/Makefile2:188: src/CMakeFiles/gdl.dir/all] Error 2
gmake[1]: Leaving directory '/home/iurt/rpmbuild/BUILD/gdl-1.0.0-rc.3/build'
gmake: *** [Makefile:163: all] Error 2

**Comment by djsuson** [comment]
I just encountered the same problem. Did this get resolved?

**Comment by GillesDuvert** [comment]
Seem to be solved with the coming rewriting of the widgets. In a few weeks I hope.

**Comment by GillesDuvert** [comment]
please test with current sources on GH

**Comment by brandy125** [comment]
gdl-1.0.0-rc.3 on Linux Suse_Tumbleweed 5.11.6-1-default #1 SMP Thu Mar 11 16:11:36 UTC 2021 (7358b30) x86_64 x86_64 x86_64 GNU/Linux after gh repo clone:

gdlwidget.hpp:1969:35: error: ‘wxPaintEvent::wxPaintEvent(wxWindowBase*)’ is private within this context
 1969 |   event = new wxPaintEvent(GetId());
      |                                   ^

and

gdlwidget.hpp:1969:33: error: invalid conversion from ‘wxWindowID’ {aka ‘int’} to ‘wxWindowBase*’ [-fpermissive]
 1969 |   event = new wxPaintEvent(GetId());
      |                            ~~~~~^~
      |                                 |
      |                                 wxWindowID {aka int}


any news on that?

**Comment by GillesDuvert** [comment]
Hi @brandy125 , would you remove the lines 1967 to 1975 in gdlwidget.hpp (they define SendPaintEvent() that is not used and indeed is forbidden according to the 3.1 documentation). Then recompile?

**Comment by brandy125** [comment]
almost runs to the end:

/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/gdl.dir/saverestore.cpp.o: undefined reference to symbol 'xdr_opaque@@TIRPC_0.3.0'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libtirpc.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/gdl.dir/build.make:2396: src/gdl] Error 1
make[1]: *** [CMakeFiles/Makefile2:185: src/CMakeFiles/gdl.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

What is wrong here?

**Comment by fawltylanguage** [comment]
Add -ltirpc somewhere in src/CMakeFiles/gdl.dir/link.txt after configuration.

**Comment by brandy125** [comment]
Thank you @fawltylanguage and @GillesDuvert, now it worked!

**Comment by brandy125** [comment]
I still have to write every time 

-ltirpc somewhere in src/CMakeFiles/gdl.dir/link.txt after configuration

can this be done somehow automatically from your side?

**Comment by GillesDuvert** [comment]
@brandy125 details of what library to link are not part of GDL, as they are handled by 'cmake'. (in other terms, the link.txt file is automatically generated). GDL does not specifically use irpc, the dependency is indirect, and may come from whatever installed library. I'm afraid there is nothing we can do on the GDL side.

**Comment by brandy125** [comment]
Hi @GillesDuvert, thanks for pointing this out. Let me just ask you one more thing because it is not clear for me if it is ok like it is.

If I run cmake .. the configuration finishes successfully (at least without error message):
```
...
RPC                    ON (libs:; headers:/usr/include)
...
```

If I compile I get following error message:

```
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: CMakeFiles/gdl.dir/saverestore.cpp.o: undefined reference to symbol 'xdr_opaque@@TIRPC_0.3.0'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/libtirpc.so.3: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/gdl.dir/build.make:2426: src/gdl] Error 1
make[1]: *** [CMakeFiles/Makefile2:185: src/CMakeFiles/gdl.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
```

If I configure with

```
cmake .. -DRPCDIR=/usr/include/rpc
```

I get the same error message.

The only solution in both cases is to edit the file src/CMakeFiles/gdl.dir/link.txt after configuration and put -ltirpc in there, then in both cases the compilation finishes.

Which directory I have to specify with -DRPCDIR? The directory /usr/include/rpc exists. I also tried with 

cmake .. -DRPCDIR=/usr/lib
and
cmake .. -DRPCDIR=/usr/lib64
and some other directories.

Do you have any idea how it is on Suse Tumbleweed 5.11.11? 

Thanks

**Comment by GillesDuvert** [comment]
@brandy125 
what gives 
`pkg-config --libs libtirpc`
?

**Comment by GillesDuvert** [comment]
clearly #338 is not fully solved.

**Comment by brandy125** [comment]
@GillesDuvert, this command gives:
bash$ pkg-config --libs libtirpc
-ltirpc 
bash$

**Comment by tckosvic** [comment]
Success !!  The suggestion below got past the linking errors.

"  -ltirpc somewhere in src/CMakeFiles/gdl.dir/link.txt after configuration  "

Makes an awkward compilation with having to edit a link text  file after cmake and before make.  But it finished.  Configuration, also, was done with nothing turned off.

Now, I have to see if it runs and gets some results.  Anyone have a good test series?

Then, I need to get onto gdlde.  I know nothing about gradle.

The one I have completely compiled is the cloned current version from github;  not the download labeled "latest".

thanks,   tom kosvic

**Comment by slayoo** [comment]
> Now, I have to see if it runs and gets some results. Anyone have a good test series?

Please try ``make check`` - this is what is executed on CI runs.
