### ISSUE TITLE
DEFSYSV, /TEST

### ISSUE THREAD

**Issue by PaddyLeahy** [gnudatalanguage/gdl#834]
Error message:
DEFSYSV: Keyword parameter <TEST> not allowed in call to: DEFSYSV

Tested under both unix and Windows 10 (win64). 

There is a simple workaround: test for existence with EXIST=is and create only if not is. Still, it means I have to change my code to run under GDL!

**Comment by GillesDuvert** [comment]
An easy add, good for newcomers. TEST (introduced after 8.4)  just permit to do the job if the system variable does not exist and silently nothing if not.

**Comment by alaingdl** [comment]
It has been done few days ago, but no test around, I think ...

```
GDL> #defsysv
Internal PROCEDURE : DEFSYSV,[4 Args],EXISTS,TEST
```

**Comment by GillesDuvert** [comment]
looks good, let's close it
