### ISSUE TITLE
CW_FILESEL

### ISSUE THREAD

**Issue by PaddyLeahy** [gnudatalanguage/gdl#839]
Like other compound widgets, CW_FILESEL is not implemented in GDL. However, even with access to the source code it does not run in GDL since it invokes the long-deprecated CANCEL_BUTTON and DEFAULT_BUTTON options in WIDGET_CONTROL, which have not been implemented in the GDL version. 

I note that CW_FILESEL duplicates the functionality of DIALOG_PICKFILE, which has been implemented in GDL, except that CW_FILESEL can be embedded in other widgets,  I wonder if this means that a GDL version of CW_FILESEL could be relatively quickly implemented based on DIALOG_PICKFILE?

**Comment by maynardGK** [comment]
It would be easy enough to implement a non-functional keyword function such as CANCEL_BUTTON,
so that code compiles but ignores that keyword usage.

**Comment by GillesDuvert** [comment]
@PaddyLeahy thanks for mentioning this issue. The solution is indeed very simple and will be implemented.

**Comment by GillesDuvert** [comment]
done but that makes it barely useable still.
