### ISSUE TITLE
label_region reimplementation in GDL (code attached)

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#84]
Quoting here the full message from Philip Rooney posted on SF.net (https://sourceforge.net/p/gnudatalanguage/feature-requests/119/):

```
Hi I have made my own version of label_region which was missing. Not sure how to post it in the relevant request area so will put it wherever this goes and hope somebody who needs it finds or somebody puts it where it is meant to be.

I have recreated it with 2 codes: region_label_alt.pro and blob_maker_alt.pro

It takes a fair bit longer than IDL to run, I was getting times of about 25 seconds on 512, 512 images. It outputs exactly the same results as region_label in /all_neighbours mode for everything I have tried it on. I imagine somebody more experianced could speed up the code, I already have a few ideas - the blob making function is recursive and moves between pixels and often checks one already visited which could be fine tuned. Not yet got the time to do so but hope to do soon.

As this is my first upload any and all feedback/ criticism is sought.

Cheers

Philip
```

[label_region.zip](https://github.com/gnudatalanguage/gdl/files/1886797/label_region.zip)

**Comment by brandy125** [comment]
Is there any progress in implementing label_region to GDL?

I think this region_label_alt from Philip could serve as a basis.

**Comment by brandy125** [comment]
Can I test somehow this label_region?

**Comment by alaingdl** [comment]
I gave a chance to the code in SF but I think I do not understant how to use it :disappointed: 

What I did : 
* download the two files _blob_gen_alt.pro_ and _region_label_alt.pro_ from the SF message
* copy the image _rbcells.jpg_ in current dir
*  run this (bad) code : 

```
file='rbcells.jpg'
READ_JPEG, file, img
ref_img=img
help, img
big_img=BYTARR(512,512)
big_img[0:432-1, 0:389-1]=img
img=big_img
sbl = SOBEL(img) lt 200

sbl[*,0:1] = 1
sbl[*,-2:-1] = 1
sbl[0:1,*] = 1
sbl[-2:-1,*] = 1

lab=region_label_alt(sbl)

```
and then I am lost !
Feedback welcome !

**Comment by brandy125** [comment]
Well, I tested the code and it is

1) very slow 
2) “works" only on a specific dataset of 512x512 pixels
3) needs a lot of RAM
4) does not work on 1-dim arrays
5) crashes with segmentation fault (maybe because of its recursive calling)

GDL> a=region_label_alt((head11))
% Compiled module: REGION_LABEL_ALT.
% Compiled module: BLOB_GEN_ALT.
Segmentation fault (core dumped)


Unfortunately this code is not helpful and needs to be re-written from scratch.

Who could help here?

**Comment by GillesDuvert** [comment]
C++ fast code (orignal development) now in GDL #1257
