### ISSUE TITLE
WIDGET_TAB with one tab fails to inherit size (wxwidgets)

### ISSUE THREAD

**Issue by PaddyLeahy** [gnudatalanguage/gdl#840]
The following code in IDL produces a widget with a 512 pixel square draw window in a single tab, and the plot works.
tlb   = WIDGET_BASE(/column)
tabs  = WIDGET_TAB(tlb)
tab1  = WIDGET_BASE(tabs,title='Tab 1', /column, xpad=0, ypad=0,space=0)
draw1 = WIDGET_draw(tab1,xsize=512,ysize=512,retain=2) 
WIDGET_CONTROL, tlb, /realize
WIDGET_CONTROL, draw1, get_value = plot1
WSET, plot1
PLOT, randomn(seed,20)

In GDL under linux with wxwidgets, the widget realised is tiny, with a draw size just about big enough for one character. However, if I create a second tab, the draw windows have the requested 512 x 512 size, and the plot works.
In GDL under windows, the code produces the right size widget, so no problem with widget_tab, however WSET fails (next issue).

**Comment by GillesDuvert** [comment]
Corrected in development version (not yet available).

**Comment by GillesDuvert** [comment]
closed by #882
