### ISSUE TITLE
WSET cannot switch to draw widget (windows problem only)

### ISSUE THREAD

**Issue by PaddyLeahy** [gnudatalanguage/gdl#841]
Under windows, the following code fails

tlb   = WIDGET_BASE(/column)
draw1 = WIDGET_draw(tlb,xsize=512,ysize=512,retain=2) 
WIDGET_CONTROL, tlb, /realize
WIDGET_CONTROL, draw1, get_value = plot1
WSET, plot1

Error message is 
% WSET: Window is closed and unavailable.

This code snippet works fine under linux, with Wxwidgets.

**Comment by GillesDuvert** [comment]
Do you have a better success with "gdl --use-wx"?
Drawing in wxWindows depends on the version of plplot used, and on the plplot wxwidgets driver. Already tricky under linux, fingers crossed on Windows...

**Comment by JWF9912** [comment]
> Do you have a better success with "gdl --use-wx"?
> Drawing in wxWindows depends on the version of plplot used, and on the plplot wxwidgets driver. Already tricky under linux, fingers crossed on Windows...

**Comment by JWF9912** [comment]
This is still a problem as of the 14Feb21 build.  When the draw widget is realized it is assigned a window index but the WSET procedure will not accept the window index value.  Also, the system variable !D.WINDOW is not set to the window index of the draw widget.

If GDL --use-wx is used the draw widget window index is set correctly but GDL returns a warning message

![image](https://user-images.githubusercontent.com/78502834/107989063-6763a980-6f9f-11eb-9ea5-8cce73d01b31.png)

**Comment by GillesDuvert** [comment]
this is completely solved in version 2 of gdl widgets (PR #882) .
