### ISSUE TITLE
Cursor setting

### ISSUE THREAD

**Issue by PaddyLeahy** [gnudatalanguage/gdl#842]
The following options are not available in CURSOR_IMAGE, CURSOR_XY, CURSOR_MASK (error messages are issued). Hence it is not possible to make custom cursors. 

The CURSOR_CROSSHAIR option is accepted by GDL, but for a draw window under wxwidgets produce an error message:

Cursor Setting not ready for wxWindow draw panel, please contribute.

Since the crosshair is the default and only cursor at the moment  for the draw widget it would be nice if GDL could trap this request and not pass it to wxWindow.  These are minor issues, reported for completeness.

**Comment by GillesDuvert** [comment]
wxWidgets has the wxCursor object to do that. Good point.

**Comment by GillesDuvert** [comment]
done, PR submitted
