### ISSUE TITLE
AXIS not working with explicitly set !X.window, !Y.window

### ISSUE THREAD

**Issue by PaddyLeahy** [gnudatalanguage/gdl#843]
The following code draws an axis with labelled tick-marks along the bottom of a colour scale, and a plain axis without labels or ticks along the top:

WINDOW, 0, XSIZE = 512, YSIZE = 100
nxpix = !D.x_vsize - 40  &  nypix = 20
scale = BYTSCL(FINDGEN(nxpix))
x0 = 20               &  x1 = x0 + nxpix - 1
y0 = !D.y_vsize - 23  &  y1 = y0 + nypix - 1
TV, REBIN(scale, nxpix, nypix), x0, y0
position = CONVERT_COORD([x0,x1], [y0,y1], /DEVICE, /TO_NORMAL)
!Y.window = [position[1,0], position[1,1]]
!X.window = [position[0,0], position[0,1]]
r1 = 0.0
r2 = 0.01
AXIS, XAXIS=0, XRANGE = [r1, r2], XSTYLE = 1, XTICKLEN = 0.4
AXIS, XAXIS=1, XTICKS = 1, XSTYLE = 0

Under GDL, AXIS produces error messages:
HGDL> AXIS, XAXIS=0, XRANGE = [r1, r2], XSTYLE = 1, XTICKLEN = 0.4

*** PLPLOT WARNING ***
plwind: Invalid window limits in y.
HGDL> AXIS, XAXIS=1, XTICKS=1, XSTYLE = 0

*** PLPLOT WARNING ***
plwind: Invalid window limits in x.

*** PLPLOT WARNING ***
plwind: Invalid window limits in y.

Not surprisingly he tickmarks are drawn in the wrong place: at the bottom of the device by the first call to AXIS. The labels are invisible since presumably off-screen. The second call to AXIS, which should produce no labels or tickmarks, draws labels from -1 to 1. along the bottom of the device.  This behaviour is identical under linux and windows. 

I note that the algorithm for setting tickmarks appears to by different in GDL from IDL, in that the GDL version produces minor tickmarks in this case but IDL just gives major tickmarks.

**Comment by GillesDuvert** [comment]
Hm this is a bug. Another plplot idiosyncrasies...

**Comment by GillesDuvert** [comment]
Actually it is an IDL bug, eh , feature.
IDL Doc says "!X.WINDOW Contains the normalized coordinates of the axis end points, the plot data window. (...) **Changing its value has no effect.** A 2-element floating point array. To change the default plotting window, set !P.POSITION. The keyword parameter POSITION sets the plot data window on a per call basis.
GDL thus does not check X.Position, it just sets it each time a box is made.
```
!P.POSITION=position[0:1,*]
plot,[0,0.01],[0,1],XST=1,YST=4,/NODA,/NOER
```
Does the trick (sort of).
The TICKLEN=0.4 (0.4 is expressed in normal coordinates)  would make too long ticks.

**Comment by GillesDuvert** [comment]
To complement, as an afterthought, GDL could probably, internally, behave as if !p.position was temporarily set by !X.window and !Y.window. This would work only I believe for commands that do not set the box position, such as AXIS. Will need thorough testing as the behaviour of GDL is largely dictated by the underlying plplot limitations.

**Comment by GillesDuvert** [comment]
OK, done in #1027
