### ISSUE TITLE
Function "HANNING()" is missing

### ISSUE THREAD

**Issue by PattiMichelle** [gnudatalanguage/gdl#845]
GDL> bb=hanning(5)
% READ_AIJ: Ambiguous: Variable is undefined: HANNING or: Function not found: HANNING
GDL> 

"The Hanning window is defined as: 
w(k) = alpha - (1-alpha)*cos(2 pi k/ N), k = 0,1,...,N-1 
where alpha=0.5 for the Hanning, and alpha=0.54 for the Hamming window."
Result = HANNING( N1 [, N2] [, ALPHA=value{0.5 to 1.0}] [, /DOUBLE] )

**Comment by GillesDuvert** [comment]
strange, GDL comes with hanning.pro written by James Tappin.
```
GDL> bb=hanning(5)
% Compiled module: HANNING.
```
May be there is a deeper problem, such as an intervening procedure that changes !PATH ?

**Comment by alaingdl** [comment]
Which version of GDL do you use ? HANNING was added only recently (End of April 2020)

**Comment by PattiMichelle** [comment]
Ah, I'm using GDL from the Debian repo.  (Linux Mint Debian Edition)  Let me check version...
Ah, build date = April 2019
(0.9.9-10)

It looks to me like it's best to build GDL yourself!  I guess I should try building for my opensuse leap 15.1 rather than using it on a LMDE on virtualbox.   (I did that b/c I could just install GDL from a repo rather than attempting a difficult build.)

**Comment by PattiMichelle** [comment]
> strange, GDL comes with hanning.pro written by James Tappin.
> 
> ```
> GDL> bb=hanning(5)
> % Compiled module: HANNING.
> ```
> 
> May be there is a deeper problem, such as an intervening procedure that changes !PATH ?

Thank you for the reply!  No, I never messed around with !PATH.  So, I think I can get HANNING() on my current GDL install if I download the latest GDL and just copy **hanning.pro** to the directory containing all the other default GDL "pros."  (That way I don't have to switch platforms or recompile.)

**Comment by slayoo** [comment]
There are newer Debian package versions: 
- https://packages.debian.org/search?keywords=gnudatalanguage
- https://metadata.ftp-master.debian.org/changelogs//main/g/gnudatalanguage/gnudatalanguage_1.0.0~rc.3-1_changelog

**Comment by PattiMichelle** [comment]
TY
