### ISSUE TITLE
[SOLVE][Installation errors] -- Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by Minnielam** [gnudatalanguage/gdl#846]
Hi, I am installing GDL on my masOS Catalina using homebrew while errors happened as follows:
 

cmake .. -DPLD_xwin=ON -DENABLE_ada=OFF -DENABLE_d=OFF -DENABLE_qt=OFF -DENA
Last 15 lines from /Users/m.lam/Library/Logs/Homebrew/gnudatalanguage/01.cmake:
  if given arguments:

    "APPLE" "AND" "-framework" "IN_LIST" "lasi" "pango" "pangoft2_LDFLAGS_OTHER"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/modules/pkg-config.cmake:126 (_pkg_check_modules_internal)
  cmake/modules/psttf.cmake:59 (pkg_check_pkgconfig)
  cmake/modules/drivers.cmake:95 (include)
  cmake/modules/plplot.cmake:549 (include)
  CMakeLists.txt:135 (include)

-- Configuring incomplete, errors occurred!
See also "/tmp/gnudatalanguage--plplot-x11-20201028-5051-x1a5yu/plplot-5.12.0/plplot-build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/brewsci/homebrew-science/issues

I have already deactived my conda, but errors still showed. Could you please give me some suggestions on the issues? 

Thanks a lot.

Man I

**Comment by GillesDuvert** [comment]
Hi, I do not have a Mac and do not use homebrew but this looks like errors arising when installing the plplot library, not GDL per se. Perhaps you will have a better chance installing plplot first, then GDL?

**Comment by Minnielam** [comment]
Hi Gilles, thanks for your comments. I actually tried to install plplot first but it still failed. In fact, the GDL installation process asked to remove the link from plplot and retried.

**Comment by alaingdl** [comment]
Did you try the script "minimum_script4gdl.sh" in scripts/ dir. ?

It was written in such a way to reduce the problem to compile Plplot on OSX

**Comment by Minnielam** [comment]
Hi Alain, yes, I have tried to compile the minimum_script4gdl.sh but it failed. The issues seem to be not from Plplot, but cmake. I am trying to figure out whether it's due to the latest Xcode version in Mac Catalina.

**Comment by alaingdl** [comment]
I do consider this is an important point. 
1/ could you send me the message (or extract it and post here ?)
(last one seems to be related to plplot + pango, which can be deactivated)
2/ give feedback here 
Thanks

I have VM for OSX from 10.10 till 10.14 for GDL and no problem with this script, but at my job we do delay upgrades to 10.15 (Catalina) because of too much side effects. Then no way to test up to now.

**Comment by Minnielam** [comment]
Hi Alain,
Thanks for your suggestion. I extracted the message as follows:

** preparing GDL
preparing to compiled GDL 1.0.0rc3 VANILLA version
rm: build/: is a directory
CMake Deprecation Warning at CMakeLists.txt:22 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


CMake Warning at /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/Platform/Darwin-Initialize.cmake:286 (message):
  Ignoring CMAKE_OSX_SYSROOT value:

   /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk

  because the directory does not exist.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.4/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:24 (project)


CMake Error at CMakeLists.txt:365 (message):
  RPC support is mandatory.

  Note that SunRPC has been removed in glibc-2.26 and later, while being
  optional in earlier versions.  Consider using the recommended and more
  modern libtirpc instead.

  Use -DRPCDIR=DIR to specify the rpc directory tree.



-- Configuring incomplete, errors occurred!
See also "/Users/m.lam/GDL/gdl/scripts/gdl-1.0.0-rc.3/build/CMakeFiles/CMakeOutput.log".
See also "/Users/m.lam/GDL/gdl/scripts/gdl-1.0.0-rc.3/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.

It seems a problem occured during the compilation of GDL
Please check carrefully the outputs

It seems everything is ready but the Xcode is a suitable for the current GDL version.  I am trying the downgrade my Xcode..

**Comment by slayoo** [comment]
Related to #338 & #361 
Please try installing tripc, it's available for macOS, e.g., via Homebrew: https://formulae.brew.sh/formula-linux/libtirpc
Thanks for feedback!

**Comment by Minnielam** [comment]
Hi @slayoo, thanks a lot for your suggestion. However, the link that you posted is a Linuxbrew function, so I could not install it correctly. Besides, it seems like there are issues for libtripc in MacOS compilation. https://github.com/openwrt/packages/issues/8756. 
Do you have other suggestions/solutions? Many thanks.

**Comment by Minnielam** [comment]
I finally succeed in the MacOS Big Sur (version 11.1) by using the following cmake command:

cmake .. -DREADLINE=no -DPNGLIB=OFF -DOPENMP=OFF \
 -DGSLDIR=/usr/local/Cellar/gsl/2.6 \
-DPLPLOTDIR=/usr/local/Cellar/plplot/5.15.0_2 \                      
-DMAGICK=OFF -DWXWIDGETS=OFF -DTIFF=OFF -DNETCDF=OFF\
 -DHDF=OFF  -DHDF5=OFF  -DFFTW=OFF  -DLIBPROJ4=OFF \
 -DPYTHON=off -DUDUNITS2=OFF -DEIGEN3=OFF  -DGRIB=OFF \
 -DGLPK=OFF -DSHAPELIB=OFF -DX11=OFF

It needs to specify the locations of plplot as well as gsl packages, and switch off anaconda as well as python.  The minimum_script4gdl.sh is not working as report in #879. 

Moreover, some functions are still not working, such as hdf5 files. 

100% tests passed, 0 tests failed out of 212

Total Test time (real) =  47.15 sec

The following tests did not run:
	 19 - test_bug_3055720.pro (Skipped)
	 20 - test_bug_3057511.pro (Skipped)
	 21 - test_bug_3057520.pro (Skipped)
	 22 - test_bug_3061072.pro (Skipped)
	 28 - test_bug_3100945.pro (Skipped)
	 41 - test_bug_3275334.pro (Skipped)
	 81 - test_constants.pro (Skipped)
	112 - test_grib.pro (Skipped)
	114 - test_hdf5.pro (Skipped)
	139 - test_mpfit.pro (Skipped)
	140 - test_mpi.pro (Skipped)
	144 - test_netcdf.pro (Skipped)
	152 - test_plot_usersym.pro (Skipped)
	163 - test_python.pro (Skipped)
	179 - test_simplex.pro (Skipped)
	197 - test_tiff.pro (Skipped)
	201 - test_tv.pro (Skipped)
	206 - test_window_background.pro (Skipped)
[100%] Built target check

Hopefully that's useful.
