### ISSUE TITLE
INTERPOL performs forward fill

### ISSUE THREAD

**Issue by mankoff** [gnudatalanguage/gdl#847]
I'm unsure if I'm using INTERPOL incorrectly or if this is a bug. I'd expect the interpolated value to be `2`, not `1`.

```
foo = [1, -999, 3]
good = [0,2]
bad = [1]
foo[bad] = interpol(foo[good], good, bad)
foo
     1 1 3
```

**Comment by mankoff** [comment]
If the indices are floats (below I change `bad` to `1.0`) then this works:

```
foo = [1, -999, 3]
good = [0,2]
bad = [1.0]
foo[bad] = interpol(foo[good], good, bad)
foo
       1       2       3
```

**Comment by GillesDuvert** [comment]
Hi, thanks for the report. GDL's interpol is known to be buggy. The plan was to replace that procedure by the interpolation method of the GSL library. This however will take time.
As it is a procedure (interpol.pro) you could eventually patch it (in which case we are interested by the patch) or use (temporarily I hope) the IDL (copyrighted) procedure.

**Comment by mankoff** [comment]
If it's known to be buggy it seems like a warning should be issued when it is used.

I'm happy to see this is flagged "priority".

The fix for this bug is fairly straightforward, I think. Convert inputs to FLOAT?

I would patch this if I were using GDL. I'm not - I'm just running it to check that our Python code produces the same output. For now I can either re-create the bug (e.g. use `ffill` in Python) or wrap the inputs to INTERPOL in `FLOAT()`. Sorry that I won't be issuing a patch for this.

**Comment by GillesDuvert** [comment]
@mankoff thanks for the tip. It will make life easier for the brave one that will patch this useful function.

**Comment by mankoff** [comment]
Note - although the fix I demonstrated only requires changing `bad` to a floating point number, I find in practice I need to cast both inputs to float in order for INTERPOL to behave as expected. That is, change calls from `Result = INTERPOL( V, X, XOUT )` to `Result = INTERPOL( V, FLOAT(X), FLOAT(XOUT) )`

**Comment by GillesDuvert** [comment]
Hi, actually it is the FINDEX function used inside INTERPOL that wrongly returns INTs in your case. Corrected.
