### ISSUE TITLE
implement FILE_LINK

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#85]
As reported on SF.net, FILE_LINK is still missing: 
https://sourceforge.net/p/gnudatalanguage/feature-requests/85/

Note that FILE_READLINK is already available what should make the implementation easier.

**Comment by maynardGK** [comment]
I have a file.cpp ready to go with file_link, file_copy, file_delete, and file_move all using
the c routines.  Working equally well on Linux and Windows. 
 I've also made a set of IDL routines to compare results to previous practices
of employing a spawn call for each operation - the old methods are contained in 
file_t_delete.pro , etc. routines and test_file_t_delete.pro call on the _T_ routines.
On my computer I use a subdirectory to contain these .pro supplemental test procs:
file_etc.  I plan to make this a subdirectory of testsuite upon submission.

**Comment by GillesDuvert** [comment]
Excellent. Let's make one dedicated PR for all that stuff together.

**Comment by maynardGK** [comment]
This is next on my tasks once I get gdlhelp submitted.  I may stage it in two or more commits,
beginning with file_search(,-etc) changes and then proceeding to the additional routines..
PR is ready and has passed its tests:
https://github.com/gnudatalanguage/gdl/pull/94

**Comment by maynardGK** [comment]
file_link is now compiled into GDL, only for non-WIN32 usage.  For win32 a file  link  needs
privileges usually not set - also the link and symlink functions are not available in MINGW. 
 And so  the entry in libinit will be conditioned (#ifndef _WIN32);
A file_link.pro will be entered into src/pro to provide the error info in that case.

**Comment by slayoo** [comment]
@maynardGK thanks!
Wouldn't it be more maintainable to implement the error info logic in C++ somewhere around the #ifdef? If we come up with some neat solution for it, this could be also used to address #353

**Comment by maynardGK** [comment]
As it is now, the error comes when the routine is invoked.  But that is more restrictive than necessary.
Under certain conditions it is possible to make file links in windows, so if the function is removed then
a user can make his own file_link() with GDL code and spawn it on demand.
  (from an MSYS shell if
 export MSYS=winsymlnks:nativestrict 
and it is "run as administrator" then 
GDL> spawn,'ln -s '+target+" " + link_name
 will make a real link.  From a command shell (CMD.exe) other commands would be needed.

**Comment by slayoo** [comment]
understood, thanks!
