### ISSUE TITLE
widget_draw not working ?

### ISSUE THREAD

**Issue by roche-emmanuel** [gnudatalanguage/gdl#853]
Hi guys,

I've been experimenting with GDL in the past few days to try to get an IDL program working in it. But unfortunately, this currently doesn't seem to work for me:

Basically I could perform a few successful test trying to build GUIs with GDL, but the moment I try to bring draw widgets in the loop, everything simply falls apart :-S.

Point is, I tested this on windows and on multiple linux distributions so far with no success anywhere:

* On Windows, I'm using the GDL version 1.0.0-rc3
* I also tried on archlinux (x64), building gdl version 0.9.9 from the AUR repository.
* I tried on Ubuntu 20.04 (x64) with GDL 0.9.9 too,
* Then I tried on ubuntu 18.04 (x64) with GDL 0.9.7
* Then I even on Mageia 7 (i586) with the package gnudl-0.9.9-6.1.mga7.i586.rpm

* The program I'm trying to use is defined as follow:

`pro gmv_test_draw_event, evt
    
end

PRO gmv_test_draw  
  
    ; device, true=24, retain=2, decomposed=0
    ; device, /true_color, retain=2, decomposed=0

    ;Create a base widget.  
    base = WIDGET_BASE()  
    
    button = WIDGET_BUTTON(base, value='Done')

    ;Attach a 256 x 256 draw widget.  
    PRINT,"Creating draw"
    draw = WIDGET_DRAW(base, XSIZE = 256, YSIZE = 256, /frame)  
    PRINT,"Done creating draw"
    

    ;Realize the widgets.  
    WIDGET_CONTROL, /REALIZE, base  

    PRINT,"Setting draw window"
    WSET, draw
    im=bytarr(210,210)
    im(0:209,0:209)=!d.table_size-1
    tv,im
        
    PRINT,"Done drawing."

    ;Obtain the window index.  
    ; WIDGET_CONTROL, draw, GET_VALUE = index  
    
    ; PRINT,"Draw window id is: ", index

    ;Set the new widget to be the current graphics window  
    ; WSET, index   

    PRINT, "Done building interface."

    xmanager, "gmv_test_draw", base
    return
END`

Then I run a typical command such as: `gdl --use-wx -e gmv_test_draw`

And for instance, on Mageia, I get the following results: 

`[kenshin@mageia tests]$ gdl -e gmv_test_draw
% WARNING: your version of the GraphicsMagick library will truncate images to 8 bits per pixel

  GDL - GNU Data Language, Version 0.9.9

- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): 
  +/usr/share/gnudatalanguage/lib
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at:
  https://github.com/gnudatalanguage/gdl

% Compiled module: GMV_TEST_DRAW.
Creating draw

*** PLPLOT ERROR, ABORTING OPERATION ***
wxPLDevice::SetDC The DC must be set before initialisation. The device is outputting to a separate viewer, aborting operation

*** PLPLOT ERROR, ABORTING OPERATION ***
error in plD_tidy_wxwidgets., aborting operation
Done creating draw
Setting draw window
% WSET: Window is closed and unavailable.
% Execution halted at: GMV_TEST_DRAW       25 /mnt/hgfs/EUM_RESP_T4/gui_cm/tests/gmv_test_draw.pro
%                      $MAIN$          
GDL>`

=> So... the fact that this is really working nowhere is starting to really puzzling me and this makes me think there must really be something I'm missing here ? Do you guys have any idea what this could be ?

=> Or could you maybe point me in the proper general direction if I want to be able to display a widget_draw element in GDL ? (even if I need to recompile everything from scratches that's OK with me as long as I can find some basic indications somewhere :-) )

Thank you very for your help ! And please let me know if you need me to try anything to investigate this further.

Note: I'm attaching the test .pro file I've been using so far for clear reference (in a zip):

[gmv_test_draw.zip](https://github.com/gnudatalanguage/gdl/files/5588628/gmv_test_draw.zip)

**Comment by roche-emmanuel** [comment]
For reference, also note that this issue might be somehow related to issue #841, since, as reported just above, I can observe the same error message:

> % WSET: Window is closed and unavailable.

... But for the moment I'm more concerned with the plplot error I get when trying to build the draw widget:

> *** PLPLOT ERROR, ABORTING OPERATION ***
> wxPLDevice::SetDC The DC must be set before initialisation. The device is outputting to a separate viewer, aborting operation

Any idea what I could be missing in my program/environment to setup this DC correctly ?

**Comment by roche-emmanuel** [comment]
Okay, and now I just found the issue #749 with indications on how to rebuild everything and hopefully get something working in the end on ubuntu 20 so I'll try that path already ;-)!

**Comment by roche-emmanuel** [comment]
Okay, cool! Following the instructions from [this comment](https://github.com/gnudatalanguage/gdl/issues/749#issuecomment-625541146) I could successfully build GDL on ubuntu 20.04, and now the small test app I mentioned above **will work** **if I remove the part where I try to display some content in the draw widget**:

`
PRINT,"Setting draw window"
WSET, draw
im=bytarr(210,210)
im(0:209,0:209)=!d.table_size-1
tv,im
    
PRINT,"Done drawing."
`

=> So the plplot major error is gone, I only have one window showing up (I could get 2 windows before, with one completely unresponsive), so this is good already.

But now I still need to figure out how to actually display some content in that window...

I think I had another minimal example to do just that... let's see...

**Comment by roche-emmanuel** [comment]
And bingo! I could finally figure out what was wrong: it's simply that I was trying to pass the "draw" object itself to WSET, while I should rather pass the index for that object: so I updated the code as follow:

`
    PRINT,"Setting draw window"
    WIDGET_CONTROL, draw, GET_VALUE = index  
    PRINT, "Draw index is: ", index
    WSET, index
    im=bytarr(210,210)
    im(0:209,0:209)=!d.table_size-1
    tv,im
    PRINT,"Done drawing."
`

=> With that code, no "Window is closed and unavailable." error, and I get a small white area in my draw widget.

All good!

Now trying on windows the exact same code to see if this is working better...

**Comment by roche-emmanuel** [comment]
And I can confirm now that this code is not working on windows: first I need to replace the line:
> device, retain=2, decomposed=0

with:

> device, decomposed=0

Because I first got the error:

> % DEVICE: Current device does not support keyword RETAIN.

And then I get the unfamous error:

> % WSET: Window is closed and unavailable.

So there is something going wrong on the windows version I believe. 

But anyway, I can work with the ubuntu version so that's good enough for me for the moment :-) 

Feel free to reopen this issue if anyone wants to to discuss this further.

**Comment by GillesDuvert** [comment]
Hi, as you have seen the packaging of GDL by the official distributors is, eh, suboptimal.
Running your procedure with an 'OK' GDL gives:
```
GDL> gmv_test_draw     
% Compiled module: GMV_TEST_DRAW.
Creating draw
Done creating draw
Setting draw window
% WSET: Window is closed and unavailable.
% Execution halted at: GMV_TEST_DRAW       25 /tmp/gimp/gmv_test_draw.pro
%                      $MAIN$   
```       
**The error is the same using IDL**

The trick is, 'draw' is NOT a window number, it is a WIDGET_DRAW number. Hence the error if a graphic window of the same 'number' is not already open (and in any case it would not be the window you want to draw on...)
The window number to use to draw something in the draw area, must be retrieved before use with the command:
`widget_control, draw, get_value=window_number`
then 
`wset, window_number`
before plotting anything.

I know this is annoying but IDL widgets have been superimposed above the existing plot windows, they are only containers to otherwise normal plot windows.
