### ISSUE TITLE
INTERPOL: not tolerant to X with duplicated values

### ISSUE THREAD

**Issue by ShamrockLee** [gnudatalanguage/gdl#855]
INTERPAL(V, X, Xout) is a function to perform interpolation.
(X, V) -> (Xout, result)

The [document](https://www.l3harrisgeospatial.com/docs/INTERPOL.html) suggests that the argument X must be strictly ascending or descending, but continuous equal values in vector X is tolerable for the IDL 8.5 compiler and interpreter.

It would be helpful when X is generated using julday since it is not 100% bijective.

**Comment by alaingdl** [comment]
Thanks

We do have several discrepancies in INTERPOL(), we have to re-work on that.

I was surprised to see that _interpol.pro_ is the same in IDL 7.1 and 7.2, but did change in 8.2 then 8.4
(code in 8.4, 8.5 and 8.7 are the same)
(NaN keyword was added in 8.0)


Could you please provide examples on JULDAY usage, it is not clear for me.

**Comment by GillesDuvert** [comment]
see #733 also and comments.

**Comment by ShamrockLee** [comment]
> Could you please provide examples on JULDAY usage, it is not clear for me.

JULDAY(YEAR, MONTH, DAY, HOUR, MINUTE,  SECOND) turns the date-time into double (array).

BTW, I have just found that the duplication of value already exists in the original date-time data. It has nothing to do with the JULDAY function.

**Comment by GillesDuvert** [comment]
see #733

**Comment by GillesDuvert** [comment]
closed by #911, comments welcome!
