### ISSUE TITLE
DEVICE, DECOMPOSE=0 cause !P to become readonly

### ISSUE THREAD

**Issue by ShamrockLee** [gnudatalanguage/gdl#857]
!P is a built-in global variables that controls the plot settings:
```IDL
!P.BACKGROUND = 255 ; Set background color
!P.COLOR = 0 ; Set line color
!P.multi = [0, 1, 2] ; Divide the plotting window into vertical halves and switch to the upper half
```
and DEVICE, DECOMPOSE=[boolean value] can decide whether to use true color or color table to represent colors
```IDL
DEVICE, DECOMPOSE=0 ; Use a color table index instead of true colors ([r, g, b])
```

It is expected behavior to be able to use the color table index and adjust the color and multi settings, which is also the current behavior of IDL 8.5 and 8.7.
```IDL
device, decompose=0
!P.BACKGROUND = 255
!P.COLOR = 0
!P.MULTI = [0, 1, 2]
```
GDL 0.9.9, however, complains
```
% Attempt to write to a readonly variable: !P
```

**Comment by Barney-9000** [comment]
Doesn't appear to be a problem in GDL 1.0.0-rc.3 (macOS 10.14.6)

**Comment by alaingdl** [comment]
I am also unable to reproduce that on some GDL version I have around, including 0.9.9 vanilla

0.9.9 is quite old ... We strongly advice to move to the current Git running version _git clone ..._ 
(or  https://github.com/gnudatalanguage/gdl/archive/master.zip) or a tagged release
e.g. https://github.com/gnudatalanguage/gdl/releases/tag/v1.0.0-rc.3

Some advice here https://github.com/gnudatalanguage/gdl/wiki

Could you give OS and details, using : print,  !GDL

**Comment by GillesDuvert** [comment]
Those very basic commands worked since the beginnings of GDL. Would this be a platform specifics? GDL for Windows? Some tricky redefinition of !P ?

**Comment by ShamrockLee** [comment]
I cannot reproduce it now. Sorry for bothering you.

Info about the environment:
Dockerfile:
```Dockerfile
FROM rsolano/debian-slim-vnc
RUN apt-get update && apt-get install -y gnudatalanguage
```

Build and run command:
```sh
docker build -t debian-gdl .
docker run --rm -v /dev/shm:/dev/shm -v $HOME/Documents:/home/debian/Documents -v $HOME/Projects:/home/debian/Projects -p 5900:5900 debian-gdl
```
Version: 
```console
debian@68cd0aaf5bdd:~/Documents/Reports1091/IDLProgramming/HW09$ gdl --version
% WARNING: your version of the GraphicsMagick library will truncate images to 16 bits per pixel
GDL - GNU Data Language, Version 0.9.9
```

```
GDL> print, !gdl
{ 0.9.9 Apr 23 2019  1555977600}
```
