### ISSUE TITLE
CIR_3PNT is missing

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#859]
The library routine CIR_3PNT is not yet in GDL.
Solution:
Add the attached file and test routine.
[cir_3pnt.txt](https://github.com/gnudatalanguage/gdl/files/5703879/cir_3pnt.txt)
[test_cir_3pnt.txt](https://github.com/gnudatalanguage/gdl/files/5703881/test_cir_3pnt.txt)

**Comment by GillesDuvert** [comment]
Hi, thanks! Nice work!

**Comment by GillesDuvert** [comment]
many thanks, PR sumitted now.
