### ISSUE TITLE
Windows' drivers have a focus problem.

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#872]
With new coding in GDL it has been possible to nearly replicate the desirable behavior of 
keyboard focus without patching the plplot drivers, wingcc,c or wingdi.c.
    Previously, keyboard focus was controlled solely by returning focus to the foreground 
window.  The foreground window was however changed in the original wingcc driver and so
un-doing this change via a patch in plplot allowed for a correct behavior:
````
--- /f/plplot/plplot-5.13.0/drivers/wingcc.c	Fri Aug 25 19:43:25 2017
+++ /f/tarball/plplot-5.13.0/drivers/wingcc.c	Sat Jun 09 12:44:28 2018
@@ -636,7 +634,7 @@
     // sort of thing).
     //
     ShowWindow( dev->hwnd, SW_SHOWDEFAULT );
-    SetForegroundWindow( dev->hwnd );
+    BringWindowToTop( dev->hwnd );
````
(this patch was proposed and rejected by the plplot group)

The new interface to wingcc #864 works around this but it is somehow inadequate, failing the following test with multiple windows (can be .RUN or just executed with "\@"). 
````
fs=findgen(40) & !prompt="" & iw=-1
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
iw++&window,iw,xs=512,ys=512,xp=128*iw,yp=128*iw&plot,fs,chars=iw,thi=iw
wshow,iw,0
wshow,iw-1,0
wshow,iw-2,0
wshow,iw-2,/icon
wshow,iw-2,0
wshow,iw-3,0
wshow,0,0,/icon
wshow,0
end
````

**Comment by pjb7687** [comment]
~~I suspect below picks up a wrong handle.~~
~~https://github.com/gnudatalanguage/gdl/blob/4e3415725f3a48ee07761cf289ae03d9e29ffed0/src/gdlwinstream.hpp#L195~~

This is okay.

**Comment by pjb7687** [comment]
Also, this seems to be raising the previous plot:
https://github.com/gnudatalanguage/gdl/blob/4e3415725f3a48ee07761cf289ae03d9e29ffed0/src/gdlwinstream.cpp#L462

**Comment by pjb7687** [comment]
Tried to fix it: https://github.com/gnudatalanguage/gdl/commit/3eb16a4bb16f0b956925e58c83246a84cd3076f1
Two things are fixed:
1. The plot is not properly repainted when I run the suggested code using GDL Workbench.
2. The code works when I replace the third argument of `wshow` function (`show`) to be 1.

I simply removed the `UnsetFocus` function from devicewin. I have searched for how IDL behaves on Windows on Youtube, seems like the Windows IDL also doesn't do this...

I found that when the third argument (show) is 0, then actually the window should be hidden, according to this:
https://www.l3harrisgeospatial.com/docs/WSHOW_Procedure.html

But instead, it seems like the current implementation tries to bring the window bottom (in the z-order). I don't know which one is the right behavior of IDL, so postponed fixing it...

**Comment by pjb7687** [comment]
When the third argument is 1:
![image](https://user-images.githubusercontent.com/1440536/105644305-4377e100-5e95-11eb-85e8-3fdce4dcf8c4.png)

**Comment by pjb7687** [comment]
Having no ideas about IDL behavior, I'll make it behave the same as ubuntu GDL... Makes sense?

**Comment by pjb7687** [comment]
Another fix: https://github.com/gnudatalanguage/gdl/commit/77c3f031e64f0b836c825011f749f4f835be85e7
This is when the third argument is 0:
![image](https://user-images.githubusercontent.com/1440536/105645720-cac85300-5e9b-11eb-9f4a-073fa309f997.png)

**Comment by pjb7687** [comment]
Is this okay now?

**Comment by GillesDuvert** [comment]
wshow,3,0 puts window 3 below all others.
wshow,3,1 put it above.
wshow,3,/icon iconize the window. It cannot be shown again unless a wshow,3,icon=0 is issued, and the window appears above all the others,  even after a command like 'wshow,3,0,icon=0 .
GDL is apparently not completely OK with this with the X11 driver on unix.
Concerning the focus, IDL always disable passing the focus to a plot window, which is IMHO more than clever, but the plplot windows (so, the GDL ones,  example: the X11 window) somehow obey the desktop behaviour on 'focus stealing' and are not declared 'no focus at all'. One can instruct the window manager (KDE in my case) to disable focus always on windows named 'GDL*' but this is too system dependent. There must be a magic call to have all plplot windows to never get focus.

**Comment by pjb7687** [comment]
@GillesDuvert Thank you so much for clarifying this! Then the patched Windows driver behaves correctly. It never steals the focus from the GDL command line.

**Comment by pjb7687** [comment]
One exception is when you fire up a new plot window using 'plot'. However at least wshow seems to work okay.. I will further investigate it.

**Comment by GillesDuvert** [comment]
obsolete since #882 has been merged
