### ISSUE TITLE
Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"... (macos 10.14.6)

### ISSUE THREAD

**Issue by Barney-9000** [gnudatalanguage/gdl#873]
Compile on macos 10.14.6 using the **minimum_script4gdl.sh** seems to work OK (as it has done previously).  However, the latest build attempt results in a GDL that gives a Segmentation Fault, seemingly whenever any command calls a graphics output procedure (whatever the device - X11 or Postscript):

**Magick: abort due to signal 11 (SIGSEGV) "Segmentation Fault"...
Abort**

Xcode Version 11.3.1, Xquartz  2.7.11 

Everything seems to be much as it was before when GDL compiled and worked as expected, so I am at a loss as to what might be the cause.

**Comment by alaingdl** [comment]
did you try the script with option "6" ??

I will try too on my dedicated VM

**Comment by Barney-9000** [comment]
Compilation fails with option "6":

**CMake Error at CMakeLists.txt:261 (message):
  GNU readline was not found.

  Use -DREADLINEDIR=no to explicitely disable it.

  (suitable Debian/Ubuntu package: libreadline-gplv2-dev or libreadline-dev)

  (suitable Fedora/CentOS package: readline-devel)**

**Comment by alaingdl** [comment]
how do you get the versions of Xcode & Xquartz in CLI ?
I am on  OSX 10.14.4, remotely (ssh)

I have no problem to launch GDL then to plot
```
GDL> gdl_status
[...]
 10 Magick ? :        1
```

Do you get the last minimal script from Git ?

**Comment by alaingdl** [comment]
> Compilation fails with option "6":
> 
> **CMake Error at CMakeLists.txt:261 (message):
> GNU readline was not found.
> 
> Use -DREADLINEDIR=no to explicitely disable it.
> 
> (suitable Debian/Ubuntu package: libreadline-gplv2-dev or libreadline-dev)
> 
> (suitable Fedora/CentOS package: readline-devel)**

that is strange, it should download readline to avoid any trouble due to the terrific incomplete editline provided by OSX

**Comment by Barney-9000** [comment]
Fixed! Apologies, my blunder.  Failing drive replaced a few weeks ago, omitted to (re)install macOS_SDK_headers_for_macOS_10.14.pkg (which I recall caused problems ages ago).  That seems to have sorted it. Sorry for the bother.

**Comment by alaingdl** [comment]
First compilation on Big Sur, without X11 (more to come after the WE ;), with Clang 12.0.0

Trouble within Readline (TBC). GSL & PLplot compiled using minimal_script.sh
Cmake comes from Brew. 


```
$ cmake --version
cmake version 3.19.3

$ sw_vers 
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69

$ cmake .. -DREADLINE=no -DPNGLIB=OFF -DOPENMP=OFF \
 -DGSLDIR=/Users/alain/GDL/Vanilla100rc3/gsl-1.16/Compilation/ \
-DPLPLOTDIR=/Users/alain/GDL/Vanilla100rc3/plplot-5.13.0/Compilation/ \
-DMAGICK=OFF -DWXWIDGETS=OFF -DTIFF=OFF -DNETCDF=OFF\
 -DHDF=OFF  -DHDF5=OFF  -DFFTW=OFF  -DLIBPROJ4=OFF \
 -DPYTHON=off -DUDUNITS2=OFF -DEIGEN3=OFF  -DGRIB=OFF \
 -DGLPK=OFF -DSHAPELIB=OFF -DX11=OFF 

(ok, this computer lacks some basics ;)


[...]

100% tests passed, 0 tests failed out of 212

Total Test time (real) =  64.20 sec

The following tests did not run:
	 16 - test_bug_2974380.pro (Skipped)
	 19 - test_bug_3055720.pro (Skipped)
	 20 - test_bug_3057511.pro (Skipped)
	 21 - test_bug_3057520.pro (Skipped)
	 22 - test_bug_3061072.pro (Skipped)
	 28 - test_bug_3100945.pro (Skipped)
	 41 - test_bug_3275334.pro (Skipped)
	 50 - test_bug_3376577.pro (Skipped)
	 81 - test_constants.pro (Skipped)
	109 - test_get_screen_size.pro (Skipped)
	112 - test_grib.pro (Skipped)
	114 - test_hdf5.pro (Skipped)
	139 - test_mpfit.pro (Skipped)
	140 - test_mpi.pro (Skipped)
	144 - test_netcdf.pro (Skipped)
	152 - test_plot_usersym.pro (Skipped)
	155 - test_pmulti_basic.pro (Skipped)
	163 - test_python.pro (Skipped)
	179 - test_simplex.pro (Skipped)
	197 - test_tiff.pro (Skipped)
	201 - test_tv.pro (Skipped)
	206 - test_window_background.pro (Skipped)
[100%] Built target check

```

Nothing strange that tests are skipped since X11 & other dependences are not used.

**Comment by Barney-9000** [comment]
Identical error message as before for (apparently successful) OPENMP compile using brew llvm. Here's the cmake command:

**cmake .. -DREADLINEDIR=/usr/local/opt/readline/ -DPYTHON=OFF -DGRIB=OFF -DOPENMP=ON -DPLPLOTDIR=/path-to/gdl-master/scripts/plplot-5.13.0/Compilation -DCMAKE_PREFIX_PATH="/usr/local/opt/llvm" -DCMAKE_CXX_COMPILER="/usr/local/opt/llvm/bin/clang++" -DCMAKE_C_COMPILER="/usr/local/opt/llvm/bin/clang"**

Command line test shows 200% CPU, so (otherwise) seems to be OK (gdl_status output below). I'm guessing this is the same issue as previously with Apple clang prior to installing the missing headers (**macOS_SDK_headers_for_macOS_10.14.pkg**) which are now not being picked up with llvm clang. Perhaps there is a simple fix for this, but I haven't been able to work it out.

GDL> gdl_status
% Compiled module: GDL_STATUS.
% Compiled module: GDL_IDL_FL.
 1 DSFMT ?  :        1
 2 Eigen3 ? :        1
 3 Expat ?  :        1
 4 FFTw ?   :        1
 5 GEOTIFF ?:        1
 6 GLPK ?   :        1
 7 GRIB ?   :        0
 8 HDF ?    :        1
 9 HDF5 ?   :        1
10 Magick ? :        1
11 NetCDF ? :        1
12 NetCDF4 ?:        1
13 OpenMP ? :        1
14 PNGLIB ? :        1
15 Proj4 ?  :        1
16 Proj4 new:        1
17 Python ? :        0
18 ShapeLib :        1
19 TIFF ?   :        1
20 UDUNITS  :        1
21 WxWidgets:        1
22 X11      :        1
All _EXISTS() functions have been detected !

**Comment by Barney-9000** [comment]
BTW, has _anyone_ managed to compile GDL with OpenMP under macOS 10.14.6?

**Comment by pjb7687** [comment]
> BTW, has _anyone_ managed to compile GDL with OpenMP under macOS 10.14.6?

Perhaps related to PR https://github.com/gnudatalanguage/gdl/pull/866??

**Comment by Barney-9000** [comment]
Not absolutely certain, but I suspect not since I managed to run some command line loops which soaked two or more CPUs. Crash occurs when output is to any device other than the command lone, i.e. X-windows or PS.  I've tried all manner of kludges to include the headers installed by macOS_SDK_headers_for_macOS_10.14.pkg in the (brew) llvm compile, no luck.

**Comment by GillesDuvert** [comment]
After merge of PR #882, GDL uses only wxWidgets on MacOSX and there should be no difficulties building it provided all dependencies used in `.travis.yml` for the osx case are installed (Brew) and brew's plplot is reinstalled using `scripts/brew_enable_wxwidgets`

**Comment by GillesDuvert** [comment]
See [Wiki instructions,](https://github.com/gnudatalanguage/gdl/wiki/GDL-on-OSX) use buildègdl.sh et voilà.
No more use for minimum_script4gdl.sh
