### ISSUE TITLE
GDL on OSX 11.1 Big Sur

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#879]
Following first report on GDL on OSX 11.1 here https://github.com/gnudatalanguage/gdl/issues/873#issuecomment-765679886 
I made some progress but I had also a lot of problems : 

* minimal_script.sh is not working at the GDL stage, due to an issue with readline
* with GCC 10 (from Brew), with and without OpenMP, I cannot compile.
* with LLVM/Clang 10, I cannot activate OpenMP
* I do have a serious issue with readline, then I need to desactivate it
* (up to now) no brew package for : hdf (hdf5 and netcdf OK), udunits2

What can be useful : X11 headers from Brew are in libx11

At the end, I succeed with : 
```
$ cmake .. -DREADLINE=no -DMAGICK=OFF -DWXWIDGETS=OFF  -DHDF=OFF -DPYTHON=OFF -DUDUNITS2=OFF  -DOPENMP=off
```

Please note that I am working remotely on that machine, and up to now I did not succeed to switch on the X11 forwarding. (X11 forwarding request failed on channel 0). I do have solutions for all previous OSX versions from 10.6 to 10.14 ... (why do they change tricky details in those /etc/ssh files ?!)

**Comment by kkin1995** [comment]
Hi, I just installed GDL from source on macOS Big Sur. This was the process I followed:

1. Install command line tools 

```xcode-select --install```

2. Clone the GDL repository to your local machine 

```git clone https://github.com/gnudatalanguage/gdl```

3. Set the working directory to the GDL directory 

```cd gdl```

4. Make a directory to store all the built files

```mkdir build```

5. ```cd build```

6. 
```
cmake .. -DREADLINE=no -DPNGLIB=OFF -DOPENMP=OFF
-DGSLDIR=/usr/local/Cellar/gsl/2.6
-DPLPLOTDIR=/usr/local/Cellar/plplot/5.15.0_2 \
-DMAGICK=OFF -DWXWIDGETS=OFF -DTIFF=OFF -DNETCDF=OFF
-DHDF=OFF -DHDF5=OFF -DFFTW=OFF -DLIBPROJ4=OFF
-DPYTHON=off -DUDUNITS2=OFF -DEIGEN3=OFF -DGRIB=OFF
-DGLPK=OFF -DSHAPELIB=OFF -DX11=OFF
```

Note: If the 6th command says that some packages are not installed, they need to be installed (can be done through homebrew) and then re-run the 6th command.

7. ```make -j 4```

8. ```make check```

Note: Some tests in command 8 may fail

9. Create a "gdl-startup.pro" file in the gdl directory that was created and add the following line to the file:

```!PATH=/Users/<youraccount>/gdl/src/pro/```

Change <youraccount> to the name of the home folder on your Mac

Then, add the following line to your .profile file:

```export GDL_STARTUP='/Users/<youraccount>/gdl/gdl-startup.pro'```

10. To run gdl from the PATH, an alias has to be added to the profile. For Example, if you are using a ZSH terminal, the profile is found at ~/.zshrc

Add the following line to your .profile,

``` alias gdl='/Users/<youraccount>/gdl/build/src/gdl'```

Change <youraccount> to the name of the home folder on your mac
