### ISSUE TITLE
new keywords START= (and INCREMENT) in MAKE_ARRAY() and *INDGEN()

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#89]
As reported on SF.net: https://sourceforge.net/p/gnudatalanguage/feature-requests/156/ and https://sourceforge.net/p/gnudatalanguage/feature-requests/155/

A keyword START has been added in IDL since 8.2.1 in MAKE_ARRAY()
Then a INCREMENT keyword (related to START !) was add in 8.3

A keyword START has been added in IDL since 8.2.1 for all the *INDGEN() functions.

**Comment by rexso** [comment]
In addition to #272, #316 finalises this issue, no?

**Comment by slayoo** [comment]
correct, thanks!
