### ISSUE TITLE
READ_PNG, keyword has wrong type.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#892]
Attempting to read from a PNG file in 1.0.0rc3, causes an error:
````
read_png, 'test.png', px
% MAGICK_READ: Keyword must be a INT in this context: <Expression> <LONG      (           1)>
% Error occurred at: INTERNAL_READ_PNG   118 /usr/share/gnudatalanguage/lib/read_png.pro
%                    READ_PNG           147 /usr/share/gnudatalanguage/lib/read_png.pro
%                    $MAIN$          
% Execution halted at: $MAIN$     
````
The offending line is:
````
   image=MAGICK_READ(mid, rgb=1)
````
I'm not sure whether it would be better to make the call with `rgb=1s` or to modify `magick_read` (which I assume to be intrinsic), I suspect that dropping the `idl2` compile option would be a seriously bad idea.

N.B. The code is still the same in the master branch.

P.S. The error is occurs whether the build is against graphicsmagick or imagemagick.

**Comment by GillesDuvert** [comment]
confirmed!
