### ISSUE TITLE
R_CORRELATE, candidate routine.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#894]
R_CORRELATE is not currently in the GDL library. Attached is an implementation, and a basic test routine.

Notes:
1. the PROBD and ZD keywords are not implemented.
2. Since IBETA is not available, I have included a sufficient implementation for R_CORRELATE (scalar & real only) as an internal routine, called BETAI to avoid any clashes at a later date.
3. For larger datasets the KENDALL implementation does give different answers from the one in IDL, and I've checked both routines and my conclusion is that IDL's version has rounding errors (it's also a lot slower than this version).

[r_correlate.pro](https://github.com/gnudatalanguage/gdl/files/6030514/r_correlate.pro.txt)
[test_r_correlate.pro](https://github.com/gnudatalanguage/gdl/files/6030516/test_r_correlate.pro.txt)

**Comment by GillesDuvert** [comment]
just added in main, thanks!
see #895
