### ISSUE TITLE
Ambiguous: Variable is undefined: MEAN or: Function not found: MEAN 

### ISSUE THREAD

**Issue by kkin1995** [gnudatalanguage/gdl#896]
Hi, I installed GDL on a Linux (Ubuntu-based) system using apt. The default packages are at
``` /usr/share/gnudatalanguage/lib```
which also has the file mean.pro with the function MEAN.
Additionally I also linked to external packages using the GDL_STARTUP environment variable. However, when I run a program with the MEAN function, it gives the following error:

``` Ambiguous: Variable is undefined: MEAN or: Function not found: MEAN ```

Any ideas about a solution to this issue?

Thanks !

**Comment by GillesDuvert** [comment]
Hi, mean() is in the C++ code of GDL since 0.9.8 
So whatever the existence of a mean.pro file anywhere, GDL will use this code.
You should not have a mean.pro file in `/usr/share/gnudatalanguage/lib` as this was removed since 0.9.8
I wonder what happened with your installation? (and what exactly Ubuntu provides)
A simple test, that should work with a GDL more recent than 3 years ago:
```
GDL> !PATH="/tmp" ; so: no path or so few...
GDL> print,mean(findgen(32)) ; proving mean is intrinsic.
      15.5000
```

**Comment by kkin1995** [comment]
Hi, so I tried to reset the PATH but it gave the same error. The version of GDL is 0.9.7 from Ubuntu. Will it help to reinstall GDL from apt or should I try compiling from source for the latest ?

**Comment by kkin1995** [comment]
Also, I forgot to mention, I'm using Peppermint OS which is based on Ubuntu Bionic Beaver. Maybe, that's probably why apt is shipping an old version of GDL for my system.

**Comment by GillesDuvert** [comment]
probably mean.pro is not in your !PATH.
I suggest strongly to use the most recent version of gdl. We cannot easily support such old systems and versions due to the rapid development of GDL.

**Comment by kkin1995** [comment]
I checked the PATH and ```\usr\share\gnudatalanguage\lib``` is there. That is where mean.pro resides. 

Yes, I also tested the mean function on a different system with GDL 1.0.0 (installed from source) and it was working.

Thanks for your help !
