### ISSUE TITLE
Missing MAP_SET?

### ISSUE THREAD

**Issue by whimian** [gnudatalanguage/gdl#897]
MAP_SET is missing from the package from gnudatalanguage amd64 0.9.0-12build1 for  Ubuntu.

**Comment by alaingdl** [comment]
really 0.9.0 ?! Please move to a recent version ! We did delivered 1.0.0rc3 months ago. Compilable from Ubuntu 14.04 to 20.10

**Comment by slayoo** [comment]
map_set was added in Aug 2019: https://github.com/gnudatalanguage/gdl/commits/4697f51a1ffd1c6b9674b3eda2c4765f5ef00e95/src/pro/map/map_set.pro

There was no "0.9.0" in the history of GDL, Google doesn't know anything about "0.9.0-12build1". 
I guess you mean 0.9.9 which was released back in Nov 2018 - before map set was added.

Please update.

**Comment by GillesDuvert** [comment]
@whimian , additionnally, we are interested in having comments about the behaviour of the implementation of mapping capabilities that was deployed, as @slayoo said, in 1.0.0rc3 .
Given that [such things work](https://github.com/gnudatalanguage/gdl/pull/882#issuecomment-776940336) .
Comments are thus welcome on, not only MAP_SET, but also [all the related commands](https://www.l3harrisgeospatial.com/docs/routines-44.html) that have been ported.

**Comment by whimian** [comment]
@alaingdl @slayoo @GillesDuvert I installed gnudatalanguage from apt on ubuntu 20.4, the latest version of gnudatalanguage is still 0.9.0. Do I have to build the 1.0 version from the source?

**Comment by whimian** [comment]
@GillesDuvert And I would like to know how could I specify the path of `plplot ` `-DPLPLOTDIR="somewhere"`.

**Comment by whimian** [comment]
@GillesDuvert And I would like to know how could I specify the path of plplot -DPLPLOTDIR="somewhere", when building with `cmake`.

**Comment by slayoo** [comment]
Ubuntu 20 ships with 0.9.9: http://packages.ubuntu.com/gnudatalanguage

plplot should be autodetected on Ubuntu after you install its headers package: libplplot-dev
