### ISSUE TITLE
gdlde no longer working

### ISSUE THREAD

**Issue by wogallery** [gnudatalanguage/gdl#899]
I had gdlde working a week ago. Then I installed a lot of python stuff (anaconda, pycharm) and upgraded java (version 11). Now gdl command line works but the de does not. I uninstalled and reinstalled the pre-built GDL Installer (full, x86_64, Release)_x.zip with no luck. The error I get is:

An error occurred. See the log file 
C:\usr\Bill\.gdl\gdlworkbench-config\165766251403.log

This file contains a lot of error messages of the form:
...
Unresolved requirement: Import-Package: org.eclipse.e4.core.commands
                         -> Export-Package: org.eclipse.e4.core.commands; 
bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="0.13.0.v20201119-1132"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,  org.eclipse.e4.ui.workbench,  org.eclipse.e4.ui.workbench.renderers.swt,  org.eclipse.ui.workbench,  org.eclipse.e4.ui.workbench.swt,  org.eclipse.e4.ui.progress,  org.eclipse.e4.core.commands.tests"...

Here is the file:
[1615766251403.log](https://github.com/gnudatalanguage/gdl/files/6137921/1615766251403.log)

What am I missing? 
Cheers,
Bill Gallery

**Comment by pjb7687** [comment]
Close due to duplicate: https://github.com/gnudatalanguage/gdlde/issues/5
