### ISSUE TITLE
implement color_quan using magick_quantize?

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#90]
As reported on SF.net: https://sourceforge.net/p/gnudatalanguage/feature-requests/65/

MAGICK_QUANTIZE procedure is already available - perhaps creating a wrapper around it would be an easy way to provide COLOR_QUAN functionality?

**Comment by GillesDuvert** [comment]
easy procedure, as :
id=magick_open("Saturn.jpg") 
magick_quantize,id,3,/dither
MAGICK_WRITEFILE, id, "quantzed.png", "PNG"
