### ISSUE TITLE
A_CORRELATE & C_CORRELATE

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#903]
I wrote these a while back, thought I had submitted them.

[test_ac_correlate.pro](https://github.com/gnudatalanguage/gdl/files/6182166/test_ac_correlate.pro.txt)
[c_correlate.pro](https://github.com/gnudatalanguage/gdl/files/6182168/c_correlate.pro.txt)
[a_correlate.pro](https://github.com/gnudatalanguage/gdl/files/6182169/a_correlate.pro.txt)

**Comment by GillesDuvert** [comment]
PR submitted, thanks!
