### ISSUE TITLE
OSX & plplot & wx.h

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#905]
Since last days, I am unable to compile current Git version on OSX 10.14.4, 10.15 & 11 to have graphical outputs.

And I do not what to do with :
```
$ sh ./brew_enable_wxwidgets 
==> cmake .. -DCMAKE_INSTALL_LIBDIR=/usr/local/Cellar/plplot/5.15.0_2/lib -DPL_HAVE_QHULL=OFF -DENABLE_ada=OFF -DENABLE_d=OFF -DENABLE_octave=OFF -D
==> make
Last 15 lines from /Users/coulais/Library/Logs/Homebrew/plplot/02.make:
#include <wx/font.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/plplot.dir/__/drivers/wxwidgets_comms.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /tmp/plplot-20210326-40317-1iyeshl/plplot-5.15.0/drivers/wxwidgets_dev.cpp:44:
/tmp/plplot-20210326-40317-1iyeshl/plplot-5.15.0/drivers/wxwidgets.h:32:10: fatal error: 'wx/wx.h' file not found
#include <wx/wx.h>
         ^~~~~~~~~
1 error generated.
make[2]: *** [src/CMakeFiles/plplot.dir/__/drivers/wxwidgets_dev.cpp.o] Error 1
1 error generated.
make[2]: *** [src/CMakeFiles/plplot.dir/__/drivers/wxwidgets.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/plplot.dir/all] Error 2
make: *** [all] Error 2



```

**Comment by pjb7687** [comment]
I fixed this in https://github.com/gnudatalanguage/gdl/pull/902, the Plplot formula needs a dependency on `wxmac`.

**Comment by pjb7687** [comment]
I am planning to merge it by tomorrow.

**Comment by GillesDuvert** [comment]
yes i was able to recompile plplot on a machine (Catalina) with what I tought would work everywhere (scrpits/brew_enable_wxwidgets ) but indeed this did not work on the GH machines and now, on @acoulais machines. 
Happy to see you have found the culprit!
Your involvement is really appreciated! :+1:

**Comment by alaingdl** [comment]
progress but ... on a remote OSX 10.14.4 (yes, ssh -X is working)

steps : 
* update of system & brew
* git pull
* ...
* sh ./brew_enable_wxwidgets   SUCCESS !
* cmake .. -DREADLINEDIR=/usr/local/Cellar/readline/8.1/ -DHDF=OFF  -DLIBPROJ=off -DOPENMP=off
* make -j 20
* sh ../quick_start_GDL.sh 

crash :(

(I had this problem in the past with WXwidgets and never find a way to fix it)

 sh ../quick_start_GDL.sh 
Running current GDL with ./src/pro and ./testsuite in GDL_PATH
+/Users/coulais/GDL/gdl-1.0.0rc3-git210330CMake/src/pro/:+/Users/coulais/GDL/gdl-1.0.0rc3-git210330CMake/testsuite/
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
2021-03-30 23:41:59.582 gdl[19547:101033] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2dbe6cf9 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff587c7a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2dc0d3e9 __CFArrayCopyDescription + 0
	3   libwx_osx_cocoau_core-3.0.dylib     0x00000001102f0014 _Z19wxClientDisplayRectPiS_S_S_ + 32
	4   libwx_osx_cocoau_core-3.0.dylib     0x00000001103f3595 _Z22wxGetClientDisplayRectv + 48
	5   libwx_osx_cocoau_core-3.0.dylib     0x00000001104652ef _ZN20wxTopLevelWindowBase14GetDefaultSizeEv + 9
	6   libwx_osx_cocoau_core-3.0.dylib     0x00000001102f3d8f _ZN16wxNonOwnedWindow6CreateEP8wxWindowiRK7wxPointRK6wxSizelRK8wxString + 143
	7   libwx_osx_cocoau_core-3.0.dylib     0x00000001102f720b _ZN19wxTopLevelWindowMac6CreateEP8wxWindowiRK8wxStringRK7wxPointRK6wxSizelS4_ + 47
	8   gdl                                 0x000000010f6f1f34 _ZN17gdlwxPhantomFrameC2Ev + 132
	9   gdl                                 0x000000010f6cfb28 _ZN9GDLWidget4InitEv + 424
	10  gdl                                 0x000000010faac46e _Z7InitGDLv + 110
	11  gdl                                 0x000000010faaf566 main + 12038
	12  libdyld.dylib                       0x00007fff59ff53d5 start + 1
	13  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Magick: abort due to signal 6 (SIGABRT) "Abort"...
../quick_start_GDL.sh: line 91: 19547 Abort trap: 6           ${Absolute_PATH}/src/gdl

**Comment by GillesDuvert** [comment]
`FAILED TO establish the default connection to the WindowServer` is it not related to the problem that you ask for an X11 connexion to a program (gdl) that is not linked to X11? 
In other terms, wxWidgets is native (cocoa), not X11 compatible. Same for GDL on windows of course.
Obviously the wxWidgets version will not obey X11 remote conections. Only a remote use with, e.g., teamviewer, will work.
An alternative is to compile gdl with X11 (and, probably safer, **without wxWidgets**), start the X11 server on the mac, then it should mostky work unless I've missed something in the devices.

**Comment by GillesDuvert** [comment]
closing as solved.
