### ISSUE TITLE
`issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by csalyk** [gnudatalanguage/gdl#906]
Hi, I am trying to install GDL with homebrew, and got an error: "undefined method `full_name' for nil:NilClass".  The full error is below.  Is there a way to fix this?  Thank you!

Traceback (most recent call last):
	42: from /usr/local/Homebrew/Library/Homebrew/build.rb:227:in `<main>'
	41: from /usr/local/Homebrew/Library/Homebrew/build.rb:134:in `install'
	40: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	39: from /usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block in install'
	38: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1234:in `brew'
	37: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2261:in `stage'
	36: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	35: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	34: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	33: from /usr/local/Homebrew/Library/Homebrew/resource.rb:198:in `mktemp'
	32: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	31: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	30: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	29: from /usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
	28: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:87:in `stage'
	27: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:100:in `chdir'
	26: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:100:in `chdir'
	25: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
	24: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2281:in `block in stage'
	23: from /usr/local/Homebrew/Library/Homebrew/utils.rb:550:in `with_env'
	22: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2282:in `block (2 levels) in stage'
	21: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1241:in `block in brew'
	20: from /usr/local/Homebrew/Library/Homebrew/build.rb:175:in `block (2 levels) in install'
	19: from /Users/cosalyk/gnudatalanguage.rb:47:in `install'
	18: from /usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
	16: from /usr/local/Homebrew/Library/Homebrew/resource.rb:198:in `mktemp'
	15: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
	13: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
	12: from /usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
	11: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:87:in `stage'
	10: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:100:in `chdir'
	 9: from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:100:in `chdir'
	 8: from /usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
	 7: from /Users/cosalyk/gnudatalanguage.rb:65:in `block in install'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2190:in `mkdir'
	 5: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
	 4: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
	 3: from /Users/cosalyk/gnudatalanguage.rb:66:in `block (2 levels) in install'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2068:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2068:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2132:in `block in system': Failed executing: cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gnudatalanguage/0.9.7_4 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -DPLD_xwin=ON -DENABLE_ada=OFF -DENABLE_d=OFF -DENABLE_qt=OFF -DENABLE_lua=OFF -DENABLE_tk=OFF -DENABLE_python=OFF -DENABLE_tcl=OFF -DPLD_xcairo=OFF -DPLD_wxwidgets=OFF -DENABLE_wxwidgets=OFF -DENABLE_java=OFF -DENABLE_f95=OFF (BuildError)
	5: from /usr/local/Homebrew/Library/Homebrew/brew.rb:155:in `<main>'
	4: from /usr/local/Homebrew/Library/Homebrew/brew.rb:167:in `rescue in <main>'
	3: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:494:in `dump'
	2: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:440:in `issues'
	1: from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:444:in `fetch_issues'
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:66:in `issues_for_formula': undefined method `full_name' for nil:NilClass (NoMethodError)

**Comment by slayoo** [comment]
The key message is:
> Failed executing: cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gnudatalanguage/0.9.7_4 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -DPLD_xwin=ON -DENABLE_ada=OFF -DENABLE_d=OFF -DENABLE_qt=OFF -DENABLE_lua=OFF -DENABLE_tk=OFF -DENABLE_python=OFF -DENABLE_tcl=OFF -DPLD_xcairo=OFF -DPLD_wxwidgets=OFF -DENABLE_wxwidgets=OFF -DENABLE_java=OFF -DENABLE_f95=OFF (BuildError)

which seems to tell us that the error happens at the stage of building dependencies, not GDL itself.
The CMake options suggest that it fails to install plplot:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/plplot.rb#L26

Could you try first installing plplot with brew and if it fails report the problem at Homebrew issue tracker (https://github.com/Homebrew/homebrew-core/issues/new/choose) or to plplot maintainers (https://sourceforge.net/p/plplot/bugs/)?

The other option is to compile plplot yourself (and then do the same with GDL).

Thanks for reporting.

**Comment by slayoo** [comment]
The above message also show that homebrew is aactually offering you GDL 0.9.7 that dates back to Jan 2017! Plplot might also be outdated, so first of all it would be great to switch to recent versions of both plplot and gdl.

**Comment by GillesDuvert** [comment]
We have now automated builds on each architecture, thanks to PR #902 by @pjb7687 . There are 'artifacts' for MacOSX.
see
 https://github.com/gnudatalanguage/gdl/runs/2206298173
probably not directly useable, but shows that by following the installation scripts, having a complete up-to-date gdl is possible, with widgets, native graphics etc...

**Comment by csalyk** [comment]
Thanks!  I installed plplot and then tried using the cmake command provided here:
https://github.com/gnudatalanguage/gdl/wiki/GDL-on-OSX
but then I got the following error:

CMake Error at CMakeLists.txt:586 (message):
  PlPlot was compiled without xwin (or wingcc on Windows) driver, aborting. 
  Do you mean -DINTERACTIVE_GRAPHICS=OFF ?

**Comment by GillesDuvert** [comment]
indeed, all this is quite new: to have the uptodate GDL, with graphics, on OSX, you need to have a plplot compiled with at least its wxwidgets driver. Which is not the case with the homebrew plplot. But look at GDL's [scripts/brew_enable_wxwidgets](https://github.com/gnudatalanguage/gdl/blob/master/scripts/brew_enable_wxwidgets) , one can recompile afterwards plplot with the wxwidgets driver.
Alternatively you could compile without any graphics at all, (cmake -DINTERACTIVE_GRAPHICS=OFF etc..) this is probably not what you want.
This is a homebrew defect in my opinion, and the more people report this to homebrew headquarters, the faster this problem will be solved. 
There may be another distro (macPorts?) that does compile plplot with the wxWidgets driver, but who knows?

**Comment by csalyk** [comment]
I got it working after reinstalling plplot with wxwidgets, as suggested, then remaking gdl.  Thanks again for your help.

**Comment by GillesDuvert** [comment]
superb!
You are now sort of a beta-tester, for this version is the cutting edge. Keep us informed if graphics or widgets have problems (that should be the sole difference on macOSX ). Remarks on[ the wiki page](https://github.com/gnudatalanguage/gdl/wiki/GDL-on-OSX) will also be beneficial for all.
