### ISSUE TITLE
Codecov not working

### ISSUE THREAD

**Issue by pjb7687** [gnudatalanguage/gdl#907]
It seems the latest build lacks the file `codecov.info`
https://github.com/gnudatalanguage/gdl/runs/2209103022?check_suite_focus=true#step:12:37

I am not familiar with Codecov, help needed.

**Comment by slayoo** [comment]
I think the problem might be that we no longer do "make codecov"?

https://github.com/gnudatalanguage/gdl/blob/JOSS/.travis.yml#L270

**Comment by pjb7687** [comment]
It does run "make codecov":
https://github.com/gnudatalanguage/gdl/blob/master/.ci/build_gdl.sh#L339

**Comment by slayoo** [comment]
I see the intention is to do it, but seems like it is not entering the right path in the conditional, if it would the output would look like here:
https://travis-ci.com/github/gnudatalanguage/gdl/jobs/493800207#L3751

**Comment by pjb7687** [comment]
Oh that's right. I will check it again later

**Comment by alaingdl** [comment]
stupid question. CodeCov seems to deseapere because the file .travis.yml was removed (in fact evolved into .ci/build_gdl.sh). But what wil happen if I re-introduce suche a file limited to the CodeCov part ?
Or the story is more complex ?

**Comment by pjb7687** [comment]
I created a new GA script: https://github.com/gnudatalanguage/gdl/blob/master/.github/workflows/codecov.yml
You can also manually trigger the workflow here: https://github.com/gnudatalanguage/gdl/actions/workflows/codecov.yml

**Comment by alaingdl** [comment]
Great ! Thanks you ! I was quite lost with the new interface. Numbers are not that good :( 
And writing tests covering in details functions is time consuming ...

**Comment by alaingdl** [comment]
just to illustrate the interest : 
-- in basic_pro.cpp : no tests for BYTEORDER, JULDAY, CALDAT ...
-- in basic_fun.cpp : no test for CALL_METHOD(), LOGICAL_AND() Missing types and larges parts in TOTAL() ...
Idem in PRODUCT(), MEDIAN(), MEAN() ... 

All these functions are critical ones ...

**Comment by slayoo** [comment]
Thank you @pjb7687 !
