### ISSUE TITLE
IDL_VALIDNAME missing from GDL

### ISSUE THREAD

**Issue by kkin1995** [gnudatalanguage/gdl#908]
Hi, The function IDL_VALIDNAME seems to be missing from GDL installed from APT. I first got the error when I was trying to run a .pro file. Then I tested it with an example in the GDL REPL.

```
print,IDL_VALIDNAME('!var!a$a',/convert_all)
```
which gave me the following error:

```
% Function not found: IDL_VALIDNAME
% Execution halted at: $MAIN$
```
Any idea how to fix this ?

GDL Version: 0.9.9
OS: Linux Mint 20.1

**Comment by GillesDuvert** [comment]
worksforme:
```
GDL> print,IDL_VALIDNAME('!var!a$a',/convert_all)
% Compiled module: IDL_VALIDNAME.
!var_a$a
```
probably a problem accessing the` idl_validname.pro` in your `!PATH` . Mine is at `/usr/local/share/gnudatalanguage/lib/idl_validname.pro`

**Comment by GillesDuvert** [comment]
@kkin1995 or is it that all GDL procedures are in a separate package in APT? Please look at their documentation. These files are mandatory and packagers should not keep them spearately (or provide a so-called meta-package).

**Comment by kkin1995** [comment]
Hi, apologies for delay in getting back. I checked again and discovered that only the sub-folders in "/usr/share/gnudatalanguage/lib" was there in the PATH but not the folder itself.

I added the folder to GDL_PATH and it worked.
