### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#91]
See also: https://sourceforge.net/p/gnudatalanguage/bugs/574/
(pointing out that CMakeModules/FindNumpy.cmake uses Python-2 syntax of print)

**Comment by eatdust** [comment]
One can select explicitly the python version with:
-DPYTHONVERSION=2            \
-DPYTHON_EXECUTABLE=/usr/bin/python2

and in 0.9.8, this works fine, also with python3. However, In view of python2 being obsoleted, python3 should be supported, but compilation with python3 fails at multiple places afterwards.

Cheers.

**Comment by opoplawski** [comment]
For the record - the FindNumpy.cmake issue was addressed with f997bac3cbbc03a296c612dce4af07067b6a5f9c
