### ISSUE TITLE
missing procedure truncate_lun

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#912]
Anybody can implement truncate_lun?

**Comment by GillesDuvert** [comment]
Hi @brandy125 I looked into that, and saw that some file (lun) procedures were in gdl, not in c++. Pretty bad for performance. Looking into that now.

**Comment by GillesDuvert** [comment]
introduced in GDL. please test, as we have no test file for this.

**Comment by brandy125** [comment]
Hi @GillesDuvert, unfortunately truncated_lun does not work as expected:

GDL> openw,1,'testfile'
GDL> writeu,1,fltarr(1000)
GDL> $ls -al testfile
-rw-r--r-- 1 chris users 4000 Apr 14 14:36 testfile
GDL> truncate_lun,1
GDL> $ls -al testfile
-rw-r--r-- 1 chris users 0 Apr 14 14:36 testfile

In this case it should preserve the file size.

Could you have a look to it?
Thanks

**Comment by GillesDuvert** [comment]
indeed.

**Comment by GillesDuvert** [comment]
corrected!

**Comment by brandy125** [comment]
Hi @GillesDuvert, now works fine. Thanks!
