### ISSUE TITLE
code with extended ASCII char 0xA0 0xA7

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#92]
As reported by @alaingdl on SF.net:

Code containing extended ASCII char (above 128) including 0xA0 0xA7 compiles and runs without change with IDL on Linux. 

In GDL the compilation fails on few extended ASCII chars (above 128) : e.g. 0xA0 and 0xA7
Unfortunatelly, sometime GDL does not reports the bad line number (but not always).

GDL> .r mirim_compute_psfs.pro
% Token stream error: unexpected char: 0xA0
At: mirim_compute_psfs.pro

Maybe we can skip the ext. ASCII char ??
If not, we need to know the line nulber !

**Comment by GillesDuvert** [comment]
Please give an example for tests.

**Comment by slayoo** [comment]
For the record, this is the original report: https://sourceforge.net/p/gnudatalanguage/bugs/668/

**Comment by GillesDuvert** [comment]
no example given and the parser accepts codes from 0 to 255 . Closing.
