### ISSUE TITLE
Missing Libraries from x86_64 full installer (build #239)

### ISSUE THREAD

**Issue by JITivT** [gnudatalanguage/gdl#929]
I've just downloaded and installed the installer for the windows X86_64 full package but the following 2 libraries are missing;
libcrypto-1_1-x64.dll
libssl-1_1-x64.dll

Are these prerequisites or should they be included in the installer package?

**Comment by GillesDuvert** [comment]
same for me, I suspect some libraries on github now need this dependency. At least GDL does not need them. obviously they should be part of the installer..

**Comment by alaingdl** [comment]
on https://github.com/gnudatalanguage/gdl/releases/tag/weekly-release
I just tried the current "gdl-windows-x86-64-standard.zip" and "gdlseup-Windows-x86_64_standard.exe" and both failed to start : missing VCRUNTIME140.dll
