### ISSUE TITLE
Socket hangs during read

### ISSUE THREAD

**Issue by bdtempleman** [gnudatalanguage/gdl#932]
A socket read using readf or readu hangs and never returns.  I used both the SOCKET procedure and tcpclientsocket.  Both produce the same result.  The actual connection seems good and does not return an error.  The same code works fine in IDL.  We are transitioning from IDL to GDL.  The socket is a local connection on the same server and the port number is 5998.

Thanks for the help!

**Comment by alaingdl** [comment]
any chance to have a sub-set of the code to gain time to study the problem ?
thanks !

A

**Comment by GillesDuvert** [comment]
worksforme, at least the example in https://idlastro.gsfc.nasa.gov/ftp/pro/sockets/webget.pro which use SOCKET.
