### ISSUE TITLE
ssh without -X is blocking launching GDL compiled with Graphic output ON

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#935]
up to now, in GDL before March 2021, if we connect on a cmputer with GDL compiled within X11 support, but without -X,
it was OK, just no plots ...
```
GDL> plot, findgen(10)
% Cannot connect to X server
```

But now it is not possible to just start GDL, it even hangs the CLI !

**Comment by GillesDuvert** [comment]
Thanks Alain!
In retrospect that was an expectable side effect of the unification of plots and widgets behing wxWidgets, and is one reason version v1.0 is not out!
See also #936 .
Trapping these failures (wxWidgets not initializing, X11 not present) must be done before plplot drivers are called and devices created.
