### ISSUE TITLE
plot window gets corrupted after resizing 

### ISSUE THREAD

**Issue by brandy125** [gnudatalanguage/gdl#938]
When I resize the plot window, making it a little bigger, the contents does not get redrawn.
This might be ok.
When I execute the plot command again, the window does not show the new plot in some part of the plot window.

```
GDL>plot,findgen(100)

now make the window bigger and execute the same plot command again

GDL>plot,findgen(100)
```

the new plot is not drawn completely.

![Screenshot_2021-05-07 11 11 30_Tz28gf](https://user-images.githubusercontent.com/59102584/117462931-83834100-af25-11eb-9b10-69edc8c6a4a2.png)

I can not remember this behaviour before.

Here my system:
GDL> hash(!GDL)
EPOCH:  1620356400
RELEASE:1.0.0-rc.3 git
GDL_POSIX:   1
BUILD_DATE:May  7 2021
GDL_USE_WX:   1
GDL_USE_DSFMT:   1

Linux Suse_Tumbleweed 5.11.11-1-default #1 SMP Tue Mar 30 17:57:52 UTC 2021 (dbc4a02) x86_64 x86_64 x86_64 GNU/Linux

**Comment by GillesDuvert** [comment]
@brandy125 actually the plot should grow and resize automatically if you change the plot size. Color would change to red (and font shapes would stretch) if the plot device was X11, and stay the same with a wxWidgets plot. Only PSYMs woudl stretch shape in both cases, calling to a new 'plot' command to get the good shape again. But your behaviour is puzzling.

**Comment by GillesDuvert** [comment]
added: from the box labels, nice font shapes, you have the wxWidgets windows (normal).
Does the problem depend on the speed of the resizing? You should be able to drag the frame while keeping the left button pressed as long as you wish, and the resizing should be performed only when the button is released.
Your behaviour suggests the resizing event is not properly trapped by wxwidgets. WxWidgets  event loop in GDL is not very satisfactory I'm sure and would benefit from some expert of wxWidgets...

**Comment by brandy125** [comment]
@GillesDuvert The problem does not depend on the speed. While resizing I just see the frame of the window, when I release the button the contents gets redrawn (in case of shrinking) or not (in case of increasing).

I did more tests and would describe as follows:

1) the window can be resized to a smaller size and the contents gets redrawn in the same color as the original plot. It can be resized several times and it works as expected. 

2) At any point when the window is being resized to a bigger size, that part of the window becomes black that is "outside of the original" window.

3)   If the window is resized to a size smaller than the original size, the contents gets correctly redrawn again.

**Comment by brandy125** [comment]
Any news on that? 
Can this be fixed?

**Comment by GillesDuvert** [comment]
cannot reproduce here.

**Comment by brandy125** [comment]
I tested now on Debian and does not occur as well. Just on my Suse Tumbleweed under Parallels on a Mac Mini

**Comment by GillesDuvert** [comment]
tumbleweed but no problem like in[ #961](https://github.com/gnudatalanguage/gdl/issues/961#issuecomment-858690250) ?

**Comment by brandy125** [comment]
what exactly from #961 do you mean?

This is the status now:

1) compilation works only after putting -ltirpc somewhere in src/CMakeFiles/gdl.dir/link.txt <https://github.com/gnudatalanguage/gdl/issues/831#issuecomment-815998581>
2) The compilation with 
     cmake .. -DX11=ON
     cmake .. -DINTERACTIVE_GRAPHICS=OFF
     or starting GDL with —no-use-wx
     all of this does not show any difference, the plot window still gets corrupted after making it bigger.
     Making it smaller works always, just making it bigger does not work.

What else can I try?

**Comment by GillesDuvert** [comment]
... I've nothing more to suggest. I have created a OpenSuze Tumbleweed virtual machine to check both your and #961 problems.I stumbled on the ?&%*@! xdr problem. I needed to define PLPLOT_DRV_DIR before calling gdl. All these ridiculous defects still present in 2021, especially the PLPLOT driver location not defined by the system is very frustrating. 
So: I can reproduce your problem. Wonder if it is a new unwanted feature of the plplot driver. probably easy to overcome.

**Comment by pjb7687** [comment]
So you mean the plot works fine after defining PLPLOT_DRV_DIR? Perhaps we can try temporarily hardcoding the candidate paths of the driver directory for SUSE.

**Comment by GillesDuvert** [comment]
PLPLOT_DRV_DIR permits to avoid this:
```
GDL> plot,dist(100)
% Compiled module: DIST.

*** PLPLOT ERROR, ABORTING OPERATION ***
plInitDispatchTable: Could not open drivers directory, aborting operation
% PLplot installation lacks the requested driver: wxwidgets
% Execution halted at: $MAIN$ 
```         
For some reason, although all the plplot-related packages are installed, the plplot library cannot find the drivers by itself, people will be obliged to add
`export PLPLOT_DRV_DIR=/usr/lib64/plplot5.15.0/drivers`
in a .bashrc or equivalent.

The only, but very anoying problem is this lack of complete refresh of the window after a resizing, visible only on this suse, whose cause i cannot put my finger on.

**Comment by GillesDuvert** [comment]
![image](https://user-images.githubusercontent.com/33936193/122799033-8f527900-d2c1-11eb-95c8-ac2113e61488.png)

**Comment by GillesDuvert** [comment]
the bug arrives with plplot 5.15
If instead of `plot,findgen(100)` (that use the plplot driver) you do `tvscl,dist(512) ` (that dies not use the plplot dirver) then the image is not clipped. In short: line plots are wrongly clipped after a window resize. Now: what to do?

**Comment by GillesDuvert** [comment]
bug finally found, in the wxwidget driver of plplot.

**Comment by GillesDuvert** [comment]
#967 will solve it.

**Comment by GillesDuvert** [comment]
closing, please open new issues if #967 (now merged) did not cure this (it does for me on all platforms)

**Comment by brandy125** [comment]
Perfect!

Compilation and plot works out of the box now!

Thanks to all!
