### ISSUE TITLE
tv and tvscl hazardous with current builds and the wxWidgets driver

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#939]
if the plot window (command PLOT) is driven by the wxWidgets plplot driver (the default now), tvscl of non-even sized arrays will crash the driver and gdl all the same.

**Comment by Barney-9000** [comment]
Just to add to this, on my setup, GDL doesn't crash but the TV/TVSCL elements of the (wxWidgets) window appear for just a split second before being erased -- leaving behind only what was drawn by the PLOT command(s).  In contrast, output to the Postscript devices is as expected.

macOS mojave 10.14.6, RELEASE:1.0.0-rc.3 git -- compiled using llvm clang (everything except GRID & X11).

Lastly, a chance observation running TIME_TEST3 on both GDL and IDL (8.4): first, second and third runs give:
GDL: 0.297050=Total Time; 1.01042=Total Time; 1.00013=Total Time
IDL:  0.165914=Total Time ; 0.167038=Total Time; 0.166031=Total Time
With GDL, second and subsequent runs of TIME_TEST3 take 3-4 x longer than the first. Odd...

**Comment by GillesDuvert** [comment]
I do not have this behavour. Time depend strongly on what other tasks processor(s) do. I get ~0.26 s to this test in average, idl 8.4 is slow at 1.28 s ... Do you have both Eigen and -O3 optimization?

**Comment by Barney-9000** [comment]
Did have Eigen previously, but not -O3 -- just recompiled with the -O3 option.  Slightly faster, but the same effect with subsequent runs slower:
GDL 0.231373=Total Time; 0.809846=Total Time; 0.807148=Total Time

Another difference with the -O3 flag: TVSCL (without any associated PLOT commands) worked previously, now it doesn't - appears just briefly in the window then blanks.

My IDL is also 8.4, so surprised that GDL times are comparable but my IDL is much faster. CPU is 4 GHz Intel Core i7

% Compiled module: GDL_STATUS.
% Compiled module: GDL_IDL_FL.
 1 DSFMT ?  :        1
 2 Eigen3 ? :        1
 3 Expat ?  :        1
 4 FFTw ?   :        1
 5 GEOTIFF ?:        1
 6 GLPK ?   :        1
 7 GRIB ?   :        0
 8 HDF ?    :        1
 9 HDF5 ?   :        1
10 Magick ? :        1
11 NetCDF ? :        1
12 NetCDF4 ?:        1
13 OpenMP ? :        1
14 PNGLIB ? :        1
15 PROJ ?   :        1
16 Python ? :        1
17 ShapeLib :        1
18 TIFF ?   :        1
19 UDUNITS  :        1
20 WxWidgets:        1
21 X11      :        0
All _EXISTS() functions have been detected !

**Comment by GillesDuvert** [comment]
what about time_test4?
```
GDL> time_test4
|TIME_TEST4 performance for IDL 8.2:
|       OS_FAMILY=unix, OS=linux, ARCH=x86_64
| Mon May 17 18:54:36 2021
       1    0.0788960 Empty for loop, 6000000 times
       2     0.140383 Foreach, 6000000 elements
       3    0.0182459 Call empty procedure (1 param) 300000 times
       4    0.0333691 Add 600000 integer scalars and store
       5    0.0330100 150000 scalar loops each of 5 ops, 2 =, 1 if)
       6   0.00258803 Mult 512 by 512 byte by constant and store, 90 times
       7    0.0192790 Shift 512 by 512 byte and store, 900 times
       8   0.00536704 Add constant to 512x512 byte array, 300 times
       9   0.00599909 Add two 512 by 512 byte arrays and store, 240 times
      10   0.00907707 Mult 512 by 512 floating by constant, 90 times
      11    0.0144880 Shift 512 x 512 array, 180 times
      12    0.0125010 Add two 512 by 512 floating images, 120 times
      13    0.0148010 Generate 3000000 random numbers
      14    0.0191200 Invert a 332^2 random matrix
      15    0.0105100 LU Decomposition of a 332^2 random matrix
      16    0.0439370 Transpose 665^2 byte, FOR loops
      17    0.0758021 Transpose 665^2 byte, row and column ops x 10
      18     0.130861 Transpose 665^2 byte, TRANSPOSE function x 100
      19    0.0341439 Log of 300000 numbers, FOR loop
      20   0.00975609 Log of 300000 numbers, vector ops 10 times
      21     0.148774 2097152 point forward plus inverse FFT
      22    0.0489700 Smooth 512x512 byte array, 5x5 boxcar, 30 times
      23    0.0744102 Smooth 512x512 floating array, 5x5 boxcar, 30 times
      24    0.0289660 Write and read 512x512 byte array, 120 times
      25     0.258384 Create 120000 empty lists
      1.27164=Total Time,      0.027574859=Geometric mean,      25 tests.
```

**Comment by GillesDuvert** [comment]
for TVSCL, I suspect a (plplot) flush at the right place  has been wrongly commented...

**Comment by Barney-9000** [comment]
Just a tad longer:

GDL> time_test4
% Compiled module: TIME_TEST4.
% Compiled module: TIME_TEST.
|TIME_TEST4 performance for IDL 8.2:
|       OS_FAMILY=unix, OS=darwin, ARCH=x86_64
| Tue May 18 10:30:22 2021
       1    0.0607851 Empty for loop, 6000000 times
       2     0.323784 Foreach, 6000000 elements
       3    0.0142369 Call empty procedure (1 param) 300000 times
       4    0.0538950 Add 600000 integer scalars and store
       5    0.0626030 150000 scalar loops each of 5 ops, 2 =, 1 if)
       6   0.00160694 Mult 512 by 512 byte by constant and store, 90 times
       7    0.0141640 Shift 512 by 512 byte and store, 900 times
       8   0.00420594 Add constant to 512x512 byte array, 300 times
       9   0.00418806 Add two 512 by 512 byte arrays and store, 240 times
      10   0.00561595 Mult 512 by 512 floating by constant, 90 times
      11    0.0109320 Shift 512 x 512 array, 180 times
      12   0.00934887 Add two 512 by 512 floating images, 120 times
      13    0.0106320 Generate 3000000 random numbers
      14    0.0131159 Invert a 332^2 random matrix
      15    0.0114338 LU Decomposition of a 332^2 random matrix
      16    0.0518818 Transpose 665^2 byte, FOR loops
      17    0.0326259 Transpose 665^2 byte, row and column ops x 10
      18    0.0565169 Transpose 665^2 byte, TRANSPOSE function x 100
      19    0.0372169 Log of 300000 numbers, FOR loop
      20   0.00523996 Log of 300000 numbers, vector ops 10 times
      21     0.120189 2097152 point forward plus inverse FFT
      22    0.0375500 Smooth 512x512 byte array, 5x5 boxcar, 30 times
      23    0.0491259 Smooth 512x512 floating array, 5x5 boxcar, 30 times
% Compiled module: FILEPATH.
      24     0.114212 Write and read 512x512 byte array, 120 times
      25     0.227590 Create 120000 empty lists
      1.33270=Total Time,      0.024147124=Geometric mean,      25 tests.

IDL 8.4:    1.15020=Total Time,      0.023876586=Geometric mean,      25 tests.
