### ISSUE TITLE
spl_init and spl_interp dont respect type of passed arguments

### ISSUE THREAD

**Issue by eloirozier** [gnudatalanguage/gdl#943]
If I do something like :
GDL> a = double(lindgen(100)) & b = sin(xin)

Then the array returned by : spl_init(a, b) is of FLOAT type, although a and b are DOUBLE arrays. Same issue with spl_interp. Of course adding the instruction /double solves this, but respecting the arguments types should be automatic.
I'm currently working on correcting this minor issue

**Comment by GillesDuvert** [comment]
thanks @eloirozier
