### ISSUE TITLE
interpol errors

### ISSUE THREAD

**Issue by eloirozier** [gnudatalanguage/gdl#951]
I was working on interpol when I stumbled upon a (quite concerning) issue for when it takes two arguments...

`GDL> y = FINDGEN(10)-5 & print, interpol(y,1)`
returns: `-NaN`

In IDL I get the right value (which is -5.0). It seems to be related with the recent c++ version of this function... I'll try to address this problem.

**Comment by alaingdl** [comment]
nooooon ! incredible ! Is was working for me upon recently. And no test in testsuite catched that ?

**Comment by alaingdl** [comment]
Was OK in the beginning of April (4/2/21). A diff should help you a lot to locate the changes.

**Comment by eloirozier** [comment]
Ok thanks for the tip !
And no, test_interpol does not detect any error...

**Comment by eloirozier** [comment]
It's very specific !
The error only occurs when N=1 in interpol(V,N), because it involves a division by 0... quite simple to fix
