### ISSUE TITLE
Window blanks and placement with wxWidgets fix on macOS

### ISSUE THREAD

**Issue by Barney-9000** [gnudatalanguage/gdl#964]
Firstly, many thanks for the wxWidgets fix -- looks great. Works largely as expected (i.e. like x11) with one or two little quirks as follows:

a) For a procedure which repeats a data display (both PLOT & TV commands) in a small loop (just five instances), one of the windows is occasionally left mostly blank with just some of the PLOT drawing showing.  Seems to be usually the second of the five windows that is affected, though occasionally others. A timing/flush issue in plplot?

b) Nice to see that the x11 successive window placement feature has been implemented, i.e. clockwise at the corners of the display. On macOS the placement of the upper two windows is at the very top edge of the display, rather than just below the menu bar. That leaves barely one or two pixels showing where the cursor can 'grab' the window (say, to shift it aside). Not a big deal, but maybe worth mentioning.

**Comment by GillesDuvert** [comment]
Hi @Barney-9000  I noticed the problem with the top window placement on MacOSX, the screen size is given by wxWidgets and apparently there is no simple way to know what is the taskbar size (which can now be hidden). Any idea? At the worst, reserving a ~30 pixels strip for the taskbar will be a workaround probably.
Concerning the for .. plot loop timing that needs investigation.

**Comment by Barney-9000** [comment]
According to [this](https://github.com/feedback-assistant/reports/issues/140), 22 or maybe 24 should cover it. On 10.14.6 it looks like 22 pixels.

**Comment by GillesDuvert** [comment]
Actually, HGeospatial documentation says:
"There is no known way to find the resolution of the largest unobstructed graphics window on a MACINTOSH computer, so a fudge factor  of 22 pixels is used... 
We chose 24.
