### ISSUE TITLE
“Gtk WARNING: gtk_disable_setlocale() must be called before gtk_init()” on calling plot in gdl (gnu data language)

### ISSUE THREAD

**Issue by jyothischandran** [gnudatalanguage/gdl#969]
I installed GDL to run some IDL code for my project. But when I try to call the plot function in GDL it gives the following error and exits:

*(gdl:1003695): Gtk-WARNING *: 22:57:44.888: gtk_disable_setlocale() must be called before gtk_init() Segmentation fault (core dumped)

I am using ubuntu 20.04 with kubuntu-desktop. Any suggestions are welcome.

On starting GDL, the text I get is:

_(gdl:484266): Gtk-WARNING **: 19:24:59.488: Theme parsing error: colors.css:71:52: Expected ')' in color definition

(gdl:484266): Gtk-WARNING **: 19:24:59.488: Theme parsing error: colors.css:74:64: Expected ')' in color definition

(gdl:484266): Gtk-WARNING **: 19:24:59.488: Theme parsing error: colors.css:76:67: Expected ')' in color definition

(gdl:484266): Gtk-WARNING **: 19:24:59.488: Theme parsing error: colors.css:77:76: Expected ')' in color definition
  GDL - GNU Data Language, Version 1.0.0-rc.3 git
- For basic information type HELP,/INFO
- Default library routine search path used (GDL_PATH/IDL_PATH env. var. not set): /usr/local/share/gnudatalanguage/lib
- Using WxWidgets as graphics library (windows and widgets).
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set). 
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

GDL>_

**Comment by GillesDuvert** [comment]
I have tested and apparently this comes from a clash between wxWidgets 3.1.5 and the plplot library.

**Comment by jyothischandran** [comment]
So, which versions of wxWidgets and plplot I should use to correct this?

**Comment by jyothischandran** [comment]
Actually, I am able to plot now. I just compiled the plplot to /usr/local/ and provided the path while compiling gdl.

But, when I run check, two tests are failing always.

99% tests passed, 2 tests failed out of 189

Total Test time (real) =  73.77 sec

The following tests did not run:
        100 - test_grib.pro (Skipped)
        126 - test_mpi.pro (Skipped)

The following tests FAILED:
         93 - test_fixprint.pro (Failed)
        184 - test_window_background.pro (Failed)
Errors while running CTest
make[4]: *** [Makefile:118: test] Error 8
make[3]: *** [testsuite/CMakeFiles/check.dir/build.make:59: testsuite/CMakeFiles/check] Error 2
make[2]: *** [CMakeFiles/Makefile2:222: testsuite/CMakeFiles/check.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:229: testsuite/CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:214: check] Error 2

**Comment by GillesDuvert** [comment]
Yes, see end of the #961 conversation, recompiling plplot *after* wxwidgets removes the core dump. We (at last I) are investigating, as this endangers the possibility of a version 1.0 of GDL.
I understand that the `Gtk-WARNING **: 19:24:59.488: Theme parsing error: colors.css:71:52: Expected ')' in color definition` have disappeared as well?

**Comment by jyothischandran** [comment]
Thank you.
Nope. I suspect the color.css warning happens because I am using some custom themes in KDE desktop. For them to go away, I have to manually edit out an extra value that appears like rgb(.. , .. , .. , 216) from colors.css.

**Comment by GillesDuvert** [comment]
@jyothischandran1597 Apparently with 4 values it should be written as rgba(r,g,b,a) not rgb(r,g,b,a)

**Comment by jyothischandran** [comment]
I think the comment in https://github.com/gnudatalanguage/gdl/issues/961 by @GillesDuvert to compile plplot after wxwidgets does it for this problem. Now I am comfortably running gdl with HEALPix IDL, even using jupyter kernels. Now, only if gdl has idl functions like TS_SMOOTH, everything would be perfect!

**Comment by jyothischandran** [comment]
Also, in rgba the a which is alpha is between 0 and 1. In my colors.css file in ~/.config/gtk-3.0 the 4th value was 216 for multiple lines. when i edited that value out, everything works fine as far as i know.

**Comment by opoplawski** [comment]
I'm seeing the same test failures with latest gdl git.  Worth opening a separate issue for those?
