### ISSUE TITLE
The new "FindXdr.cmake" needs to find xdr. (Mingw32)

### ISSUE THREAD

**Issue by maynardGK** [gnudatalanguage/gdl#97]
My build attempt of the git failed on linking to xdr.  I find in cmake output that
the only xdr reference found was that of the include directory.  

using the new FindXdr.cmake:
`$ grep -i xdr ../temp/cmake.out
-- Found XDR: C:/msys64/mingw32/include
`
When regressed to the old Findxdr.cmake
`$ grep -i xdr cmake.out
-- Found XDR: C:/msys64/mingw32/lib/libxdr.dll.a
`

**Comment by GillesDuvert** [comment]
Certainly worth to at least include the older FindXdr content in cas the target is mingw!

**Comment by maynardGK** [comment]
As a workaround, I use a one-line script that I apply from the build
directory:
>
> sed -e 's;cblas;cblas -lxdr;' -i  src/CMakeFiles/gdl.dir/linklibs.rsp

**Comment by slayoo** [comment]
This @pjb7687's commit fixed the issue:

https://github.com/gnudatalanguage/gdl/commit/f21fa8052eace2c8fa40bf12fbcb0f8a93315882#diff-af3b638bc2a3e6c650974192a53c7291

However, @maynardGK raised concern that:

```

So I think you've identified the problem, but reversed the solution.  The error is in FindXDR.cmake not setting XDR_LIBRARIES,
which is the conventional name, also followed in our own build.

 $ grep LIBRARIES /f/github/gdlgit/CMakeLists.txt
        set(LIBRARIES ${LIBRARIES} dl)
                set(LIBRARIES ${LIBRARIES} ${CURSES_LIBRARIES})
                        set(LIBRARIES ${LIBRARIES} ${CURSES_LIBRARIES})
      set(CMAKE_REQUIRED_LIBRARIES ${CURSES_LIBRARIES})
etc
```
