### ISSUE TITLE
test_fixprint.pro and- test_window_background.pro failed

### ISSUE THREAD

**Issue by jyothischandran** [gnudatalanguage/gdl#973]
I am running GDL Version 1.0.0-rc.3

When I run check, two tests are failing always.

99% tests passed, 2 tests failed out of 189

Total Test time (real) = 73.77 sec

The following tests did not run:
100 - test_grib.pro (Skipped)
126 - test_mpi.pro (Skipped)

The following tests FAILED:
93 - test_fixprint.pro (Failed)
184 - test_window_background.pro (Failed)
Errors while running CTest
make[4]: *** [Makefile:118: test] Error 8
make[3]: *** [testsuite/CMakeFiles/check.dir/build.make:59: testsuite/CMakeFiles/check] Error 2
make[2]: *** [CMakeFiles/Makefile2:222: testsuite/CMakeFiles/check.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:229: testsuite/CMakeFiles/check.dir/rule] Error 2
make: *** [Makefile:214: check] Error 2

**Comment by GillesDuvert** [comment]
Fixprint is OK now.
test_window_background is an interactive test, to be put in testuite/interactive_tests and should not be tested by 'make test'.
But it is an important test, apparently works with current gdl, I've tested.
