### ISSUE TITLE
bug in delvarrnew

### ISSUE THREAD

**Issue by pjb7687** [gnudatalanguage/gdl#980]
I found the reason why `test_delvarrnew` stuck during windows tests. It turned out a bug in GDL. The test stuck because the 'assertion' error is displayed as a dialog on Windows, waiting for the user to dismiss the dialog.

On Linux, the error is reproducible too:

```
~/build/testsuite$ ../src/gdl -quiet delvarrnew.pro
Unable to init server: Could not connect: Connection refused
02:38:07: Error: Unable to initialize GTK+, is DISPLAY set properly?
WARNING: wxWidgets not initializing, widget-related commands will not be available.
IGOT            FLOAT     = Array[4]
IGET            FLOAT     = Array[4]
gdl: /home/pjb7687/gdl/src/datalistt.hpp:124: T& EnvTypePreAllocListT<T, defaultLength>::operator[](SizeT) [with T = EnvType; long long unsigned int defaultLength = 64; SizeT = long long unsigned int]: Assertion `i<sz' failed.
Magick: abort due to signal 6 (SIGABRT) "Abort"...
Aborted
```

The error occurs here:
https://github.com/gnudatalanguage/gdl/blob/master/src/envt.cpp#L1310

**Comment by GillesDuvert** [comment]
Hm, I've mixed feelings about test_delvarrnew, I suggest we remove it from the 'active' list for the time being.
But this is not the subject: Apparently, there are 'popups' from an external library that hangs GDL?

**Comment by pjb7687** [comment]
#981 should fix it

**Comment by pjb7687** [comment]
> But this is not the subject: Apparently, there are 'popups' from an external library that hangs GDL?

The popup is from a Windows internal API. Below image is **NOT** from GDL, but it should look similar:

https://user-images.githubusercontent.com/30054587/42539104-893fbf9a-845f-11e8-99bd-76bc19b346ee.PNG
