### ISSUE TITLE
document and stabilize test_delvarrnew.pro

### ISSUE THREAD

**Issue by GillesDuvert** [gnudatalanguage/gdl#984]
test_delvarrnew failed for reasons having nothing to do with its purpose, as seen in #980
It must be documented and give clear error messages, as at the moment, using .RNEW and non-procedures in GDL is problematic if not totally out of scope.
test_delvarrnew will be moved to testsuite/wrong until fixed and reviewed

**Comment by pjb7687** [comment]
In addition, it would be nice to review this 'Removeall' function too, which was introduced 3 years ago:

![image](https://user-images.githubusercontent.com/1440536/124134322-01298000-da83-11eb-9f85-4e20544c33cf.png)
(line 1305 of `envt.cpp`)

I don't get the purpose of the function, as this produces GDLException `env and pro out of sync` as below:

```
$ ../src/gdl.exe delvarrnew.pro
  GDL - GNU Data Language, Version 1.0.0-rc.3 git
- For basic information type HELP,/INFO
- Using WxWidgets as graphics library (windows and widgets).
- No startup file read (GDL_STARTUP/IDL_STARTUP env. var. not set).
- Please report bugs, feature or help requests and patches at: https://github.com/gnudatalanguage/gdl

IGOT            FLOAT     = Array[4]
IGET            FLOAT     = Array[4]
% env and pro out of sync.
  At: C:\msys64\home\pjb7687\gdl\build\testsuite\rnewtest.pro
% env and pro out of sync.
```

**Comment by GillesDuvert** [comment]
As I understand, Removeall() was introduced by @maynardGK in #114 because of .RNEW , which deletes all variables before compiling some procedure.
Unfortunately, ".RNEW' does not delete all existing variables in the current version, **but does delete them in version 0.9.9**. Addtionally, I even got something like
```
GDL> .rnew ~/gdl/testsuite/gdl_idl_fl.pro
% Compiled module: GDL_IDL_FL.
GDL> help
% At $MAIN$          
% BaseGDL::ToStream(...) called.
% Execution halted at: $MAIN$          

```
There is something fishy.

**Comment by GillesDuvert** [comment]
Ah, understood
SizeT is an unsigned. reverse loops are somehow ignored by the compiler (mine at last).
negative increment loops should be made with ssize_t  that is signed.
Doing that, no more errors of test_delvarrnew.
PR submitted.

**Comment by GillesDuvert** [comment]
reopened as this concerns test_delvarrnew DOC and not .RNEW

**Comment by alaingdl** [comment]
sorry @maynardGK , what is  meaning or usage of the file `test_delvarrnew.pp.pro`, it does interfere with others tests on IDL (test_resolve_routine.pro). Is it still useful ?

**Comment by maynardGK** [comment]
test_delvarrnew is a test of delvar and of .RNEW.  In order to accomplish the test, it writes files that are to be executed from $MAIN.  Apparently at some point I was calling these temporary files (now delvrrnew.pro and rnewtest.pro) with an extra suffix attached.   I doubt they are of any use.

@GillesDuvert There are a few other instances of SizeT usage with a decrementing index - are they failing also?

**Comment by GillesDuvert** [comment]
_@maynardGK you asked: "There are a few other instances of SizeT usage with a decrementing index - are they failing also?"_
I already corrected a few last year.. Perhaps I missed some.
