### ISSUE TITLE
an example of a somehow misleading error message

### ISSUE THREAD

**Issue by slayoo** [gnudatalanguage/gdl#99]
As reported on SF.net: https://sourceforge.net/p/gnudatalanguage/bugs/231/

```
GDL> $cat bug.pro
pro bug
n = 1
if (n ne 1 then n = 1
end
```

```
IDL> bug
if (n ne 1 then n = 1
^
% Syntax error.
```

```
GDL> bug
% Lexer/Parser syntax error: expecting EQUAL, found 'NE'
At: bug.pro, Line 3 Column 9
```

**Comment by GillesDuvert** [comment]
@slayoo , actually GDL says it is a syntax error, and where in the line things begin to be abnormal. IDL wrongly indicates the beginning of line. I do not see why one would prefer the IDL behaviour?
Besides, as the error is trapped by ANTLR there is little chance to serioulsy mimic IDL's behaviour.
If there was such things as a compendium of GDL vs IDL idiosyncrasies this shoud go there, not in the bug section.

**Comment by slayoo** [comment]
Yes, let's close it.
