### ISSUE TITLE
ACOS and ASIN bug with arithmetic operation in argument: OpenMP compiled masOS 10.14.6

### ISSUE THREAD

**Issue by Barney-9000** [gnudatalanguage/gdl#994]
Quite by chance, discovered this worrying behaviour when there is an arithmetic operation in the supplied argument to ACOS and ASIN. Here's an example for ACOS:

GDL> h = FINDGEN(100)
GDL> h = h/MAX(h)
GDL> PLOT, ACOS(h), ACOS(h/1.0), psym=1    ; gives a nice (and worrying) curve -- totals below.
<img width="859" alt="Screenshot 2021-07-04 at 10 17 42" src="https://user-images.githubusercontent.com/74673118/124379852-53e87f00-dcb1-11eb-8588-075d10cba01b.png">

GDL> PRINT, TOTAL(ACOS(h)), TOTAL(ACOS(h/1.0))
      99.7567      45.9304
GDL> PRINT, TOTAL(ACOS(h)), TOTAL(ACOS(h*1.0))
      99.7567      45.9304
GDL> PRINT, TOTAL(ACOS(h)), TOTAL(ACOS(h+0.0))
      99.7567      45.9304

I still have an (X11) minimum install GDL -- it does not show this bug. Let me know if you need any more info from me.
Best

**Comment by alaingdl** [comment]
whouaou :worried: :worried:

I succeed to reproduce it

the change was between May 17 & 25 but large changes in the code at that time : 

basegdl.hpp 
basic_fun.cpp 
basic_pro.cpp 
convert2.cpp 
datatypes.cpp 
interpolate.cpp 
libinit_jmg.cpp 
str.cpp 
and
math_fun_ac.cpp 
math_fun.cpp

**Comment by GillesDuvert** [comment]
solved directly in the trunk is 2 minutes. Cut and paste problem of course.
Many thanks !

**Comment by Barney-9000** [comment]
Whoa!  Excellent.  It was only by chance that I compared a sample of reruns to an older set produced by IDL.  Difference in the graphical outputs wasn't huge -- a small displacement in some plotted points.  So might have gone unnoticed had I not made a direct comparison of the numerical results also. And then began the hunt for the rogue...  A lucky find.  And a super-quick fix.
